### ISSUE TITLE
cant edit enterprise fees on UK production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#902] opened 2016-04-13 13:32 UTC
On the Stroudco back end when i click on enterprise fees nothing happens, the existing fees dont open, there is no option to edit or add fees
![screenshot 2016-04-13 14 30 37](https://cloud.githubusercontent.com/assets/10517702/14494790/8f80d41c-0184-11e6-9436-44f75732d8f1.png)

**Comment by OliverUK** [comment] 2016-04-13 14:05
Other enterprise screens don't load either. Need this looked at so that we can progress Stroudco's transition onto OFN. Lynne is aware of it though.

**Comment by OliverUK** [comment] 2016-04-13 14:31
@NickWeir63  
Nick, maybe you could somehow mark this as important? It must be a problem with the new version and rather crucial!

**Comment by lin-d-hop** [comment] 2016-04-13 17:16
Yeah I'm on it. I've identified the revision that caused this so going through that to find the cause. Will keep you posted.

**Comment by lin-d-hop** [comment] 2016-04-13 17:17
I can revert production if needed to a version with the shopfront loadspeed improvements and without this issue. Let me know if priority increases.

**Comment by OliverUK** [comment] 2016-04-14 09:12
Hi @lin-d-hop Lynne,
It can wait a few days, especially if it means you may be able to fix it without spending time on reverting to a prior version. But if it's something that will potentially draw out, I'd rather be getting on with preparing for our switch-over, which includes fiddling with enterprise settings. Maybe as soon as you can have a guess at how long it might take, let us know?

**Comment by Rocksj** [comment] 2016-04-14 10:11
Lots of buttons don't work on the dashboard Primary Details, Social, About, Business Details, Delivery Methods, Enterprise Fees, Tag Rules, Shop Preferences. As we've just started a new service to a Council building it would be good to be able to change things if required! Was it an issue with loading 1.6 onto production?

**Comment by lin-d-hop** [comment] 2016-04-14 11:59
Yes I mentioned this on the hangout the other day, @Rocksj . I'm looking into it, though yesterday and today are not OFN days. If I can't fix this evening I'll revert to the last working version until fixed.

**Comment by Rocksj** [comment] 2016-04-14 12:08
Sorry Lynne, slow on the uptake at the time in the morning! Its fine for now as I don't think we need to change anything

**Comment by lin-d-hop** [comment] 2016-04-14 12:12
Had a couple more complaints have come in via email so I'm reverting.
Back to [41970ecf](https://github.com/openfoodfoundation/openfoodnetwork/commit/41970ecf077bbffca1a9488ff9ade9b503003796) which was the last one that worked. That means @stveep's are out, caching is in, tagging is out. Will keep you posted.

**Comment by OliverUK** [comment] 2016-04-14 15:24
Thanks Lynne. I'm able to edit Enterprises again but I noticed something which may be related or not. On trying to change the notifications email for one producer, I was unable to get the system to save the change. I also tried to resend the confirmation email to the current address and doesn't look it's send anything. 
![screen shot 2016-04-14 at 16 23 36](https://cloud.githubusercontent.com/assets/17590921/14533522/4c995b04-025d-11e6-9682-ec7881bbad92.png)

**Comment by lin-d-hop** [comment] 2016-04-15 11:26
Fixed with updates to the locales file. On branch uk/enGB-updates which is currenlty on UK production so all v1.6.0 functionality should be deployed now.

Also added to deployment process (a file in our G Drive) that we need to check all locale changes before deployment. I want to add something to our pre-deployment checks as well.

**Closed by lin-d-hop** 2016-04-15 11:26 UTC
Labels: p - important
