### ISSUE TITLE
as Producer participating in OC, I should not be able to apply or remove others' fees . . 

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#499] opened 2015-04-16 03:03 UTC
but i should be able to see them  . .

at the moment, I can see, add and remove fees from the coordinator. Should be able to see that it's there but not add or remove (I think?)

If another producer's fee is applied to my incoming exchange (e.g. by the Coordinator), I can see the empty boxes, and remove the fee, but not add it myself. See @sstead's comment at http://community.openfoodnetwork.org/t/what-permissions-do-i-have-in-a-full-order-cycle/137/8?u=openfoodnetwork

I should be able to see it, but not be able to remove it

![image](https://cloud.githubusercontent.com/assets/2911176/7173305/56456ccc-e438-11e4-8d9f-f22492a13d8b.png)

**Comment by myriamboure** [comment] 2018-03-19 15:29
If I sum up the need (which is not a bug so will need to be put in some "improve producer UX"  icebox:
- producer needs to be able to see fees applied to his products in an OC, whoever those fees are attached to
- BUT he should only be able to add remove fees that are attached to his own enterprise
I retested and the unwanted behaviors are still there (both the one described by Kirsten and Sally in the connected page)

This might change though in the order cycle overhaul that might happen with the product chain overhaul so I'm not sure if I should create an icebox now. Will think about it.

**Comment by myriamboure** [comment] 2018-03-20 09:39
Closing as this is part of icebox https://community.openfoodnetwork.org/t/users-have-the-appropriate-permissions-given-their-role-and-all-those-who-can-be-created-automatically-are/1267 #gitcull2018

**Closed by myriamboure** 2018-03-20 09:39 UTC
