### ISSUE TITLE
Redirect to /details step, after visiting /cart (from the /summary step)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11211] opened 2023-07-13 12:19 UTC
## Description

Relates to #11188.

If a user reaches the /summary step but makes changes to the cart, proceeding with checkout will redirect the customer to the /details step.

This leaves the order in the `confirmation` state.

## Expected Behavior

Resuming checkout should redirect the customer to the step from which the customer visited the cart from.

## Actual Behaviour

After updating the cart the user always gets redirected to the `/details` step (regardless from where the customer visited the cart from)

## Steps to Reproduce

1. Add items to the cart and proceed to the /summary step
2. Edit the cart, and make some changes (add or remove an item). Click the Update button.
3. While on the cart page, click Checkout 
4. Notice you'll have to start checkout all over again -> you've been redirected to the /details step

## Workaround

You're able to checkout... But your starting over each time you edit your cart.

## Severity

Process-wise: an s4 - it affects checkout and we have reports of customers not confirming orders and leaving them in the confirmation state.

## Your Environment

* Version used: v4.4.2
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by RachL** [comment] 2023-07-14 08:13
@filipefurtad0 as this involves checkout, maybe we should bump to s3 so instance can select it?

**Comment by filipefurtad0** [comment] 2023-07-14 09:28
Sounds good @RachL :ok_hand:

**Comment by cyrillefr** [comment] 2023-07-19 15:54
Hello @filipefurtad0, @RachL ,

May I work on this issue ?

**Comment by filipefurtad0** [comment] 2023-07-20 11:59
Hey @cyrillefr ,

Thanks for interest in this issue. Please go ahead - please let us know if you find difficulties, these redirects are sometimes tricky (I think). 
I've assigned you now - thanks!

**Comment by cyrillefr** [comment] 2023-07-21 15:21
Hello @filipefurtad0,


I have made some tests and identified what is going on.
From what I now know, it seems to me it is a legit business rule.

When a user makes changes to the cart while in `/payment` and then:
- edit cart
- and update

-> Order does not stay in `confirmation` state, but instead goes back into `address` state.

So it's not like order stays in `confirmation` state and then for some bug user has to reproceed from 1st state when wants
to checkout again (`address`).
So in my opinion it is not a bug but a business rule. This is also what I understand from reading the code

So, what is happening when one click on 'Update' button ( url is in `/cart)`?
First reach is `update_cart` method in `app/model/spree/order_contents.rb`
Which calls `update_shipment` method in `app/models/spree/order_contents.rb`
Which itself calls `ensure_updated_shipments` in `app/models/spree/order.rb`

```ruby
# Clear shipments and move order back to address state unless compete. This is relevant where
# an order is part-way through checkout and the user changes items in the cart; in that case
# we need to reset the checkout flow to ensure the order is processed correctly.
def ensure_updated_shipments   
  if !completed? && shipments.any?
    shipments.destroy_all                                                                                                    
    restart_checkout_flow <- RESET STEP HERE
  end    
end
```

With `restart_checkout_flow` method defined in `app/model/spree/order/checkout.rb`:

```ruby
def restart_checkout_flow
  update_columns(
    state: checkout_steps.first,    <- address state                                                                                   
    updated_at: Time.zone.now,
  )
end
```

Comment over the `ensure_updated_shipments` method says there is a need to do so to ensure the order is processed correctly.
So, in my opinion, it would be a feature, but there might be side effects, if I believe the comments.

What do you think ?

**Comment by filipefurtad0** [comment] 2023-07-21 15:30
Thanks so much @cyrillefr for investigating and providing this insight.

I was not aware it was designed in this way. I'm wondering though, if this is a good user experience, from a customer perspective, to always be redirected to the `/details` step, even after minor changes on the cart.

This may be acceptable for now, so I suppose we can close this issue - does this sound good to @openfoodfoundation/train-drivers-product-owners ?

**Comment by RachL** [comment] 2023-07-23 10:38
Indeed, it would be cleaner to end up on the summary page, if this was the page the user got to the cart from.

However I'm a bit afraid of potential side effects of that work. Would you agree to try to implement it @cyrillefr but if it's too complex we stop and live with it as is?
I haven't tested yet sorry but what is the workflow when edit something else on the summary step?

**Comment by RachL** [comment] 2023-08-11 09:58
thanks for this feedback @cyrillefr I'm proposing to treat this as a feature then not a bug fix, as indeed everything points out to something we designed that way. @drummer83 has already created a wishlist for it :) https://github.com/openfoodfoundation/wishlist/issues/454 so closing here in favor of this wishlist. We will need to work on this a bit before creating proper issues

**Closed by RachL** 2023-08-11 09:58 UTC
Labels: bug-s3, feedback-needed
