### ISSUE TITLE
Images cannot be included  in group settings 

### ISSUE THREAD

**Issue by eugenichafer** [openfoodfoundation/openfoodnetwork#5740] opened 2020-07-07 09:03 UTC
![imagegroup](https://user-images.githubusercontent.com/64070973/86756036-5da9b900-c042-11ea-8ed4-627264c30450.gif)
## Description

When you try to include an image in the configuration of a new group, even though doing so does not give any error, the image is not saved even using images that are already part of the configuration of another group. 

## Expected Behavior

Images should be stored and displayed correctly for both the logo and promo images.

## Actual Behaviour

Images are not saved although when it leaves the page it says that the group has been updated correctly

## Steps to Reproduce

1. Open group configuration
2. Upload new logo and promo images 
3. Update group configuration 
4. Navigate to group 

## Your Environment

* Version used: V3.
* Browser name and version: Chrome and Safari
* Operating System and version (desktop or mobile): MacOs Catalina desktop

**Comment by RachL** [comment] 2020-07-09 07:32
duplicate of #5752

**Closed by RachL** 2020-07-09 07:32 UTC
