### ISSUE TITLE
suspend auto-e2e-link creation e.g. if i am group manager creating lots of enterprises

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#576] opened 2015-05-27 05:26 UTC
WHAT WE SHOULD DO:
Now: 
- We should disable creation of E2Es to/from profile-only hubs (this can be done immediately)

Later:
- We should improve the E2E interface (a suggested layout in doc below)
- We could also make buying groups inherit E2Es from Coordinating Hubs (to reduce the number of E2Es that have to be set up/maintained)

**Comment by sstead** [comment] 2015-07-10 00:25
Just to clarify... I had a look at E2E link creations when the user owned a group and multiple enterprises. 

No E2Es are formed when a user adds enterprises to the group.

The problem is simply that when 1 user is tasked with creating profiles for all members of a group...
- Every time the user creates a Producer- it will grant all hubs owned by that user with P-OC and P-VO.

and 

- Every time the users creates a Hub- all producers owned by the user will grant that hub P-OC. And this new hub will grant all other hubs owned by the user with P-OC.

Auto E2E creation fits well in the case of a hub owner creating profiles for their supplying producers and their buying groups. It doesn't hold up as well in the case of a user creating profiles for all members of a large group. 

If we think about this in the context of the MALPN group. It's not accurate to say that all producers within the group (if created by 1 user) will want to trade with all hubs and vice versa.

**Comment by kirstenalarsen** [comment] 2015-07-14 00:59
thanks @sstead - can you have a go at recommending a solution? what should we do about this? what should the new rules for auto E2E links be? ref. if useful http://community.openfoodnetwork.org/t/what-e2e-links-do-new-enterprises-have/33

**Comment by sstead** [comment] 2015-09-25 02:30
I had a big old session on this a while ago. Don't think much has changed since then. Doc below. 
The takeaway message was "remove E2E creation between PROFILE ONLY hubs"
[E2E rethink, automatic, interface.docx]

**Comment by kirstenalarsen** [comment] 2015-09-25 02:48
can you include link to this issue in your new groups discourse page - thanks :)

**Comment by kirstenalarsen** [comment] 2015-09-25 02:49
and also, was hoping you could suggest the logic for how we fix it - what exactly do we want the guys to implement? e.g. if I am a group manager and a hub, how do we know when to apply auto-e2e and when not to?

**Comment by sstead** [comment] 2015-09-25 04:58
I don't think we need to disable Auto E2Es for group users....Here's why: Group creator users will generally only be creating profiles (not shopfronts), so no E2Es will be formed. If it's a SEFH type of group, they will create shops, but then the existing Auto E2E rules are good, because all memebrs of the group are all trading with one another. But for groups were only some members will trade (ie MALPN and Castelmaine Market, or the MFM group) the E2Es will need to be set up manually, according to which enterprises are included and which ones want to retain ownership of their profiles or not. So a hub will be created (under a different username to who created the group) and all E2Es will be set up. 

WHAT WE SHOULD DO:
- We should disable creation of E2Es to/from profile-only hubs (this can be done immediately)
- We should improve the E2E interface (a suggested layout in doc above)
- We could also make buying groups inherit E2Es from Coordinating Hubs (to reduce the number of E2Es that have to be set up/maintained)

**Comment by daniellemoorhead** [comment] 2016-02-24 01:06
@sstead and @serenityhill and @mkllnk is this in any way related to the work that's been happening in v1.5 around groups? Is this still something we're wanting to implement via the AU backlog?

**Comment by mkllnk** [comment] 2016-02-24 06:27
It's not directly related to groups. But it is something we want to do for our Australian businesses.

**Comment by kirstenalarsen** [comment] 2016-07-20 06:10
@sstead - did this get sorted as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/757 or still needs work?

**Comment by sstead** [comment] 2016-07-20 06:16
Still needs doing.

**Comment by kirstenalarsen** [comment] 2016-07-20 06:16
is important do you think?

**Comment by sstead** [comment] 2016-07-20 06:23
Important but not urgent I think. The worst that can happen is a hub finds they have permission to stock lots of enterprises's products when they shouldn't (if they were created as part of a group). But realistically at this point, for Australia, there aren't many groups being setup, and of those, there aren't lots of profiles that then go to add products and setup shops. It should be fixed eventually, but not urgently. Also, I'm not sure what the impact of 'junk E2Es'. If a developer thinks this could be clogging things, then that might be a reason to prioritise this.

**Comment by myriamboure** [comment] 2018-03-20 09:39
Closing as this is part of icebox https://community.openfoodnetwork.org/t/users-have-the-appropriate-permissions-given-their-role-and-all-those-who-can-be-created-automatically-are/1267 #gitcull2018

**Closed by myriamboure** 2018-03-20 09:39 UTC
Labels: australia
