### ISSUE TITLE
Subs cannot be edited

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#4410] opened 2019-10-28 16:24 UTC
## Description

When a manager or super admin tries to edit a subscription, the changes are not taken into account.

## Steps to Reproduce

1. Got to `/admin/subscriptions`
2. Create a new subs, and edit it or click straight on the edit button of a subs already existing
3. Change something e.g. add a product or change a quantity. Save
4. The display shows the new info
5. Now come back to `/admin/subscriptions` and check your subscription again. You will see nothing has been actually saved.

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/fce98263-79e8-4fb9-b43f-04f114559190)

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/eea10d7f-9234-44a3-b66d-df23d56bea90)

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/934356e2-a9d0-47ae-8778-0044584cc8e2)

## Workaround
The workaround is to cancel the subs and create a new one.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.5.3
* Browser name and version: Firefox 70
* Operating System and version (desktop or mobile): Desktop

**Comment by Matt-Yorkley** [comment] 2019-12-06 13:14
Is this a duplicate of #4322 or not?

**Comment by RachL** [comment] 2019-12-06 13:29
@Matt-Yorkley it is maybe related to the same problem. But both are two different icon/problem: there is the edit icon and there is the unpause button. In #4322 you can pause but not unpause. Here you cannot edit.

**Comment by luisramos0** [comment] 2019-12-06 17:27
I can replicate it 😮 🤕 
https://recordit.co/FTggcjjEcw

**Comment by luisramos0** [comment] 2019-12-06 17:29
yeah, same cause as #4322 
error:
```
undefined method `final_weight_volume' for #<SubscriptionLineItem:0x007fc1167c9ff0>

Rails.root: /Users/luisramos/dev/ofn/openfoodnetwork
Application Trace | Framework Trace | Full Trace

app/models/calculator/weight.rb:28:in `line_item_weight'
app/models/calculator/weight.rb:23:in `block in total_weight'
app/models/calculator/weight.rb:22:in `total_weight'
app/models/calculator/weight.rb:16:in `compute'
app/services/subscription_estimator.rb:57:in `shipping_fee_estimate'
app/services/subscription_estimator.rb:52:in `assign_fee_estimates'
app/services/subscription_estimator.rb:14:in `estimate!'
app/services/subscription_form.rb:22:in `block in save'
app/services/subscription_form.rb:21:in `save'
app/controllers/admin/subscriptions_controller.rb:69:in `save_form_and_render'
app/controllers/admin/subscriptions_controller.rb:40:in `update'

```

**Comment by sauloperez** [comment] 2019-12-09 17:38
I can confirm. The only hub using subscriptions in Katuma is experiencing this.

**Closed** 2019-12-11 11:20 UTC
Labels: BE, bug-s3
