### ISSUE TITLE
Order remains in payment state after payment is completed

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#8224] opened 2021-09-23 18:56 UTC
## Description

https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1631824275068900

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by filipefurtad0** [comment] 2021-09-29 14:46
Hey @andrewpbrett, 
I think this could be the root cause - shops with all shipping methods set to backoffice only, https://github.com/openfoodfoundation/openfoodnetwork/issues/8219.

**Comment by Cecilia-Hn** [comment] 2021-11-03 15:10
Hi @filipefurtad0 and @RachL 
We've got 2 new cases for hub 2468 

These two following payments are captured in Stripe but in red statu in OFN

R862447072
<img width="1369" alt="Capture d’écran 2021-11-03 à 13 42 32" src="https://user-images.githubusercontent.com/67476305/140062380-4aff03f3-357b-4a85-aa61-39841b600459.png">



<img width="1096" alt="Capture d’écran 2021-11-03 à 13 42 44" src="https://user-images.githubusercontent.com/67476305/140062531-5ed21f69-8d15-4c82-bf95-43a2a83601f5.png">




Same behavior for R157315143 but for this one the user could change the OFN statu 


This Shop still have spain registered for state information

**Comment by RachL** [comment] 2021-11-03 15:27
@Matt-Yorkley or @mkllnk any chance one of you has room to check these out?

**Comment by filipefurtad0** [comment] 2021-11-03 20:25
> This Shop still have spain registered for state information

Yes, hub 2468 its still has its address set for Spain (`id=175`). Also, it seems to be the same distributor (`id=2210`) as in issue #8296. But now the order has both ship and bill address for France/Finisterre (`state_id=548`, `country_id=13`), but this seems not to prevent this bug...

Bugsnag:
https://app.bugsnag.com/open-food-france/coopcircuits/errors/60f11496903af700075b686d?filters[search]=ameetmomo29%40hotmail.fr

**Comment by Matt-Yorkley** [comment] 2021-11-15 11:58
I think I'll close this one for now. From the issue description and the linked Slack discussions it looks like the reported problems are either a duplicate of #8296, or a duplicate of #6136, or some combination of the two.

**Closed by Matt-Yorkley** 2021-11-15 11:58 UTC
Labels: bug-s2
