### ISSUE TITLE
Separate menu tabs to own page

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2709] opened 2018-09-13 11:26 UTC
Shop header menu tabs currently open 'in screen' drop downs that push the content of the page down. We are changing the design so that each Shop Header menu item is its own page and will have its own link

There should be five by default 
Shop
About
Producers
Contact
Groups

Note: #2710 related

**Comment by daniellemoorhead** [comment] 2019-12-13 04:17
Duplicate of #4568

**Closed by daniellemoorhead** 2019-12-13 04:17 UTC
