### ISSUE TITLE
Profile only shops should not show when filtering

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1851] opened 2017-09-22 06:10 UTC
The shops filters should only apply to functioning shops, not shops that are profile only. In the case below the shop was previously active on OFN, but then became 'profile-only'. It's still showing in filter results.

![image](https://user-images.githubusercontent.com/10843056/30731420-9f56641c-9fb0-11e7-9cff-0a9a87581ba5.png)

**Comment by daniellemoorhead** [comment] 2017-09-26 22:44
Don't forget the bug label @sstead 😃

**Comment by myriamboure** [comment] 2018-07-13 09:22
I tried to reproduce but I'm not able to reproduce the error, I'm closing it for now @sstead but reopen if you test and it is still here!

**Closed by myriamboure** 2018-07-13 09:22 UTC
Labels: bug
