### ISSUE TITLE
Emails are not going through in CA

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#7634] opened 2021-05-13 09:54 UTC
## Description

As of May 12th 19:24 UTC (15:24 EDT) we're seeing what seems to be all email deliveries failing in OFN Canada. They all fail with the message `Net::SMTPAuthenticationError · 535-5.7.8 Username and Password not accepted. Learn more at`.

![Screenshot from 2021-05-13 11-43-29](https://user-images.githubusercontent.com/762088/118110036-351ce900-b3e2-11eb-9c94-5915ffdd0db3.png)

Error: https://app.bugsnag.com/open-food-network-canada-1/open-food-network-canada/errors/609c578f077ab200080df30a

## Expected Behavior
They should go through

## Actual Behaviour
They don't

## Workaround

There's none.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by sauloperez** [comment] 2021-05-13 10:02
These are the stats

![Screenshot from 2021-05-13 12-02-17](https://user-images.githubusercontent.com/762088/118110756-18cd7c00-b3e3-11eb-8a13-1e5183a11cd1.png)

As soon as we fix the issue we can retry them manually :crossed_fingers:

**Comment by sauloperez** [comment] 2021-05-13 10:13
This really looks like the issue we had months ago when someone changed the password of Canada's Gmail account. This instance uses Gmail's SMTP server. I'll investigate further though.

Again, IMO this is sustainable because AFAIK there's no way to see logs or configure anything from a dashboard.

**Comment by sauloperez** [comment] 2021-05-13 10:23
> we're seeing what seems to be all email deliveries failing in OFN Canada

No emails were successfully sent since the issue started.

![Screenshot from 2021-05-13 12-21-17](https://user-images.githubusercontent.com/762088/118113014-07d23a00-b3e6-11eb-9272-554e61629af7.png)

**Comment by sauloperez** [comment] 2021-05-13 10:28
I retried one of them and the issue is still there

```
I, [2021-05-13T10:27:28.403514 #26464]  INFO -- : 2021-05-13T10:27:28+0000: [Worker(delayed_job host:ca-prod pid:26464)] Job ConfirmOrderJob [23c45dd6-211f-4ad2-ae38-30c5ce4578b5] from DelayedJob(default) with arguments: [471651] (id=762350) (queue=default) RUNNING
E, [2021-05-13T10:27:29.451062 #26464] ERROR -- : 2021-05-13T10:27:29+0000: [Worker(delayed_job host:ca-prod pid:26464)] Job ConfirmOrderJob [23c45dd6-211f-4ad2-ae38-30c5ce4578b5] from DelayedJob(default) with arguments: [471651] (id=762350) (queue=default) FAILED (12 prior attempts) with Net::SMTPAuthenticationError: 535-5.7.8 Username and Password not accepted. Learn more at
```

**Comment by tschumilas** [comment] 2021-05-13 11:05
Is there anything we can do?

**Comment by tschumilas** [comment] 2021-05-13 11:21
We also de-selected 2-step verification -  would that have caused this?   So just confirming -  I just logged into the account and password has NOT changed.  Recovery phone is now back to me and I'm up and awake now if you need me do do anything.  I've also re-enabled 2 step verification in case this was caused by any of those things.

**Comment by andrewpbrett** [comment] 2021-05-13 15:28
It looks like when 2-step verification was toggled off and then back on, it deleted the app password that we were using to sign into the account. 

I created another app password, provisioned the CA server with it, and restarted delayed job and unicorn. This fixed the problem last time, but it appears to have no effect now. I checked and the new app password does appear to be provisioned correctly on the server. 

I think the best (possibly only) way to get this working again is to move off of using this Gmail account to send emails.

**Comment by sauloperez** [comment] 2021-05-13 15:54
Update on behalf of @andrewpbrett , he's reached out to customer support asking if we were blocked.

**Comment by tschumilas** [comment] 2021-05-13 15:54
Can you advise or help us do that. I am na for a few hrs now but maybe David can helpSent from my Galaxy
-------- Original message --------From: Andy Brett ***@***.***> Date: 2021-05-13  11:28 a.m.  (GMT-05:00) To: openfoodfoundation/openfoodnetwork ***@***.***> Cc: Theresa S ***@***.***>, Mention ***@***.***> Subject: Re: [openfoodfoundation/openfoodnetwork] Emails are not going through in CA (#7634) 
It looks like when 2-step verification was toggled off and then back on, it deleted the app password that we were using to sign into the account.
I created another app password, provisioned the CA server with it, and restarted delayed job and unicorn. This fixed the problem last time, but it appears to have no effect now. I checked and the new app password does appear to be provisioned correctly on the server.
I think the best (possibly only) way to get this working again is to move off of using this Gmail account to send emails.

**Comment by tschumilas** [comment] 2021-05-13 16:00
Thanks Andy -- and sorry for the hassle-- what would be a good next step on
my end?

**Comment by andrewpbrett** [comment] 2021-05-13 21:37
This is fixed now, CA is setup on SendGrid. David has the credentials for it and they're in the password manager as well. The emails that failed to send while it was down are now going out and should all arrive shortly.

**Closed by andrewpbrett** 2021-05-13 21:37 UTC
Labels: bug-s1

**Comment by sauloperez** [comment] 2021-05-14 06:46
> CA is setup on SendGrid

:astonished: that was fast!
