### ISSUE TITLE
Staging1 Confirm Email Links to Staging2

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#1337] opened 2016-12-16 11:45 UTC
I create a new enterprise on Staging1.

When confirming my email via the link within the email I am taken to Staging2 and asked to log in.
The email appears to come from staging2 and links me to staging2. 

My email address is unconfirmed on staging1.

Link in here:
![staging2confemail](https://cloud.githubusercontent.com/assets/8669848/21261670/cffd773a-c384-11e6-9b34-df8e2ec9184d.png)

Takes me here: 
http://staging2.openfood.com.au/enterprise/confirmation?confirmation_token=VaEDrDo6FxqErSFhiRdF

Marking as critical as SO testing has just gone out and you'll be getting a lot of enterprises created and needing to create order cycles.

**Note: You can get around this by copying the link from the email and editing in a text editor. Change the staging2 to staging1 and paste into the browser. Don't let this keep you from SO testing ;-)**

**Comment by daniellemoorhead** [comment] 2018-02-02 01:17
Duplicate of #394

**Closed by daniellemoorhead** 2018-02-02 01:17 UTC
Labels: australia, bug-s5
