### ISSUE TITLE
Error 500 when trying to log in as super admin to /admin

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5441] opened 2020-05-15 14:03 UTC
## Description

I've issue like this https://github.com/openfoodfoundation/openfoodnetwork/issues/3567
but i've translated all keys (zero,one,other)
It happens when I've added more products, with 1 product i've no 500 error, with 3 and 4 products i've 500 error

```
I, [2020-05-15 16:53:31#2858]  INFO -- : Started GET "/admin" for 127.0.0.1 at 2020-05-15 16:53:31 +0300
I, [2020-05-15 16:53:31#2858]  INFO -- : Processing by Spree::Admin::OverviewController#index as HTML
I, [2020-05-15 16:53:32#2858]  INFO -- :   Rendered admin/shared/_user_guide_link.html.haml (1.0ms)
I, [2020-05-15 16:53:32#2858]  INFO -- :   Rendered spree/admin/overview/_products.html.haml (2.4ms)
I, [2020-05-15 16:53:32#2858]  INFO -- :   Rendered spree/admin/overview/multi_enterprise_dashboard.html.haml within /spree/layouts/admin (6.9ms)
I, [2020-05-15 16:53:32#2858]  INFO -- : Completed 500 Internal Server Error in 52.9ms
F, [2020-05-15 16:53:32#2858] FATAL -- :
ActionView::Template::Error (translation data {:zero=>"У Вас нет активных товаров.", :one=>"У Вас один активный товар.", :other=>"У Вас %{count} активных товаров."} can not
 be used with :count => 4):
    12:     - if @product_count > 0
    13:       %div.seven.columns.alpha.list-item
    14:         %span.six.columns.alpha
    15:           = t(".active_products", count: @product_count )
    16:         %span.one.column.omega
    17:           %span.icon-ok-sign
    18:       %a.seven.columns.alpha.button.bottom.blue{ href: "#{admin_products_path}" }
  app/views/spree/admin/overview/_products.html.haml:15:in `_app_views_spree_admin_overview__products_html_haml__207721215433571024_47333462518160'
  app/views/spree/admin/overview/multi_enterprise_dashboard.html.haml:16:in `_app_views_spree_admin_overview_multi_enterprise_dashboard_html_haml__3988539692030240509_47333
463013160'
  app/controllers/spree/admin/overview_controller.rb:15:in `index'
```
```
irb(main):004:0> I18n.t('spree.admin.overview.products.active_products.zero')
=> "У Вас нет активных товаров."
irb(main):005:0> I18n.t('spree.admin.overview.products.active_products.one')
=> "У Вас один активный товар."
irb(main):006:0> I18n.t('spree.admin.overview.products.active_products.other')
=> "У Вас %{count} активных товаров."
```
```
irb(main):001:0>  I18n.t('spree.admin.overview.products.active_products',count:0)
=> "У Вас нет активных товаров."
irb(main):002:0>  I18n.t('spree.admin.overview.products.active_products',count:1)
=> "У Вас один активный товар."
irb(main):003:0>  I18n.t('spree.admin.overview.products.active_products',count:2)
I18n::InvalidPluralizationData: translation data {:zero=>"У Вас нет активных товаров.", :one=>"У Вас один активный товар.", :other=>"У Вас %{count} активных товаров."} can not be used with :count => 2
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/pluralization.rb:35:in `pluralize'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/base.rb:40:in `translate'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/fallbacks.rb:45:in `block (2 levels) in translate'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/fallbacks.rb:44:in `catch'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/fallbacks.rb:44:in `block in translate'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/fallbacks.rb:42:in `each'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n/backend/fallbacks.rb:42:in `translate'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n.rb:157:in `block in translate'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n.rb:153:in `catch'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/i18n-0.6.11/lib/i18n.rb:153:in `translate'
        from (irb):3
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
        from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
        from ./openfoodnetwork/current/script/rails:6:in `require'
        from ./openfoodnetwork/current/script/rails:6:in `<main>'
irb(main):004:0>
```

## Steps to Reproduce

1. Log in as super admin
2. Go to /admin
3. Get 500

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.9.6
* Browser name and version: Firefox 68.8.0esr
* Operating System and version (desktop or mobile): Desktop openSUSE 15.1

**Comment by romale** [comment] 2020-05-15 14:28
This issue happen only if I logged as super admin. From enterprise owner (manager?) it's works (without 500 error)

**Comment by romale** [comment] 2020-05-15 16:12
It also happens on ofn2.9.8

**Comment by luisramos0** [comment] 2020-05-17 21:12
pls see #5445 this is related to the translations file. I'd say the translations are not loaded correctly so this is a duplicate of #3567

**Comment by romale** [comment] 2020-05-28 09:23
This command solve issue
https://github.com/openfoodfoundation/openfoodnetwork/issues/5436#issuecomment-634755002

**Comment by romale** [comment] 2020-10-07 07:56
Still not working as expected, even after being transferred to transifex. I am using the ru.yml translation file from transifex. All keys are translated:
```
       overview:
         enterprises_header:
           ofn_with_tip: Enterprises are Producers and / or Centers and are the primary organizational unit within the Open Product Network.
         products:
           active_products:
             zero: "You have no active items."
             one: "You have one active product."
             other: "You have% {count} active items."
```

**Comment by romale** [comment] 2020-10-07 08:01
```
I, [2020-10-07 10:49:51#1226]  INFO -- : Started GET "/admin" for 127.0.0.1 at 2020-10-07 10:49:51 +0300
I, [2020-10-07 10:49:51#1226]  INFO -- : Processing by Spree::Admin::OverviewController#index as HTML
I, [2020-10-07 10:49:51#1226]  INFO -- :   Rendered admin/shared/_user_guide_link.html.haml (0.9ms)
I, [2020-10-07 10:49:51#1226]  INFO -- :   Rendered spree/admin/overview/_products.html.haml (2.2ms)
I, [2020-10-07 10:49:51#1226]  INFO -- :   Rendered spree/admin/overview/multi_enterprise_dashboard.html.haml within spree/layouts/admin (7.5ms)
I, [2020-10-07 10:49:51#1226]  INFO -- : Completed 500 Internal Server Error in 51ms
F, [2020-10-07 10:49:51#1226] FATAL -- : 
ActionView::Template::Error (translation data {:zero=>"У Вас нет активных товаров.", :one=>"У Вас один активный товар.", :other=>"У Вас %{count} активных товаров."} can not be used with :count => 12):
    12:     - if @product_count > 0
    13:       %div.seven.columns.alpha.list-item
    14:         %span.six.columns.alpha
    15:           = t(".active_products", count: @product_count )
    16:         %span.one.column.omega
    17:           %span.icon-ok-sign
    18:       %a.seven.columns.alpha.button.bottom.blue{ href: "#{admin_products_path}" }
  app/views/spree/admin/overview/_products.html.haml:15:in `_app_views_spree_admin_overview__products_html_haml___4999575537669568_47374283392140'
  app/views/spree/admin/overview/multi_enterprise_dashboard.html.haml:16:in `_app_views_spree_admin_overview_multi_enterprise_dashboard_html_haml___1278353207081497372_47374283898700'
  app/controllers/spree/admin/overview_controller.rb:15:in `index'
```

**Comment by RachL** [comment] 2021-06-06 10:51
@romale have you find the root cause here? Is this fixed?

**Comment by RachL** [comment] 2022-04-25 13:25
Closing, but we can reopen if it's still reproductible.

**Closed by RachL** 2022-04-25 13:25 UTC
