### ISSUE TITLE
Admin cannot bulk edit orders -  hangs in v2

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4027] opened 2019-07-10 03:07 UTC
## Description

Checking if this is expected?    In V2,  a user cannot edit orders from the 'orders' menu.  They must go to the 'bulk order mgmt' menu.    But admin is still able to edit orders in the 'orders' menu as before.   BUT,  the 'bulk order mgmt' menu doesn't open for admin in V2 -  just hangs.

## Expected Behavior

Not sure  - should any user be able to edit orders on the 'orders' screen,  just as admin can?  And, admin should be able to access the bulk order mgmt screen.

## Steps to Reproduce

1.create an order,  and as a user try to edit -  add a variant - see that you need to go to the bulk edit orders page to do this
2. as admin - see that you can add variants as before from the order screen
3. as admin -  see that the bulk order mgmt tab does not open -  hangs (I waited 15 min)
4.

## Animated Gif/Screenshot

![user sees no edit options](https://user-images.githubusercontent.com/13171778/60936916-c11cd180-a29c-11e9-9030-e7b94b417be7.jpg)
![admin - edit orders tab](https://user-images.githubusercontent.com/13171778/60936993-fb866e80-a29c-11e9-80f4-66c2a8d5addc.jpg)
![admin can't access bulk edit orders](https://user-images.githubusercontent.com/13171778/60937338-0ee60980-a29e-11e9-8e9e-b493fed3b1cb.jpg)

## Context

users need to edit orders -  I just want to make sure it is expected that users and admin have different capabilities on the orders screen in v2.
And -  admin should be able to bulk edit orders I imagine.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by luisramos0** [comment] 2019-07-15 10:17
this must be related to #4038, I'll try to replicate.

**Comment by luisramos0** [comment] 2019-07-15 13:20
from slack

rachel [10:34 AM]
@tschumilas what's the severy of this: https://github.com/openfoodfoundation/openfoodnetwork/issues/4027 are you still experiencing it?


tschumilas [1:42 PM]
Yes - still experiencing -   admin can edit orders on the 'orders' screen - including deleting items (as was in v1),  but admin cannot access bulk order managment - hangs.    A manager  -  its the opposite.  If they choose orders -- edit order -   they can add but not delete a variant.  BUT -  the manager can access the bulk orders management screen,  and delete items there.

**Comment by RachL** [comment] 2019-07-15 14:42
I'm not sure what we call admin vs manager here, is it super admin? 

Let's keep #4038 for the edit order part. So here the problem is that the BOM page has an infinite spinner right?

**Comment by tschumilas** [comment] 2019-07-15 14:51
Yes - when I said 'admin'  I mean super-admin.  Manager is any other user with a shopfront.

**Comment by luisramos0** [comment] 2019-07-15 17:18
As seen in previous issues in the BOM, this page is very picky: if there is one single variant (or variant override) with a problem, this page will fail for superadmins and any users that have access to that variant (variant override).
So, I'd bet there's a broken variant somewhere.

The error stack trace is this one:
```
NoMethodError (undefined method `supplier_id' for nil:NilClass):
  app/serializers/api/admin/line_item_serializer.rb:7:in `supplier'
  app/controllers/spree/admin/base_controller_decorator.rb:79:in `render_as_json'
  app/controllers/admin/bulk_line_items_controller.rb:9:in `index'
```

This means it is a line_item without product... it looks very familiar. This is **most probably** already resolved by #4030

I am not sure but this can probably be replicated by deleting a product and then going to the BOM page.

Anyway, this 4030 PR will be released as part of the next release 2.2.1. Next week we should be able to deploy 2.2.1 to Canada.

**Comment by luisramos0** [comment] 2019-07-15 17:20
I put S3, please correct if you think it should be S2.
Also, please let me know if we can just wait for 2.2.1 in Canada or shall we investigate further.

**Comment by tschumilas** [comment] 2019-07-15 17:35
It really only effects me -   so yes,  I can wait.  I can add user logins to any enterprise I need to help in the meantime.

**Comment by RachL** [comment] 2019-07-25 13:08
@tschumilas I've tested with my super admin account on OFN Canada and with the latest release you can reach BOM, it does not hang anymore. 

Ability to edit order with manager access on order edit page will be brought by next release (in around 2 weeks more or less). 

Feel free to reopen if you think something is missing.

**Closed by RachL** 2019-07-25 13:08 UTC
Labels: blocked, bug-s3
