### ISSUE TITLE
Confused Packing Reports - same name customers

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1134] opened 2016-08-21 09:33 UTC
Please investigate:
Two customers have the same surname. They order one each of the same product. The "pack by customer" report allocates them correctly but the pack by supplier report gives both items to one of the two customer and none to the other. 

I will share the customer details privately with @lin-d-hop Lynne by email. Lynne is welcome to forward to others by email.

The affected order numbers are R548817735 and R373471107.

**Comment by MagsHall** [comment] 2016-08-22 15:18
I have replicated this problem using OFN Test Hub, order cycle 18th August Cycle. Orders appear correct using 'Pack by Customer' report, but in 'Pack by Producer', if customers with the same surname have ordered the same product, this is bundled together under one customer. 

This happens for people with identical names but different emails, and those with just the same surname. I have tried it with both user accounts and checking out as a guest and the same thing happens. 'Pack by Producer' seems to be assuming that customers with the same name are the same person, regardless of order no, email address or other details of the order.

**Comment by rhodri** [comment] 2016-09-07 16:17
Looking at the code it seems like the issue is here, where we group by last name: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/packing_report.rb#L86

So I'll switch this to group by email instead!

**Comment by lin-d-hop** [comment] 2016-10-04 14:02
PR #1175

**Comment by lin-d-hop** [comment] 2016-10-20 07:57
Merged. Thanks!

**Closed by lin-d-hop** 2016-10-20 07:57 UTC
Labels: bug, reports, uk
