### ISSUE TITLE
Click buttons not visible when creating profile on OFN

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1810] opened 2017-09-06 08:16 UTC
A: action | P: problem | S: solution

A: register on OFN as a hub/shop/etc.
P: I get an 'agree with the terms' window, but I can't see where to continue. You apparently have to scroll down to see that button.
![image](https://user-images.githubusercontent.com/31434588/30101359-5f614bf2-932f-11e7-9b0a-fef8515b61ba.png)
P: same happens when you need to tell if you're a producer yes / no. Have to scroll down for button to continue, but is not obvious. 
![image](https://user-images.githubusercontent.com/31434588/30101370-6ba452b0-932f-11e7-9674-65dd60ff8d9b.png)
S: make the buttons directly visible. --> easy and fast to click, no confusion/irritation for the user

**Comment by myriamboure** [comment] 2017-09-06 09:21
100% agree :-)

**Comment by sauloperez** [comment] 2017-09-06 10:53
sort of duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/1766

**Comment by daniellemoorhead** [comment] 2017-09-08 05:32
Duplicate of #1766

**Comment by RachL** [comment] 2019-04-01 15:21
@daniellemoorhead hey I didn't know you could mark things as duplicate! Does this mean this issue will be closed when #1766 is closed?

**Comment by daniellemoorhead** [comment] 2019-04-01 22:57
Not sure @RachL. We should test that!

**Comment by sigmundpetersen** [comment] 2019-08-19 10:02
So #3791 was merged and it didn't close this automatically, so we have now tested that 😊 Closing manually

**Closed by sigmundpetersen** 2019-08-19 10:02 UTC
