### ISSUE TITLE
[Spree Upgrade] I get the snail page when trying to access the checkout page

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3393] opened 2019-01-25 02:03 UTC
## Description
This issue could be related to other issues relating to the shopfronts (https://github.com/openfoodfoundation/openfoodnetwork/issues/3392
https://github.com/openfoodfoundation/openfoodnetwork/issues/3391
), but I'll log it as a bug anyway. 

We need to get this bug fixed before much more Spree testing can be done

While testing Spree I'm finding that I can't access the final page in checkout, when I try to reach the checkout page I get the snail error page.

## Expected Behavior
I should be able to checkout 

## Steps to Reproduce
1. Head to any shop on French staging and try to checkout
E.g. https://staging.openfoodfrance.org/producer-of-pommes/shop

## Your Environment
French staging, spree upgrade, PC, Chrome, Desktop

**Comment by luisramos0** [comment] 2019-01-27 12:09
I think this is related to the shipping methods being used. We need to review all calculators (flat rate, per weight, etc) being used in shipping methods, payment methods and enterprise fees and make sure they all work in each of these different places.
I'll take this one this week.

**Comment by luisramos0** [comment] 2019-01-27 20:10
Long tech story short, spree v2 introduces copy pasted classes for the calculators of shipping methods. I totally missed this change until today. I put a simple solution to the problem by ignoring the new version of the calculators in v2 (it's the same logic) and keeping to our own calculators that are throughly tested by our test suite. Long tech story available in the PR #3400.

@sstead it's still pending code review but I've deployed the PR and the issue seems resolved.

**Comment by luisramos0** [comment] 2019-02-07 23:49
actually, the PR could have been staged.
the solution has been and still is in staging FR to be validated and I can now stage 2-0-stable branch so we can validate the problem is fixed in 2-0-stable (not the PR branch).
we can close the issue when @sstead or another tester validates it's fixed.

@sigmundpetersen basically we are in the transition phase where v2 PRs will start following normal PR workflow with staging and testing.

**Comment by luisramos0** [comment] 2019-02-14 18:55
as per #3400 testing, fixed :tada:

**Closed by luisramos0** 2019-02-14 18:55 UTC
