### ISSUE TITLE
Need help with this issue

### ISSUE THREAD

**Issue by kefayatullahkhadem** [openfoodfoundation/openfoodnetwork#11285] opened 2023-07-27 00:02 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by mkllnk** [comment] 2023-07-27 06:42
Duplicate of #11286.

**Closed by mkllnk** 2023-07-27 06:42 UTC
