### ISSUE TITLE
[Spree 2.1] Missing translations keys in Enterprise settings left menu

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5436] opened 2020-05-15 08:26 UTC
## Description

Whole left menu in English. 

## Steps to Reproduce
1. Log in as manager and go to Enterprise settings
2. See left menu

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/82028816-6612f280-9696-11ea-9e8a-b23346df4082.png)

## Severity

This is an s2 for non english instances

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment] 2020-05-16 11:22
This is caused by the manual process I used to deploy an extra language in uk staging.
I redeployed now and it looks good again.

ping @Matt-Yorkley fyi there's a manual fix in uk staging to make FR availalble and not just en_GB.

**Comment by romale** [comment] 2020-05-17 10:03
I've this too on 2.9.6, 2.9.8. Or is it not related?
![image](https://user-images.githubusercontent.com/928628/82141436-84b3ed80-983e-11ea-9dcd-89896511908d.png)

**Comment by luisramos0** [comment] 2020-05-17 10:42
hello @romale
Is that Russian? If so, your problem is missing translations, you can add it in transifex here:
https://www.transifex.com/open-food-foundation/open-food-network/translate/#ru/enyml/80855452?q=key%3Aprimary_Details

Russian is still mostly untranslated:
![image](https://user-images.githubusercontent.com/1640378/82142319-5a106780-9833-11ea-88f8-8deb6f64edc2.png)

**Comment by romale** [comment] 2020-05-17 10:58
@luisramos0 , yes it's russian. Now, i translate via local yaml file. I don't use transifex yet.
May be this will help
```
openfoodnetwork@ofn-prod:~$ cd apps
openfoodnetwork@ofn-prod:~/apps$ RAILS_ENV=production ./openfoodnetwork/current/script/rails console
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/openfoodnetwork/.gem/ruby/2.3.0/gems/activesupport-3.2.22.5/lib/active_support/dependencies.rb:236:in `load_dependency'
Instance method "invalid?" is already defined in ActiveRecord::Base, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.
Instance method "open" is already defined in Object, use generic helper instead or set StateMachine::Machine.ignore_method_conflicts = true.
Loading production environment (Rails 3.2.22.5)
irb(main):001:0> I18n.t('primary_details')
=> "Основная Информация"
irb(main):002:0>
```
It's ru_RU.yml in text editor
![image](https://user-images.githubusercontent.com/928628/82142621-5f2ae200-9846-11ea-94ef-3e0d934be35a.png)

**Comment by luisramos0** [comment] 2020-05-17 14:01
Hi @romale your problem is most probably related to your custom translations process.
I dont think we will support a different translation process not in transifex. You can upload your file to transifex and follow the normal process.

**Comment by filipefurtad0** [comment] 2020-05-18 14:16
@luisramos0 ,

This is now fixed, the menu is now displayed correctly:
![image](https://user-images.githubusercontent.com/49817236/82223336-6d4a3280-991a-11ea-8a07-feb1db070e1d.png)
:+1:

**Closed** 2020-05-18 19:46 UTC
Labels: bug-s2

**Comment by romale** [comment] 2020-05-27 13:54
> Hi @romale your problem is most probably related to your custom translations process.
> I dont think we will support a different translation process not in transifex. You can upload your file to transifex and follow the normal process.

Hi @luisramos0 . In this file
`/home/openfoodnetwork/apps/openfoodnetwork/current/config/application.yml`
i've variable
`AVAILABLE_LOCALES: en,ru_RU`
for testing, in file 
`/home/openfoodnetwork/apps/openfoodnetwork/current/config/locales/en.yml`
i was change 
`  primary_details: "Primary Details"`
to
`  primary_details: "BlaBla"`
systemctl restart nginx && systemctl restart unicorn_openfoodnetwork (and even reboot OFN host)

But no result, the interface shows "Primary Details" .

Can the information from this en.yml file with translations be written to some other places?

And for the experiment I translated this word here https://www.transifex.com/open-food-foundation/open-food-network/translate/#ru/enyml/80855452?q=key%3Aprimary_Details . Will it be available in upcoming releases?

if this is not reproduced on other installations or test instances, then there are no questions.

**Comment by luisramos0** [comment] 2020-05-27 14:46
You probably need to recompile assets which part of the normal deployment process.

Yes, the data in transifex will be committed to git and included in the next release. We should do that. 
We may need to add the ru.yml to github as a manual step I am not sure, anyway, it's very easy. It looks like you already have a lot of translations done. Do you know how to upload your ru_RU.yml file to transifex? If you dont, let me know I can help.

**Comment by romale** [comment] 2020-05-27 15:50
Now this solved, yyyes! :)
this command helped me:
```
su - openfoodnetwork
cd /home/openfoodnetwork/apps/openfoodnetwork/current
RAILS_ENV=production bundle exec rake assets:clean assets:precompile
systemctl restart unicorn_openfoodnetwork
```
My translation file works too.

![image](https://user-images.githubusercontent.com/928628/83041467-2ca09680-a049-11ea-8586-0cf2375c0ffe.png)

About push my translation on transifex. I will do it, but some time later. I need to start ofn instance in production before it.
