### ISSUE TITLE
[Spree Upgrade] Fix spec/features/admin/orders_spec.rb (1 broken spec)

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#3485] opened 2019-02-13 12:24 UTC
## Description

`spec/features/admin/orders_spec.rb:185` is still failing in 2-0-stable's build.

This is the error:

```
Failures:

  1) 
    As an administrator
    I want to manage orders
 capture payment from the orders index page
     Failure/Error: expect(@order.reload.payment_state).to eq "paid"
     
       expected: "paid"
            got: "balance_due"
     
       (compared using ==)
     # ./spec/features/admin/orders_spec.rb:197:in `block (2 levels) in <top (required)>'
```

**Comment by sigmundpetersen** [comment] 2019-02-13 13:00
Does not fail in #3299 though https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3299/builds/4

**Comment by luisramos0** [comment] 2019-02-13 13:08
this is the same as #3113 after fixing the translation problem here: https://github.com/openfoodfoundation/openfoodnetwork/issues/3113#issuecomment-451743948

**Comment by sauloperez** [comment] 2019-02-13 16:38
After some investigation the problem seems to be that OFN's OrderUpdater is not always being picked up so we're using Spree's `#updater_payment_state` instead of OFN's. It seems that the calls to `#ensure_correct_adjustment_with_included_tax` that are triggered from https://github.com/openfoodfoundation/openfoodnetwork/blob/2-0-stable/spec/features/admin/orders_spec.rb#L22 go through `Spree::OrderUpdater` instead. I have to say though that this while `background` block is very suspicious.

**Comment by sauloperez** [comment] 2019-02-13 16:50
I might not be related to that block only. The common pattern I see is that the calls that end up in `Spree::OrderUpdater#update_payment_state` are either originated from `app/models/spree/payment_decorator.rb`'s `#ensure_correct_adjustment` or `app/models/spree/shipment_decorator.rb`'s `#ensure_correct_adjustment_with_included_tax`, so it really smells like an load order issue.

**Comment by luisramos0** [comment] 2019-02-14 09:11
wow, good work!
you unassigned yourself, do you have plans for this? what shall we do?
shall we merge my original solution (call update_shipping_fees in the factories) so we get a green build and then keep on finding a proper solution for this issue?

**Comment by sauloperez** [comment] 2019-02-14 11:24
I think I have other things assigned already that I want to close first while someone else could pick up this one. I'm afraid that fixing factories won't fix the actual problem (if any) in production.

**Comment by luisramos0** [comment] 2019-02-14 12:40
Fixing the factories makes the build green.
There is a problem but it's interesting that we don't know if it really affects some part of the system...

So, short term (I mean today), I'd merge my PR (Maikel had approved it already so if you agree we can do it now) and keep this task open for investigation. Can we do this?
Thanks.

**Comment by sauloperez** [comment] 2019-02-14 13:49
I just want to get it green :trollface: I got lost with the issues. AFAIK this spec is not covered in https://github.com/openfoodfoundation/openfoodnetwork/pull/3299 AFAIK

**Comment by luisramos0** [comment] 2019-02-14 13:52
ah, I understand now.
this is a duplicate of #3113 the spec is the same, just a different error message: "capture payment from the orders index page"

**Comment by sauloperez** [comment] 2019-02-14 13:53
Ah, that's right I remember noticing the different error. Well, I'm caught digging into #3299 I fixed some but let's see if I survive.

**Comment by luisramos0** [comment] 2019-02-26 09:09
I am closing this, it's a duplicate of the already closed 3113.

**Closed by luisramos0** 2019-02-26 09:09 UTC
