### ISSUE TITLE
Bulk Edit Products page search categories not visually resetting with clear filter button 

### ISSUE THREAD

**Issue by JenRSmith** [openfoodfoundation/openfoodnetwork#5592] opened 2020-06-12 05:15 UTC
## Description
When clicking the clear filter button on the Bulk Edit Products page, any filters applied remain visually active, although they don't affect the subsequent searches. This may cause confusion to the user who has selected to clear the previous filters.

## Expected Behavior
All filters should show in their inactive state - nothing selected.

## Actual Behaviour
Any filter previously selected remains visually active, although not functionally.

## Steps to Reproduce

1. Login as Admin>Accounts>Products>Bulk Edit Products
2. Add a product into search (or leave blank)
3. Apply filters (producer/category/import date)
4. Click clear filters button
5. Filter remains in its previous state, appears active

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/54344358/84466997-20117480-acbe-11ea-987f-59e6f663f0b4.png)

![image](https://user-images.githubusercontent.com/54344358/84467005-299adc80-acbe-11ea-99d0-4279dca4c175.png)

## Workaround
This is a visual bug, it doesn't affect subsequent searches.

## Severity
bug-s4

## Your Environment

* Version used: https://staging.katuma.org/
* Browser name and version: Chrome Version 83.0.4103.97 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by filipefurtad0** [comment] 2020-06-26 11:37
Hi @JenRSmith ,

Thank you for adding this issue!

I ran into this as well, while testing another PR. I think it can lead to misleading search results, if a search is performed after clearing filters. For example, adding to the Steps to Reproduce you described above:

6. Add an Import Date
7. Press Filter Results

One sees that what is visually displayed in the filters is not being considered when performing a new search. It's easy to end up with:

![image](https://user-images.githubusercontent.com/49817236/85851859-6a5b2100-b7a7-11ea-9495-1ce5f8fbc6aa.png)

It's also possible to reach less obvious but wrong search results, like in this case, in which the Category column needs to be added for this to spot that something is not right:

![image](https://user-images.githubusercontent.com/49817236/85852297-33d1d600-b7a8-11ea-8ae5-a68d72747805.png)

Perhaps this makes it a bug-s3?

**Comment by luisramos0** [comment] 2020-06-26 12:36
yeah, I agree s3
This must be a little js tweak, I am going to mark it as good first issue.

Also, I see this in multiple staging servers, but I cant replicate this locally with sample data...

**Comment by meronokbay** [comment] 2021-09-04 22:42
Can I pick up this issue?

**Comment by meronokbay** [comment] 2021-09-05 01:12
I tried reproducing this locally, but the clear filter button is working as expected. Could this be due to the lack of options in the "import date" field? I tried uploading a template csv file in Product Import, but I got a no valid entry error.
![image](https://user-images.githubusercontent.com/22526062/132111669-00c5657a-9e19-4d9a-a0af-33c92a66fd9f.png)

**Comment by RachL** [comment] 2021-09-06 07:43
hey @meronokbay nice catch! I can't reproduce this issue as well. closing as it appears to be fixed 🎉

**Closed by RachL** 2021-09-06 07:43 UTC
Labels: good first issue, bug-s3, hackathon
