### ISSUE TITLE
Missing translation key "spree.tax rate"

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#6350] opened 2020-11-09 15:53 UTC
## Description

In path
/admin/tax_rates

A current key has space: 'spree.tax rate'
Perhaps this is the reason that the phrase was left without translation

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/98563813-ad341600-22bc-11eb-9aea-081a692b0624.png)

## Your Environment

* Version used: 3.3.1
* Browser name and version: FF 78.4.0esr
* Operating System and version (desktop or mobile): Desktop

**Comment by bradkIsaacs** [comment] 2020-11-18 16:13
What language is this?

**Comment by filipefurtad0** [comment] 2020-11-18 17:38
Hey @romale - thanks for reporting this!
I'm closing this issue as it is a duplicate of #6387 :+1:

**Closed by filipefurtad0** 2020-11-18 17:38 UTC
Labels: bug-s4
