### ISSUE TITLE
User experience on mobile devices

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1092] opened 2016-07-06 01:29 UTC
Our intern Kathryn will be testing the shopfront on various devices over the coming weeks. This is a collection of the bugs that are out there...

I tested the website using  https://openfoodnetwork.org.au/sally-s-demo-farm/shop on both my iPhone and my iPad using two different browsers. Everything looked okay. All of the images appeared, the columns all lined up and all of the filters and tags worked. Conformation emails were sent and received for each of the orders I carried through the whole process. There were a few things from each browser and device that I have listed below.

iPhone (iOS 9.3.2) - Safari:

Doesn’t show the pie chart/price breakdown option when shopping.  Have to type in the number of items you want, there are no up/down buttons. I have attached an image for these problems which appears the same on each device and browser experiencing the same issue.
![image](https://cloud.githubusercontent.com/assets/10843056/16604830/c0473bd4-436c-11e6-9e8a-f0f944dd7dec.png)

iPad (iOS 9.3.2) - Safari:

During check out, the box that shows the order has text rather than number totals under shipping, transaction fee and total. Doesn’t let check out as guest. Couldn’t get past this point to check if the shipping details, etc. worked. Have to type in the number of items you want, there are no up/down buttons. I have attached an image of the problem with the text rather than number totals.
- Raised in https://github.com/openfoodfoundation/openfoodnetwork/issues/1013
  ![image](https://cloud.githubusercontent.com/assets/10843056/16604831/c9cdbc28-436c-11e6-8723-29c05eb173b8.png)

iPad (iOS 9.3.2) – Google Chrome

Have to type in the number of items you want, there are no up/down buttons

iPhone (iOS 9.3.2) – Google Chrome

Doesn’t show the pie chart/price breakdown option when shopping. Have to type in the number of items you want, there are no up/down buttons

**Comment by sstead** [comment] 2016-07-22 05:32
Android - Chrome 
Some dropdown menus were split on the screen and difficult to click on. Included select enterprise for new OC and for viewing Customers in the back.
![image](https://cloud.githubusercontent.com/assets/10843056/17047434/59eba5de-5021-11e6-9bd1-7065efbe9682.png)

**Comment by kirstenalarsen** [comment] 2016-07-22 05:44
given the discussion at http://community.openfoodnetwork.org/t/ux-upgrades/640, I think is useful to label issues like this . . "mobile" or "ux"? @lin-d-hop @sstead @daniellemoorhead - anyone have a view?

**Comment by pmackay** [comment] 2016-07-23 10:24
@kirstenalarsen labels added.

**Comment by OliverUK** [comment] 2016-08-03 08:34
Does it sound reasonable to focus any work on improving the front end first? I'd expect hub admins to be using a computer but I may be old-fashioned in this regard.

**Comment by NickWeir63** [comment] 2016-08-14 14:17
Here is some feedback from a Stroudco shopper using a tablet:
**A few blips – clicking on producer info eg Jessies Ladies Milk & Winstons Ice Cream brought up some corrupted text. Others were fine eg Wharf Farm. I couldn’t face checking all the producers!!
Clicking on the categories eg ‘Dairy’ correctly brought up dairy stuff I then moved onto ‘Bread & Baking’ & the page stayed on Dairy. I was able to reach the Bread by typing that into the search box. The ‘Tea\Coffee’ under the ‘+10 More Items’ worked the 1st time but non of the other categories came up & nor did the Tea\Coffee when I tried it again. Returning to the Dairy category brought up the Alcohol products.**

**Comment by lin-d-hop** [comment] 2016-08-14 16:55
@NickWeir63 They don't sound like specifically tablet based issues to me.
@MagsHall Are you able to check the above walk through on another device to see if you can replicate?
Thanks :-)

**Comment by oeoeaio** [comment] 2016-08-15 00:21
@NickWeir63 @lin-d-hop @OliverUK Just looking at the feedback from your customer using a tablet. The pattern of category switching, the observed changes and the language used to describe it (eg. "moved onto Bread & Baking") suggest to me that perhaps this particular customer does not realise that clicking a new category does not "move you on" to that category, but rather that it adds that category of products to what is already selected. This could be perhaps because the UI for the filters themselves are not providing visual cues in they way they are supposed to for some reason? Just hypothesising...

For example: if I go to the Stroudco shop and click the 'Dairy' filter, the list of products changes and I can see some dairy products. If I then click on Bread & Bakery, nothing happens in my immediate field of vision. This is because those products have been added to the list, but are visible further down the page (possibly due to Stroudco having set the ordering of the categories in the shop in this way, possibly because that is the order that the server decided to render them in). If I then type 'Bread' into the filter, the Bread & Bakery products come to the top of the list, because all of the Dairy products are filtered out. This exactly matches the behaviour observed by the user...is anyone able to sit with them and confirm that this is a possibility?

If I am right, our issue here is UX, rather than mobile/tablet specific performance.

**Comment by NickWeir63** [comment] 2016-08-15 08:22
thanks @oeoeaio yes you are right that is exactly what is happening.  I will explain that to the shopper and when we are working on UX we need to reference https://github.com/openfoodfoundation/openfoodnetwork/issues/985
i have checked the shopper's report of corrupted text and that is not a tablet issue either.  the text is corrupted in the admin screen (see below).  I wonder if this happened as part of a recent deployment.  I will check with @OliverUK to see if he has noticed the corruption before.  Maybe we can correct the corruption and check it again after the next deployment.
Thanks again Rob for getting onto this so quickly
![screenshot 2016-08-15 09 17 05](https://cloud.githubusercontent.com/assets/10517702/17659339/bfa01f12-62c9-11e6-858b-c3197148239f.png)

**Comment by OliverUK** [comment] 2016-08-15 08:31
@NickWeir63  Not something I've been made aware of before.

**Comment by NickWeir63** [comment] 2016-08-15 08:33
Feedback from another shopper using an iPad:
**Hi
Yes worked well
Great 
Thanks
Caroline Denny**
.....and she put in an order for the first time in months!! :)

**Comment by NickWeir63** [comment] 2016-08-15 08:57
OK i have updated the Jess's Ladies text to remove the corruption.  let's keep a regular eye on it and see if it corrupts again.
At some point we need to go through the other producers and correct any other corrupt ones.

I will check with Sara (does she not have a github name?) if Tamar have seen any corruption.  this may have been caused by Aidan's import of data from the stroudco legacy system

**Comment by Rocksj** [comment] 2016-08-15 09:58
Just checked a few of our Producer Profiles and all looks fine here @NickWeir63

**Comment by myriamboure** [comment] 2018-02-28 08:24
Sorting at the mess of issues/features/ in this:
- retested and open an issue on pie chart not appearing on mobile : https://github.com/openfoodfoundation/openfoodnetwork/issues/2102 (feature that is supposed to work but not working)
- for tablet issue I need to find a tablet to retest but opened an issue to keep that on track: https://github.com/openfoodfoundation/openfoodnetwork/issues/2103
Closing this one then. Please in the future let's try to open one issue per bug, and all feature improvement should be treated as wishlist/icebox.

**Closed by myriamboure** 2018-02-28 08:24 UTC
Labels: bug
