### ISSUE TITLE
Can not compile invoices pdf

### ISSUE THREAD

**Issue by nicolasVr** [openfoodfoundation/openfoodnetwork#12215] opened 2024-02-28 15:16 UTC
## Description
On French Instance compilation of invoices pdf doesn't work in some cases. The problem doesn't appear when printing from order page.

## Expected Behavior
When required pdf should be generated.

## Actual Behaviour
Only waiting screen is displayed

## Steps to Reproduce
Using Firefox 123.0 (Ubuntu), I ask printing of 2 orders on shop with ID 4523. The screen below stalls for more than 10 minutes without ending.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/46503289/7f8c462b-1017-4e62-8e49-4edb7f650317)

This was tried with at least another shop as super-admin.

The same reports were edited correctly using chromium on the same computer (and with Firefox by another user with another computer).

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by filipefurtad0** [comment] 2024-02-28 15:45
To the dev picking this up - it looks like this is the related Bugsnag error: https://app.bugsnag.com/open-food-france/coopcircuits/errors/65d4639bd6f75a0008d8ef8c?filters[error.status]=for_review&filters[event.since]=30d

Transcribing as errors for Coopcircuits are kept for 30 days only:
```

app/jobs/bulk_invoice_job.rb:27:in `sorted_orders': undefined method `map' for nil:NilClass

    order_ids.map { |id| orders_by_id[id.to_i] }
             ^^^^ (NoMethodError)
    from app/jobs/bulk_invoice_job.rb:10:in `perform'
```

**Comment by abdellani** [comment] 2024-02-28 21:49
I noticed the same bug on AU-Prod
https://onenr.io/0EjOnNxlpR6

The job was created with **bulk_ids = null**.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/16113997/b7f4420c-5a2e-4c62-8404-c501c2c614a0)

This is weird because if you don't select any orders, the actions dropdown will be disabled.

**Comment by abdellani** [comment] 2024-02-28 23:40
I tried to inspect the issue on Newrelic.
Between 8:53 and 8:55, there are [5 calls to bulk invoice](https://onenr.io/0LREVgz4bja) (through "StimulusReflex::Channel#receive") and [ 5  records](https://onenr.io/0BR6Z6pqdRO) containing "Enqueued jobs" (This is printed when sidekiq load a job).
5 of 5  `bulk_invoice` calls have an array of IDs and they are identical.
2 of 5 jobs have  `bulk_ids = null`

is it safe to conclude that the issue is not on the UI?

**Comment by abdellani** [comment] 2024-02-29 15:58
I suggest waiting for this PR
https://github.com/openfoodfoundation/openfoodnetwork/pull/11918
it updates the affected part.

**Comment by abdellani** [comment] 2024-05-09 14:33
is this still happening? 

@nicolasVr  @RachL @filipefurtad0

**Comment by filipefurtad0** [comment] 2024-05-09 18:37
Hey @abdellani :wave: :-) 

On devops notification, this seems to be the last occurrence (2 months ago):

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/65e98a74dafe660008659feb?event_id=65e98a7400ddc91ce3130000&i=sk&m=nw

Maybe we can close?

**Comment by RachL** [comment] 2024-05-10 07:18
I wonder if this isn't a stimulus reflex problem? and therefore only happening sporadically? that being said I don't know if SR is used in the loading screen.

Let's close and reopen if we get another occurence or if @nicolasVr has still users who end up in this situation.

**Comment by nicolasVr** [comment] 2024-05-13 06:58
It is solved for me. I have emailed the customer who first reported the bug to check if it is ok for him.
Thanks !

**Comment by nicolasVr** [comment] 2024-05-17 12:30
Also solved for the customer !

**Comment by nicolasVr** [comment] 2024-06-22 09:35
Unfortunately I just had 2 customers this week who could not print invoices. I have tested and also got the problem. I think we can re-open the issue as a new issue would have the same description.

**Comment by RachL** [comment] 2024-06-24 08:09
@nicolasVr so the issue is again on firefox only? I'm not able to reproduce :/

**Comment by nicolasVr** [comment] 2024-06-24 08:21
I could reproduce this morning with Firefox. I can check again later. The customer who had difficulties last week tried with Edge and Chrome. I am not sure it is browser dependent.

24 juin 2024 10:06:57 Rachel Arnould ***@***.***>:

**Comment by abdellani** [comment] 2024-06-24 10:39
I checked the  bugsnag report for the last 7 days and I couldn't find any issues related to the invoices bulk printing.
https://app.bugsnag.com/open-food-france/coopcircuits/timeline?filters[event.since]=7d&pivot_tab=error
I think this is a different problem  from what @filipefurtad0  reported https://github.com/openfoodfoundation/openfoodnetwork/issues/12215#issuecomment-1969267700.

**Comment by tschumilas** [comment] 2024-06-24 11:26
I have not been able to reproduce this,  using Chrome,  on OFN-Canada.   Is the issue that NO bulk printing is working?  I ask because it does take a while to compile - maybe the user didn't wait?   I just selected and printed 100 invoices - took just over 1 minute to compile.   This  is the most invoices you can print becuase the selection is lost if you select a second page,  and 100 is the most orders you can view per page. (When I bulk print my orders - over 100 -- I set the pagination to 100 orders per page view,  and print each page's orders separately)

**Comment by nicolasVr** [comment] 2024-06-24 12:16
I just made further tests with Firefox /Linux : as a normal user it was fast for 2 invoices and about 3 minutes for 50 invoices. As SA for 8 invoices it has been working for 4 minutes before I stop. And now another trial with 15 invoices nothing happens (no wheel).
Just tried with Chromium linux with 15 invoices, it worked in about 15 seconds.
During all those trials I received no email with attached reports.

**Comment by tschumilas** [comment] 2024-06-24 13:00
Don't you just love sporatic and random bugs?

**Comment by mkllnk** [comment] 2024-06-27 04:00
We observed this here in Australia as well. Invoices never showing up even though there were compiled. We don't have a workaround at the moment.

**Comment by dacook** [comment] 2024-07-03 02:37
This is similar to the problem with reports. Although we haven't been able to prove the exact cause, it's likely due to a websocket message not getting through (eg due to browser timeout when busy server fails to respond to ping request after 10 seconds).

Similar to reports, it is a longrunning job that produces an output, but with no persistent way to access the output. With reports, we send an email with the link if it takes a long time. So if the message doesn't appear onscreen, at least you get a notification. We could consider doing the same here.

In the long term, we intend to replace the CableReady / WebSocket implementation anyway, so we could do that. We don't have a solution ready for longrunning jobs, I will discuss ideas in Slack.

Another option is to produce each invoice separately, and provide each one as it becomes available. I think we could trigger the download in the browser as each becomes available, otherwise you'd have to click on each and every one.
In any case, if the websockets fail, you still get left waiting indefinitely for the results (or perhaps worse, one is missing but you don't realise).

**Comment by dacook** [comment] 2024-07-03 04:53
Discussed with Maikel and Gaetan, I will make a start on replacing the CableReady/WebSocket implementation with HTTP polling. This will maintain the existing behaviour from a user point of view, but will be able to ensure the PDF is presented once ready.

**Comment by RachL** [comment] 2024-07-03 08:47
@dacook FYI in the new invoice system (see feature toggle "invoices"), invoices are stored individually. Maybe it would help point 3?

> Another option is to produce each invoice separately, and provide each one as it becomes available.

Currently invoices are not released as they rely on core funding, it's mostly paused. But there is not so much work left to release them:

**Closed** 2024-07-05 00:05 UTC
Labels: bug-s2
