### ISSUE TITLE
Add directive to enable clicking outside 'quick-cart' to close it

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#543] opened 2015-05-07 12:39 UTC
users getting confused and can't work out how to close it

once directive is added, we can apply elsewhere where this problem is occurring

**Comment by Matt-Yorkley** [comment] 2017-03-08 00:56
This might be a good candidate for an introductory task. It'll probably require an angular directive or something to slot in to the existing directive, and it'll probably need to bind a click event on $window.

**Comment by podoglyph** [comment] 2017-09-19 16:59
Hi, I'm a new contributor to OFN. This seems like something I could handle. The suggestion from @Matt-Yorkley seems like a good direction to go in. If nobody is assigned to this I'm happy to take it on.

**Comment by NickWeir63** [comment] 2017-09-19 17:32
Hi @podoglyph welcome to OFN ! If you let me have your email address I will join you up to our Slack channel to help with communication. My email is nick@openfoodnetwork.org.uk This issue is not ladbelled as 'Rubies for Newbies' but I will ask @lin-d-hop or @daniellemoorhead  to let you know if it is suitable for a first-time contribution.

Thanks very much for getting involved. Hope to meet you soon.

**Comment by podoglyph** [comment] 2017-09-19 18:41
Thanks @lin-d-hop
I'll start working on it and check in with questions. And thanks to @NickWeir63 for getting me in the slack channel!

**Comment by myriamboure** [comment] 2018-03-04 19:07
Closing as duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/1300

**Closed by myriamboure** 2018-03-04 19:07 UTC
Labels: australia, good first issue
