### ISSUE TITLE
Order Cycle Customer Totals report breaks when query too large

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1139] opened 2016-08-23 17:23 UTC
i set a date range of 1st Jan 2016 to 23rd Aug 2016 for Stroudco Food Hub and after a bit of a wait I got the slug 'system error - We're sorry, but something went wrong" message
![screenshot 2016-08-23 18 20 15](https://cloud.githubusercontent.com/assets/10517702/17902260/84181f6c-695e-11e6-9170-7cd37cc09dd8.png)

**Comment by NickWeir63** [comment] 2016-09-14 15:19
....but when I select a shorter date range it all works fine
![screenshot 2016-09-14 16 15 38](https://cloud.githubusercontent.com/assets/10517702/18518169/ce9155b0-7a96-11e6-867a-52a5a951026f.png)

Can we either get it to load just part of the report at a time or give an error message suggesting the user selects a shorter date range?

**Comment by myriamboure** [comment] 2018-02-23 10:39
#gitcull2018 closing as part of report performance issues and duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/1539 where there are some solutions discussed.

**Closed by myriamboure** 2018-02-23 10:39 UTC
Labels: bug
