### ISSUE TITLE
Products can be ordered beyond available stock level

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1491] opened 2017-03-17 11:45 UTC
When two customers shop at the same time OFN lets both orders check out even if there isn't enough stock of any item to fill both orders. This then results in negative stock levels.

![screen shot 2017-03-17 at 11 28 37](https://cloud.githubusercontent.com/assets/17590921/24041787/e4cc2cdc-0b06-11e7-83cb-ff11b454a2c7.png)

I tried this on UK production by putting the same product into my basked in two different browsers (one logged in the other guest checkout) and then proceeding through checkout.

**Comment by lin-d-hop** [comment] 2017-03-17 11:54
Blocks #1031

**Comment by lin-d-hop** [comment] 2017-04-12 10:54
Notes from Rob:
If you grep for `insufficient_stock_lines` in the `orders_controller_decorator` you should find the logic. If this is not working properly, then it is just a bug, I don't think it represents a new feature.

I'm just looking now and perhaps the problem is that we only check when item quantities are updated (ie shopfront and cart pages) and a final check isn't performed at the checkout phase? Perhaps we need to redirect back to the cart from checkout in `CheckoutController#update` in that same way that we do from `OrdersController#update`

**Comment by lin-d-hop** [comment] 2017-04-12 10:55
@stveep @Matt-Yorkley might either of you have a moment to take a look at this issue in between tasks?

**Comment by myriamboure** [comment] 2017-04-12 11:04
Is it the same issue I documented here: https://github.com/openfoodfoundation/openfoodnetwork/issues/1335 ?

**Comment by lin-d-hop** [comment] 2017-04-12 11:10
Looks like it :-)

**Comment by lin-d-hop** [comment] 2017-04-18 14:03
Closed - duplicate

**Comment by Matt-Yorkley** [comment] 2017-08-09 18:52
For reference this is apparently not a duplicate of #1335, and still occurs whilst `allow_backorders` is disabled.

**Comment by Matt-Yorkley** [comment] 2017-08-09 22:44
Nope, this is definitely fixed by disabling `allow_backorders`.

**Comment by lin-d-hop** [comment] 2017-08-10 09:27
@sstead can confirm it is not.

**Comment by lin-d-hop** [comment] 2017-08-10 09:30
Here is the bug spelled out:
If I had an item in my cart, then I logged out, then the item was removed from the OC (either just that item or the supplier), then I log in and go to the shopfront- my cart hangs and I'm unable to proceed through checkout. If I instead login and click straight on the edit my cart dropdown link, I can proceed through checkout and purchase something that's no longer in the OC.

**Comment by myriamboure** [comment] 2017-12-22 04:54
@lin-d-hop I put s3 as it seems pretty few users are impacted right ?

**Comment by lin-d-hop** [comment] 2017-12-27 07:45
@myriamboure This is another issue that is not affecting many users simply because we don't have many users. However it is affecting the critical workflow. I agree this is an s3 for now, however if our user base grew and we regularly had concurrent customers this would become an s1. I feel it would be a mistake to ignore this one for too long :-)

**Comment by lin-d-hop** [comment] 2018-02-15 17:20
Closing as this is more thoroughly defined in #2067

**Closed by lin-d-hop** 2018-02-15 17:20 UTC
Labels: bug-s3, uk
