### ISSUE TITLE
n8n tech debt / stability issues

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#11717] opened 2023-10-26 11:46 UTC
## Description

We need to ensure a production ready N8N instance to continue using this in production.

## Acceptance Criteria

1. Backups: Outstanding question on if backups will contain personal data. Depending on the answer we will have to ensure GDPR compliance for EU instances and likely some regulatory compliance for other folks too.
2. Monitoring: Let's get monitoring on New Relic for the N8N server

**Comment by kirstenalarsen** [comment] 2023-11-02 23:34
@rioug to do estimate

**Comment by rioug** [comment] 2023-12-11 06:08
@kirstenalarsen 
> Monitoring: Let's get monitoring on New Relic for the N8N server

**2h to 4h,** I just need to look at the documentation to figure out what to do

> Backups: Outstanding question on if backups will contain personal data. Depending on the answer we will have to ensure GDPR compliance for EU instances and likely some regulatory compliance for other folks too.

**1 -2 days** 
TODO :
* Cloudron, figure out what is backed up
* N8N figure out if any workflow store personal data (15 Aus workflow, 4 Regen workflow) . This not including workflow from other instances. 

Nice to have **1 day** :
* move backup to another server other than the n8n one

**Comment by kirstenalarsen** [comment] 2023-12-11 12:58
Great, do it. Thanks @Gaetan Craig-Riou ***@***.***>

**Comment by rioug** [comment] 2024-01-05 02:38
So it turns out that it's not recommended to install other software on a server running Cloudron (we use self hosted couldron to manage N8N and Kuma) as we saw when I broke the server while trying to install New Relic monitoring.  But somehow we know have New Relic monitoring after the server was fixed by Cloudron support. That said it's not a sustainable approach, we'll most likely lose this if we need to change the server for any reason. Maikel suggested we might be able to install New Relic monitoring before installing Cloudron to get around the problem, but this is untested for now.

It turns out, Cloudron provide an API with a couple of endpoint we can use for basic monitoring, server status, and disk usage : 
* https://docs.cloudron.io/api.html#tag/System/operation/getDiskUsage
* https://docs.cloudron.io/api.html#tag/Cloudron/operation/getStatus

I have set up some monitoring and alerts in New Relic using said API, it will send alert to devops-alert channel in slack :
* synthetic monitoring  : https://one.eu.newrelic.com/synthetics?account=4028699&duration=3600000&state=f2c948ba-9c19-873f-8548-a401a3dd41cb
* Alert set up based on the monitoring : https://one.eu.newrelic.com/alerts-ai/condition-builder/condition-list?account=4028699&duration=3600000&state=f2c948ba-9c19-873f-8548-a401a3dd41cb

An other option we could explore is this app : https://github.com/get-zen-dev/nomon/tree/master , forum discussion : https://forum.cloudron.io/topic/9373/nomon-server-resources-monitoring-alerting-for-cloudron/5
But I am not sure we want do rely on another 3rd party app that's not provided by Cloudron app store

**Comment by rioug** [comment] 2024-01-05 05:36
@kirstenalarsen @mkllnk 
Backup and personal data :
I re enabled N8N backup, they were turned off for some reason, currently we keep 2 days of backup, ie 2 backup as automatic backups run once a day.
N8N keeps a record of workflow executions for up to 14 days or up to 20k executions (https://docs.n8n.io/hosting/scaling/execution-data/#reduce-saved-data) , which means backup of N8N contains personal data. Fortunately Cloudron provide [encryption of backups](https://docs.cloudron.io/backups/#encryption) , which I have set up. The passphrase for decryption is in Bitwarden. 

Disclaimer, I am not a lawyer, but according to this : https://www.salvagedata.com/data-backup-gdpr-compliant/ as long as we have:
- a document which describe how we are using customer data
- ask for user permission
- have a system in place to delete customer data on request
- encrypt and keep more than one back up
We should be GDPR compliant.

Questions :
* do we think 2 backup of cloudron/N8N is enough ? Personally I think I would feel better if we had up to 7 days of backup.
* N8N past workflow executions, are we happy with keeping up to 14 days of data ? I think it's too much, and we should reduce it to 7 days, maybe even less. 

TODO:
* copy backup to an external server/service. I will monitor the backup size for the next couple of days so we know how much data we are dealing with. The easiest solution here, would be to copy back to S3 storage, as we already use it to store OFN data.

**Comment by mkllnk** [comment] 2024-01-07 21:05
> I re enabled N8N backup, they were turned off for some reason

I think we had trouble with the disk filling up on the server at some point. Now we should receive warnings about that, right?

> do we think 2 backup of cloudron/N8N is enough ?

More would be better. I would even keep two weeks in case someone makes a mistake and doesn't realise it straight away.

> N8N past workflow executions, are we happy with keeping up to 14 days of data ?

I would be happy with 5 days. So if something went wrong on Friday and I look into it on Tuesday then I still have the data with errors. Usually we deal with re-producible problems though and a 1 day log would be enough in 90% of cases. 5 or 7 days would be more convenient though.

**Comment by rioug** [comment] 2024-01-08 00:16
> I think we had trouble with the disk filling up on the server at some point. Now we should receive warnings about that, right?

Correct, I am going to keep an eye on it the next couple of week to make sure it's working as expected.

I updated the setting to have 7 days of backup for Cloudron and N8N, as well as 7 days of data for N8N.
Quick back of the envelope calculation gives me about 2G of data to store 7 days of backups. I used https://calculator.aws/ to get an estimate on how much it will cost to keep that on amazon S3 storage in Europe, and it came to about 0.60 USD ( ~0.90 AUD) per year. 

This is ridiculously cheap, so unless anyone object I'll go ahead and implement storing the backups in S3 next week.

**Comment by rioug** [comment] 2024-01-15 03:27
I just set up the copying of backup on S3, based on this documentation : https://docs.cloudron.io/backups/

@mkllnk It's been a while since I had to use AWS, could you double check I have done things correctly : 
* created a S3 bucket with no public access
* created a user, and created a new policy attached to the user to allow access to the S3 bucket
* created an access key associated to the new user for Cloudron to use.

I'll keep an eye on this for the coming week. I'll move this issue to done once I have confirmed backup are copied correctly.

**Comment by mkllnk** [comment] 2024-01-15 05:02
Setup looks good. A shame that there's no "backup now" button. We could have selected every hour in the schedule to trigger one and see it works. We should see tomorrow morning if a backup ran.

**Comment by rioug** [comment] 2024-01-21 23:24
Backup are working as expected/

**Closed** 2024-01-21 23:25 UTC
