### ISSUE TITLE
Product thumbnail images on Edit Cart could be clickable, opening product modal

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1925] opened 2017-10-25 02:22 UTC
This is a further improvement on https://github.com/openfoodfoundation/openfoodnetwork/issues/1075

On the edit cart page we see images of each product in the cart. It would be nice if these images were clickable- clicking would open the same product modal seen in the shopfront (and below). Or in future if we add product URLs, the URL could open in a new tab.

![image](https://user-images.githubusercontent.com/10843056/31977214-6d0bc614-b987-11e7-8b41-ff40a01bb768.png)

**Comment by myriamboure** [comment] 2018-05-21 16:46
@sstead I'm not sure I agree with the fact that this is nice to have, I guess we would need some ux view on it. Anyway it is not a bug and we have lots of other things to fix so I added that in the icebox "improve shopping ux" https://community.openfoodnetwork.org/t/customer-easily-go-through-the-whole-placing-order-process/1245 and we can discuss about it when we decide to prioritize. So I'm closing it for now.

**Closed by myriamboure** 2018-05-21 16:46 UTC
Labels: good first issue, p - low
