### ISSUE TITLE
When creating products, pre-select the supplier when there is only one enterprise available

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#8176] opened 2021-09-13 09:25 UTC
## Description

**- As a:** enterprise user
**- On page:** `/admin/products/new`
**- I want to be able to do:** Avoid having to select a supplier if there is only one supplier available in the dropdown

## Acceptance Criteria & Tests

1. Log in as an admin of 1 enterprise
2. Got to `/admin/products/new`
3. See that your enterprise is already selected in the supplier field => same behavior than the shipping category dropdown (the supplier is selected by default but the dropdown remains clickable)

![image](https://user-images.githubusercontent.com/6525576/133059225-118b4017-50c2-496a-a35a-7eea19bb19ee.png)

**Comment by sinansonmez** [comment] 2021-09-21 14:09
@RachL this seems to be relevantly easy task(to be confirmed by maintainers). If this is the case, please assign this to me and i can start working on it

**Closed** 2021-10-19 03:12 UTC
Labels: good first issue, hacktoberfest, enhancement
