### ISSUE TITLE
Ugly error message when state is missing at registration

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#7655] opened 2021-05-17 18:54 UTC
## Description

During registration, using the new map selector can make us easily miss the state selector. Users can go until the end of the registration process and end up with an ugly error message they do not understand.

## Expected Behavior

I expect the field to work like when the localization of the address is not used: the mandatory field is highlighted.

## Actual Behaviour

I see an ugly error at the end of the tunnel and I don't know what that error means. It's not translated and does not show the field which has a missing info.

## Steps to Reproduce

1. Go to /register and start registering as a new enterprise
2. Write a complete address without using the state and country selectors
3. Localize the address
4. Move on to the others steps
5. Try to finish

## Animated Gif/Screenshot

No error message here:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/5cb61a7e-1155-40e3-b0fa-d37a2d5912e1)

Only here:
![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/9049cf71-f16f-4ef3-937a-a97e33361db2)

## Workaround
Select a state. But how would a user know that this is intended?

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v.3.7.1
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): Both

## Possible Fix
Clearly indicate to the user that state and country are mandatory, the same way we do it for the other part of the address?

![image](https://user-images.githubusercontent.com/6525576/118541643-39cefd80-b752-11eb-8c1b-7b7b0763a47c.png)

**Comment by RachL** [comment] 2021-05-17 19:00
Waiting for feedback on severity before moving to dev ready.

**Comment by mkllnk** [comment] 2021-05-18 03:21
I would say: a critical feature broken with workaround. That's not on our scale but I think that s2 is good for this.

**Comment by andrewpbrett** [comment] 2021-05-24 23:24
This is indirectly caused by the fact that the default country is not set correctly. Because the default country doesn't appear in the dropdown, the states do not appear in the state dropdown, and we don't do the check for whether the country `requires_states` is true (in the case of FR it looks like it's set to false). 

So this should be fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/7647

**Closed** 2021-05-25 09:21 UTC
Labels: bug-s2
