### ISSUE TITLE
Bugsnag initializer should be in application code, not provisioning

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1929] opened 2017-10-26 11:01 UTC
Right now some instance use [Bugsnag](https://www.bugsnag.com/) to monitor application failures.

The configuration is set in provisioning [here](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/app/templates/bugsnag.rb.j2) but was not activated, https://github.com/openfoodfoundation/ofn-install/pull/87 solves this.

Our opinion on this is that we should have the `bugsnag.rb` initializer in this repo, not in `ofn_install` and use `application.yml` to set all the credentials and any instance specific information through environment variables.

If an instance doesn't use Bugsnag they don't have to do anything, the initializer will just "early return".

This is one of those little things that make it easier to setup new instances and maintain existing one.

**Comment by enricostano** [comment] 2017-12-19 06:15
Moved to icebox https://community.openfoodnetwork.org/t/define-a-common-strategy-for-exceptions-logging/1156

**Comment by sauloperez** [comment] 2019-02-26 16:27
The root cause of Katuma not being able to send errors to Bugsnag was the lack of the `ln -s /home/openfoodnetwork/apps/openfoodnetwork/shared/config/bugsnag.rb config/initializers/bugsnag.rb` symlink. Thanks @pacodelaluna for giving the idea!

Therefore, I'm going to work on this right away. I'll spend more time trying to understand why the link wasn't performed than moving this initializer to its right place.

**Closed** 2019-02-28 15:42 UTC
Labels: tech debt
