### ISSUE TITLE
Cannot change calculator on existing shipping method

### ISSUE THREAD

**Issue by Renatacumming** [openfoodfoundation/openfoodnetwork#7657] opened 2021-05-18 07:44 UTC
## Description
When a user tries to change an existing shipping method; wants to change calculator from Weights, to Flat Rate, and gets the 'opps, something went wrong' error. Have recreated this in the Aus Demo Hub with same result. 

## Expected Behavior
Should be able to change the calculator from one method to another method and save with no error

## Actual Behaviour
When the user changes the calculator from one method to another method the 'oops, something went wrong' error appears

## Steps to Reproduce
1. Go into an existing shipping method.
2. Try to change the calculator from one method to another method
3. Click Update

## Workaround
Create new shipping method and make old shipping method 'display - back office only'

bug-s3: a feature is broken but there is a workaround

**Comment by kirstenalarsen** [comment] 2021-05-18 07:48
Is coming up in Bugsnag -https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60a34c07fbf6410007eb6401?event_id=60a34c07007c935b1e800000&i=sk&m=nw

**Comment by filipefurtad0** [comment] 2021-05-18 07:58
This looks related and perhaps a duplicated of:
https://github.com/openfoodfoundation/openfoodnetwork/issues/6300

**Comment by Matt-Yorkley** [comment] 2021-05-18 08:31
It doesn't look related to adjustments, and also doesn't look like it's new in this release...

**Comment by filipefurtad0** [comment] 2021-05-20 10:32
Confirmed duplicate of #6300, closing here.

**Closed by filipefurtad0** 2021-05-20 10:32 UTC
