### ISSUE TITLE
Shopfront tabs not displaying content in Mobile view

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1295] opened 2016-12-07 01:52 UTC
Shop sections are showing up empty in Mobile/Tablet - but render content in Desktop. Tested in uk. au and staging. staging .au shows the red border but no content. Some shops have the content show (openfoodnetwork.org.uk/stroudco/shop#/about)

Recommendation: If a shop section / tab is empty - do not show tab. Test this on an actual phone, don't emulate.
Devices: Mobile/Tablet
Where: Shopfront
![image](https://cloud.githubusercontent.com/assets/10843056/20951774/f7de7368-bc7b-11e6-895e-26360e9a82aa.png)

**Comment by Matt-Yorkley** [comment] 2016-12-17 23:39
@sstead I just tested this on my mobile using Firefox for Android and it seems to be working fine on various enterprises on both UK and AUS production. The tabs all work and show content in the right place.

Is the issue that tabs don't show content when they should, or show an empty content box when there is no content to show, or both?

**Comment by sstead** [comment] 2016-12-21 01:31
Hey @Matt-Yorkley, I've been unable to replicate it as well. I think this Enterprise simply had no 'about us' text. Yuko's recommendation is that we hide the tab if the enterprise has no content written.

**Comment by Matt-Yorkley** [comment] 2016-12-21 11:10
@sstead yeah I was trying to think of a decent way of dealing with the empty tab scenario. I think if the user clicks the button and nothing happens it will seem like the button's not working, and I'm not sure that's better feedback than showing an empty tab...

**Comment by sstead** [comment] 2016-12-22 22:46
Could the tab be invisible if it contains no content?

**Comment by pmackay** [comment] 2017-01-03 20:09
Alternatively a default "empty state" content, e.g.

_No description available for this producer._

**Comment by KeirOsborn** [comment] 2017-03-30 18:46
Hi,

So is the "empty state" content route the one we want to go down? It seems like the cleanest option to me. If so though, I assume we want an empty state message for each tab. I'm not fully up to speed on the taxonomy, is this wording ok:

"_There is no description for this shop._"
"_There are no producers for this shop._"
"_There are no contact details for this shop._"
"_There are no groups for this shop._"

**Comment by daniellemoorhead** [comment] 2017-03-30 23:39
My preference is to not show the tab at all, you're just disappointing the user when they click on it and hit a dead end. I think this is why the hide the tab suggestion was made by @yukoosawa in the first place. Empty state is a less optimal solution, but if it's too hard to completely hide tabs when there is no content then I guess we have to go down that path?

Thoughts @sstead @Matt-Yorkley @pmackay @KeirOsborn?

**Comment by yukoosawa** [comment] 2017-03-31 00:48
Hiding the tab would definitely be first preference. However an empty state, whilst not great, is still better than what happens currently.

Based on the screenshot it looks like I was testing in Staging2 which was full of fake shops. Perhaps a way to prioritise what solution to go forward with for right now could be determined by how common it is in production (AU or UK or both) for a shop/hub/business to not have these data points completed.

**Comment by KeirOsborn** [comment] 2017-03-31 12:13
Ok cool, no problem, i'll implement a tab-hiding solution. 

Yuko, looking at the live site it does look like most of the shops on the live sites do have description data, associated producers and contact info, but a lot of them don't have groups. I guess the point is that if a tab is very often not applicable, it makes sense to hide it in those cases, because the viewer doesn't feel like they're missing something in it's absence?

**Comment by lin-d-hop** [comment] 2017-04-24 12:39
That's my understanding @KeirOsborn. Tab-hiding for groups sounds like highest priority, though might as well do all at once :-)
Are you still happy ticking on with this?

**Comment by KeirOsborn** [comment] 2017-04-25 22:29
Hi,

Yep cool no probs, plan is indeed to do it all at once. 

It turns out to be a bit more complicated than I first thought because each tab is given a specific width. When hiding tabs you have to also decide how to re-size the remaining ones in order to give prominence to the about tab as in the original layout. 

But yes, happy to proceed with this. I have some free time this weekend so should be able to get it done then.

Cheers,

**Comment by myriamboure** [comment] 2018-03-14 18:38
Hi @KeirOsborn any move on this one ? Do you still plan to work on it (after embed group I guess ;-)) or shall we put that back in the pool of issues?

**Comment by myriamboure** [comment] 2018-03-29 11:06
Not a bug as "mobile ready" not yet a feature we really offer, too many things bugging on mobile. So captured in icebox https://community.openfoodnetwork.org/t/customers-easily-go-through-the-whole-placing-order-process-on-mobile/1244 and new feature "mobile ready" started to be worked on, so closing for now.

**Closed by myriamboure** 2018-03-29 11:06 UTC
Labels: bug-s4
