### ISSUE TITLE
Relationship panels - update for Enterprise types and permissions

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#500] opened 2015-04-16 06:51 UTC
Enterprise type 'Producer with Shop' (own) - Producer should show in the our producers list / fat view and tab

Producers tab on shopfront should only show Producers that have given P-OC to this Hub (currently also reading in other related enterprises / producers, including those that this producer/shop has given P-OC to)

![image](https://cloud.githubusercontent.com/assets/2911176/7173565/ffdd2a78-e43c-11e4-8faf-b74a7e0b2251.png)

**Comment by myriamboure** [comment] 2018-03-19 15:35
I don't think this is still happening, I did some test and couldn't reproduce so closing now. @kirstenalarsen @sstead if you think this is still happening please reopen.

**Closed by myriamboure** 2018-03-19 15:35 UTC
