### ISSUE TITLE
BO orders: silent error 500 - choosing a distributor while leaving OC blank (NaN)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7131] opened 2021-03-16 10:15 UTC
## Description

When placing a new BO orders, before adding line items the admin needs to
1) choose a distributor. Click "Next".
2) choose an open OC

It is currently possible to skip the second step, which triggers error 500 in the console/bugsnag, due to the missing OC info (NaN)

Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f74a73d2931290017d4734a?event_id=5f74a73d0060b0928c010000&i=sk&m=nw

Related (I think this error is possible to trigger in slightly different context)
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/604ad36ea34722000725cc83?event_id=604ad36f0073be9f5cf50000&i=sk&m=sn

## Expected Behavior

The user should not be allowed to proceed to searching for products, before OC info is inputted. I guess a flash warning should do it?

## Actual Behaviour

The "Next" button works and leads the user to the next step, despite having left a mandatory field blank. 

## Steps to Reproduce

1. admin/orders/new
2. Select a Distributor
3. Leave OC info blank
4. Click Next - open the console
5. Search for a variant - see error 500

## Animated Gif/Screenshot

Choosing a distributor and clicking "Next" (leaving OC field blank): 

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/15571f1d-2173-4790-a409-9d7d1a27566a)

Searching for a variant:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/ccb68f8b-91a3-414b-9759-0610e38709da)

Leads to:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e42e863f-2d59-499b-9e5c-c63b8153ec07)

## Workaround

Scrolling down, and choose an OC.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.5.14
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu

**Comment by RachL** [comment] 2023-04-13 13:04
duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/6133 I leave 6133 open as it has a bit more details

**Closed by RachL** 2023-04-13 13:04 UTC
Labels: bug-s4
