### ISSUE TITLE
[Checkout] Impossible to complete order 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10533] opened 2023-03-08 12:25 UTC
## Description
On FR Prod, two users warned that since last release the users can no longer validate their order and remain stuck on the delivery or withdrawal information step without being able to select the method. 

At the step ‘’contact, billing address, means of delivery’' the next step cannot pass because an error message is displayed ‘’ fill in the delivery address, city, postal code ‘’. However, the insert ‘’delivery address etc’' does not exist and the means of delivery is well selected. 

Shops ID : 3395 & 4239

## Expected Behavior
Checkout should be possible.

## Steps to Reproduce
Will do it.

1.
2.
3.
4.

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

**Comment by sigmundpetersen** [comment] 2023-03-08 12:27
Is this on Legacy or Split Chackout?

**Comment by RachL** [comment] 2023-03-08 12:29
@audez i think they are experiencing this error : [#](https://github.com/openfoodfoundation/openfoodnetwork/issues/10479)

if they are existing user you can add a shipping address to their profile (via customer menu) and it should be fixed for them. Or exclude them from split checkout.

I'm closing here but please reopen if I'm wrong 👍

**Closed by RachL** 2023-03-08 12:29 UTC
Labels: bug-s1

**Comment by audez** [comment] 2023-03-08 12:36
@RachL thanks! The problem is: i don't know the customers names (should i ask the shops for every users?) and there's probably users that never checked out before? Also, these are 2 shops who realized the issues but there's probably many more..

**Comment by audez** [comment] 2023-03-08 12:48
I just tested to add a shipping address to the customer but it's not working. Does it mean that the bug occurs for anyone?

**Comment by RachL** [comment] 2023-03-08 13:03
@audez Can you share a screenshot of your test?

**Comment by RachL** [comment] 2023-03-08 13:03
> The problem is: i don't know the customers names (should i ask the shops for every users?)

we can check all their customers to be safe, I will have a look.

**Comment by audez** [comment] 2023-03-08 13:06
It's the same issue whether the customer already ordered on the shop or not, or whether they had the same billing address or not. 
I tested the following:
- pass an order on legacy with a user
- with same user, now activated on split, it's impossible to pass an order

So for me this means that we have to disable split checkout for all users. 

> @audez Can you share a screenshot of your test?
![Screen Shot 2023-03-08 at 13 42 41](https://user-images.githubusercontent.com/28386648/223720677-0421e8c5-9092-4e7c-a3b0-861ae3dd5a4e.png)

![Screen Shot 2023-03-08 at 13 44 37](https://user-images.githubusercontent.com/28386648/223720747-7547670e-d1aa-46ea-8506-fb804ccc1705.png)

**Comment by RachL** [comment] 2023-03-08 13:14
ok thanks for the screenshot, this could actually different than #10479 

@audez are you sure both shops you have listed have the same problem? You added an error message in the description;

>  fill in the delivery address, city, postal code

Which is different from the screenshot. Which error belongs to which shops?

> So for me this means that we have to disable split checkout for all users.

No so fast we have had more than 200 orders passing without error on split checkout, I know the problem can be overwhelming but if we just deactivate right now we won't understand what is happening. Let's dig a bit more before doing that.

**Comment by RachL** [comment] 2023-03-08 13:20
@audez OK I've found and fixed the problem for shop 4239. It was not really a bug but more a consequence of https://github.com/openfoodfoundation/openfoodnetwork/issues/9629

We don't work on legacy checkout anymore so this enhancement is only available on split checkout (that's why you couldn't reproduce on legacy checkout). Their shipping method was not matching their product, hence no shipping method was appearing. I've switch their shipping method to "default" category to fix the bug. But it might be worth checking now if all their product matches this category.

**Comment by RachL** [comment] 2023-03-08 13:26
@audez but for shop 3395 I'm stuck: everything is working on my side :/. Do you have a screenshot for that shop?

**Comment by audez** [comment] 2023-03-08 13:27
I did a test on a shop of mine, which had a pickup method, with user on split checkout:
- i tried to checkout: impossible
- i added a second pickup method: the second pickup method appears and not the first one
![Screen Shot 2023-03-08 at 14 27 17](https://user-images.githubusercontent.com/28386648/223725258-946217ff-2cc8-4af4-bf57-4250e72edb5b.png)
![Screen Shot 2023-03-08 at 14 26 36](https://user-images.githubusercontent.com/28386648/223725262-c5df6525-106d-41df-ad72-1c174882afa8.png)

So maybe recreating a shipping method is a workaround.

**Comment by audez** [comment] 2023-03-08 13:29
> Their shipping method was not matching their product
Indeed! Same on my shop actually, now both methods are appearing

**Comment by audez** [comment] 2023-03-08 13:51
> @audez but for shop 3395 I'm stuck: everything is working on my side :/. Do you have a screenshot for that shop?
I can't reproduce either! i'll ask him for a screenshot. 
Thanks a lot!

**Comment by RachL** [comment] 2023-03-08 14:02
@audez yeah that sounds really like https://github.com/openfoodfoundation/openfoodnetwork/issues/10479 but I didn't find a customer on their list without shipping address :/

let's see with his feedback

**Comment by audez** [comment] 2023-03-08 14:10
but i don't understand, i tested with a brand new account with no shipping address and couldn't reproduce 🤔
@rioug is there anything else specific on the customer you used?

**Comment by RachL** [comment] 2023-03-08 14:24
@audez i've managed to replicate on master this way:

- Set up a shop with two shipping methods, one requiring a shipping address, and one pick up only
- Start an order and go to checkout
- First choose the shipping method requiring an address, untick "Shipping address same as billing address?"
- Make sure the shipping address is empty
- Then choose the pick up shipping method

and boom:

![image](https://user-images.githubusercontent.com/6525576/223738131-49be375a-22e9-4df7-80c1-f2825481edc8.png)

**Comment by RachL** [comment] 2023-03-08 14:25
but indeed it doesn't seem to happen for a guest checkout or new user checkout. It's a tough one :)

**Comment by audez** [comment] 2023-03-08 14:32
oh this reminds me of this 😆 https://github.com/openfoodfoundation/openfoodnetwork/issues/9056#issuecomment-1278772422
Did you "unlock" the user in this way?
Because shop 3395 has only 1 pickup method activated

**Comment by audez** [comment] 2023-03-08 15:05
We have another user (id= 24155) reporting that she can't order anymore on another shop (2931) with same error than shop 3395 (they're asked to fill in the delivery info address, city etc)
- She has a saved shipping address
- She never had trouble ordering
- She can't order anymore 
- The shop has only 1 pickup method

For me it's not the same than https://github.com/openfoodfoundation/openfoodnetwork/issues/10479, looks more like https://github.com/openfoodfoundation/openfoodnetwork/issues/9056

Where info on the shipping address and billing address was available but when sending the request, two fields were missing (`order[bill_address_attributes][id]`, `order[ship_address_attributes][id]`) and the request failed. That might explain why we have difficulties reproducing it?

Ah, 3395 just sent the screenshot: 
![Screenshot_2023-03-08-15-43-40-459_com android chrome](https://user-images.githubusercontent.com/28386648/223748348-08a8034d-c06c-4409-8074-692bcb32f6da.jpg)

**Comment by RachL** [comment] 2023-03-08 15:14
@audez 

Problem is, #9056 is not reproductible for now :( , so we have to bet the fix for #10479 works in both cases :/ 

Can we try the following: keep the single shipping method for both shops, but turn it as a delivery type. Do you think both user could retry their checkout? I know it's tricky as they might not want to test, but fingers crossed hub 3395 has the problem on his own hub account?

**Comment by audez** [comment] 2023-03-08 15:14
Same issue on shop 160 
Users report the same error message: "La sauvegarde n'a pas fonctionné, veuillez mettre à jour les champs en rouge. Adresse de livraison (Numéro et Rue) doit être rempli(e), Adresse de livraison – Ville doit être rempli(e) et Code postal doit être rempli(e)."

**Comment by audez** [comment] 2023-03-08 15:17
> Problem is, https://github.com/openfoodfoundation/openfoodnetwork/issues/9056 is not reproductible for now :( , so we have to bet the fix for https://github.com/openfoodfoundation/openfoodnetwork/issues/10479 works in both cases :/
But the bug could be open still, as it's ongoing. It's just that it doesn't feel right to put all the info in the comments of another issue. Or do i open a new bug?

> keep the single shipping method for both shops, but turn it as a delivery type.
I think we could do it, but we now have at least 3 shops that reported the issue, so this means others must be concerned

**Comment by RachL** [comment] 2023-03-08 15:27
@audez if we don't do it, opening a bug won't be very helpful as the team won't be able to reproduce. We don't keep open issues that are fixed in master. If we open a new issue it would be nice to have the correct step to reproduce it.
