### ISSUE TITLE
upgrade to Ruby 2

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#705] opened 2015-11-06 00:03 UTC

**Comment by flov** [comment] 2015-11-11 13:42
what's the issue? I just upgraded seemlessly.

**Comment by pmackay** [comment] 2015-11-23 16:16
When testing this out locally am noticing that this warning is appearing:

`Digest::Digest is deprecated; use Digest`

@oeoeaio do you know what the cause is?

**Comment by oeoeaio** [comment] 2015-11-23 21:21
Hi @pmackay,

Not sure off the top of my head, but it is on my radar as I have been seeing it too.

**Comment by elf-pavlik** [comment] 2015-12-13 11:53
everyone here in Berlin uses 2.1.5 as specified in
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/.ruby-version

can you please clarify what exactly it takes to close this issue?

**Comment by daniellemoorhead** [comment] 2016-02-03 03:08
Actually happened in v1.3

**Closed** 2016-02-03 03:08 UTC
