### ISSUE TITLE
Create New Product 'Display As' missing compulsory field identifier

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5107] opened 2020-03-30 09:17 UTC
## Description

User Adds new product to their main enterprise inventory. Product has units of 'items' and hence the 'Display As' field is not automatically completed.
If no text is added to the 'Display As' field then when selecting 'Create' or 'Create and Add Another' the following error message is displayed:
1 error prohibited this record from being saved :
There were problems with the following fields ;
Variant Unit Name can't be blank

Compulsory fields should be marked with a red asterisk. The 'Display As' field is not marked.

## Expected Behavior

Compulsory fields should be marked with a red asterisk to highlight to the user which boxes must be completed. 

## Actual Behaviour

The 'Display As' field is not marked.  Error message occurs and item is not created if the field is not completed.

## Steps to Reproduce

1. Create new product with units of 'items' and fill in all fields other than 'Display As'
2. Select Create
3. Error message encountered. When moved to the error screen the 'units' and 'Value' fields empty automatically as well as the 'Display as' and so second screen shot is misleading.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/45104035/77895159-46eb0d80-726e-11ea-97fb-83eadb013af7.png)
![image](https://user-images.githubusercontent.com/45104035/77895192-52d6cf80-726e-11ea-8204-9042a2ace574.png)

## Severity

bug-s4

For New users though this is a blocker to them starting their enterprises in a simple and pain free manner.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Add Asterisk to the 'Display As' field.

**Comment by lbwright22** [comment] 2020-03-30 09:18
![](https://github.trello.services/images/mini-trello-icon.png) [Sole Of Discretion problems](https://trello.com/c/OBo51SPF/774-sole-of-discretion-problems)

**Comment by dacook** [comment] 2020-04-17 02:12
I can replicate this on v2.9.2.

It's worth noting that when you choose unit size of "Items", the Display As (`display_as`) field disappears and Unit Name (`variant_unit_name`) appears in it's place. 
So the problem is that the **(Variant) Unit Name should be labelled as compulsory**. 

Also its translated differently in the error message, I think it should match the field label, but I don't know which is more correct?

1. Unit Name; or
2. Variant Unit Name

I'll get started on this no-one else is.

David.

**Comment by dacook** [comment] 2020-04-17 03:24
I've added the asterisk, but would like to know if we should also review these:

1. When submitting the form with validation errors, some entered values are cleared, which is not only a pain for the user, but could lead to error if they don't realise they have to re-enter them:
  * Unit Size
  * Value
  * Unit Name
  * On hand
  * On demand
2. The variant_unit_name field is labelled with "Unit Name" `t(".unit_name")`, but the validation error says "Variant Unit Name".
 * Which one is correct, 
 * Shouldn't these be loading the translation value from the same place?
 * (and where does the validation message come from? I haven't found it yet...)

**Comment by mkllnk** [comment] 2020-04-17 03:44
Hi @dacook and welcome back!

I'm closing this issue because it has been solved already. I just merged the other pull request.

Outside contributors can't assign themselves to an issue. So we usually tell them to comment on the issue when they start working on it. This one fell through the gaps...

Your thoughts on further fixes of the page sound really good. If you are happy to continue that work then you can create an issue and start working on it. I have no idea though how easy it's going to be.

If you want to pick from our special selection for newcomers, we have a project overview for that: https://github.com/openfoodfoundation/openfoodnetwork/projects/27
We also use Zenhub to see which issues are actively worked on, when they are ready for review, testing and so on.

**Closed** 2020-04-17 03:50 UTC
Labels: AU, bug-s4, good first issue

**Comment by dacook** [comment] 2020-04-17 07:13
Thanks @mkllnk , I'm guessing the existing issues are more important so will focus on those in the short term.
