### ISSUE TITLE
Payment method fees cannot have tax applied

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1469] opened 2017-02-24 04:03 UTC
It should be an option to setup a tax category for a payment method fee. This isn't currently possible.

**Comment by lin-d-hop** [comment] 2019-08-28 17:42
Duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/3278

**Closed by lin-d-hop** 2019-08-28 17:42 UTC
