### ISSUE TITLE
Social links are not validated

### ISSUE THREAD

**Issue by marthaerm** [openfoodfoundation/openfoodnetwork#6558] opened 2020-12-24 04:12 UTC
## Description

In the **enterprise settings>social** the links for social media are not validated. The user can add the link in different formats and it cause problems when the link is generated in the ui.

## Expected Behavior

The user can add the link in any format (depending on the social network) and the system process it and save just the username for each social.

**Facebook**
 https://www.facebook.com/username -> username

**LinkedIn**
https://www.linkedin.com/in/username -> username

**Twitter**
 https://twitter.com/username -> username

## Actual Behaviour

If the user add https://www.facebook.com/username to the facebook field, it will ve converted into https://www.facebook.com/https://www.facebook.com/username on the frontend

## Steps to Reproduce

1. Go to _enterprise settings_ and click on _social_ tab
2. Add a link in the incorrect format to a social field
3. Open the enterprise front end
4. Click on _contact_ tab and click on the social icon you want to test

## Workaround

The user can just add the link how it is supposed to, but there is no validation for that.

## Severity

**bug-s4**
It could cause a problem if the social link is added in a wrong way, but if the user add it in a correct way, it works. To solve this issue can improve the user experience.

## Your Environment

* Browser name and version: Chrome 87
* Operating System and version (desktop or mobile): macOS 11.0.1

## Possible Fix

The same issue happened with instagram, but there is already an issue https://github.com/openfoodfoundation/openfoodnetwork/issues/1760 opened for that and there is this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6544 that solves it.
I'd suggest to take the same approach as this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/6544, use regex to convert the link introduced and store just the user name, also use a migration to update the current social link on the db.

**Comment by marthaerm** [comment] 2020-12-24 04:14
I worked on the mentioned PR, so I would like to work also on this one if possible :)

**Comment by RachL** [comment] 2021-03-02 09:55
@andrewpbrett can this one be a good-first-issue?

**Comment by andrewpbrett** [comment] 2021-03-02 15:27
@RachL Yep! I just put in on the welcome board too.

**Comment by RachL** [comment] 2021-03-02 15:29
@andrewpbrett thank you!!!

**Comment by YasuhiroYoshida** [comment] 2021-09-16 09:58
I could not reproduce this issue.

I entered both `https://www.facebook.com/username` and `www.facebook.com/username` in the input field. It came out fine - the expected behavior was observed - on the enterprise front end.

**Comment by andrewpbrett** [comment] 2021-09-17 03:19
Thanks for checking this @YasuhiroYoshida - I also took a look and it looks like Twitter is the only one that still doesn't work, the others get converted to the correct format. I'm not sure why we would have done everything but Twitter, but if we fix that one I think we can close this issue.

**Comment by SarvarKh** [comment] 2021-11-07 05:50
It seems like only Twitter and Instagram links are not being validated.
1. Create (register) a new entity -> click on the `Register here` btn on the `http://localhost:3000/abc/shop#/contact`;
2. Fill all the fields as required till the 6th step of registration - Social;
3. Fill out the social form as below.
```
Website:
https://sarvarkhalimov.com/
=> sarvarkhalimov.com/

Facebook:
https://www.facebook.com/username 
=> www.facebook.com/username

LinkedIn:
https://www.linkedin.com/in/username/ 
=> www.linkedin.com/in/username/ 

Twitter:
@username 
=> twitter.com/@username

Instagram:
@username 
=> instagram.com/@username
```

Will try to work on this.

**Closed** 2022-01-11 12:53 UTC
Labels: good first issue, bug-s4, hackathon
