### ISSUE TITLE
Reformat Shop Header menu pages

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2716] opened 2018-09-13 11:34 UTC
Zeplin [About](https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5b957e1f82f24f0d3e7aa434)
![image](https://user-images.githubusercontent.com/2911176/46519593-46adc400-c8bc-11e8-9f2c-c15eb8957f68.png)

Zeplin [Producers](https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5b957e20d374679ce5dc58b8)
![image](https://user-images.githubusercontent.com/2911176/46519611-4f05ff00-c8bc-11e8-9f88-56cb2858276c.png)

Zeplin [Contact](https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5b957e20d374679ce5dc58df)
![image](https://user-images.githubusercontent.com/2911176/46519617-57f6d080-c8bc-11e8-8ab3-79fe7b091fb1.png)

Groups? We don't have a design for this but is it possible / easy to apply same style changes . . ?

**Comment by daniellemoorhead** [comment] 2019-12-13 05:08
Duplicate of #4569 and #4570 and #4571

**Closed by daniellemoorhead** 2019-12-13 05:08 UTC
