### ISSUE TITLE
Canceling an order has to be confirmed twice

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8704] opened 2022-01-11 20:58 UTC
## Description
When canceling an order as a customer I have to confirm two warnings, if I really want to cancel the order. One warning should be enough. It can be seen on the screen video in #8620 already.

## Expected Behavior
When canceling an order there should be just one confirmation dialog.

## Actual Behaviour
There are two confirmation dialogs.

## Steps to Reproduce
0. As a shop owner open an order cycle and allow orders to be changed or canceled (/admin/enterprises/___shop___/edit#!/shop_preferences)
1. As a customer place an order.
2. On the order confirmation page or in the customer profile cancel the order
3. Confirm two warning dialogs

## Animated Gif/Screenshot
https://user-images.githubusercontent.com/1790176/149019650-40b3499b-4c77-41f5-8086-62c8d6586d85.mp4

## Workaround
None.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v4.1.12
* Browser name and version: Firefox 95.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS Desktop

## Possible Fix

**Comment by jibees** [comment] 2022-01-12 09:51
I guess it could be a good candidate for Papercut

**Comment by RachL** [comment] 2022-01-12 10:26
@jibees can it be a good first issue?

**Comment by jibees** [comment] 2022-01-12 10:27
Yes, `good first issue` too I guess! (but we can always be surprised ;))

**Comment by lin-d-hop** [comment] 2022-01-24 09:18
@Dmoment is going to take a look at this one :-)

**Comment by Dmoment** [comment] 2022-01-25 16:44
I am not able to reproduce this issue. Tried both in Chrome and firefox. I am only getting a single confirmation warning.

**Comment by drummer83** [comment] 2022-01-25 17:46
Interesting, @Dmoment! I also couldn't reproduce it anymore on the German production server (same server as I used in the video above). 
Maybe worth mentioning that I also cannot reproduce #8620 anymore (which is also seen in the video above).
Something has changed here... but the only merged PR I could find which is somewhere near around this topic would be #8661.

Maybe @filipefurtad0 has some magic to add, otherwise we might close them both?

**Comment by filipefurtad0** [comment] 2022-01-26 10:25
Could not reproduce this one either, see #8620 :+1: 
Closing.

**Closed by filipefurtad0** 2022-01-26 10:25 UTC
Labels: good first issue, bug-s4
