### ISSUE TITLE
Bulk invoice generation possible, despite missing ABN/ACN

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10452] opened 2023-02-16 17:23 UTC
## Description

Relates to #10337 

Under invoice settings (`/admin/invoice_settings/edit`), the instance may require ABN/ACN numbers in order to generate invoices. This setting is ignored, if the invoice is generated using the bulk invoice generation (`/orders` page)

## Expected Behavior

- A modal should be displayed, like this (currently generated on the `/orders` page):

![image](https://user-images.githubusercontent.com/49817236/219426636-aff144f8-abf7-4523-90fa-dd258a7bf85c.png)

- invoice(s) should not be generated

## Actual Behaviour

Bulk invoice generation is possible, despite missing ABN/ACN

## Steps to Reproduce

As superadmin
1. Under `/admin/invoice_settings/edit` check `Require a business number to generate an invoice?` 

As a hub:
2. Visit `/admin/enterprises/<enterprise_name>/edit#!#business_details_panel` and empty the fields ABN/ACN
3. Verify that you **can't** print invoices on the `/orders/<order_id>/edit` page :green_circle:  
4. Verify that you **can** bulk print invoices on the `/orders` page :red_circle: 

## Animated Gif/Screenshot

Not relevant.

## Workaround

Don't generate an invoice without tax numbers if your instance manager does not want you too :sweat_smile: 

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.2.34
* Browser name and version: Firefox 110
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by RachL** [comment] 2023-02-17 10:33
Duplicate of https://github.com/openfoodfoundation/wishlist/issues/247

Closing

**Closed by RachL** 2023-02-17 10:33 UTC
Labels: bug-s3

**Comment by filipefurtad0** [comment] 2023-02-17 10:58
Oops, forgot to check on the wishlist repo - thanks Rachel!
