### ISSUE TITLE
Reports combining product variant listings from different orders

### ISSUE THREAD

**Issue by gracejam** [openfoodfoundation/openfoodnetwork#9217] opened 2022-05-25 07:03 UTC
## Description
When pulling Order Cycle Customer Totals reports, repeat orders of any one product variant are combined into a single line item. The line item is still attributed to a customer, meaning reports are incorrectly displaying product orders. 
One hub downloads a CSV of a report for 4 different order cycles at once, to import into Airtable. On 17th May, the hub pulled this report and had 538 product variant line items. I pulled the same report with the same filters and had 227 line items. In this report it looks like one customer ordered 10 x 2kg Potatoes from a particular farm, when actually those 10 products were spread across 9 different customer orders (seen by checking each individual order detail) 

## Expected Behavior
One line item is shown for each product variant per customer order in the Order Cycle Customer Totals report. The quantity column corresponds to the quantity of that variant ordered by the customer

## Actual Behaviour
One line item is shown for each product variant but the quantity is combined from multiple different orders and order cycles. This is still attributed to a customer who ordered one of those products, but not necessarily all. The quantity column does not necessarily correspond to the quantity ordered by the mentioned customer

## Steps to Reproduce
1. Go to Order Cycle Customer Totals report
2. Filter by order cycle, producer or date range
3. Where quantity is >1, check the actual order detail if this is correct for this customers order, or other orders are being combined in this line

## Severity
bug-s1 - as requested by Lynne in [#instance-managers here on Slack](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1653459143253259?thread_ts=1653415721.962479&cid=CG7NJ966B)

**Comment by RachL** [comment] 2022-05-25 07:57
Possible scenario happening (need confirmation) : 

The report is aggregating per customers.

This is the list of orders I have on staging, all order with quantity of 1 product : 

![image](https://user-images.githubusercontent.com/6525576/170211354-ef74e26d-dc55-4f43-aa61-89f3f9f5d05b.png)

Reports only shows 2 lines because it aggregated all my rhubarbe: 

![image](https://user-images.githubusercontent.com/6525576/170211460-0bafa8f0-dcf5-4def-9066-081eb3526025.png)

**Comment by RachL** [comment] 2022-05-25 08:28
pinging @seballot if you might have a clue?

**Comment by lin-d-hop** [comment] 2022-05-25 08:48
Is this ONLY impacting Order Cycle Customer Totals?

**Comment by drummer83** [comment] 2022-05-25 08:57
It seems to me that also the date range is not respected. The report shows 7 orders of 'pak choi', but only one was after 1st May, which is the date range filter I applied.

**Comment by drummer83** [comment] 2022-05-25 09:33
Date Completed :
    May 09, 2022 10:08 AM

Order contains Pak choi, Salat Victoria, Strawberries, and more ...

Date range filter START: 
2022-05-**02** 00:00 --> ONLY Pak choi showing (7 instead of 1 during this period)
2022-05-**03** 00:00 --> ONLY Salat Victoria showing
2022-05-**04** 00:00 --> ONLY Strawberries showing
2022-05-**05** 00:00 --> ONLY Stielmus & Bread showing

This is not what I would be expecting...

I can provide order number and username in private message (it's a "real" example).

**Comment by lin-d-hop** [comment] 2022-05-25 09:34
@drummer83 this looks to be a different issue from the one described originally. Meaning it will help to create a new issue for it. It will have a different PR and each fix needs to come out small and fast on these S1s. Would you create a new issue with all the info and images plese? :pray:

**Comment by filipefurtad0** [comment] 2022-05-25 09:59
Yes I agree with your conclusions @RachL @drummer83 : 
- line items are being **aggregated per customer** and being displayed incorrectly on a given order
- changing the date range also changes the **number of aggregated line items** and changes the **displayed order number**

![image](https://user-images.githubusercontent.com/49817236/170235334-ee04af98-1eb2-4176-b242-da9e6ec30731.png)

This hides line items on orders placed before the 09.05:

![image](https://user-images.githubusercontent.com/49817236/170235978-c0c37e56-96b9-4d64-9129-a30489457028.png)

It seems to me that, in the limit, the **report works correctly** for a date range which includes only one order.

So, yeah the issue is reproducible and well described - nice catch @gracejam :raised_hands:

**Comment by drummer83** [comment] 2022-05-25 10:00
`Is this ONLY impacting Order Cycle Customer Totals?`

Packing reports (all three types) seem to be ok, @lin-d-hop

**Comment by lin-d-hop** [comment] 2022-05-25 10:04
Let's see if @jibees fix resolves the date filter issue too...
Depending on the order the filters translate into 'where' conditions it may be fixed by the recent PR or it may be a separate issue :thinking: 
One for testing... but I think we can just get the fix out because it will definitely improve regardless of whether it solves all the issues.

**Comment by seballot** [comment] 2022-05-25 10:18
Hi ! Sorry I was on a meeting, looking at it now

**Comment by lin-d-hop** [comment] 2022-05-25 10:23
@seballot there are already fixes ready to go for the two s1s:
https://github.com/openfoodfoundation/openfoodnetwork/pull/9192 For all orders_and_fulfillment reports, distinct product by variant, price & order_id
https://github.com/openfoodfoundation/openfoodnetwork/pull/9219 Add order range on packing reports

**Comment by RachL** [comment] 2022-05-25 11:50
Solved by #9192 - closing and we can reopen if we have other data to reproduce.

**Closed by RachL** 2022-05-25 11:50 UTC
Labels: bug-s1
