### ISSUE TITLE
Using internetbrowser back button, forgets all shopping cart items #ux

### ISSUE THREAD

**Issue by simoneluijckx** [openfoodfoundation/openfoodnetwork#1809] opened 2017-09-06 08:09 UTC
A: action | P: problem | S: solution

A: I'm viewing my shopping cart but want to do more shopping, I click on my internet browser's backbutton
P: My cart is empty suddenly! (so frustrating, could lead to people not continuing their shopping)
![image](https://user-images.githubusercontent.com/31434588/30100920-cf626b04-932d-11e7-84e5-1a1a78579b0d.png)
S: the 'continue shopping' button should be better visible OR when clicking the internet's back button, it should remember your cart (best solution I think)

**Comment by sauloperez** [comment] 2017-09-06 08:39
What happens if you then (after clicking on the browser's back button) refresh the page? AFAIK the line items are persisted in your cart until you remove them or place the order

**Comment by simoneluijckx** [comment] 2017-09-06 10:53
After clicking on the back button and next on the refresh button, nothing changes. Still an empty card...

**Comment by sauloperez** [comment] 2017-09-06 10:58
weird... perhaps it's not persisted until you reach the checkout page...

**Comment by simoneluijckx** [comment] 2017-09-06 11:14
Here are the steps I took:
1: 
![image](https://user-images.githubusercontent.com/31434588/30108916-9e9a0652-9347-11e7-8138-b7c7ff9f5f0b.png)
2. 
![image](https://user-images.githubusercontent.com/31434588/30108976-ea783882-9347-11e7-947b-a39d56de2a02.png)
3. 
![image](https://user-images.githubusercontent.com/31434588/30109072-45fdb16e-9348-11e7-9826-7967c4660fd9.png)

**Comment by myriamboure** [comment] 2018-05-21 18:28
Closing as duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/1213 which has been fixed and merged!

**Closed by myriamboure** 2018-05-21 18:28 UTC
Labels: bug
