### ISSUE TITLE
Producers not showing in group 'our producers tab' despite showing on map

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1173] opened 2016-10-03 01:24 UTC
This is of reasonably high priority, because we're trying to get groups on board and the pages need to be functioning.. Likely related to recent work done to property and taxon filters by Rohan.

Some producers are not showing the the 'our producers tab' for thenew [Demo North east group](https://openfoodnetwork.org.au/groups/north-east-local-food-producers#/producers). This is despite them being in the group, being visible and showing on the group's map. Playing with the filter may reveal some enterprises and make them unhidden, so I suspect it's related to the filters. Exisiting group pages seem to be fine - e.g. https://openfoodnetwork.org.au/groups/flavour-crusader#/producers 

![image](https://cloud.githubusercontent.com/assets/10843056/19025433/60fe9652-8964-11e6-8c73-0111ebf763c1.png)

**Comment by sstead** [comment] 2016-10-07 03:58
Maikel said this was due to one profile- we removed that enterprise from the group and this solved the problem. Chocolate RenMar

**Comment by RohanM** [comment] 2016-10-14 03:42
Discussed with @sstead and it seems that although we can work around it, it would be better to fix the root problem. We suspect that is: When an enterprise has an address that can't be geocoded, it doesn't appear on the listing.

@sstead Could you post instructions to reproduce the problem?

**Comment by sstead** [comment] 2016-10-14 06:27
I've tried to replicate the problem unsuccessfully today, by creating a new enterprise with errors in the address and then adding it to a group. Bug hasn't reappeared. Can try again if needed.

**Comment by sstead** [comment] 2016-10-21 00:09
Dani has suggested that an even better solution would be to implement an address validator - https://github.com/openfoodfoundation/openfoodnetwork/issues/546

Then we won't have any funny bugs caused by incorrect addresses.

**Comment by myriamboure** [comment] 2017-12-21 05:15
@sstead if we can't reproduce that bug, can we just close it and maybe create an icebox or wishlist item for https://github.com/openfoodfoundation/openfoodnetwork/issues/546 ? Please reopen if you disagree ;-)

**Closed by myriamboure** 2017-12-21 05:15 UTC
Labels: bug
