### ISSUE TITLE
Resend email confirmation should not return me to dashboard

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#1966] opened 2017-11-15 22:25 UTC
## Description
I am resending email confirmations from entreprise menu (tab "managers") and each time i do one it returns me to dashboard.
(NOTE: wait for email confirmation job to be complete before checking and working on this)

## Expected Behavior
When I resend email confirmation I stay on the same enterprise set up menu. This is inconsistent with other behaviour in site.

## Actual Behavior
When I resend email confirmation I am redirected to dashboard page.

## Steps to Reproduce
1. Go in an enterprise set up menu, tab "managers"
2. Invite some user who is not yet on OFN, you get the message telling you that a confirmation link has been sent to her.
3. Try to click on "resend"
4. You are redirect to the dashboard.

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/2911176/32863591-201820d4-cab0-11e7-9c2f-49b6789e217d.png)

![image](https://user-images.githubusercontent.com/2911176/32863593-258fbb4e-cab0-11e7-80ca-992482ace3c3.png)

## Context
As an admin when trying to manage user confirmation issues.

## Severity
S5. Annoying but we can live with it, it happens very rarely that a hub has to do that, mainly an instance admin.

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by RachL** [comment] 2019-03-19 17:05
@kirstenalarsen I don't see this link anymore. Was this something removed part of the work with email confirmation stuff?

**Comment by lin-d-hop** [comment] 2022-11-18 17:15
Closing as i couldnt reproduce

**Closed by lin-d-hop** 2022-11-18 17:15 UTC
Labels: bug-s5
