### ISSUE TITLE
When creating a new product, if I see an error all my data is lost

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#9067] opened 2022-04-04 16:12 UTC
## Description

When creating a product there are many many silly little things that can cause my product not to save because of an error.
However after seeing the error all of the data I input to create my product is lost.
Many error messages are opaque and hard to understand. And when they pop up my info has been lost so I can't actually see what the 'invalid data' might have been and I have to start from scratch. I'm then really likely to make the same mistake and this is ANNOYING

## Expected Behavior

When I see an error on creating a product, all the information that I input is still there on the screen so I can relate the error to the data. Even better would be if the field that caused the error was highlighted in some way!

## Actual Behaviour

When I hit save the data disappears from the screen and I can't see which field the error might actually have been relating to.

## Steps to Reproduce

1. Hit New Product
2. Input all the fields but leave 'value' blank
3. Hit save
4. See that some of the info is removed, some of the missing compulsory fields have a note to let you know while others don't. There is no uniformity to the experience for the user. It is pretty confusing. 

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

The ideal solution will include:
- No fields are wiped when you hit save
- All compulsory fields show in the same way when not completed. In the big warning box and with the small red text under the field.

**Comment by RachL** [comment] 2022-04-04 16:20
@lin-d-hop I think this is a duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/9047

Are selecting this as your_current_ S3 or papercut selection?

**Comment by apricot12** [comment] 2022-04-19 07:26
@lin-d-hop If at all possible, could you give me more details on the errors you encountered?

**Closed** 2022-06-13 13:54 UTC
Labels: bug-s4, UK
