### ISSUE TITLE
Product price jumps to a new line in non english locale

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#6567] opened 2020-12-28 10:33 UTC
## Description

In path: https://openfoodnetwork.ru/demo-ferma-dyadi-vani/shop?locale=ru#/shop
when adding item to cart, if item price is more than 4 digits and locale is 'ru', then item cost is jump to a new line

## Steps to Reproduce

1. open shop url above
2. add to cart item with price xxxx, for example meat

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/103208044-c8142580-4910-11eb-8c54-16c5ec85b1ca.png)
![image](https://user-images.githubusercontent.com/928628/103208061-d104f700-4910-11eb-88a7-fb376430f383.png)
![image](https://user-images.githubusercontent.com/928628/103208081-da8e5f00-4910-11eb-82c8-b0821a20d950.png)

## Your Environment

* Version used: 3.4.5
* Browser name and version: Firefox 78.5.0esr 
* Operating System and version (desktop or mobile): desktop opensuse 15.2

**Comment by filipefurtad0** [comment] 2020-12-28 12:15
Thanks for opening this one @romale :+1: 
It looks like this the empty space is breaking the line - related to issue #6252 and PR #6383.

I can't quite reproduce this scenario on our staging servers, as I'm unable to observe a price which has an empty space, as a thousands marker such as `1 000,00` - as shown in your pic. According to your settings, the "Currency thousands separator" marker should be a comma `,` right? This might be related to the "Use the international thousand/decimal separator logic" option, but I'm not sure.

**Comment by dacook** [comment] 2023-09-27 07:04
A space seems like a valid thousands separator. I think it's probably fixable by setting the CSS text wrapping mode to not wrap. This might be relevant for other parts of the app where price is displayed, but I'd start by focusing on this case first.

**Comment by dacook** [comment] 2024-07-08 00:57
Good spotting, it seems that the currency setting can only be updated by setting environment variables.

However for this bug, I think you just need to change the "Currency thousands separator" to a space. Then you can create a price that is more than 1 thousand to test it out.

**Comment by dacook** [comment] 2024-07-17 23:20
Thanks for testing this out. I'm wondering if you tried different screen sizes too? 

If it's not an issue on any screen sizes, then I guess it is fixed already, which is good news! Once you can confirm, we can close the issue.

**Comment by wandji20** [comment] 2024-07-18 15:40
Hi
It seems this issue has been fixed in the scope of another.
While resizing, I noticed some edge cases at some breakpoints with displays for product unit price and total price.

- From 641px up till 735px
![Screenshot from 2024-07-18 14-21-02](https://github.com/user-attachments/assets/6a5e231c-50c6-45ba-a2a6-493c22f4321a)

- From 1025px up till 1145px
![Screenshot from 2024-07-18 14-23-29](https://github.com/user-attachments/assets/052ea87e-75ca-412e-bea5-7a82ea5f35a7)

#### Possible Fix
Increasing the width of the total price on medium screens would resolve the first one.

**Comment by dacook** [comment] 2024-07-21 23:30
Thanks for investigating @wandji20. That sounds like a good fix for both those breakpoints, could you please go ahead and try it? 

It would be worth testing with a long unit description, for example (`/admin/products`):
![Screenshot 2024-07-22 at 9 28 03 am](https://github.com/user-attachments/assets/fb83aef5-56a8-4b36-aafb-d253a9b622b1)
(But it looks like that should still fit pretty well)

**Closed** 2024-08-18 11:25 UTC
Labels: good first issue, bug-s4, hackathon
