### ISSUE TITLE
[User->New] Language is displayed twice

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#11513] opened 2023-09-08 10:54 UTC
## Description

Follow up of #11487.

Admin > Users > New

The default language (English in this case) is appearing twice in the list of languages.
I assume this happens because we are listing the LOCALES + AVAILABLE LOCALES (see `.env` file). If the locale is listed as available locale as well (as it is probably in a well configured instance) we should only show it once.

## Expected Behavior

Show every language once only.

## Actual Behaviour

The default language is shown twice.

## Steps to Reproduce

0. In the `.env` file (or `.env.development` or `.env.staging`) make sure you have the `LOCALE` language listed in the `AVAILABLE LOCALES` as well. Restart Puma if you had to change this.
1. Log in as super admin.
2. Check the language dropdown menu on the /admin/users/new page

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/43aa5903-2a99-4dd0-8ff9-cc03f397c469)

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: staged #11487 
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Decoder76** [comment] 2023-12-22 12:08
Assign this to me

**Comment by drummer83** [comment] 2023-12-22 12:14
Thanks @Decoder76!

Don't hesitate to get in touch here on in Slack if you get stuck. Response times may be a bit longer during Christmas time though...

**Comment by dacook** [comment] 2024-03-17 22:36
This form is located at `app/views/spree/admin/users/_form.html.haml`, which points to https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/i18n_config.rb#L18-L21
Looks like the duplicates are not considered by `uniq`. Maybe we need to  add a block with a custom comparison for `uniq`.

**Comment by dacook** [comment] 2024-03-18 22:27
Thanks for looking into this. 
@drummer83 I can see now this is a configuration problem, not a bug. I just tried this:

```
LOCALE="en"
AVAILABLE_LOCALES="en,en_AU,en_GB,fr,es,en"
```
I can see three "English" options, which I believe is correct: `en`, `en_AU` and `en_GB`. There's no duplicate of `en`. They look like duplicates because they have the same label, because normally we don't have more than one English enabled on a system.

![Screenshot 2024-03-19 at 9 23 02 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/48a9a5c5-04f7-4ab6-83e1-778008dabb4d)


I looked at the staging environment, and we have something a bit different:
```
LOCALE="en_AU"
AVAILABLE_LOCALES="en,fr,es"
```
I don't think it should be configured like that, so will update it.

**Comment by dacook** [comment] 2024-03-18 22:57
Ok, I fixed the config, but there is still a bug. The default `en` language is always showing. For example with this config, `en` is appended to the end of the list. @sergioosouzaa would you be able to investigate why?

```
LOCALE="en_AU"
AVAILABLE_LOCALES="en_AU,fr,es"
```
![Screenshot 2024-03-19 at 9 56 33 am](https://github.com/openfoodfoundation/openfoodnetwork/assets/4188088/305d91bc-12d1-4952-8f90-dff4c8ea7f6d)

**Comment by sergioosouzaa** [comment] 2024-03-19 13:45
@dacook I was able to identify the issue, however, I need some clarification about the business rules. English is always being appended at the end of the list, because the source_locale defined on the code (en) is always appended at the end, and in this case, since the default language is en_AU, this passes the .uniq method. Is this behaviour intended? Should English always be available even if it is not in the .env variables?

**Comment by dacook** [comment] 2024-03-20 00:50
I think that here, when creating a user, only the configured "AVAILABLE_LOCALES" should be showing.

Looking again now, I think I can see this was an unintended effect in PR referred to at the top of this issue.
I think that `I18nHelper::locale_options`, should be using the method `OpenFoodNetwork::I18nConfig.selectable_locales` instead of `available_locale`. 

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/lib/open_food_network/i18n_config.rb#L12-L21
(it's a bit confusing because the method names don't match the env var name)

**Comment by mkllnk** [comment] 2024-05-03 05:26
Fix was reverted:

* https://github.com/openfoodfoundation/openfoodnetwork/pull/12434

**Comment by mkllnk** [comment] 2024-05-03 06:02
Instead of modifying `available_locales` we should make use of `locale_options` in the front-end.

**Comment by dacook** [comment] 2024-05-05 23:13
☝️ Agreed!!

**Comment by wandji20** [comment] 2024-07-19 09:36
Hi
I have an open [PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12655) for this one

**Comment by drummer83** [comment] 2024-07-19 09:54
Thank you!
I've moved it to Code Review! 💪🏻

**Closed** 2024-07-28 11:46 UTC
Labels: bug-s5
