### ISSUE TITLE
Updating Order Cycles hangs when number of products grows too large

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#838] opened 2016-02-25 18:00 UTC
I edited the current (only!) Stoudco order cycle on staging by adding a new producer ("Stroudco Food Hub") to the incoming list.  Clicked update and this saved correctly.  I then added the new "Stroudco Food Hub" products to the outgoing order cycle but when i clicked update nothing happened.  I waited over an hour and still nothing!
when i went back in to the order cycle the new products were still unselected in the outgoing list.

![screenshot 2016-02-25 12 32 14](https://cloud.githubusercontent.com/assets/10517702/13329008/add060b0-dbe9-11e5-8f37-6a1296157f71.png)
![screenshot 2016-02-25 12 32 26](https://cloud.githubusercontent.com/assets/10517702/13329010/add1be10-dbe9-11e5-8092-1729aeb61fcb.png)
![screenshot 2016-02-25 12 33 00](https://cloud.githubusercontent.com/assets/10517702/13329009/add052aa-dbe9-11e5-994e-87e9dca7ba72.png)
![Uploading Screenshot 2016-02-25 17.58.45.png…]()

**Comment by NickWeir63** [comment] 2016-03-03 14:18
This now seems to be working fine.  all the order cycles were wiped from staging during the updates last night (slightly worrying) but i am now able to create and update order cycles fine.  so closing this now

**Comment by NickWeir63** [comment] 2016-03-06 18:46
this is not working again
i have added loads of products to the incoming part of the Stroudco order cycle on staging but when i add them to the outgoing part of the cycle and click update - nothing happens and when I come back to it the products are not included in the outgoing list
@lin-d-hop do you have time to look at this?
thanks

**Comment by lin-d-hop** [comment] 2016-03-07 13:08
Hi @NickWeir63 I've been looking into this and the problem only occurs when the order cycle starts to get really large, with >500 products.
Looking at staging2 none of the super admin order cycles has more than 30 products so they won't be experiencing this.
Our production server has double the memory (4gig) to our staging server so this would likely explain why we don't see the issue on production.

It is troubling that the length of time to update the order cycle seems to increase exponentially with increase in number of products.

**Comment by NickWeir63** [comment] 2016-03-07 14:02
thanks for looking at this
shall we put it in icebox?

**Comment by lin-d-hop** [comment] 2016-03-07 14:26
No, it will severely limit our ability to test product load speed functionality.

**Comment by lin-d-hop** [comment] 2016-03-07 16:25
Ok I think we close this for now. It's not really a bug, but will quite possibly be the cause of future enhancements. If we need to test on large data in the future (should remain unlikely on the staging server, which is more to check functionality) we know server memory is an issue. If we find this issue popping up on production we will either need to optimise order cycle updates or increase server memory (both come with a cost obviously so we'll need to figure out the best solution then).

**Comment by NickWeir63** [comment] 2016-03-24 17:18
Sorry but this is now happening on production.  We have added new producers to the current Stroudco order cycle and although it will save changes to the incoming part of the cycle it will not save the additions to the outgoing cycle

**Comment by NickWeir63** [comment] 2016-03-24 17:36
OK  so i just went in and removed some redundant producers from the order cycle and it brought the variant total down from 688 to 577 and it is now updating correctly.
So we are OK for now but might need to do something about this in the near future

**Comment by lin-d-hop** [comment] 2016-03-24 17:43
Yep, this will need a looking at soon and I think it might be best to ask @RohanM if he might be able to take a look since the profiling will be fresh in his huge brain along with the potential solutions.
@daniellemoorhead Could we explore tagging this on to the end of the load speed work? Or speccing it to start with?
Huge thanks!!

**Comment by lin-d-hop** [comment] 2016-04-07 18:21
Chatting with @oeoeaio today we've come up with the following:
- This looks like it will be tackled as part of the inventory management by having inventories added to order cycles instead of individual products
- This work won't be scheduled until mid winter for the southern hemispherers.
- This will soon be a priority for the UK team
- The UK team will work around by upping the memory on our servers when this becomes an issue.

**Comment by oeoeaio** [comment] 2016-04-07 21:40
Hey @lin-d-hop, I'm just thinking: it might be worth playing around on the inventory page for a hub with 500+ products to see how it handles them. There are obvious improvements to usability through being able to search and filter products, and in the way that the inventory only initially renders 20 products by default. However, we should be sure that we are not just shifting the load time problem from the OC page to the Inventory page, or that we at least think the inventory page represents a better option in the long term.

Note: be careful with hiding products on the inventory page, this is now flowing through to the shopfront, meaning that hidden products become unavailable to select in order cycles and therefore in the shop.

**Comment by lin-d-hop** [comment] 2016-04-08 09:05
Nice thinking @oeoeaio... will do.

**Comment by OliverUK** [comment] 2016-04-13 14:25
I just tried to save our current order cycle and on pressing "update and close" nothing seemed to happen. The changes appear to be saved though.

**Comment by oeoeaio** [comment] 2016-04-14 00:07
Hi @OliverUK. Should be directing you back to the order cycle list after it has saved. @bingxie is going to be working on some improvements (#881) to help communicate what is happening during long save/load actions.

**Comment by OliverUK** [comment] 2016-04-14 09:07
Hi @oeoeaio Rob,
I couldn't replicate it just now as after a minute or so it did actually do it. Yesterday it didn't but then everything else was running really slowly yesterday in the backoffice. Maybe there was more capacity available this morning?

**Comment by NickWeir63** [comment] 2016-04-14 16:46
I am having similar intermittent problems.  Just now when I clicked 'update' nothing happened but when I click 'update and close' the update did work after a few minutes delay.

**Comment by lin-d-hop** [comment] 2016-04-20 16:41
hi @oeoeaio 
Playing around with an Inventory of 800+ products the inventory page seems a great way to manage products in an order cycle. The pagination makes all the difference. It seems to hang on loading all products but given the search and filter options I don't think this is a problem. In fact I would be tempted to remove the 'Load All'  button...?

**Comment by OliverUK** [comment] 2016-04-26 16:20
Once again unable to safe OC.

**Comment by NickWeir63** [comment] 2016-04-26 17:08
Just talked this through with Oliver.  Both of us are getting intermittent problems with the order cycle sometimes not updating, sometimes it goes back to the list of order cycles when we click "update and close", sometimes nothing appears to happen but the order cycle has updated correctly and sometimes nothing appears to happen and the order cycle has not updated correctly.
@lin-d-hop is it worth upgrading the server and see if this helps with this issue and with [the loadspeed issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/828)

**Comment by lin-d-hop** [comment] 2016-05-02 12:48
@pmackay 
Would you upgrade our production server this week when you get a chance? Since it involved some downtime could you try and plan for a slow time of day?

@NickWeir63 Happy to try upgrading the server for the Stroudco switch, but I don't think we've found the core of any problems on this just yet. The bottleneck seems to be CPU usage on our servers and I hope the upgrade to 4 cores will help relieve this a little but in the longer term this will take more work, particularly for the slower internet connections we see around a lot of the areas we work.

**Comment by NickWeir63** [comment] 2016-05-02 16:21
Thanks for the upgrade.  However, I have managed to update order cycle successfully twice today (now up to 562 variants) but I know that @OliverUK  has found it trickier than me - he is away for a few days but will check with him later this week

**Comment by lin-d-hop** [comment] 2016-05-02 17:24
@NickWeir63 No upgrade has happened yet. I suspect today is an exceptionally low traffic day ;-)

**Comment by NickWeir63** [comment] 2016-05-02 20:12
OK yes lets go for the upgrade.  Thanks

**Comment by pmackay** [comment] 2016-05-03 07:25
Will try to do this Thursday.

**Comment by OliverUK** [comment] 2016-05-03 12:34
I'm grateful.

**Comment by NickWeir63** [comment] 2016-05-03 16:57
Very very slow/stopped again today - bring on that upgrade!

**Comment by NickWeir63** [comment] 2016-05-04 13:51
I was just working with a Stroudco producer who has permission to add to the Stroudco order cycle.  When we logged in as her and added new products it was very quick and easy to add these products to the order cycle.  Is there any way we can log in as a producer without them having to give us their password?

**Comment by OliverUK** [comment] 2016-05-04 16:09
I must admit the same thought had crossed my mind.

**Comment by lin-d-hop** [comment] 2016-05-04 20:01
That's interesting. This might suggest it's the enterprise relationships that is slowing this page down.
Is your goal to then log in as each producer you need to update in order to make changes? So you need all of the producers log ins that you would want to edit?

**Comment by OliverUK** [comment] 2016-05-04 21:23
Lynne, I guess the answer is yes. It doesn't sound ideal but as we keep getting stuck on saving our 600+ item order cycle it would be a work-around to log in as the producer whose items need adding. This then only shows their products and we can save from there. In fact everything is quicker on the produce side, presumably because much fewer items need to load?

**Comment by lin-d-hop** [comment] 2016-05-04 22:10
Can you instead ask another user (belonging to you) to be made a manager of that enterprise? This way you don't need their passwords.

**Comment by OliverUK** [comment] 2016-05-05 08:48
@lin-d-hop  That makes it more complicated but yes, it's possible. Maybe we can see if the upgrade helps first. @pmackay ?

**Comment by OliverUK** [comment] 2016-05-05 13:41
I have tried what @lin-d-hop  suggested and added my self as manager of Woodchester Valley Vineyard under an email address different to the one I use as hub manager. 
I'm able to see the wine in question but I'm unable to add it to the order cycle. OFN simply won't let me tick it. 
![screen shot 2016-05-05 at 14 37 27](https://cloud.githubusercontent.com/assets/17590921/15044906/7daf414a-12cf-11e6-85c2-99af9ab71489.png)

**Comment by OliverUK** [comment] 2016-05-05 13:53
And my dashboard looks like this. A list of enterprises flashes up for a split second and then disappears again.

![screen shot 2016-05-05 at 14 50 59](https://cloud.githubusercontent.com/assets/17590921/15045152/00e32c92-12d1-11e6-91b5-6a0fa4982edf.png)

**Comment by NickWeir63** [comment] 2016-05-05 18:16
Hi @OliverUK can i just check that you have given Woodchester permission to add to the Stroudco order cycle

**Comment by NickWeir63** [comment] 2016-05-05 19:40
I have just tried a regular update of the full Stroudco order cycle and 10 minutes after clicking "update and close" still nothing has happened...... Can I just check @pmackay whether you have upgraded the server?
Thanks

**Comment by pmackay** [comment] 2016-05-05 20:10
I havent yet, I pinged a few questions at @lin-d-hop earlier but no reply yet (must be busy!). Will update here when its upgraded.

**Comment by OliverUK** [comment] 2016-05-05 20:41
@NickWeir63 No, I hadn't. That's where I went wrong then!

**Comment by NickWeir63** [comment] 2016-05-06 13:30
Thanks @pmackay for your text confirming the update.  Was that an update to the software or an upgrade to the server?  Anyway I just tried opening the Stroudco order cycle and it seemed to open faster than it used to (but maybe that was wishful thinking!) but then when I added a missing product to the outgoing order cycle then clicked "update and close" nothing happened - I waited 6 minutes then gave up.  When I reopened the order cycle sure enough the change had not been saved  -it still shows "630/631 selected" for the outgoing cycle

**Comment by OliverUK** [comment] 2016-05-06 13:42
If it was my computer I'd say it runs out of memory during the operation.

**Comment by pmackay** [comment] 2016-05-06 14:29
@NickWeir63 if you want to get on skype and test that again while I scan the logs we could try that? I updated the software yesterday to v1.7 and the hardware today. So maybe this is a software issue?

**Comment by pmackay** [comment] 2016-05-06 15:15
While @NickWeir63 and I were testing, it looks like Bugsnag was triggered and recorded this:

`Products JSON differs from cached version for distributor: 200171, order cycle: 200195`

@RohanM can you give a bit of info about what this means and why it would happen? Could it be a cause of the order cycle not being saved properly?

And might this be related to #983?

**Comment by NickWeir63** [comment] 2016-05-06 15:21
Thanks Paul for the skype chat just now.  This is a log of what we tried for the record.  Basically it seems that the update process is now working correctly - apart from the fact that when we click update and close it doesnt take us back to the "Admin Order Cycles" page where it used to.   But the update is successful (according to Paul's log it takes just a couple of minutes)
The weird thing is that there is something wrong with the incoming order cycle of one of our producers; Over Farm.  There seems to be an invisible product in the order cycle....  When I deselect all the Over Farm products the "PRODUCTS"  box still shows 1 / 61 selected even though none of the products below are selected.   
![screenshot 2016-05-06 16 17 39](https://cloud.githubusercontent.com/assets/10517702/15077455/5b8586ce-13a6-11e6-893c-e957d0db76b5.png)

anyway the good news is that the server upgrade has sorted our updating problem - thanks very much @pmackay  and @lin-d-hop

**Comment by pmackay** [comment] 2016-05-09 11:25
@NickWeir63 what's the status of this now? Does the "Over Farm" issue need resolving? Should that be a separate issue?

**Comment by NickWeir63** [comment] 2016-05-09 11:49
there is still an issue that when we click update and close it doesnt close and when we click update we dont know when it has updated.  I dont know whether the over farm issue is separate or whether this phantom product is causing this issue.  It looks (from my very uneducated guess) like the bugsnag you listed above might be to do with a dodgy product??

**Comment by lin-d-hop** [comment] 2016-05-09 12:28
The bugsnag looks to me like the standard bugsnag triggered when the cache is out of sync. 
Not sure what is happening with the dodgy product. I took a quick look but will need to dive a little deeper. I don't think the Over Farm inconsistency is related to the Order cycle updates. 

The processing icon #881 is due out in the dot release next week. I say wait for this in order to gain more clarity on whether an order cycle has updated or not.

**Comment by OliverUK** [comment] 2016-05-09 15:27
I don't think the fact that it doesn't "close" the screen is the only problem now left. I've been unable to save an order cycle today. Having set up a new order cycle I was able to save the name and date changes and even changes to the incoming side but the outgoing part won't save.

**Comment by lin-d-hop** [comment] 2016-05-09 19:46
@OliverUK Unfortunately there is no quick fix for this so you will have to bear with us. We understand this is important for Stroudco and we are scheduling the work.
Here are some more work arounds in the mean time:
1) Try making the updates at quiet times when other people aren't using OFN. I understand this may be inconvenient but it will work. Weekends, Early am and late at night should be fine.
2) The loading feedback scheduled to be released in the upcoming dot release will make it more obvious what is happening.

Please feel assured that this issue is known to UK and Au development teams and is a priority.

**Comment by NickWeir63** [comment] 2016-05-09 20:27
I just updated the 21st May order cycle by adding the new products to the outgoing part of the cycle, clicked 'update and close' and although nothing happened, when I then clicked on 'order cycles' at the top I see that the 'Admin order cycles' menu shows this order cycle now has 626 variants (627 less the one phantom product) so appears to have saved successfully.  However when I reopen the 21st May order cycle it looks like there are only 612 products in the outgoing order cycle.  @OliverUK please can you check whether any of the new products that you have just added to this order cycle show up in the shopfront if you make this order cycle live temporarily.
So if the new products have saved successfully then maybe I have a faster internet connection (?) so a short term fix @OliverUK is that you just let me know whenever you want an outgoing order cycle updating and I will do it.  We could also experiment with you logging in as me on your connection and me logging in as you here to see if this narrows down the issue definition?

**Comment by lin-d-hop** [comment] 2016-05-09 20:32
@Nick, more likely 9:30pm is a slower time for our server traffic and hence you've not had the same trouble. Similarly 9:30pm might be a generally slower web traffic time around Stroud. I think the timing is the most likely aspect. Try making changes at 'off-peak' times as per my previous comment.

**Comment by NickWeir63** [comment] 2016-05-09 20:33
.....another option @OliverUK is that we give Godsells permission to add to order cycle and login on their account to add these new products

**Comment by OliverUK** [comment] 2016-05-09 20:42
@NickWeir63 I reckon the Admin Order Cycles screen takes the 626 figure from the incoming part and that it's no indication whether the outgoing part is saved. 
@lin-d-hop I often work on OFN in the mornings and haven't found that order cycles save any more successfully then, unfortunately.

**Comment by NickWeir63** [comment] 2016-05-09 21:44
Yes and I just tried updating it again just now 10.40pm and it still didn't save.  I will do the workaround (giving Godsells permission to add to order cycle) tomorrow morning

**Comment by NickWeir63** [comment] 2016-05-10 10:08
OK I made my nick@stroudco a manager of godsells.  i gave gosells permiossion to add to order cycle, then logged in as nick@strtoudco and added godsells products to the outgoing order cycle.  It updated quickly and now shows as 626/627 products (there is still a phantom product in there) in the outgoing cycle.  The only thing I cant seem to update is the 'pick up/delivery' date which should read '21st may' - any ideas how we can update this before tomorrow night when this order cycle needs to go live?
![screenshot 2016-05-10 09 56 28](https://cloud.githubusercontent.com/assets/10517702/15142925/1f7be898-169f-11e6-8ac6-7ceb78a21c89.png)

**Comment by NickWeir63** [comment] 2016-05-10 13:42
i tried editing just the 'pick up/delivery' date to 21st May in superadmin but it wont update.  I guess we could take out some of the suppliers from the incoming order cycle, change the date and update it with fewer suppliers and then add the suppliers back in again using the reduced login fix above....... but that is a bit long winded - is there a quicker way @lin-d-hop @daniellemoorhead ?

**Comment by NickWeir63** [comment] 2016-05-11 10:55
Thanks Lynne for finding a temporary work around for this.  For the time being @oliver we need to set up the new order cycle a few days in advance of when we need it so that Lynne can find time to adjust the date for us

**Comment by OliverUK** [comment] 2016-06-03 13:44
@NickWeir63 @lin-d-hop 
I've been trying to save the outgoing order cycle with no luck again today. Nick could you "select all" in the outgoing cycle and see if you have any more luck? Our work around for other producers is still ok, where we log in as someone who only has a small number of items under his management and who is allowed to add to our OC. But as I'm changing products for producer Stroudco, this doesn't work. 
Lynne, I don't know what you do when you amend the "ready for" date for us but can you use the same trick to add products?

**Comment by lin-d-hop** [comment] 2016-06-03 14:24
Nope, I can't risk adding products in this way. The data has too many dependancies. Sorry @OliverUK 

As you can see from http://community.openfoodnetwork.org/t/order-cycles-2-0-schedules/575/5 its rather complex to come up with a good long term solution. So we'll be waiting for a little while. But we do need to look at scheduling this work if we can finance it ok.

Temp workaround... add these products under another producer temporarily until we can get this fixed...?

**Comment by NickWeir63** [comment] 2016-06-03 14:32
I selected all on the outgoing then update.  the 'SAVING....' message came up for ages but it has not saved.

What about Lynne's idea of making a separate email address the manager of just the Stroudco products - or have you tried this already?

**Comment by lin-d-hop** [comment] 2016-06-03 14:46
A whole separate enterprise... like all the ones that do work. Even if it is just for new products while we can't actually save the OC.

**Comment by OliverUK** [comment] 2016-06-03 14:48
Yes, it would have to be a separate enterprise, so I don't get all the 600+ products. It guess that'll have to be the way forward for now.

**Comment by lin-d-hop** [comment] 2016-06-03 15:03
You will have to add that enterprise to the outgoing order cycle.

Perhaps another workaround required... are there any other enterprises that could adopt products?

**Comment by OliverUK** [comment] 2016-06-03 15:07
Let me try. I think if I add it to incoming first, which usually does save, then I may be able to add to outgoing from the separate account.

**Comment by OliverUK** [comment] 2016-06-03 15:26
OK, I created an enterprise (Essential Trading) and put the Essential items in it. I was able to add the enterprise to incoming and then switch user and add the items to outgoing.

**Comment by OliverUK** [comment] 2016-06-03 15:27
@lin-d-hop while I have your attention, I'd be grateful to have the "ready for" date for my latest OC fixed again. There is a new OC called 18th June.

**Closed** 2016-06-24 00:52 UTC
Labels: p - important, uk
