### ISSUE TITLE
[Flaky] ./spec/system/admin/order_cycles/simple_spec.rb:753

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10302] opened 2023-01-20 14:07 UTC
### What we should change and why (this is tech debt)

```

  1) 
    As an administrator
    I want to manage simple order cycles
 modify the minute of a order cycle with the keyboard, check that the modifications are taken into account
     Failure/Error:
       within "#save-bar" do
         expect(page).to have_content "You have unsaved changes"
       end
     
     Capybara::ElementNotFound:
       Unable to find visible css "#save-bar"
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3968267993/jobs/6801215972

**Comment by anshu1992** [comment] 2023-02-13 04:44
I can work on this.

**Comment by jibees** [comment] 2023-02-13 09:49
Hi @anshu1992 👋 
and thanks a lot, I'll assign it to you ;)

**Comment by mkllnk** [comment] 2023-02-14 03:23
Here's a another failure: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4169999563/jobs/7218546561

**Comment by anshu1992** [comment] 2023-02-15 08:45
Hey @mkllnk and @jibees. I will do both of these in the same PR.

**Comment by anshu1992** [comment] 2023-02-20 12:17
Hey @jibees, I tried to run this particular spec as well as all the specs in that file. They don't fail for me at all. Tried over 10 times. I tried to run all the specs but they take over 2 hours for me and even then get stuck (doesn't finish the process at all). 

Is there another way to test this? I see there is a `retry: 3` option on the failing spec block and I tried to run it after removing it but no luck. They all pass.

**Comment by filipefurtad0** [comment] 2023-02-22 17:39
Hey @anshu1992 ,

Thanks for working on this. We've came up with a routine to track flaky specs, locally. It's basically a script, which allows running a spec repeatedly while the output is recorded in a temp file. It's described [here](https://app.gitbook.com/o/-L9rgjXCVdbnhSow2XnR/s/-M7NnFH2urYVKG6zlEtN/testers-toolkit/flaky-specs). I hope this helps!

**Comment by anshu1992** [comment] 2023-02-23 12:57
Hey @filipefurtad0,

Thank you for the resource, will check it out.

**Comment by anshu1992** [comment] 2023-02-26 09:25
Hey @jibees and @filipefurtad0 , I ran the spec 100 times and it passes 99% of the time.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/13817656/221402453-6e3c6557-7d47-42ba-a383-0dcb0aa4339f.png">

**Comment by jibees** [comment] 2023-02-27 14:38
I agree, I can't make it fail at the moment either.

Wondering if we should close this issue for now or unassigned yourself and let it open anyway. 

Any thoughts @filipefurtad0 ?

**Comment by filipefurtad0** [comment] 2023-02-27 15:47
Hey @jibees @anshu1992 ,

Tricky one. I've [changed this file recently](https://github.com/openfoodfoundation/openfoodnetwork/commits/master/spec/system/admin/order_cycles/simple_spec.rb) to address flakyness... but it the error keeps resurfacing.

Now, I've removed the `retry: 3` option and ran the spec 100 times locally. Got two failures but interestingly, none of them with the error reported for flakyness cause, but rather a timeout:

`Ferrum::TimeoutError: Timed out waiting for response. `

So I think the issue is real, and that 1% failure you've observed eventually reappears again, since our build is ran several times a day. Ideally, we'd remove the `retry: 3` altogether.

I'm not sure if this would change the outcome in the spec, but what if:
- instead of typing in the value for minutes, and sending a `:enter` keystroke
- we click the up/down arrow

![image](https://user-images.githubusercontent.com/49817236/221610645-e66905cb-dc5a-4d33-a5d2-2f0a6bef513e.png)

What do you think @jibees ?
Would you like to try this, @anshu1992 ?

Of course, as said, this is a tricky one! So please feel free to unassign yourself and work on something else, if you prefer.

**Comment by jibees** [comment] 2023-02-27 15:54
> I'm not sure if this would change the outcome in the spec, but what if:
...


I cannot see why it could change anything, but why not trying for sure. 

I'd love to removing this `retry: 3` as well.

Working with time seems to be a mess in automatic specs...

**Comment by anshu1992** [comment] 2023-02-27 16:15
Hey @filipefurtad0 @jibees , I would like to give it a try.

**Comment by filipefurtad0** [comment] 2023-05-30 07:58
Re-occurred here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5112122296/jobs/9189819826

**Comment by jibees** [comment] 2023-05-30 08:27
Could not reproduce locally ... (even with removing `retry: 3`)

**Comment by filipefurtad0** [comment] 2023-05-30 09:17
> Could not reproduce locally ... (even with removing retry: 3)

Me neither... But I hope to have found the reason why, made a PR [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10908).

**Closed** 2023-05-30 15:43 UTC
Labels: tech debt
