### ISSUE TITLE
Change email from which order confirmations are sent

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1070] opened 2016-06-24 13:50 UTC
A hub is using OFN, the clients of the hubs receive today their order confirmations from info@openfoodfrance.org.
Can the order confirmation emails be sent from the email of the owner of the hub? Or can the hub set up from which email address he wants the order confirmation emails to be sent?

The problem is that some people reply to the order confirmation, so I receive the message instead of the hub owner.

Maybe there is already something in place but not yet in France, anyone can share how they do? Thanks :-)

**Comment by lin-d-hop** [comment] 2016-06-24 14:09
Hi @myriamboure 
See #1044 for more details

**Comment by lin-d-hop** [comment] 2016-07-04 15:57
Duplicate of #1025

**Closed by lin-d-hop** 2016-07-04 15:57 UTC
Labels: france
