### ISSUE TITLE
Duplicate enterprise name error message tweek.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#620] opened 2015-07-10 05:54 UTC
If it's not too hard can we please change the error message from...

"Name has already been taken. If this is your enterprise and you would like to claim ownership, please contact the current manager of this profile at sstead@student.unimelb.edu.au."

to 

"Name has already been taken. If this is your enterprise and you would like to claim ownership, or if you would like to trade with this enterprise please contact the current manager of this profile at sstead@student.unimelb.edu.au"

This is just to capture the user case of....'I'm a hub, I'm adding profiles for my supplying producers, I already checked to see if they had live profiles at .org.au, but maybe I couldn't see one because it is 'invisible'... so I try to make a profile for it... but can't.... WHY (they might get confused).

**Comment by myriamboure** [comment] 2018-03-04 20:04
@sstead has this been done since this issue was open? Else I get it's just one line to change in the en.yml file... maybe you can ask @mkllnk if you don't know how to do it it would take him 5 min I guess ;-) But I think it's a good proposal to do what you said :-) I let you deal with it and close this issue!

**Comment by rtrunkhill** [comment] 2018-04-10 18:58
Hello, I've new a new programmer and never contributed to an OS before, but i can handle this if you're still looking to get it done

**Comment by sstead** [comment] 2018-04-10 21:07
Thanks @rtrunkhill that would be much appreciated!

**Comment by myriamboure** [comment] 2018-04-10 21:49
Hi @rtrunkhill and welcome to the OFN community! It seems it's still to be done, I guess you can see yourself in the code base en.yml file (I'm not a dev but I think that's where English masters strings are) what is the original English text and yes change it to the new version. If you need to understand how internationalisation works I guess you can look at https://github.com/openfoodfoundation/openfoodnetwork/wiki/i18n# but not sure you need that complexity here :-)

**Comment by rtrunkhill** [comment] 2018-04-13 20:01
So i'm having issues with just doing an bundle update.  when I run it i get this message:

Gem::InstallError: guard-rails requires Ruby version >= 2.2.3.
An error occurred while installing guard-rails (0.8.1), and Bundler cannot continue.
Make sure that `gem install guard-rails -v '0.8.1'` succeeds before bundling.

but ofc i can't change the ruby version ( I tried that).  i've been trying to figure this out for a couple days and havn't had any luck with it so i cant do pull request for something that was a pretty simple fix.

Any help here would be appreciated!

**Comment by mkllnk** [comment] 2018-04-15 23:55
That's odd. Since this is a question unrelated to the issue, you have a better chance to get a reply in the Slack dev channel.

I just looked into the `Gemfile.lock` file and it declares `guard-rails (0.7.2)` as dependency. So the command you were running tried to install a newer version of guard-rails. Are you using rbenv? Did you install Ruby 2.1.5 with `rbenv install`? Did you install the bundler for that ruby version?

**Comment by rtrunkhill** [comment] 2018-04-17 18:09
I used RVM to change ruby versions. If i dont declare the guard-rails version it get the error you saw before.  

rtrunkhill:~/workspace (master) $ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
rtrunkhill:~/workspace (master) $ bundler -v
Bundler version 1.7.6

i'm really at a loss.  i want to do more for this project but I need to get this resolved and im not sure where i go from here.  

I'm using cloud9 workspace if that makes a difference

**Comment by sauloperez** [comment] 2018-04-17 18:53
I think you are running on a pretty old bundler version the latest version is 1.16. You can read more about it in https://bundler.io/whats_new.html. Try running `gem update bundler` and then try `bundle install` again. This will hopefully solve your problem.

**Comment by rtrunkhill** [comment] 2018-04-17 19:13
okay tried that, got the same error, the bundle install gets interrupted w/: 

```Fetching guard-rails 0.8.1 (was 0.7.2)
Installing guard-rails 0.8.1 (was 0.7.2)
Gem::InstallError: guard-rails requires Ruby version >= 2.2.3.
An error occurred while installing guard-rails (0.8.1), and Bundler cannot continue.
Make sure that `gem install guard-rails -v '0.8.1'` succeeds before bundling.

In Gemfile:
  guard-rails
rtrunkhill:~/workspace (master) $ bundler -v
Bundler version 1.16.1```

**Comment by sauloperez** [comment] 2018-04-17 19:18
that's weird. I don't get why bundler decides to resolve guard-rails to 0.8.1 all of a sudden. Can you share the exact commands you run? You can also share a recording using https://asciinema.org/, which might be even better.

**Comment by rtrunkhill** [comment] 2018-04-17 19:47
bundle install gives me:
```Bundle complete! 97 Gemfile dependencies, 260 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

and all my jobs fail at: 
RAILS_ENV=test bundle exec rake db:create db:schema:load

**Comment by sauloperez** [comment] 2018-04-17 20:00
please, share your terminal's output when troubleshooting otherwise is impossible to know happened.

**Comment by rtrunkhill** [comment] 2018-04-17 20:09
```rtrunkhill:~/workspace (master) $ bundle install
Using rake 12.3.1
Using CFPropertyList 2.3.6
Using i18n 0.6.11
Using multi_json 1.13.1
Using activesupport 3.2.21
Using builder 3.0.4
Using activemodel 3.2.21
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.7
Using rack-cache 1.7.1
Using rack-test 0.6.3
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.1
Using actionpack 3.2.21
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.5
Using actionmailer 3.2.21
Using concurrent-ruby 1.0.5
Using active_model_serializers 0.9.7
Using mini_portile2 2.1.0
Using nokogiri 1.6.8.1
Using activemerchant 1.71.0
Using arel 3.0.3
Using tzinfo 0.3.54
Using activerecord 3.2.21
Using activeresource 3.2.21
Using acts-as-taggable-on 3.5.0
Using acts_as_list 0.1.9
Using public_suffix 3.0.2
Using addressable 2.5.2
Using andand 1.3.3
Using rack-ssl 1.3.4
Using rdoc 3.9.5
Using thor 0.20.0
Using railties 3.2.21
Using angular-rails-templates 0.2.0
Using angularjs-file-upload-rails 1.1.6
Using angularjs-rails 1.5.5
Using ast 2.4.0
Using atomic 1.1.100
Using awesome_nested_set 2.1.5
Using awesome_print 1.8.0
Using json 1.8.6
Using uuidtools 2.1.5
Using aws-sdk 1.11.1
Using bcrypt 3.1.11
Using bcrypt-ruby 3.1.5
Using blockenspiel 0.5.0
Using bugsnag 6.7.1
Using bundler 1.16.1
Using byebug 9.0.6
Using cancan 1.6.8
Using mini_mime 1.0.0
Using xpath 2.1.0
Using capybara 2.18.0
Using chronic 0.10.2
Using chunky_png 1.3.10
Using climate_control 0.2.0
Using cliver 0.3.2
Using cocaine 0.5.8
Using coderay 1.1.2
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using coffee-rails 3.2.2
Using colorize 0.8.1
Using sass 3.4.25
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.10.3
Using ffi 1.9.23
Using rb-inotify 0.9.10
Using compass 1.0.3
Using sass-rails 3.2.6
Using compass-rails 3.0.2
Using safe_yaml 1.0.4
Using crack 0.4.3
Using css_parser 1.6.0
Using css_splitter 0.4.6
Using custom_error_message 1.1.1 from https://github.com/jeremydurham/custom-err-msg.git (at master@3a8ec9d)
Using daemons 1.2.6
Using dalli 2.7.8
Using database_cleaner 0.7.1
Using excon 0.62.0
Using formatador 0.2.5
Using fog-core 1.45.0
Using fog-json 1.0.2
Using ipaddress 0.8.3
Using xml-simple 1.1.5
Using fog-aliyun 0.2.1
Using fog-xml 0.1.3
Using fog-atmos 0.1.0
Using fog-aws 2.0.1
Using inflecto 0.0.2
Using fog-brightbox 0.14.0
Using fog-cloudatcost 0.1.2
Using fog-digitalocean 0.3.0
Using fog-dnsimple 1.0.0
Using fog-dynect 0.0.3
Using fog-ecloud 0.3.0
Using fog-google 0.1.0
Using fog-internet-archive 0.0.1
Using fog-joyent 0.0.1
Using fog-local 0.5.0
Using fog-openstack 0.1.25
Using fog-powerdns 0.1.1
Using fog-profitbricks 4.1.1
Using fog-rackspace 0.1.5
Using fog-radosgw 0.0.5
Using fog-riakcs 0.1.0
Using fog-sakuracloud 1.7.5
Using fog-serverlove 0.1.2
Using fog-softlayer 1.1.4
Using fog-storm_on_demand 0.1.1
Using fog-terremark 0.1.0
Using fission 0.5.0
Using fog-vmfusion 0.1.0
Using fog-voxel 0.1.0
Using trollop 2.1.2
Using rbvmomi 1.11.7
Using fog-vsphere 2.1.1
Using fog-xenserver 0.3.0
Using fog 1.41.0
Using rails 3.2.21
Using db2fog 0.9.0
Using debugger-linecache 1.2.0
Using deface 1.0.0.rc3 from https://github.com/spree/deface.git (at 1110a13@1110a13)
Using delayed_job 4.1.5
Using delayed_job_active_record 4.1.3
Using orm_adapter 0.5.0
Using warden 1.2.7
Using devise 2.2.8
Using devise-encryptable 0.1.2
Using diff-lcs 1.3
Using diffy 3.2.0
Using eventmachine 1.2.5
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using factory_girl 4.9.0
Using factory_girl_rails 4.9.0
Using multipart-post 2.0.0
Using faraday 0.9.2
Using ffaker 1.15.0
Using figaro 1.1.1
Using foreigner 1.7.4
Using foundation-icons-sass-rails 3.0.0
Using foundation-rails 6.1.2.0
Using foundation_rails_helper 0.4 from https://github.com/willrjmarshall/foundation_rails_helper.git (at rails3@4d5d53f)
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using ruby-progressbar 1.9.0
Using fuubar 2.2.0
Using geocoder 1.4.7
Using gmaps4rails 2.1.2
Using listen 3.0.8
Using lumberjack 1.0.13
Using nenv 0.3.0
Using shellany 0.0.1
Using notiffany 0.1.1
Using method_source 0.9.0
Using pry 0.11.3
Using guard 2.14.2
Using guard-compat 1.2.1
Using guard-livereload 2.5.2
Using guard-rails 0.7.2
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using guard-rspec 4.7.3
Using temple 0.8.0
Using haml 5.0.4
Using hashdiff 0.3.7
Using highline 1.6.15
Using multi_xml 0.6.0
Using httparty 0.9.0
Using i18n-js 3.0.5
Using immigrant 0.3.6
Using jquery-migrate-rails 1.2.1
Using jquery-rails 2.2.2
Using json_spec 1.1.5
Using jwt 1.5.6
Using kaminari 0.13.0
Using kgio 2.11.2
Using knapsack 1.16.0
Using launchy 2.4.3
Using letter_opener 1.6.0
Using libv8 3.16.14.19 (x86_64-linux)
Using momentjs-rails 2.20.1
Using money 5.1.0
Using newrelic_rpm 5.0.0.342
Using oauth2 1.2.0
Using ofn-qz 0.1.0 from https://github.com/openfoodfoundation/ofn-qz.git (at 60da2ae@60da2ae)
Using oj 3.5.1
Using paper_trail 3.0.9
Using paperclip 3.5.4
Using parallel 1.12.1
Using parallel_tests 2.21.3
Using parser 2.5.1.0
Using paypal-sdk-core 0.2.10
Using paypal-sdk-merchant 1.106.1
Using pg 1.0.0
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using poltergeist 1.16.0
Using polyamorous 0.5.0
Using powerpack 0.1.1
Using pry-byebug 3.4.3
Using rabl 0.7.2
Using rack-livereload 0.3.17
Using rails-i18n 3.0.1
Using rainbow 3.0.0
Using raindrops 0.19.0
Using ransack 0.7.2
Using redcarpet 3.4.0
Using ref 2.0.0
Using representative 1.0.5
Using representative_view 1.2.2
Using roadie 3.3.0
Using roadie-rails 1.0.6
Using rubyzip 1.2.1
Using roo 2.7.1
Using rspec-rails 3.7.2
Using rspec-retry 0.5.7
Using unicode-display_width 1.3.0
Using rubocop 0.55.0
Using select2-rails 3.5.10
Using shoulda-matchers 2.8.0
Using simple_form 2.0.2 from https://github.com/RohanM/simple_form.git (at master@45f08a2)
Using skylight 1.6.1
Using spinjs-rails 1.4
Using state_machine 1.2.0
Using stringex 1.3.3
Using truncate_html 0.9.2
Using spree_core 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using versioncake 0.4.0
Using spree_api 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree_backend 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree_cmd 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree_frontend 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree_dash 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree_sample 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree 1.3.99 from https://github.com/openfoodfoundation/spree.git (at 86bf87f@86bf87f)
Using spree_auth_devise 2.0.0 from https://github.com/openfoodfoundation/spree_auth_devise.git (at spree-upgrade-intermediate@da9eece)
Using spree_i18n 1.0.0 from https://github.com/spree/spree_i18n.git (at 1-3-stable@752eb67)
Using spree_paypal_express 2.0.3 from https://github.com/openfoodfoundation/better_spree_paypal_express.git (at spree-upgrade-intermediate@8d95f45)
Using stripe 3.3.2
Using therubyracer 0.12.3
Using timecop 0.9.1
Using turbo-sprockets-rails3 0.3.14
Using uglifier 4.1.9
Using unicorn 5.4.0
Using unicorn-rails 2.2.1
Using webmock 3.3.0
Using whenever 0.10.0
Using wicked_pdf 1.1.0
Using wkhtmltopdf-binary 0.12.3.1
Bundle complete! 97 Gemfile dependencies, 260 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

**Comment by sauloperez** [comment] 2018-04-17 20:13
what does `RAILS_ENV=test bundle exec rake db:create db:schema:load` report?

**Comment by rtrunkhill** [comment] 2018-04-17 20:15
```
rtrunkhill:~/workspace (master) $ RAILS_ENV=test bundle exec rake db:create db:schema:load
rake aborted!
LoadError: Please install the postgresql adapter: `gem install activerecord-postgresql-adapter` (can't activate pg (~> 0.11), already activated pg-1.0.0. Make sure all dependencies are added to Gemfile.)
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:404:in `block (2 levels) in replace_gem'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/skylight-1.6.1/lib/skylight/probes.rb:83:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in `resolve_hash_connection'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:29:in `spec'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:101:in `create_database'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `each'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/bugsnag-6.7.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Gem::LoadError: can't activate pg (~> 0.11), already activated pg-1.0.0. Make sure all dependencies are added to Gemfile.
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:404:in `block (2 levels) in replace_gem'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/skylight-1.6.1/lib/skylight/probes.rb:83:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in `resolve_hash_connection'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:29:in `spec'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:101:in `create_database'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `each'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/bugsnag-6.7.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Polyglot::PolyglotLoadError: Failed to load active_record/connection_adapters/postgresql_adapter using extensions rb
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:55:in `load'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:68:in `rescue in require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/skylight-1.6.1/lib/skylight/probes.rb:83:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in `resolve_hash_connection'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:29:in `spec'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:101:in `create_database'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `each'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:62:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/bugsnag-6.7.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)

**Comment by rtrunkhill** [comment] 2018-04-19 17:07
Nope that didn't work I get the following error:
```
/usr/local/rvm/gems/ruby-2.1.5@openfoodnetwork/gems/activesupport-3.2.21/lib/active_support/railtie.rb:51:in `block in <class:Railtie>': Value assigned to config.time_zone not recognized.Run "rake -D time" for a list of tasks for finding appropriate time zone names. (RuntimeError)

```


can i get an invite to the slack workspace please?  same username @gmail

**Comment by sauloperez** [comment] 2018-04-20 12:51
> I'm using cloud9 workspace if that makes a difference

That must be troublesome. I believe that time zone related error is related to your environment settings. I just invited you to Slack btw.

**Closed** 2018-05-18 01:19 UTC
Labels: good first issue

**Comment by myriamboure** [comment] 2018-05-18 17:28
@rtrunkhill congratuation for your perseverance and your contribution! :+1:
