### ISSUE TITLE
Adding Notes to Orders Placed in Backend

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5271] opened 2020-04-20 12:04 UTC
## Description

Hub Manager (or Shop Manager) places order for customer in backend and needs to add  a note to the order (delivery instructions for example).
No place for note to be added.
Similar to issue #4146 (no space for adding a note to an existing order when editing).

## Expected Behavior

Field should be available to add a note to an order when placing it in the backend on behalf of a customer.

## Actual Behaviour

No field available to add a note to an order

## Steps to Reproduce

1.
2.
3.
4.

## Workaround

can steps outlined in #4146 be extended to back end orders too?

## Severity

s3
It is very time consuming (and potential for information to be lost or be mis-used) to have notes on paper only.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment] 2020-04-20 12:05
![](https://github.trello.services/images/mini-trello-icon.png) [Invoices & Pick Lists](https://trello.com/c/Vn1V1M9M/912-invoices-pick-lists)

**Comment by lin-d-hop** [comment] 2020-04-21 09:57
Duplicate of #4146

@louise #4146 is talking about backend orders.

**Closed by lin-d-hop** 2020-04-21 09:57 UTC
Labels: bug-s3
