### ISSUE TITLE
Can't delete (some) adjustments - Error 401 Unauthorized

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7341] opened 2021-04-07 20:39 UTC
## Description

Follow-up on [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/7108#issuecomment-799347430) and the [related PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/7112#issuecomment-799520783).

Editing an order, clicking on the Adjustments and on the trash-bin of the to-be-deleted adjustment. It generates a 401 error and quite noticeable changes in the UI, if the adjustment is a transaction fee; Other adjustments just seem to be deleted, but refreshing the page brings them back.

This is the case for _some_ of the adjustments. Others are successfully removed. It needs to be investigated which ones.

## Expected Behavior

Deleting Adjustments should be possible. The UI should not display any visible change in format/appearance when doing so.

## Actual Behaviour

Deleting adjustments doesn't work; it causes a 401 error and displays a prominet UI effect.

## Steps to Reproduce

1. Log in as admin.
2. Edit a placed order; visit the Adjustments tab.
3. Try to delete an adjustment.
4. See the UI change, the 401 error and the fact that the adjustment is still there.

## Animated Gif/Screenshot

Trying to delete an adjustment related to a transaction fee:
![Peek 2021-04-07 21-10.gif](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/72add4a8-a929-4fd4-90e4-1c0c19d99c49)
(Trippiest bug award)

It causes a 401 - unauthorized error:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/c77f27e5-9c81-4021-a715-00fdef13c2bb)

## Workaround

Edit the adjustment, setting it to zero.
The UI returns to normal after refreshing the page.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.6.4
* Browser name and version: latest Chrome and Firefox
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

**Comment by RachL** [comment] 2021-04-21 09:29
@openfoodfoundation/train-drivers-product-owners @openfoodfoundation/testers we start to receive a lot of request for this one.

It works as superadmin tough, so hubs have asked us to do the job: each week they send us the list of adjustments to delete, and we delete it for them, but it happens that we do mistakes :( I would like to bump this to s2. Does anyone disagree?

Most of the time adjustments that are causing this bug are adjustements created because of this bug: https://github.com/openfoodfoundation/openfoodnetwork/issues/3490 🙈  deleting those adjustments is mandatory to retrieve correct balances.

**Comment by Matt-Yorkley** [comment] 2021-04-21 09:53
I have a feeling this might already be fixed in master?

**Comment by RachL** [comment] 2021-04-21 10:00
@Matt-Yorkley I've just reproduced it in production. So not available in the latest release...

**Comment by Matt-Yorkley** [comment] 2021-04-21 13:20
@RachL can you give some more detail on the steps to reproduce it? I just tried it with master and couldn't see how to hit this error... :man_shrugging:

**Comment by RachL** [comment] 2021-04-21 14:03
@Matt-Yorkley  can you dump FR prod data? Otherwise I can give you manager access on Slack (with super admin it works). On FR prod try deleting the following transaction fee adjustments:

- R284276637 : adjustment/transaction fee 12 april 2021 3:01 PM of 0,75 euros
- R740427146 : April 12th  1,33 €
- R664535834 : April 12th 0,34 €

**Comment by Matt-Yorkley** [comment] 2021-04-21 14:09
Thanks, I'll take a look :+1: 

I can see two logs for FR prod that show 401 response on the adjustments controller, which indicates a permissions error...

**Comment by Matt-Yorkley** [comment] 2021-04-21 14:18
Any chance there's some weird permissions thing here where the user account you're trying to edit the adjustments with only has permission to view the order in admin because they're a producer with products in the distributor's OC, but they technically don't have full _edit_ permissions on the order you're editing?

**Comment by RachL** [comment] 2021-04-21 15:05
@Matt-Yorkley no sorry :( I'm clearly manager of hub 922.  The email I'm using is rachel.arnould+test[at]protonmail.com

**Comment by filipefurtad0** [comment] 2021-04-21 15:33
> it may relate to "shared" payment or shipping methods

That's not it either. After creating:

- a Payment Method (ownd only by Espargos Place, id=21):

![image](https://user-images.githubusercontent.com/49817236/115579476-1d0fe900-a2be-11eb-8baf-25b1e46dd64e.png)

- an a Shipping Method (owned only by Espargos Place, id=24):

![image](https://user-images.githubusercontent.com/49817236/115579636-43358900-a2be-11eb-8c24-b41a08166d1e.png)

And placing a similar order with these deleting the respective adjustments still triggers the bug.

**Comment by Matt-Yorkley** [comment] 2021-04-21 17:44
Fixed :+1:

Thanks for the extra info!

**Closed** 2021-04-22 16:07 UTC
Labels: bug-s2
