### ISSUE TITLE
Avoid `allow_any_instance_of` in specs

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6644] opened 2021-01-12 04:19 UTC
### What we should change and why (this is tech debt)
See: https://github.com/openfoodfoundation/openfoodnetwork/pull/6534#discussion_r553881544

>we need to watch out with `allow_any_instance_of` and avoid as much as possible. It's a known bad pattern that leads to brittle tests discouraged even by the RSpec team 👉 https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance.

### Context
There are several places where we use it in `spec/controllers/spree/admin/orders/payments/payments_controller_spec.rb`

**Comment by sigmundpetersen** [comment] 2024-06-06 12:33
Duplicate of #6645

**Closed by sigmundpetersen** 2024-06-06 12:33 UTC
Labels: tech debt
