### ISSUE TITLE
Deleting a variant has no direct effect on a shopfront

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#3629] opened 2019-03-20 17:46 UTC
## Description
If you delete a variant, it keeps showing up on the shopfront until you save a second time changes on your product.

If someone attempts to add this deleted variant to cart it gets a infinite loader

I saw this while testing #3619 but could reproduced it on French production

## Steps to Reproduce
1. I deleted a variant that already existed on a staging server
2. I saw that it was correctly deleted from the OC but not the shopfront (I cleared my browser cache several times)
3. I've added a new variant to my product. At this stage - as I saved again - the variant previously deleted disappear from the shop. The new variant showed up correctly
4. I deleted this new variant. Again it did not showed up in the OC, but on the shopfront yes.
5. I change the price of another variant, hit save. Then my variant is correctly deleted from shop front.

I reproduce all this on French product but this time I also tried to add the deleted variant to card. I got an infinite loader on the add to cart button:

![image](https://user-images.githubusercontent.com/6525576/54706808-11cabc00-4b40-11e9-9db5-a35391583ff9.png)

Reloading the page stop the loader, but my variant is still showing up. It's the v2 variant bottom page here: https://www.openfoodfrance.org/hub-demo-open-food-france/shop

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/54706884-3de63d00-4b40-11e9-92ed-c28e26583f57.png)

![image](https://user-images.githubusercontent.com/6525576/54706896-43dc1e00-4b40-11e9-9cc5-0c514f870b3e.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v1.28
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Ubuntu 18.10

**Comment by luisramos0** [comment] 2019-03-20 21:31
This looks like a cache problem. With the new feature to disable cache we can disable cache and see if this happens with the cache disabled :-)

**Comment by mkllnk** [comment] 2019-03-21 05:48
This could be a duplicate of #2111. In that case it's no cache problem.

**Comment by mkllnk** [comment] 2019-03-21 06:26
Changing the product a second time is a workaround, isn't it? Or first remove it from the order cycle and then delete it.

**Comment by mkllnk** [comment] 2019-03-21 07:02
I looked into this and we have all the code to update the cache when a variant is destroyed. But we never call `destroy`, we call `delete` for a soft-delete. And that method doesn't touch the cache.

The current implementation:
https://github.com/openfoodfoundation/openfoodnetwork/blob/130ba64f2f101da797125bf7ad73bbeb7e83a12b/app/models/spree/variant_decorator.rb#L127-L143

Where we should apply it:
https://github.com/openfoodfoundation/openfoodnetwork/blob/130ba64f2f101da797125bf7ad73bbeb7e83a12b/app/models/spree/variant_decorator.rb#L100-L111

This would be solved with Spree 2 because we get rid of our soft-delete implementation. Spree 2 always soft deletes when calling `destroy`.

I'm calling it a day now. Feel free to work on this issue. Otherwise I may have time tomorrow to work on this.

**Comment by RachL** [comment] 2019-03-21 08:55
> Changing the product a second time is a workaround, isn't it? Or first remove it from the order cycle and then delete it.

Yes you are right. I'm downgrading to s3.

**Comment by sauloperez** [comment] 2019-03-27 08:25
https://github.com/openfoodfoundation/openfoodnetwork/pull/3639 fixes this in `master` but would you mind testing it in v2 as well? I just checked and there is no bug in v2. I want to be extra sure though. Thanks for taking care of it @mkllnk.

**Comment by mkllnk** [comment] 2019-03-29 02:22
I'm not sure whom you asked to test it @sauloperez. Did you mean @RachL  or me to test this?

@RachL would you mind testing this when you are next testing v2 anyway?

**Closed** 2019-03-29 04:12 UTC
Labels: bug-s3

**Comment by RachL** [comment] 2019-03-29 08:26
@mkllnk will do!

**Comment by RachL** [comment] 2019-04-01 11:16
@mkllnk good catch, the issue remains in v2. I will open an issue for it.

**Comment by RachL** [comment] 2019-04-01 11:50
@mkllnk @sauloperez ok nevermind when I retested again to write the issue i couldn't reproduced it.

**Comment by luisramos0** [comment] 2019-04-01 11:56
have you enabled cache in the backoffice?

**Comment by RachL** [comment] 2019-04-01 12:10
@luisramos0 it is enabled by default I guess? Because I just saw that the bow is ticked, so I guess it was ticked when I did my test?

**Comment by luisramos0** [comment] 2019-04-01 14:15
yeah, if it is enabled now, I think it's safe to assume it was enabled when you tested.
