### ISSUE TITLE
Customer can't shop at private shop

### ISSUE THREAD

**Issue by JenSheridan** [openfoodfoundation/openfoodnetwork#5760] opened 2020-07-13 01:44 UTC
## Description
A user has been added as a customer to a private shop, but it’s still not appearing for them (we've logged in as user to test that this is definitely happening, and checked shop backend). We’ve tried resetting passwords etc and it hasn’t helped. I’ve tried adding other users as shop customers and it works fine. No tags are in use.

When I try to delete the user as a customer for the shop it notifies me that I can’t as they have active orders - when I look at those orders they are both empty. 

## Expected Behavior
Shop adds a user as a customer, they can then view the private shop and make purchases.

## Actual Behaviour
Shop adds a user as a customer, they still cannot view private shop, they cannot make purchases. 

## Steps to Reproduce
I don't know how to reproduce, it is only happening for this user and I don't want to share their email address publicly... 

## Severity
bug-s1 as it's impossible for a customer to buy food. But it only affects one user.

**Comment by luisramos0** [comment] 2020-07-13 09:36
This is an S2 but only if the workaround doesn't work, have you tried what @daniellemoorhead suggested on slack?
"you can change their email address to be an ofn one and then set them up again"

**Comment by luisramos0** [comment] 2020-07-13 14:52
@JenSheridan has applied the workaround in prod but was not able to test it because the OC was already closed.
But I did import the full DB to my local environment, logged in as the user and I can see the shopfront correctly.
I am going to assume the work around did work and so I am downgrading this to S3.

**Comment by emilyjeanrogers** [comment] 2020-07-16 00:21
The customer was not able to click on the confirmation email (for the new account) and confirm their email address. Below error message was generated: 

![image (4)](https://user-images.githubusercontent.com/47620442/87610136-d77b2a00-c747-11ea-9296-d91c416d4f47.png)

Unsure of why this happened, but @mkllnk was able to manually confirm the email address and he and I were both able to log in as the customer successfully. I opened the OC temporarily and was able to log in as the customer and view the shop. 

Have advised customer and waiting for confirmation that they can login and access the O/C.  If so, then we have a workaround, but the original issue is yet to be identified.

**Comment by emilyjeanrogers** [comment] 2020-07-16 07:47
Customer has confirmed they can log in with the above workaround.

**Comment by Matt-Yorkley** [comment] 2020-07-16 09:45
So the shop manually added the customer via admin, but their email was not confirmed..?

**Comment by luisramos0** [comment] 2020-07-16 11:05
yeah, I think that was something related to that Matt.
When I copied the live DB to my local DB, the confirmation email link didnt have the correct confirmation token, I had to fetch the token from the DB and add it to the url, and then the email got confirmed.

Lets move the devise upgrade forward, it may help with this: https://github.com/openfoodfoundation/openfoodnetwork/pull/4084

**Comment by lin-d-hop** [comment] 2021-07-28 15:40
Closing this issue as the problem was different that originally described and seems not to have been reported for some time.

If reported again it can be reopened with a clearer description :-)

**Closed by lin-d-hop** 2021-07-28 15:40 UTC
Labels: bug-s3
