### ISSUE TITLE
New products where stock is set "to order" saves with zero stock

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1420] opened 2017-01-25 16:53 UTC
![screen shot 2017-01-25 at 16 51 43](https://cloud.githubusercontent.com/assets/17590921/22300225/b80a51fc-e31e-11e6-9f20-c8571296dd32.png)
![screen shot 2017-01-25 at 16 52 11](https://cloud.githubusercontent.com/assets/17590921/22300226/b80c26d0-e31e-11e6-8590-039f0aa5d8c6.png)

**Comment by Matt-Yorkley** [comment] 2017-01-28 19:51
I think technically the value for stock _should_ be zero in this case, but the product should also be marked as "to order/on demand"). 

Just did a quick bit of testing and confirmed that new products created with "to order" checked do not have the "to order" flag applied.

**Comment by sstead** [comment] 2017-02-01 01:30
Related bug which you might be able to fix up at the same time - https://github.com/openfoodfoundation/openfoodnetwork/issues/698

**Comment by Matt-Yorkley** [comment] 2017-02-01 21:04
It's really weird that the specs don't catch this... time for some TDD :)

**Comment by Matt-Yorkley** [comment] 2017-02-02 01:31
Okay, I've sorted the fact that products didn't get set with the "on demand" property on creation. I'll address how the stock level gets displayed and other UI bits separately under the issue @sstead referenced. Should be ready for testing @OliverUK.

As a personal note: ***Achivement Unlocked** - Test Driven Development*. 

:)

**Comment by OliverUK** [comment] 2017-02-03 15:34
This seems to work fine now on UK staging. Following deployment I was able to create a new product with "on demand" ticked and after saving, the product appears in BEP, where the same box is now also ticked and the stock field is populated with "on demand". 

![screen shot 2017-02-03 at 15 29 21](https://cloud.githubusercontent.com/assets/17590921/22597049/ea7cd8c2-ea25-11e6-81dd-041f4b53a9f3.png)
![screen shot 2017-02-03 at 15 29 36](https://cloud.githubusercontent.com/assets/17590921/22597048/ea76fa1a-ea25-11e6-8437-fd66c1f1a2fb.png)

**Comment by OliverUK** [comment] 2017-02-03 15:35
Obviously all these labels "on demand" and "to order" are being changed to unlimited.

**Comment by Matt-Yorkley** [comment] 2017-02-06 16:36
Looks like that's all working as expected, so I'll see if either @stveep or @mkllnk want to do a quick code review of #1428.

**Comment by sstead** [comment] 2017-02-07 23:28
Tested and Pushed. 
If a new product is created and the 'on demand' box is checked the new products shows as 'on demand'. If the on demand box is ticked and there's a number (0 or above) in the on hand field, the number is overridden with 'on demand'. Bug #698 remains in the case where on demand is selected and on hand is blank. All other functionality appears normal.

**Closed** 2017-02-07 23:33 UTC
Labels: aus review
