### ISSUE TITLE
Order cycle cannot save

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#2304] opened 2018-05-21 15:01 UTC
Order cycle UPDATE button greys out preventing save

## Description
When I get to the out going part of a new order cycle, the update button greys out
## Expected Behavior
I should be able to create both outgoing and incoming and then click the red update button
## Actual Behavior
as soon as i get to the outgoing part the update button goes grey and will not save
## Steps to Reproduce
1. deploy v.1.15.1
2. create new order cycle
3. create incoming then outgoing sections
4. try to UPDATE

## Context
Trying to create a new order cycle

## Severity
I think would be an S1 but I also fear it might be user incompetence so I will wait for someone more clued-up to assign the label

## Your Environment
* Version used: v.1.15.1
* Browser name and version: Chrome 
* Operating System and version (desktop or mobile): Desktop Windows 7

## Possible Fix
Sorry - no idea!
![screenshot 2018-05-21 15 01 47](https://user-images.githubusercontent.com/10517702/40314220-c4098b96-5d0f-11e8-8ff9-bf88a44337f5.png)
![screenshot 2018-05-21 15 02 35](https://user-images.githubusercontent.com/10517702/40314221-c426f0e6-5d0f-11e8-823e-7d5b9e003b8b.png)
![screenshot 2018-05-21 15 04 58](https://user-images.githubusercontent.com/10517702/40314222-c4569814-5d0f-11e8-9747-c61f964f415f.png)

**Comment by NickWeir63** [comment] 2018-05-21 15:51
OK S1 it is

**Comment by NickWeir63** [comment] 2018-05-21 19:48
Finally worked out how to use Recordit...... http://recordit.co/9Pj5qO6T67

**Comment by sauloperez** [comment] 2018-05-22 06:55
Can you take a look at it @myriamboure to ensure it's not a false positive?

**Comment by myriamboure** [comment] 2018-05-22 09:08
I did straight away yesterday @sauloperez by connecting on UK production (I have an account there) and can confirm what Nick has said, the bug is there. You don't have the Bug on Katuma? It is strange if you run the same version, no? Let me do some more tests, 5 min.

**Comment by myriamboure** [comment] 2018-05-22 09:18
I can confirm, can't create OC and don't see workaround... time to investigate I guess @sauloperez or @HugsDaniel or ... whoever is awake :-)

**Comment by sauloperez** [comment] 2018-05-22 09:57
I won't be available until 13h, Barcelona time :disappointed: . So if someone else can take it, it'd be great.

**Comment by myriamboure** [comment] 2018-05-22 14:26
@NickWeir63 you need to fill in the "ready for" field for the save button to activate again. @sauloperez just reminded me that ;-) Oups! Users got used to it but it seems that sometimes we forget about some strange and not so adapted UX things that we will need to improve at some point, but not here. So closing it for now.

**Closed by myriamboure** 2018-05-22 14:26 UTC
Labels: bug-s1, uk

**Comment by oeoeaio** [comment] 2018-05-23 03:27
Do we need to address the UX issues @myriamboure? If it is not obvious to Nick that the ready for field needs to be filled in then it is probably not obvious to anyone else!

**Comment by myriamboure** [comment] 2018-05-23 12:40
I don't think so @oeoeaio as it's been like that since ages. I guess it's just that Nick forgot about this behavior (just as I did under his influence ;-)), but we were discussing with Pau and users got used to it, so I wouldn't invest energy on that and focus on treating the root causes and reaching the OC redesign stage :-)
If we want to address it, we could just keep the save button red but if user clicks on it display error message: ""ready for" is compulsory field and must be filled in", so prevent saving in another way.
What do you think @sstead ? Do you see really a big UX issue on user side that would require us to change the UX now?
