### ISSUE TITLE
When I update customer address, confusing UX on states when changing country

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2106] opened 2018-03-01 13:53 UTC
## Description
In customer address I see Australia, choose Australian state. Then change country to France, I still see the Australian state. I click to change the state and see the list of French states so I can choose the right state, but this period of seeing one country associated with states from another country is pretty confusing. 

## Expected Behavior
If I change country in customer address edit form, states field empty dynamically before I choose the right state from the new states list proposed.

## Actual Behavior
If I change country in customer address edit form, states field remain with the previous state chosen. I can then choose the right state from the new states list proposed, but it's confusing.

## Steps to Reproduce
1. Make sure you use an instance with states for at least two countries
2. Go to customer, select a shop, click to edit one customer address, and try to change countries and states.

## Animated Gif/Screenshot
https://www.useloom.com/share/f20798787a9d48abb5f7eeebf454159f 

## Context
Remaining small bug from PR #2074 that got merged (as was fixing the main issue).

## Severity
S4

## Your Environment
- Version used: Aus staging with branch PR2074
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

**Comment by daniellemoorhead** [comment] 2018-08-17 06:58
FYI: See notes on #2353 if you decide to pick up and fix this bug. There was a lot of good work and discussion included in that, so take note before you start working on this again.

**Comment by luisramos0** [comment] 2018-08-17 15:51
as mentioned in the PR, the issue is fixed and tested with functional tests.

**Comment by daniellemoorhead** [comment] 2018-08-20 03:04
>as mentioned in the PR, the issue is fixed and tested with functional tests.

Once it's (#2353) tested and merged, yes indeed!

**Closed** 2018-08-28 06:46 UTC
Labels: bug-s4
