### ISSUE TITLE
Order Cycle Management reports - Cash payments now appear as zero in report if not captured (recent regression)

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5004] opened 2020-03-17 04:58 UTC
## Description

The Payment Methods Report and delivery report used to show the amount of all payments. Now Cash / EFT / Direct Deposit amounts show up as zero unless captured. Customers use this report prior to receiving cash, so it's not appropriate for them to 'capture' the amounts before running the report. 
 

## Expected Behavior

Behaviour until recently (early March 2020 approx) was that the Payment Methods report displayed total amounts of all payment types. This is the expected behaviour.  

## Actual Behaviour

Zero amounts displayed for all cash payments that are not captured.

## Steps to Reproduce

1. Access an Enterprise that takes Cash Orders. 
2. Do not Capture cash payments (ie. to view expected payments prior to receiving cash)
3. Run Payment Methods Report and delivery report
4. All orders with cash payments will appear as zero

## Workaround

Although the report can be run successfully by capturing payments, this is not a workaround for enterprises who use the report prior to receiving cash. They do not want to capture payments when payment has not yet been received. 

## Severity

S2

**Comment by RachL** [comment] 2020-03-17 08:18
I'm changing a bit the scope of the issue: it does not impact the payment report but the delivery report as well. So whole Order Cycle Management reports.

**Comment by sigmundpetersen** [comment] 2020-03-17 08:26
Duplicate of #4967? There's already a PR in Code Review #4968

**Comment by RachL** [comment] 2020-03-17 08:27
Ah yes thank you @sigmundpetersen ! closing then

**Closed by RachL** 2020-03-17 08:27 UTC
Labels: bug-s2

**Comment by emilyjeanrogers** [comment] 2020-03-17 23:24
I believe this will be resolved by https://github.com/openfoodfoundation/openfoodnetwork/pull/4968 so will close this issue now.
