### ISSUE TITLE
[Enterprise->Create] A disabled button prevents from going forward in the process

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10009] opened 2022-11-17 00:27 UTC
## Description
When creating a new enterprise from the /register page, at step 3, if you don't choose "I'm a producer" or "No, I'm not a producer" and you click the red button to go to the next page, you have an error "Please choose one. Are you a producer?" and the button is disabled. But then, even after selecting one of the choices, the button remains disabled and you can't go forward. 

## Expected Behavior
The button must be reactivated after a selection has been done.

## Steps to Reproduce
1. Create a new enterprise from the /register page ("join" button on the homepage)
2. At step 3, don't choose either of the choices and click the "Create profile" red button
3. See that the button remains disabled whatever you do

## Animated Gif/Screenshot

![stuckystcuck](https://user-images.githubusercontent.com/28386648/202324077-443846fd-18f3-4182-b55e-0cdeea094e40.gif)

## Workaround
Quit and do it again.

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by vviekk** [comment] 2022-11-22 11:14
Hi,
How can we reproduce this on development environment?
Don't see similar UI after `join` button on homepage.
Couldn't find `staging.coopcircuits.fr/register` on dev.

Apologies if its a trivial question, a ruby(and OFN) noob here.

**Comment by RachL** [comment] 2022-11-22 11:27
Hi @vviekk the /register page should be available on your local environment. What happens when you visit it?

**Comment by vviekk** [comment] 2022-11-22 11:49
Hello @RachL,
 
It takes me to a signup page but with following UI:
![image](https://user-images.githubusercontent.com/91144693/203304897-7cb343a4-bc95-4f91-a9fd-d57935b05647.png)

When I click sign up with test data, i get the following text:
![image](https://user-images.githubusercontent.com/91144693/203305496-f2643cd2-6bab-4022-b39a-76e25e975f38.png)

How do I proceed to see the next steps as shown in the issue? 
Do I see the next steps after I confirm the new created account and log in with the same credentials? 
* If yes, how do I confirm the account? 
   1. Can i confirm the new account with the admin account? OR
   2. Do I update the database table `spree_users` directly to mark it confirmed?

Or should I be looking at a different route?

**Comment by vviekk** [comment] 2022-11-22 11:57
@RachL 
Apologies, just stumbled on the issue.
I can see the /register UI by clicking on the register button AFTER logging in with the demo credentials.

Thanks for the clarification about dev!

**Comment by vviekk** [comment] 2022-11-22 11:58
Please assign the issue to me.

**Comment by vviekk** [comment] 2022-11-23 14:49
Current behavior:
![image](https://user-images.githubusercontent.com/91144693/203575308-f29cf78e-0777-489a-8a40-743a85d62cbe.png)
The `ng-

![image](https://user-images.githubusercontent.com/91144693/203575417-a668d142-6468-4f95-a305-e5a6baff6f16.png)
![image](https://user-images.githubusercontent.com/91144693/203575769-c1f385b0-f89d-49dc-91f7-4a19167afaae.png)

**Comment by vviekk** [comment] 2022-11-28 11:43
@sigmundpetersen /@RachL
Any comments on this ^?

**Comment by sigmundpetersen** [comment] 2022-11-28 11:46
Maybe @jibees has some input on this too

**Comment by jibees** [comment] 2022-11-30 13:37
@vviekk 
Sorry I'm late.

Why not re-enable button with `enableButton()` method if the request sends the error message "Please choose one? Are you a producer?"

**Comment by vviekk** [comment] 2022-11-30 14:20
Thank you @jibees.

Are you talking about a browser alert message if the user tries to submit without making the selection?
Or simply find a way to reenable the button when the selection is made?
Either way, wouldn't it be better if we fix the underlying issue of disable on submit code as well, instead of patching it up?
I could be missing something here.
Please correct me if I miss understood.

**Comment by jibees** [comment] 2022-11-30 14:27
My understanding:
 - We cannot re-click on the button the second time because it has been marked as disabled
 - This _marked as disabled after the first click_ feature is here to avoid multiple solution

We're facing two issues:
 - Cannot re-click on submit button even if there is any validation error to re-submit the form
 - We are able to still submit multiple times the form

My thought: this PR should solve the two issues since they are very linked together.

What do you thing?

**Comment by vviekk** [comment] 2022-11-30 14:29
Agreed @jibees.
I'll try to make changes to fix both.
Thank you!

**Comment by RachL** [comment] 2022-12-19 14:39
Hello @vviekk just checking in: are you still planning to work or working on this issue?

**Comment by vviekk** [comment] 2023-01-09 04:30
@RachL 
Apologies, I was away for the holidays.
Yes, I am working on it.

**Closed** 2023-02-23 16:00 UTC
Labels: bug-s3
