### ISSUE TITLE
422 unprocessable entity on `/api/v0/order_cycles/22055/products.json?distributor=3269` (requesting a shop)

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#11521] opened 2023-09-11 08:44 UTC
## Description
The shop [tab ](https://coopcircuits.fr/ingre-ormes-2030/shop#/shop_panel)for 3269 Enterprise loads indefinitely 

<img width="1206" alt="Capture d’écran 2023-09-11 à 10 46 34" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/67476305/8d58d900-7713-4f39-bfb2-299485f53aa4">

This is the bugsnat linked : https://app.bugsnag.com/open-food-france/coopcircuits/errors/64fdc2d07d12490008ee4972?filters[event.since]=all

We observed that the loading error only appears when the products of one producer are selected in the order cycle. The producer ID is : 5055 

## Steps to Reproduce

1. Add 5055 producer products to an order cycle
2. Open this order cycle
3. Connect to the shop tab

**Comment by jibees** [comment] 2023-09-11 08:57
Could this be related to the fact that every variants for supplier 5055 Les Cochonnailles de Sologne doesn't have any price? 

<img width="872" alt="Capture d’écran 2023-09-11 à 10 55 25" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/a1a00cac-473d-43a3-84f3-7db8a72a8678">

It's sometimes shown as `0` in the interface, but it's actually NULL:

```sql
select sv.product_id, sv.id, prices.amount from spree_variants sv
JOIN spree_products sp ON sv.product_id = sp.id
JOIN spree_prices prices ON prices.variant_id = sv.id
WHERE  prices.variant_id = sv.id
AND sp.supplier_id = 5055
AND prices.amount is NULL;
```

```
 product_id |   id   | amount
------------+--------+--------
      61023 | 137427 |
      61026 | 137430 |
      61033 | 137437 |
      61036 | 137440 |
      61044 | 137448 |
      61032 | 137436 |
      61034 | 137438 |
      61035 | 137439 |
      61037 | 137441 |
      61038 | 137442 |
      61052 | 137456 |
      61039 | 137443 |
      61054 | 137458 |
      61040 | 137444 |
      61057 | 137461 |
      61058 | 137462 |
      61042 | 137446 |
      61047 | 137451 |
      61050 | 137454 |
      61056 | 137460 |
      61068 | 137475 |
      61069 | 137476 |
(22 rows)
```

**Comment by jibees** [comment] 2023-09-19 10:48
How many variants with `NULL` price on each instances? 
Ran the query 
```sql
select count(sv.id) from spree_variants sv JOIN spree_products sp ON sv.product_id = sp.id JOIN spree_prices prices ON prices.variant_id = sv.id WHERE prices.variant_id = sv.id
```

```
app.katuma.org
1


openfoodnetwork.org.uk
116


openfoodnetwork.ie
9


openfoodnetwork.be
334


openfoodnetwork.de
0


coopcircuits.fr
57


openfoodnetwork.ca
15


csicsoka.org
0


openfoodnetwork.net
3


openfoodnetwork.org.au
40


openfoodnetwork.org.nz
0


```

**Comment by RachL** [comment] 2023-09-22 07:38
Closing as it's fixed for BE, in theory adding price is fixing it FR too. We should find the root cause, but maybe not the highest priority right now.

**Closed by RachL** 2023-09-22 07:38 UTC
Labels: bug-s2
