### ISSUE TITLE
[Flaky Spec] ./spec/features/admin/shipping_methods_spec.rb:82

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#3473] opened 2019-02-11 19:22 UTC
## Description

This spec is unreliable:
./spec/features/admin/shipping_methods_spec.rb:82

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/473

## Context

Our Semaphore builds fail regularly because of these unreliable tests. If you encounter this in your build, please comment on this issue or add 👍

Error:
```

  1) shipping methods as an enterprise user creating a shipping method
     Failure/Error: expect(page).to have_flash_message message
       expected to find flash message #Shipping method "Teleport" has been successfully created!
     # ./spec/features/admin/shipping_methods_spec.rb:108:in `block (3 levels) in <top (required)>'

```

**Comment by luisramos0** [comment] 2019-02-14 18:32
this is a duplicate of #3468
maybe 3468 is not yet fixed...

**Comment by sigmundpetersen** [comment] 2019-02-14 21:55
yes it was just a different error message at a different line so I opened a new issue. @kristinalim will know if this is the same issue

**Comment by sigmundpetersen** [comment] 2019-02-19 08:04
This failed again in master https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/496

**Comment by Matt-Yorkley** [comment] 2019-02-23 20:05
I've just seen this fail again.

**Closed** 2019-02-25 11:50 UTC
Labels: tech debt
