### ISSUE TITLE
Want the full profile to be visible/accessible from the producer listing page.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#624] opened 2015-07-15 01:16 UTC
On this page.... www.openfoodnetwork.org.au/producers ...only the 'brief profile' is displayed. There is no indication that a longer profile exists and can be read.
This also carries into the Group producer listing pages.... e.g. www.openfoodnetwork.org.au/groups/mt-alexander-local-produce-network##producers

The only place where full profiles can be seen is the map page (group map pages also show full profiles).

Are either of these suggested solutions doable?
1.  Can we have the full modal open up, rather than the dropdown style, brief profile? Just as occurs in the map view?... this is already implemented on the Group- Hubs listing page... e.g. https://www.openfoodnetwork.org.au/groups/mt-alexander-local-produce-network##hubs
2.  Can we have a link in the brief profile view which says 'view full profile'?

*\* Context- Lucy from the MALPN group raised this issue. This group's full producer profiles all have 'outlets/stockists' at the bottom... she's worried visitors to the site won't see these if they look at producer profiles from the list.

**Comment by sowfrancis** [comment] 2015-12-14 13:56
https://github.com/wvengen/openfoodnetwork/tree/feature/624-link-to-producer-profile
we have added the link to the producer profile page.
Unfortunately there is no static producer profile page.
So we can create the static show profile page or use the modal already existing.

**Comment by pmackay** [comment] 2015-12-14 14:28
Personally I think its quite important that producers have a full profile page with a static URL, because it allows them to include that URL in other media. @kirstenalarsen can you comment on if there are reasons why not to do this?

**Comment by wvengen** [comment] 2015-12-14 15:24
I would agree that having a static url is a plus.

**Comment by elf-pavlik** [comment] 2015-12-14 15:32
:+1: giving permanent URL to each producer so they can share it easily and once we use WWW as intended, they have a proper - globally unique - identifier

**Comment by kirstenalarsen** [comment] 2015-12-15 00:31
hi people, couple of options here
- make the link bring up the modal, as it does if you click on a producer link in the hub/shop listing
- create a new producer page with static link

there is quite a difference between the two, as the first one allows for browsing and finding out more without moving and reloading pages, then both the producer modals and 'fat view' (in the listing) have links to places where you can actually go and buy from that producer

We have talked about having an actual producer page and has always been something we'd like to do, but has just never made it to top priority. The tricky bit to consider is whether it is just a profile page (with potential to do some fun stuff like add more photos, stream social media etc) or whether / to what extent is integrated with the shopping e.g.
- if is a 'producer with shop' then they already have a page with static link, which is their shopfront page . . but this does have limited 'profile' info
- if is a producer selling through one or many shops / hubs, then you probably want to be able to see what is available from this producer at those different outlets, and information on distribution from those different outlets, BEFORE you pick one and click through / load up their shop page . . you definitely don't want to be loading up pages that have closed shops OR where this producer is out of stock (for example)

So it needs a bit of ux design and thinking . . we did have a designer look at it really early on and I can try and dig up what he did, but was looking like a pretty big project which we didn't have capacity to take on at the time

That said . . you've got some people and energy so if someone wants to do some design and have a look at it then go for it! If you are going to do this, I think we should start with a 'wishlist' page on discourse so that we can have good discussion / agreement on the scope and a tangible chunk to get started with . . http://community.openfoodnetwork.org/c/features/wishlist

**Comment by kirstenalarsen** [comment] 2015-12-23 10:07
@sstead this needs some work to define what exactly needs to happen for the groups, smaller version (pre-having an actual producer page). Work with @mkllnk over Jan to see what can actually be done  . .

**Comment by kirstenalarsen** [comment] 2016-07-20 06:04
looks like we hit a stalemate on this? @sstead can we discuss whether / what quickfx we might want for aus re-launch?

**Comment by sstead** [comment] 2016-07-20 07:42
I'd suggest one of these options in the meantime...
1. Can we have the full modal open up, rather than the dropdown style, brief profile? Just as occurs in the map view? Do we have any reason to keep the brief description mini profile?
2. If not, can we have a link in the brief profile view which says 'view full profile', which takes them to the modal, on the map if neccessary?
On Australia's modified site there will still be map and list view. It's a shame if someone searches with the list view and only sees the short profile, they may leave thinking OFN doesn't have much info. So yes, I'd suggest this would be worthwhile if it's not too difficult.

**Comment by mkllnk** [comment] 2016-07-20 10:33
I would vote for opening the modal instead of showing the fat view. That should be quite easy. I just looked at the production site and saw some bugs in the fat view as well. The -shop-for labels are showing without any shops.

![screenshot from 2016-07-20 20 32 17](https://cloud.githubusercontent.com/assets/3524483/16983632/17d59ace-4eb9-11e6-9b3d-16af91d625f8.png)

**Comment by sstead** [comment] 2017-09-01 06:26
I've been in touch with Slow Food in Melbourne. They want to get all of their stallholders online, as they have some producers who have no other web presence. Currently profiles don't have a static URL, so producers with a profile probably don't show in a web search. This is a shame. Another good reason to have static pages for each producer?

**Comment by daniellemoorhead** [comment] 2017-09-01 06:37
>I would vote for opening the modal instead of showing the fat view. That should be quite easy.

Hey @mkllnk exactly how easy do you think this would be? Angular for newbies easy? Could we have one of our newly arrived devs look at this?

**Comment by mkllnk** [comment] 2017-09-08 04:42
There have been easier tasks than this, but it's not too complicated either. Let's try that.

**Comment by daniellemoorhead** [comment] 2017-09-08 05:54
@dannyd4315 may be something you'd be interested in picking up once the instagram PR is done. Also, there are a few UX labelled issues being added by @simoneluijckx at the  moment that could also be a tasty start to things :)

**Comment by dannyd4315** [comment] 2017-09-08 05:58
@daniellemoorhead will take a look over the weekend, I am more comfortable with Ruby but happy to have a look over. 👍

**Comment by myriamboure** [comment] 2018-05-21 19:13
That was a lot of discussion to read to understand what is to do ;-) Anyway this is not a bug and we do have a process now to handle those cases so:
- I [created an icebox item "Improve Producer visibility on OFN"](https://community.openfoodnetwork.org/t/improve-producer-visibility-on-ofn/1320) and added it to the giant spreadsheet. First feature candidate as I understand is just to display full profile pop-in from producer page instead of the current fat view (short profile) so might be quick and easy to implement when we decide to prioritize if everyone agrees.
- I'm closing this issue and we will open specified and clear ones when we have prioritized and incepted the icebox item.

**Closed by myriamboure** 2018-05-21 19:13 UTC
Labels: australia
