### ISSUE TITLE
[mobile ux] Copy-paste in shopfront message display strange white strips

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1860] opened 2017-09-26 09:38 UTC
## In a feature branch or master?
This can be merged straight to master 🎉 

## Description
When copy-pasting from another shopfront or any text file, into the "message when shopfront open/close" (in menu enterprise setting > shop preferences), here is what happens. Some shops have done that apparently and then their shopfront is not looking good.

![bug](https://user-images.githubusercontent.com/8135376/30853455-230519ce-a2af-11e7-8e56-5e12c799ba57.png)

**Comment by daniellemoorhead** [comment] 2017-09-26 22:20
Hey @myriamboure I think this could be something a newbie could do, so would you be able to add a little bit more information about what you did / where you did it and where this message displays? I'm not sure if it would be obvious for a new person :)

**Comment by myriamboure** [comment] 2017-09-27 07:55
Sure ! In the enterprise menu, the user write in "shopfront preference" a welcome message for his hub 1.
He creates another hub and wants to use the same welcome message. So he copies/pastes the welcome message from hub 1 to hub 2. He saves and go on the hub 2 shopfront, he sees the image above so the white strips below the text.
He is surprised so he goes back to the hub 2 menu and delete the message and retype it, but it doesn't change anything, still the white strips.
Hope it's clear enough, if any question come back to me :-)

**Comment by mllocs** [comment] 2017-10-18 13:17
Pretty easy to reproduce, just paste a multi-paragraph text like:

```
paragraph1

paragraph2
```

and the WYSIWYG will generate a markup with a white background paragraph...

**Comment by mjal** [comment] 2018-01-29 17:29
This seems to be fixed in the latest version of the library, copying and pasting from the editor don't add white strips anymore.

However the editor also paste the style of the text, so the example above will still highlight the text because it's inside a code segment (highlighted with a grey background)

**Comment by Matt-Yorkley** [comment] 2020-01-20 14:33
99.9% sure this is closed by #4655. Feel free to reopen if that's not the case.

**Comment by daniellemoorhead** [comment] 2020-02-07 03:13
![Screen Shot 2020-02-07 at 2 12 01 pm](https://user-images.githubusercontent.com/10949052/73997848-d9300d00-49b3-11ea-9b50-7daa461f5e41.png)

@Matt-Yorkley this bug is not fixed as was expected by changing to the home tab.

I think we need to strip any background colour formatting that is copied across to the fields.

The shop where this is happening is https://openfoodnetwork.org.au/local-produce-ladies/shop#/home

**Comment by mkllnk** [comment] 2020-02-07 03:44
@daniellemoorhead I think this is already solved. Can you check?

**Comment by daniellemoorhead** [comment] 2020-02-20 10:20
@mkllnk here's another example of background colour displaying. https://staging.katuma.org/fredo-s-farm-hub/shop#/home

I copied text from a google doc that I had highlighted in green and that background highlight colour shows up on the tab.

**Comment by mkllnk** [comment] 2020-02-20 23:50
Ah, great. I was able to copy that example. When I copy from a document locally it doesn't transfer the background colour. :woman_shrugging: Maybe my Linux is just not doing that.

**Closed** 2020-03-18 05:23 UTC
Labels: Hacktoberfest, bug-s5, good first issue, socialissues.tech
