### ISSUE TITLE
Incorrect line item tax on invoice

### ISSUE THREAD

**Issue by NiftyGaloot** [openfoodfoundation/openfoodnetwork#10831] opened 2023-05-11 19:38 UTC
## Description
On an invoice the line item Sales tax column reflects the wrong amount. 
This is confusing for the hub and the customer. This can cause the hub to make incorrect adjustments if needed.

## Expected Behavior
Sales tax should be calculated for the line item on the price the hub is selling the item for.

## Actual Behaviour
The line item sales tax is being calculated on the producer price instead of the hub price which can include fees.

## Steps to Reproduce
For a hub that charges tax and has a fee. Create an order that includes a taxable item.
Create an invoice for the order. The tax shown on the line item should reflect the item price plus hub fees.

## Animated Gif/Screenshot
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/132571876/aacce7c1-6bda-4d04-82da-23fbaafe337f)

## Workaround
For the hub to manually calculate the tax for line items and correct the amount on a printed invoice. Or, tell the customer to ignore the line item tax amount.

## Your Environment
Happens on all browsers. Is an app issue not a display issue. Happens in the US.

## Possible Fix
Change the sales tax formula for line items.

**Comment by RachL** [comment] 2024-01-24 14:24
I think this is a duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/12021 which should be soon fixed, closing here!

**Closed by RachL** 2024-01-24 14:24 UTC
Labels: bug-s3
