### ISSUE TITLE
Missing translation: "Product" in product created confirmation message

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8459] opened 2021-11-05 11:56 UTC
## Description
When creating a new product, the confirmation message at the top of the screen is not fully translated. It starts with untranslated "Product xy".

## Expected Behavior
"Product" in the confirmation message should be translated.

## Actual Behaviour
"Product" in the confirmation message is not translated.

## Steps to Reproduce
1. Choose a language other than English.
2. Log in.
3. Go to /admin/products
4. Klick 'new product' ('neues Produkt' in German)
5. Fill in all required field and select 'new'
6. Observe the confirmation message at the top of the screen

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/1790176/140506637-4002045c-1e31-4d48-a1a9-efa58de4994d.png)

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.6
* Browser name and version: Chrome 95.0.4638.69 (Offizieller Build) (64-Bit)
* Operating System and version (desktop or mobile): Windows 10, Desktop

**Comment by drummer83** [comment] 2021-11-08 19:44
Just discovered that the same is true for creating or modifying shipping methods.
So this will probably apply to more situations than the ones already covered here.

**Comment by gjacob3000** [comment] 2021-11-16 23:55
Can I be assigned to this task?

**Comment by jibees** [comment] 2021-11-17 08:26
@gjacob3000 : sure, thanks for your time! 🙏

**Comment by gjacob3000** [comment] 2021-12-09 16:57
When I used print statements to try to find the source of where the word “Product” is coming from, I traced it back to line 64 of base_controller.rb in app/controllers/spree/admin. When I print out resource_desc after it is set to object.class.model_name.human, it prints out “Product.” After it is appended with object.name in line 65, it prints out “Product ‘xyz’”.

Looking into this further, it’s clear that “Product” is being pulled from object.class.model_name.human. However, when printing both object.class and object.class.model_name, I see “Spree::Product.” It seems that @object calls permitted_resource_params on line 30, which sets @object.attributes to params[:product]. Where does params[:product] come from, and does anyone have any ideas for how to go about fixing the issue now that part of the source has been discovered?

**Comment by cbordei** [comment] 2022-03-22 15:22
@gjacob3000 identified the place in the code where the message is rendered but the fix is not to rewrite that method



```
def flash_message_for(object, event_sym)
  resource_desc  = object.class.model_name.human
  resource_desc += " \"#{object.name}\"" if object.respond_to?(:name) && object.name.present?
  Spree.t(event_sym, resource: resource_desc)
end
```


the way rails translations work (which spree overwrote with the use of `Spree.t`) is that they will pinpoint a value in the translation yml file; in this case `successfully_created: ! '%{resource} has been successfully created!'`

when the i18n replaces the `%{resource}` value it will actually replace it with `object.class.model_name.human`; thus the problem is that the model doesn't have a reference in the yml file so that the framework can know that `model_name` is also translatable.

to solve this i think we just need to add an entry for this model name (and maybe for all others) in the yml files unde `activerecord:models:{model_name}`

```
 activerecord:
    models:
      product: 'Translated name for product'
```

I can pick this up but i still need to finish up reading the guidelines for contributing on translation files (and make sure that this actually works)

**Comment by drummer83** [comment] 2022-03-22 22:47
Great to have you here, @cbordei!
Let us know if you wish to be assigned to this issue!
And @gjacob3000, just a heads up that we might remove your assignment to this issue and forward it to cbordei!

**Comment by cbordei** [comment] 2022-03-23 08:32
@drummer83 yes, please assign me

**Closed** 2022-03-28 11:54 UTC
Labels: good first issue, bug-s3
