### ISSUE TITLE
Apply tag rules in shopfront: % Discount

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#861] opened 2016-03-09 00:32 UTC

**Comment by daniellemoorhead** [comment] 2016-05-18 01:17
Unfortunately this is blocked by the way tax is set up in the system. We're doing some investigation to see whether the Spree upgrade will remove this blocker, otherwise we'll need to redesign how to implement discounts. See http://community.openfoodnetwork.org/t/spree-upgrade-purpose-and-strategy/559 for detail on Spree upgrade by @RohanM.

**Comment by myriamboure** [comment] 2019-01-21 12:59
This is one of the option described in the wishlist item https://community.openfoodnetwork.org/t/an-enterprise-can-offer-different-prices-for-different-type-of-customers-ex-members-wholesalers-etc/1148/16, this is not a bug so closing it.

**Closed by myriamboure** 2019-01-21 12:59 UTC
Labels: blocked
