### ISSUE TITLE
Delivery report filter no longer gives delivery options to choose

### ISSUE THREAD

**Issue by OliverUK** [openfoodfoundation/openfoodnetwork#1601] opened 2017-06-02 10:53 UTC
![screen shot 2017-06-02 at 11 34 25](https://cloud.githubusercontent.com/assets/17590921/26722802/818e460e-4789-11e7-94d4-8dbb1b6a191c.png)

"shipping method" filter returns nothing.
Is this possibly related to the broken date filter at the top? The date defaults to 1st June. I can change it to May (because that's when the orders came in) by typing a 5 over the 6 but I can't use the calendar button anymore. If this means the report filter only looks for orders in June, then there would be nothing there.

It may be unrelated though.

**Comment by myriamboure** [comment] 2018-02-27 23:29
![screenshot from 2018-02-28 00-28-20](https://user-images.githubusercontent.com/8135376/36761203-5051d38e-1c1e-11e8-86b8-3461a8e2103f.png)
Just tested again and couldn't reproduce that issue, so closing.
@OliverUK feel free to reopen if you still experience that issue.

**Closed by myriamboure** 2018-02-27 23:29 UTC
Labels: bug
