### ISSUE TITLE
Enable tax calcuation by enterprise on shipping fees

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4829] opened 2020-02-22 17:51 UTC
## What is the problem we are solving 
A user needs to be able to apply a tax on a shipping fee,  in the same way they can apply a tax on an enterprise fee.  At present this is not possible.  Instance wide shipping taxes are set up in configuration.  This doesn't work in instances where there are multiple shipping zones.

## Success factors = expected outcome 
Shipping fees operate the same as other enterprise fees -  the user sees a dropdown and can select the tax rate to apply.  The tax rates are set in configuration.

**Comment by tschumilas** [comment] 2020-04-22 00:49
Is it a bug or is it enhancement?  On one hand,  We have always had shipping fee taxes -  so its not a new feature.  Its just that the current functionality is not working for an instance with multiple tax zones.  There is no workaround really -  users cannot be legally compliant with tax requirements.

**Comment by daniellemoorhead** [comment] 2020-04-22 05:17
I'd call this a new feature @tschumilas as it wasn't designed to work with multiple tax zones. A bug is where something isn't working as it was designed to.

I'm also unsure that it's papercut size, but I've put it in the papercut project for @kirstenalarsen and @lin-d-hop and @sauloperez to review.

**Comment by sauloperez** [comment] 2020-04-22 15:22
I don't think this is a papercut either because it needs product research and investigation to come up with proper requirements. Shouldn't we open a wishlist item right away?

**Comment by tschumilas** [comment] 2020-04-23 11:23
Wishlist created - https://community.openfoodnetwork.org/t/enable-tax-calculation-by-enterprise-on-shipping-fees/1916

**Comment by sauloperez** [comment] 2020-04-23 11:25
I'm closing this to avoid duplicates.

**Closed by sauloperez** 2020-04-23 11:25 UTC
Labels: CA, enhancement
