### ISSUE TITLE
Development environment postgres user requires superuser permissions

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#245] opened 2014-07-02 00:53 UTC
Originally reported by @mkllnk:
1. I executed `bundle exec rake db:test:load` and that works fine.
2. I executed `bundle exec rspec spec` and get this message:
   /home/maikel/.bundle/gems/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec': PG::Error: ERROR:  permission denied: "RI_ConstraintTrigger_32544" is a system trigger (ActiveRecord::StatementInvalid)
   : ALTER TABLE "cms_revisions" ENABLE TRIGGER ALL;ALTER TABLE...

**Comment by elf-pavlik** [comment] 2015-12-13 14:24
@mkllnk I see done label assigned, does this issue still require something before closing it?

**Comment by mkllnk** [comment] 2015-12-13 20:57
Yes, the branch postgres-referential-integrity-patch has not been merged into master. It has been a low priority for us. 

I was wondering if you would like to create your own hackathon-master branch. You could merge this one in and also the timezone-fix branch.

**Comment by daniellemoorhead** [comment] 2016-02-25 23:34
@mkllnk @elf-pavlik should the done label be removed then?

**Comment by mkllnk** [comment] 2016-02-26 01:58
Yes, that label is replaced by the use of ZenHub.

**Comment by lin-d-hop** [comment] 2017-12-19 04:36
@mkllnk @enricostano @sauloperez Low priority but we have a fix.... shall we just get this merged?

**Comment by enricostano** [comment] 2017-12-19 04:45
@lin-d-hop can you please point me to the fix? This is a problem that we've faced also and still cannot spend time on investigating the root cause. It's really weird to me that we need to be `superuser` for development....

**Comment by sauloperez** [comment] 2017-12-19 04:48
and If I'm not mistaken we don't have this problem when running specs but when running db related rake tasks in staging.

**Comment by enricostano** [comment] 2017-12-19 04:54
@lin-d-hop @sauloperez found it: https://github.com/openfoodfoundation/openfoodnetwork/pull/498

It seems OK for me to merge that PR, UPGRADE ALL THE THINGS! 😂

**Comment by sauloperez** [comment] 2017-12-19 05:08
Hold on. I'd like to make sure we're all on the same page. The problem we're experiencing it's not related to specs but to the staging environment and db rake tasks. I don't even know how it works in production (I guess we have a superuser).

That PR seems to solve the issue as it does not depend on a particular environment but if we move on with it we must keep track of the patch and remove it when we upgrade to Rails 4. I guess this needs to be a new icebox item.

**Comment by enricostano** [comment] 2017-12-19 05:31
OK, you're right @sauloperez we have this problem both in `development` and `staging`. The only difference is that we "solve" this in `development` adding `superuser` role to the PG user but we still don't fully understand the issue.

**Comment by mkllnk** [comment] 2017-12-20 04:21
No, the problem is running specs without having `superuser` rights on the database. We run specs only in test environment. All normal operations of OFN don't try to mess with database system contraints. The pull request needs testing by other developers to see if it really works doesn't break anything.

**Comment by sauloperez** [comment] 2017-12-20 04:30
Ok, I took the time to check how things work.

We ask to create the user as superuser for development https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Ubuntu#step-5-set-up-postgresql while we don't create it as superuser when we provision a machine https://github.com/openfoodfoundation/ofn-install/blob/bd9fbf9057de4754ab69911dcf050cb0d8c49b5d/playbooks/provision.yml#L48.

That is why it fails when we run `rake db:setup` in staging but it works when I run the tests in my dev env (using the `test` Rails environment as @mkllnk points out).

The fix that bring in the PR would fix both cases.

**Closed** 2018-02-09 17:12 UTC
Labels: australia, bug-s5, uk
