### ISSUE TITLE
Shipping and payment methods missing from profile edit menu of producer shop account

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#606] opened 2015-06-12 06:17 UTC
![image](https://cloud.githubusercontent.com/assets/10843056/8124429/7dcacbd0-111e-11e5-86c6-f9a8061c5122.png)

**Comment by RachL** [comment] 2019-03-27 10:07
I could not reproduce this, so I'm closing it.

**Closed by RachL** 2019-03-27 10:07 UTC
