### ISSUE TITLE
Deploy Migrated Stroudco Database to UK Staging

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/openfoodnetwork#408] opened 2015-03-05 14:54 UTC
@pmackay @NickWeir63 Hi Paul - need to chat about the best way to do this - can you give me access to UK staging? 
also I notice that when all the Stroudco data is loaded on my local test server, performance is prohibitively slow when creating / editing order cycles etc. I am hoping that this is due to debugging output being on??  Not sure how to switch this off - do you know?

**Comment by pmackay** [comment] 2015-03-08 14:14
About performance, is that during migration or when using the app afterwards? 

What status is rollback support currently?

We should probably try to have that chat and decide how to handle importing the data into staging.

**Comment by aidandunsdon** [comment] 2015-03-09 12:29
Hi @pmackay 
Re Performance: If all the Stroudco Data is loaded, performance is v. slow when setting up or editing order cycles for example.  I am currently having to test with a sub set of the data to make any progress. Looking at the output command window - the select statements in the app seem to cycle through, printing all products to the screen taking several minutes each time an edit to an order cycle is attempted. Any idea whether this is debug behaviour and whether this can be switched off?

Re rollback This is not currently available  - my current priority is to incorporate the new customer model but am waiting for a outstanding commits to be merged. At present I back up the database versions in pgAdmin III and restore to roll back.

**Comment by pmackay** [comment] 2015-03-09 17:53
Perhaps @RohanM is best to comment on the performance issue - I'm not quite sure where the products are being printed. I wonder how many products the Angular UI has been tested with? 

Are you free for a chat tomorrow about the database stuff?

**Comment by NickWeir63** [comment] 2015-03-11 16:27
The testing team is keen to start a structured programme which @getweaving designed and I confirmed with her this morning.  Here is a picture of it
![alexis ofn uk testing timeline](https://cloud.githubusercontent.com/assets/10517702/6601064/5e1cd7b2-c80b-11e4-999c-37ba17b44052.jpg)
.  I then talked to @aidandunsdon about which of the staging servers the data would be on.  @aidandunsdon suggests that we migrate to the UK staging server because this will have correct currency £ settings, etc.  However there are 2 issues with this:
1) I think the UK staging server is not up to date with all the latest improvements.  @pmackay is it possible to deploy all the improvements to the UK server so that we can test them?
2) @kirstenalarsen suggested that we should do all the testing on staging 2 so that she could keep an eye on any problems that we encounter when testing.  To get around this @getweaving and I thought we could make a note of any problems we come across on the UK server and then replicate them on staging 2.  Would this work?

**Comment by kirstenalarsen** [comment] 2015-03-11 21:27
Great!! 

I suspect the best way to handle staging is for you guys to test uk staging with your real data and do your bug reporting etc, with responsibility for the UK dev team to take first look at everything and identify whether it is a problem that needs to be considered by the Aus team. If it is, then yes, you guys show how it can be replicated on staging2?

This is a bit abstract and maybe it won't be a problem. So I say test a go go on uk staging :)

re. version control - can I suggest you update at the end of this week? We're trying really hard to get some stuff through into production, or at least staging, which may even include vat . .

Cheers
Kirsten

**Comment by NickWeir63** [comment] 2015-03-12 17:21
Sounds good to me.
@pmackay is it OK with you to update UK staging when these updates are ready?
thanks
Nick

**Comment by pmackay** [comment] 2015-03-12 20:56
Yes can do after all recent updates are merged.

**Closed** 2015-04-30 09:41 UTC
Labels: task, uk
