### ISSUE TITLE
[Flaky Spec] proxy_order_spec.rb:202

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#3820] opened 2019-05-07 11:29 UTC
Just had to restart 2 builds for this one. It was green on the third run.

```
  1) ProxyOrder resume when the order cycle is already closed and the order has been cancelled returns false and does nothing
     Failure/Error: expect(subject.reload.canceled_at).to be_within(2.second).of Time.zone.now
       expected 2019-05-07 20:52:31.074108000 +1000 to be within 2 of 2019-05-07 20:52:33 +1000
     # ./spec/models/proxy_order_spec.rb:202:in `expect_cancelled_now'
     # ./spec/models/proxy_order_spec.rb:149:in `block (5 levels) in <top (required)>'
```

**Comment by sigmundpetersen** [comment] 2019-06-18 09:24
Seen again https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/678

**Comment by mkllnk** [comment] 2019-06-20 03:33
I got another example at a different place, but same problem.

spec/models/proxy_order_spec.rb:149

```
  1) ProxyOrder resume when the order cycle is already closed and the order has been cancelled returns false and does nothing
     Failure/Error: expect(subject.reload.canceled_at).to be_within(2.seconds).of Time.zone.now
       expected 2019-06-20 11:52:27.903391000 +1000 to be within 2 of 2019-06-20 11:52:30 +1000
     # ./spec/models/proxy_order_spec.rb:204:in `expect_cancelled_now'
     # ./spec/models/proxy_order_spec.rb:151:in `block (5 levels) in <top (required)>'
```
https://semaphoreci.com/mkllnk/openfoodnetwork/branches/test-spec-stability/builds/2

**Comment by jibees** [comment] 2023-05-29 14:10
Closing here: 4 years old, seems to not happen anymore ; could not reproduce as well. Could be re-open at any time.

**Closed by jibees** 2023-05-29 14:10 UTC
Labels: tech debt
