### ISSUE TITLE
Product inventory can be set against total or order cycle

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#404] opened 2015-03-05 09:07 UTC

**Comment by NickWeir63** [comment] 2015-04-20 10:52
Stroudco producers (and the hub admin on their behalf) need to be able to set stock levels in one of 2 ways: 1) that the stock level available from this product for a new order cycle reduces by the amount sold in the previous order cycle OR 2) that the stock level of this product available for a new order cycle reverts to the original total set at the beginning of previous order cycle.
In this way the producers who hold a stock in the Stroudco shed can have their stock levels automatically reduced using option 1) above and producers who always produce a maximum of 5 loaves of bread every week can use option 2)

**Comment by NickWeir63** [comment] 2015-04-20 10:54
@lin-d-hop  - please can you translate the above into tech.  thanks N

**Comment by lin-d-hop** [comment] 2015-04-30 10:13
Discussed in http://community.openfoodnetwork.org/t/inventory-reset-to-start-level-in-order-cycle/83

**Comment by stveep** [comment] 2015-12-12 19:56
This has now been merged with a more recent version of master and pushed to a new branch uk/default-inventory, so should be ready for staging/testing. I see that buildkite has already failed though which is a good start! Hopefully that shouldn't take too much fixing - can @pmackay or @lin-d-hop let me know what the issue is?

**Comment by oeoeaio** [comment] 2015-12-12 21:25
Hi @stveep,
You'll need to merge in the current version of master in order for the branch to build. I notice that the version you have merged is a week and a half old. This is required for the build pipeline to work and is generally good practice for continuous integration.

**Comment by stveep** [comment] 2015-12-12 22:30
Thanks @oeoeaio - I merged the latest one and looks like the Buildkite build has now worked, although I got one weird spec failure on the TravisCI job:

https://travis-ci.org/openfoodfoundation/openfoodnetwork/builds/96498899

This passed when I ran it locally so not sure why this is happening.

**Comment by oeoeaio** [comment] 2015-12-13 05:29
@stveep

Yeah, we are aware of that one. Working on a fix, but you can ignore it in the meantime.

**Comment by NickWeir63** [comment] 2015-12-16 14:53
Thanks for all your work on this Steve
@pmackay please can you deploy this to UK staging so that I can test it.  Thanks

**Comment by pmackay** [comment] 2015-12-17 21:28
@NickWeir63 @stveep deploy looks good, please test :)

**Comment by NickWeir63** [comment] 2015-12-18 07:59
Will do - thanks very much everyone

**Comment by NickWeir63** [comment] 2015-12-27 15:35
Thanks @stveep  - this is looking great and does what we need it to do.  The only very minor problem is that staging now sticks on this screen when i click 'reset stock to defaults' - see screenshot
![screenshot 2015-12-27 15 12 37](https://cloud.githubusercontent.com/assets/10517702/12010870/700e1ba0-acaf-11e5-83ad-04c7a24a6237.png)


it does something similar when I try to save an order cycle after adding a new producer - I click the 'update' button and nothing happens.  i click the 'update and close' button and nothing happens.

But in both cases (resetting stock levels and updating the order cycle) the changes are saved and when I go back to those screens the corrections have been made.  

And the second time I tried to reset the stock level the change was made and the screen did not stick with the saving message.....

@stveep and @pmackay - this seems like a minor issue but do you think we need to do some more checking to see if something more sinister is happening before we deploy this update onto production?

Thanks again Steve - this is looking great

**Comment by stveep** [comment] 2015-12-30 15:04
I've just had a go with this on staging, using Nick's account, and it was all working fine for me - got the confirmation message and refresh every time with lots of different update/reset operations. This was using Chrome 47 or Safari 8.0.6. So perhaps this is a problem on the client side - Nick are you able to test on a different Windows browser and/or computer?

**Comment by NickWeir63** [comment] 2015-12-30 16:45
Thanks Steve
I just logged in on my wife's laptop and used explorer and everything worked fine.  I then went back to my computer and used chrome (where i had the problem previously) and everything worked fine there too.
Aaaaargh!
If I cant replicate the problem can we assume that it is safe to go ahead and deploy this update to production?  What do you reckon @pmackay 
thanks both
Nick

**Comment by stveep** [comment] 2015-12-30 22:40
Well there must be a reason for it, but it's hard to know what to do if we can't replicate it. I have pushed a minor update to this branch - I noticed that I hadn't set it up to give an error message if the reset failed for any reason. I don't think that would be the problem though as it was succeeding, just not refreshing the data properly. Apart from that I don't see anything else obviously wrong with the code.

In case you missed it, @oeoeaio also incorporated these changes into the ng-vo-inventory-reset branch along with some other changes to the VO interface. So if it's in a finished state (not sure what the plans are) we could deploy that branch instead?

**Comment by NickWeir63** [comment] 2015-12-31 12:16
thanks Steve
Let's wait and see what @pmackay reckons is the best branch to deploy

**Comment by stveep** [comment] 2016-01-16 16:51
This is now in master along with Rob's other VO updates, so we can now deploy it.

**Closed by stveep** 2016-01-16 16:51 UTC
Labels: critical, story, uk

**Comment by NickWeir63** [comment] 2016-01-16 17:12
thanks @stveep - let's hope that this resolves #760 if @paul can delpoy this to production please

**Comment by pmackay** [comment] 2016-01-16 19:14
I've updated staging with master, please could @NickWeir63 and/or @stveep confirm recent changes look ok?

**Comment by NickWeir63** [comment] 2016-01-16 21:17
thanks @pmackay this all looks good on staging and i just put an order through successfully - I am happy for this to go to production.  thanks

**Comment by stveep** [comment] 2016-01-16 21:24
Looks good to me.
