### ISSUE TITLE
Product permalink - manage case where user sets to an already used permalink

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#671] opened 2015-09-11 03:57 UTC
If an enterprise user (EU) changes Product permalink, and the link they change it to is taken there is RSOD. 

Would be good to 
- validate this in page so they can change it straight away OR
- simple hide / make non-editable the field (does anyone even use this? do they need to?)

If you decide to check the permalinks, there is some logic already in place for group permalinks.

**Comment by Matt-Yorkley** [comment] 2017-03-08 11:30
@kirstenalarsen This bug still breaks things in really bad ways if the permalink already exists. Could be a good onboarding job. Any preference for the desired behaviour: 1) make the field non-editable by users or 2) do a check to see if the permalink is taken?

**Comment by daniellemoorhead** [comment] 2017-03-24 04:28
@kirstenalarsen thoughts on suggestions from Matt above?

**Comment by kirstenalarsen** [comment] 2017-03-24 04:31
I don’t have a preference. @sstead may be closer to people experiencing this and have an idea? If not, developer that picks it up can decide :)

**Comment by janfabry** [comment] 2017-06-16 10:27
Is this still the case? I just tried it out in a developer setup (master branch), and when I change the permalink of a product to something that already exists, it saves without a problem and a `1` is added to the permalink.

**Comment by mkllnk** [comment] 2017-06-16 12:46
I did that logic for groups which have permalinks as well more than a year ago. That might have been ported to enterprises, but I'm not aware of this in products. @Matt-Yorkley would be the best to confirm that. Can you describe how to reproduce this?

**Comment by myriamboure** [comment] 2018-05-21 19:48
I retested and the issue is fixed by a 1 being added if the permalink is already used (https://docs.google.com/document/d/1k4r7XbU7qSxBWMsdlsz3zWUnctT_-C_j8BQuOoyU150/edit?usp=sharing), so closing this issue.

**Closed by myriamboure** 2018-05-21 19:48 UTC
Labels: australia, bug, good first issue
