### ISSUE TITLE
Bug on stock management when cart is saved and stock change

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1335] opened 2016-12-14 17:12 UTC
I tested this case:
- Carrots stock level is 10kg
- As a buyer I put 8 kg in my cart, but don't go till checkout (I plan to add other products later maybe)
- As a hub manager I change the quantity of stock and put it to 2kg (I have sold them to other people)
- As a buyer I go back to my cart and go to checkout. No modification, still 8kg, I reload and still the same. I can continue and process checkout, no indication that the stock level is not enough to order and that I can only by 2kg...  I could go till payment without any alert.

It can cause serious issues to the hub manager then, quantities ordered might be more than quantity available.

This is related to that discussion:
https://community.openfoodnetwork.org/t/adding-to-cart-when-out-of-stock/550/6

**Comment by sstead** [comment] 2016-12-16 03:07
Hi @myriamboure I've tried to replicate this according to the description above, but wasn't able to. I was shown the screenshots below if the QTY on hand was lowered by the hub. Could it have been that you changed the stock level to 2kg but didn't hit the save button? Please try to replicate and if you can, include your exact steps (where did the shopper go after adding 8kg? Was stock changed in products or inventory? Was stock lowered before or after the customer left the shop?) Thanks!
![image](https://cloud.githubusercontent.com/assets/10843056/21250292/1efd06da-c398-11e6-803a-8fea3d84ac5e.png)
![image](https://cloud.githubusercontent.com/assets/10843056/21250295/2206f714-c398-11e6-88e4-ec3fc74062a0.png)

**Comment by myriamboure** [comment] 2016-12-17 08:22
Ok I redo it @sstead 
1- in the producer catalog I set up the available stock to 8
![screenshot from 2016-12-17 09-09-37](https://cloud.githubusercontent.com/assets/8135376/21285462/93a7942c-c439-11e6-8031-4f63a9c24981.png)
2- I save and refresh the inventory page (hub uses the inventory setting but no modification on stock) so same in inventory
![screenshot from 2016-12-17 09-09-53](https://cloud.githubusercontent.com/assets/8135376/21285464/9c3bfe7a-c439-11e6-8df5-5e62b4e2f46f.png)
3- in another browser I make an order of this product for quantity 7, and leave this in the basket without proceeding to checkout (I don't leave the shop, just do nothing)
![screenshot from 2016-12-17 09-11-02](https://cloud.githubusercontent.com/assets/8135376/21285465/a8ce288e-c439-11e6-9e93-ded49fc48131.png)
4- Then in the other browser I change the quantity available in the catalog producer to 2 and save
![screenshot from 2016-12-17 09-12-16](https://cloud.githubusercontent.com/assets/8135376/21285468/bc1f2104-c439-11e6-8af6-5260fe22a6ae.png)
5- I check in the inventory, the modification has applied there too
![screenshot from 2016-12-17 09-14-09](https://cloud.githubusercontent.com/assets/8135376/21285472/cec4b65c-c439-11e6-9d07-ac1222590e8d.png)
6- In the other browser, I go back to the cart, nothing has changed, refresh the page, no modification. I close the shop and reopen, still no modification in the cart, no indication that the quantity has been changed, I can proceed to checkout and pay normally.
![screenshot from 2016-12-17 09-11-02](https://cloud.githubusercontent.com/assets/8135376/21285488/500c9068-c43a-11e6-9667-e08de8b0a725.png)
7- I check what happens in the producer catalog and quantity in the inventory, both are now to -5... it shouldn't be possible to have a negative quantity on stock, but that's what happens
![screenshot from 2016-12-17 09-14-27](https://cloud.githubusercontent.com/assets/8135376/21285483/14c43f7e-c43a-11e6-88b4-40059061a8b2.png)

**Comment by lin-d-hop** [comment] 2017-04-18 13:56
Notes from Rob:
If you grep for insufficient_stock_lines in the orders_controller_decorator you should find the logic. If this is not working properly, then it is just a bug, I don't think it represents a new feature.

I'm just looking now and perhaps the problem is that we only check when item quantities are updated (ie shopfront and cart pages) and a final check isn't performed at the checkout phase? Perhaps we need to redirect back to the cart from checkout in CheckoutController#update in that same way that we do from OrdersController#update

**Comment by lin-d-hop** [comment] 2017-04-18 13:56
Blocks #1031

**Comment by jeronimo** [comment] 2017-04-20 12:03
So far after some research it looks like the problem is in `Spree::Config[:allow_backorders]` which by default is `true`. 
Even in tests it is set to `false` manually so tests always pass.

Question is? Do we need to allow backorders?

**Comment by sstead** [comment] 2017-04-21 04:06
Can I check/confirm, the issue Myriam was facing can be solved by changing the superadmin setting to disallow "Backorders"?

**Comment by lin-d-hop** [comment] 2017-04-27 20:18
@myriamboure can you confirm sallys comment above?

**Comment by myriamboure** [comment] 2017-04-28 07:55
@lin-d-hop @kirstenalarsen @sstead I tested this, and yes if I uncheck the "allow backorder" checkbox and do the same test, I can't proceed to check out and I get the message "an item in your cart has become unavailable" (non translated by the way, it seems there is WIP on it so great if the translation can be added ;-))
![screenshot from 2017-04-28 09-44-48](https://cloud.githubusercontent.com/assets/8135376/25519313/8f1580d8-2bf7-11e7-91b0-19ab7a451a58.png)

So it works ! The UX can be improved I think, I didn't see at first the "only remaining 2" mention at the side of the carrots (maybe could be more visible), but it seems to be WIP https://community.openfoodnetwork.org/t/adding-to-cart-when-out-of-stock/550/6 :-) So I guess it's fine yes, sorry I didn't know it was connected to that super admin config :-o

@lin-d-hop if that's ok with you we can close then.

**Comment by myriamboure** [comment] 2017-04-28 07:58
@lin-d-hop @kirstenalarsen @sstead I tested this, and yes if I uncheck the "allow backorder" checkbox and do the same test, I can't proceed to check out and I get the message "an item in your cart has become unavailable" (non translated by the way, it seems there is WIP on it so great if the translation can be added ;-))
![screenshot from 2017-04-28 09-44-48](https://cloud.githubusercontent.com/assets/8135376/25519313/8f1580d8-2bf7-11e7-91b0-19ab7a451a58.png)

So it works ! The UX can be improved I think, I didn't see at first the "only remaining 2" mention at the side of the carrots (maybe could be more visible), but it seems to be WIP https://community.openfoodnetwork.org/t/adding-to-cart-when-out-of-stock/550/6 :-) So I guess it's fine yes, sorry I didn't know it was connected to that super admin config :-o

@lin-d-hop if that's ok with you we can close then.

**Comment by myriamboure** [comment] 2017-04-28 07:59
I'm wondering if that "allow backorders" button shouldn't be at the hub level? I guess some hubs might be organized in a way that they manage backorders and reorder before delivering... I don't think this should be decided for the whole instance. What do you think @lin-d-hop @kirstenalarsen

**Comment by lin-d-hop** [comment] 2017-04-28 11:12
Agreed re hub level on 'allow backorders'. But zero priority and probably a maze of complications. I say open when feature is requested.

Yep, we can close this. We've reopened the issue we spotted which turns out is not a duplicate of this one :-)

**Closed by lin-d-hop** 2017-04-28 11:12 UTC
Labels: bug
