### ISSUE TITLE
Available locales login bug

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5669] opened 2020-06-25 09:47 UTC
## Description

Error 500 observed by @RachL when logging in to staging-FR - possibly with account: rachel.arnould+bamboo@protonmail.com

Bugsnag error:

https://app.bugsnag.com/open-food-france/open-food-france-prod/errors/5ef354f0dc9a3f001732340b?event_id=5ef354f0005b757586b80000&i=sk&m=nw

**Unhandled error**
I18n::InvalidLocale: "en_GB" is not a valid locale
Location
app/helpers/i18n_helper.rb:14 - set_locale

## Possible Fix

Not much more information, but perhaps related to #5648?

**Comment by luisramos0** [comment] 2020-06-30 08:23
I think this should block the roll out... I am tagging s2.

**Comment by luisramos0** [comment] 2020-06-30 19:05
I went to the DB and changed the locale manually to the unsupported locale en_GB, I get the snail.
The error is the same as the one in the description above but not the one on bugsnag.
```
F, [2020-06-30 20:55:23#19750] FATAL -- :
I18n::InvalidLocale ("en_GB" is not a valid locale):
  app/helpers/i18n_helper.rb:14:in `set_locale'
```
Where did you see this error Filipe?


The bugsnag error comes from this method enforce_available_locales that is only called if config.enforce_available_locales is enabled.
But we have
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/application.rb#L136

Anyway, I am not too worried about this, this must have been a mess up of configs and tests in staging. I dont think this should block the rollout so I am moving it to S3, ok?

**Comment by luisramos0** [comment] 2020-06-30 19:06
This could be a regression but there's no indication that it is...

**Comment by filipefurtad0** [comment] 2020-06-30 19:25
Hey @luisramos0 ,
Thanks for checking this.

I didn't trigger this error myself, I saw it on the slack channel, as @RachL commented it:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1593005297365300

And decided to open an issue should it happen again and also, due to the unexpected logout during testing (issue #5648). I have no further information on this, so I agree with downgrading. @RachL do you feel there is any detail to add?

**Comment by Matt-Yorkley** [comment] 2020-06-30 19:25
Did the available languages get changed? Maybe an old login with that locale set for the account?

**Comment by luisramos0** [comment] 2020-06-30 20:40
@filipefurtad0 sorry, my mistake, now I see the errors are the same!

**gems/i18n-0.6.11/lib/i18n.rb:285:in `enforce_available_locales!':** "en_GB" is not a valid locale (I18n::InvalidLocale)
    from gems/i18n-0.6.11/lib/i18n/config.rb:11:in `locale='
    from gems/actionpack-4.0.13/lib/action_view/lookup_context.rb:226:in `locale='
    from gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:28:in `locale='
    from gems/i18n-0.6.11/lib/i18n.rb:35:in `locale='
    **from app/helpers/i18n_helper.rb:14:in `set_locale'**

@Matt-Yorkley yes, something like that. but I dont understand why enforce_available_locales is blowing up when the config is set to false...

**Comment by sauloperez** [comment] 2020-07-01 09:01
I'm picking this up because it's blocking testing.

**Comment by sauloperez** [comment] 2020-07-01 09:19
The site is back after https://github.com/openfoodfoundation/openfoodnetwork/pull/5561#issuecomment-652291640. There are some chances that someone may have this old locale stored in the cookie but we can fix it when and if it happens.

**Comment by luisramos0** [comment] 2020-07-01 10:00
yeah, maybe we should leave this open as an S4?
I am saying this because I think that although we have config.enforce_available_locales set to false, the locales are being enforced.
Or we could just change config.enforce_available_locales to true in the config file?

**Comment by sauloperez** [comment] 2020-07-01 10:16
we seem to be using i18n 0.6.11 and the fix at https://github.com/ruby-i18n/i18n/pull/249/commits/a65fffd6f0472bc413ba41809dafc6292e29d2ae is included in this version so we should be good to remove that configuration and rely on the default enforcement.

So yes, we can take that path so we better keep this open.

**Comment by Matt-Yorkley** [comment] 2020-07-01 10:46
We noticed this in the CI build during the upgrade as well, no? Locales were being strictly enforced, we had to tweak some tests to get the build green.

**Comment by luisramos0** [comment] 2020-07-01 10:48
I think this will happen in prod, I think enforce_available_locales is activated.

For example, in FR, 4 users will see the snail:
![image](https://user-images.githubusercontent.com/1640378/86235473-6278f380-bb90-11ea-82a6-c4664a7dedb9.png)

10 users in uk:
![image](https://user-images.githubusercontent.com/1640378/86235542-850b0c80-bb90-11ea-8b0e-319b5de34bd4.png)


875 users in AUS :warning:
![image](https://user-images.githubusercontent.com/1640378/86235675-b257ba80-bb90-11ea-80eb-f36f85c019f4.png)

I'd say this is a release blocker after all.

**Comment by luisramos0** [comment] 2020-07-01 10:50
I'd say a simple migration will be enough to fix this: load available locales and update locale of all users with locales not on that list.

**Comment by Matt-Yorkley** [comment] 2020-07-01 10:51
Either way, this is error is thrown when a session is loaded when the user logs in, right? We should catch it and resolve it nicely. Maybe resetting the selected locale to the default one for the server if the locale saved in the user's session cookie doesn't exist?

**Comment by luisramos0** [comment] 2020-07-01 10:52
yes, that solution will be more resilient than a migration :+1:

**Comment by sauloperez** [comment] 2020-07-01 15:49
just for me to understand, you suggest we don't apply any migration for the invalid locales in DB and fix them manually as they happen @Matt-Yorkley ?

**Comment by luisramos0** [comment] 2020-07-01 16:14
that's what I understood and that's better, that way we will support the removal of a locale from the available locales.

**Comment by sauloperez** [comment] 2020-07-01 16:17
what if the locale is not set in the cookie but loaded from DB? that will blow up, right? or am I missing something?

**Comment by luisramos0** [comment] 2020-07-01 18:03
I dont think we need that.
We just need to make I18nHelper#set_locale resilient
something like this?
![image](https://user-images.githubusercontent.com/1640378/86276808-7db62400-bbcd-11ea-926e-41d651c7ea69.png)

**Comment by sauloperez** [comment] 2020-07-02 06:59
> EDIT: and probably add spree_current_user.update locale: I18n.default_locale

ok, at least this. Otherwise, exchanging valid data in DB for defensive coding doesn't end well IMO

**Comment by Matt-Yorkley** [comment] 2020-07-02 07:28
We could do both? A one-off migration that fixes current broken values in the DB, and defensive code for any potential future problems, with specs.

**Comment by Matt-Yorkley** [comment] 2020-07-02 09:08
Bumping this to `s1`, as I think lots of users might be unable to log in. It also blocks the next release, and the rollout in general.

**Comment by Matt-Yorkley** [comment] 2020-07-02 10:50
`cookies[:locale]` could equally contain an invalid locale, right?

**Comment by luisramos0** [comment] 2020-07-02 12:41
yes. defensive coding on cookies :+1:

**Comment by sauloperez** [comment] 2020-07-02 13:42
Agree with this manageable bit of defensive coding but 

> We could do both, if you want? A one-off migration that fixes current broken values in the DB, and defensive code for any potential future problems (with specs).

IMO we go with one or the other otherwise, we increase costs with the same result. In this case, I think leaning the trade off towards the defensive coding it's fine in this case. It'd be different if we enforced this at the DB-schema level.

**Closed** 2020-07-08 10:30 UTC
Labels: bug-s1, v3-regression
