### ISSUE TITLE
Unable to log in to UK staging and basket hanging if guest shopper

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#627] opened 2015-07-15 21:05 UTC
Trying to test UK staging and when I entered email and password it hung on this screen
![screenshot 2015-07-15 22 01 06](https://cloud.githubusercontent.com/assets/10517702/8709866/70ff0ee6-2b3d-11e5-9650-747c6553ca7d.png)
So i then tried to enter an order without logging in.  this went fine until I clicked on 'view cart' and it hung on this screen 
![screenshot 2015-07-15 22 00 12](https://cloud.githubusercontent.com/assets/10517702/8709887/a182a776-2b3d-11e5-9a75-1af9b7cb0c10.png)

**Comment by pmackay** [comment] 2015-07-15 21:10
Hi Nick, can you expand a bit on this? I seem able to load the Stroudco
page now, its a little quicker and does show all products.  Does it just
hang for you? What account are you trying to login with?

@lin-d-hop can you check if you can load Stroudco on staging?

**Comment by pmackay** [comment] 2015-07-15 21:12
Sorry, I didnt get the full email through with these screenshots. Will look into it.

**Comment by NickWeir63** [comment] 2015-07-15 21:25
thanks Paul.  my login is
nick@nickweir.co.uk
password localfood1

**Comment by lin-d-hop** [comment] 2015-07-15 21:30
Yep, hangs on 'updating cart' for me too... :-(

**Comment by pmackay** [comment] 2015-07-15 21:36
@aidandunsdon I think this is the first error I tried resolving on production after Karen reported issues last Friday. It relates to some of the delivery methods not having associated calculators, giving this error:

```
NoMethodError (undefined method `compute' for nil:NilClass):
  app/models/spree/tax_rate_decorator.rb:12:in `adjust_with_included_tax'
  app/models/spree/order_decorator.rb:140:in `add_variant'
  app/models/spree/order_populator_decorator.rb:41:in `attempt_cart_add'
  app/models/spree/order_populator_decorator.rb:22:in `block (2 levels) in populate'
  app/models/spree/order_populator_decorator.rb:20:in `each'
  app/models/spree/order_populator_decorator.rb:20:in `block in populate'
  app/models/spree/order_populator_decorator.rb:13:in `populate'
  app/controllers/spree/orders_controller_decorator.rb:27:in `populate'
```

I got around it on production db by assigning calculators. Would your changes now have reset those in any way? Does this suggest anything related to your migration? (last change seemed really useful!)

**Comment by aidandunsdon** [comment] 2015-07-16 07:07
Hi @pmackay @NickWeir63 will have a look at delivery methods and calculators

**Comment by pmackay** [comment] 2015-07-16 08:42
@aidandunsdon would be helpful to know if you can see any connection between the migration work and the delivery methods. Are they one of the data model elements you imported?

**Comment by aidandunsdon** [comment] 2015-07-16 11:10
@pmackay Delivery methods were not imported in the migration from Stroudco and Dean Forest. We agreed at a previous meeting with @kirstenalarsen that the hubs would populate the delivery and payment methods themselves. Updates were made to the calculator table in the form of adding data to null fields where a null constraint was in place adding current date to blank updated_at and created_at columns. I am wondering if its these dates that are the problem.I can try removing null conrtraint and restoring the table to the state that you sent it to me in. This shouldn't affect the previous fixes to blank supplier error #618

**Comment by aidandunsdon** [comment] 2015-07-16 11:32
@pmackay okay superseding the above, I can see some anomalies in the spree_calculators table can you confirm that logins and carts were working after assigning calculators to payment methods prior to the last db update -

**Comment by pmackay** [comment] 2015-07-16 12:03
After I ran a 1 line bit of code to associate calculators to payment
methods, I was able to make orders and I think other customers were too.

**Comment by aidandunsdon** [comment] 2015-07-16 15:33
@pmackay @NickWeir63 Hi As I posted previously, this issue stems not from the initial migration from Stroudco and DF which did not need to include payment, shipping methods and enterprise fees but from attempting to integrate payment methods etc. with calculators from subsequent additions to staging with those already on production. The problem relates to the calculable_id field in spree_calculators which points to one of 3 different tables depending on the calculable type (shipping, tax, enterprise fees).   The synchronisation of the tables was based on incrementing the ids of imported records  along with associated foreign keys.  However, calculable_id doesn't have any foreign key relationship set up so was not incremented. I can update this on the version I initially sent for testing on 21-06 and include the previous fix for #618

**Comment by pmackay** [comment] 2015-07-16 15:35
That sounds complex, but great if you have a solution!

> I can update this on the version I initially sent for testing on 21-06
and include the previous fix for #618
<https://github.com/%20openfoodfoundation/openfoodnetwork/issues/618>

So are you proposing to send another database dump for me to upload?

**Comment by aidandunsdon** [comment] 2015-07-16 16:09
Yes - But please note it will be based on the version uploaded on 21-06 so any testing in the meantime will be lost as it will be out of sync. ( I will still include the couple of fixes I have since then). Is this OK? Make a backup before restoring :->

**Comment by pmackay** [comment] 2015-07-16 16:14
Dont quite understand - I just sent you a copy of production and you
updated that one 2 days ago. What's the difference here?

**Comment by aidandunsdon** [comment] 2015-07-16 16:31
Are you free to chat for a mo?

**Comment by aidandunsdon** [comment] 2015-07-16 20:00
UK Staging back up and running with
version 0.9
database from 21-06 with 
  null supplier ids fixed
  tokenised permissions fixed
  spree_calculators fixed

I logged in OK and viewed cart
Nick did the same

When @NickWeir63 has tested can @pmackay try to apply version 1 again

**Comment by NickWeir63** [comment] 2015-07-16 20:39
Big thanks to you both for all your work on this.
I have tested UK staging and it is all looking very good.  I can put in guest shopper orders, run reports, edit order cycles and bulk edit products.  All seems to be working fine.
I think the next steps are:
1)	to ask Paul to put v1 back onto staging
2)	I then do more testing on staging
3)	If all good we ask Paul to put the data and v1 on production
Is this right?
Thanks again both of you – what a marathon!
Cheers
Nick
PS Shall I close this issue?

**Comment by aidandunsdon** [comment] 2015-07-16 21:37
hi @NickWeir63 

are the shipping methods, payment methods ok?

**Comment by NickWeir63** [comment] 2015-07-17 08:04
Yes - when i put the guest shopper order in last night I was offered the correct shipping and payment methods and I have just checked from the admin login that i can view, edit and add new methods.  All looks good.

**Comment by pmackay** [comment] 2015-07-19 10:27
@NickWeir63 were you able to test any form of email notification with the db @aidandunsdon has just setup? 

Great work @aidandunsdon on updating it :)

**Comment by NickWeir63** [comment] 2015-07-19 19:52
Hi @pmackay the order I did on UK staging last week was a test order using a dummy email address so I didnt get a notification.  I have just logged in as nick@stroudco.org.uk and put an order in.  I have not had notification either as a shopper or to the hub admin email.  However this was only 5 minutes ago ....I will check again later.

**Comment by NickWeir63** [comment] 2015-07-19 21:04
still no confirmation emails.  I am sorry - it looks like this is not working..  Should i flag this as a bug?

**Comment by NickWeir63** [comment] 2015-07-20 10:18
I just tested the password reset option on UK staging and that is also failing to send the password reset email.

**Comment by NickWeir63** [comment] 2015-07-20 10:21
I am wondering if there is a better way out of this issue?  I spoke to @aidandunsdon last week about a conversation he had had with @pmackay about going back to the original staging database before it was merged with the Scottish data.  If this is a better option then I am willing to talk to @FiferMags and Karen at Roots Shoots and Leaves about the possibility of them re-entering all their data manually into staging then migrating across to production.  What do you all think?

**Comment by aidandunsdon** [comment] 2015-07-20 11:22
The data seems OK now - if we can sort the emails I would suggest sticking with the merged database for now.

**Comment by aidandunsdon** [comment] 2015-07-20 12:26
Hi @pmackay Have you seen any erorr log output on this? If this is db related any pointers to which tables to look at ?  Cheers A

**Comment by pmackay** [comment] 2015-07-20 22:19
Have tried updating to 1.0 on staging. Now getting this log:

```
   (0.5ms)  COMMIT
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/override_actionmailer_config
  Spree::MailMethod Load (0.4ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
  Spree::MailMethod Load (0.6ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/enable_mail_delivery/1
Cache read: spree/app_configuration/site_url
  Spree::MailMethod Load (0.6ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_auth_type/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_host/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_domain/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_port/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_auth_type/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/smtp_username/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/smtp_password/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/secure_connection_type/1
Cache read: spree/app_configuration/use_s3
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.
Cache read: spree/app_configuration/use_s3
Cache read: spree/app_configuration/attachment_styles
Cache read: spree/app_configuration/attachment_path
Cache read: spree/app_configuration/attachment_url
Cache read: spree/app_configuration/attachment_default_url
Cache read: spree/app_configuration/attachment_default_style
Cache read: spree/app_configuration/use_s3
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.
Cache read: spree/app_configuration/use_s3
Cache read: spree/app_configuration/attachment_styles
Cache read: spree/app_configuration/attachment_path
Cache read: spree/app_configuration/attachment_url
Cache read: spree/app_configuration/attachment_default_url
Cache read: spree/app_configuration/attachment_default_style
```
Its timing out after restarting the server.

**Comment by NickWeir63** [comment] 2015-07-22 06:56
I talked to @aidandunsdon about this last night.  He had just found a possible solution to do with a couple of tables that needed setting from 'production' to 'staging'.  I will ask him to let @pmackay know which tables they are.  I hope this sorts the problem in time for Karen to use production this week.  Thanks all

**Comment by aidandunsdon** [comment] 2015-07-22 09:29
Hi @pmackay 
Some of the environment flags in spree_mail_methods and spree-payments are set to production. Do you think this could be the issue with this error on staging? I could try setting them all to production - what do you think?

**Comment by pmackay** [comment] 2015-07-22 09:32
Well the site is staging though, so should everything be set to Staging?


This is presumably a problem of moving dbs between sites....

**Comment by aidandunsdon** [comment] 2015-07-22 09:46
sorry yes I meant to say set them all to staging - I will try this

**Comment by pmackay** [comment] 2015-07-22 09:50
Are you working on a copy of the staging database you've downloaded? Cos it
will have migrations to v1.0 now.

**Comment by aidandunsdon** [comment] 2015-07-22 11:08
I will update the one on staging itself

**Comment by aidandunsdon** [comment] 2015-07-22 16:26
I did the above and restarted nginx - can you check the error log

**Comment by pmackay** [comment] 2015-07-22 16:43
@aidandunsdon seems to be the same problem:

```
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/currency
Cache read: spree/app_configuration/override_actionmailer_config
  Spree::MailMethod Load (0.4ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
  Spree::MailMethod Load (0.5ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/enable_mail_delivery/1
Cache read: spree/app_configuration/site_url
  Spree::MailMethod Load (0.6ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_auth_type/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_host/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_domain/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_port/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/mail_auth_type/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/smtp_username/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/smtp_password/1
  Spree::MailMethod Load (0.3ms)  SELECT "spree_mail_methods".* FROM "spree_mail_methods" WHERE "spree_mail_methods"."environment" = 'staging' LIMIT 1
Cache read: spree/mail_method/secure_connection_type/1
Cache read: spree/app_configuration/use_s3
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.
Cache read: spree/app_configuration/use_s3
Cache read: spree/app_configuration/attachment_styles
Cache read: spree/app_configuration/attachment_path
Cache read: spree/app_configuration/attachment_url
Cache read: spree/app_configuration/attachment_default_url
Cache read: spree/app_configuration/attachment_default_style
```

**Comment by pmackay** [comment] 2015-07-22 19:46
@RohanM do you have any quick ideas what might be causing this state in our database? Recognise the pattern at all?

**Comment by aidandunsdon** [comment] 2015-07-22 20:37
Also @RohanM  can you tell me what the source_id field in spree_payments points to thanks

**Comment by RohanM** [comment] 2015-07-24 05:18
@aidandunsdon Source for spree_payments is a polymorphic field, so it can point to any model. The type of the model it points to is found in the `source_type` field.

In practice, on our data it points to whatever was used to make the payment: a `Spree::CreditCard`, a `Spree::PaypalExpressCheckout` or `nil` for cheque / direct debit payments.

**Comment by RohanM** [comment] 2015-07-24 07:24
As a quick guess, what's set in the mail methods? I notice it's reading a handful of SMTP flags, so perhaps it's trying to access an SMTP server that isn't available? 

Other than that, it's hard to tell without having a closer look. Could you send me the database dump that's causing the problem? I should be able to reproduce it and I'll see if I can work out what's happening.

**Comment by aidandunsdon** [comment] 2015-07-27 10:27
Hi @RohanM   I updated the source_id field in payments but to no avail. I have sent you a link to uk staging database dump by email. Could you take a look?  Many Thanks

**Comment by RohanM** [comment] 2015-07-28 01:06
Hi @aidandunsdon,

I loaded up that database dump, and did some investigation. Here's what I found.

```
$ rails console
irb(main):001:0> Spree::Payment.count
=> 420

irb(main):003:0> Spree::Payment.all.map &:source
NameError: uninitialized constant Spree::PaypalAccount
```

```
$ rails server
# Boots up normally

# Go to localhost:3000
PG::Error: ERROR:  relation "sessions" does not exist

$ rake db:migrate
Must supply price for variant or master.price for product./home/rohan/work/rm/off/openfoodnetwork/app/models/spree/product_decorator.rb:220:in `ensure_standard_variant'
```

```ruby
# $ rails console

vs = []
errors = []
Spree::Variant.where(is_master: true).each do |v|
  begin
    v.valid?
  rescue RuntimeError => e
    vs << v
    errors << e.message
  end
end

vs.count
# 3177

errors.uniq
# ["Must supply price for variant or master.price for product."]

Spree::Variant.where(is_master: true).count
# 3177
```

From this, I'm gathering:
- Some of the payments reference a source (`Spree::PaypalAccount`) that doesn't exist, at least in a clean checkout of the v1.0 tag.
- The database hadn't been migrated to the latest version.
- When I attempted the migration, it failed because none of the master variants had a `Spree::Price` associated, but they require one.

That doesn't look like the infinite-loop failure you were experiencing. But perhaps the invalid master variants would make a good starting point for further investigation.

Cheers,
Rohan

**Comment by aidandunsdon** [comment] 2015-07-28 08:34
Hi @RohanM The db version I have here seems to contain the prices for the master variants. Could you please confirm that you loaded the second of the two dbs that I sent yesterday i.e. the link sent at Mon, 27 Jul 2015 18:13:35.  The first link I sent earlier in the day pointed to an older version which was being tested by @pmackay on staging which I was unaware of at the time.  Really sorry for the confusion.

**Comment by RohanM** [comment] 2015-07-30 05:58
Hi @aidandunsdon,

I did indeed use the second of the two dbs that you sent yesterday. However, I discovered that the price issues I experienced last time were because I forgot to change my currency from AUD to GBP. Once I did that, things ran more smoothly:

```
$ rails server
# -> Boots up normally

# Go to localhost:300
# -> Loads fine

# Select Stroudco
# -> Shopfront loads

# Checkout
# -> Redirected home by ApplicationController#check_hub_ready_for_checkout
# This happens when hub doesn't have at least one shipping method and one available payment method.
```

So the server appears to work for me as far as I tested it, and I'm still not seeing the load-loop issue. I do see the problem with the missing Spree::PaypalAccount class, though:

```
$ rails console
irb> Spree::Payment.count
=> 423

irb> Spree::Payment.all.map &:source
NameError: uninitialized constant Spree::PaypalAccount

irb> Spree::Payment.where(source_type: 'Spree::PaypalAccount').count
   (0.6ms)  SELECT COUNT(*) FROM "spree_payments" WHERE "spree_payments"."source_type" = 'Spree::PaypalAccount'
=> 134

irb> Spree::Payment.all.select(&:valid?).count
  Spree::Payment Load (2.0ms)  SELECT "spree_payments".* FROM "spree_payments" 
=> 423
```

Seeing as I was missing the currency config, could you paste your config/application.yml (minus SECRET_TOKEN)? Any idea if there are any other changes to the config/code that I might be missing? Let me know and I'll have another shot at replicating the problem.

**Comment by pmackay** [comment] 2015-07-30 10:39
For the record, I shared the config below with @rohan this morning. Still worked for him. We're going to try testing the same process which is putting the db copy Aidan sent onto UK staging and running the migration.

```
TIMEZONE: London
# Default country for dropdowns etc.
DEFAULT_COUNTRY: United Kingdom
# Locale for translation.
LOCALE: en-GB
# Spree zone.
CHECKOUT_ZONE: Europe
CURRENCY: GBP
```

**Comment by aidandunsdon** [comment] 2015-07-30 12:18
Hi @RohanM - Could you test if email notifications are working on your instance? By doing a dummy order or the like. many Thanks

**Comment by aidandunsdon** [comment] 2015-07-30 13:36
Hi @RohanM @NickWeir63 @lin-d-hop Uk Staging is now up and running with both version 1 and the merged database. A test email also successfully tested by @pmackay. Looks like it was the source_id field in spree_payments that was at fault. I had fixed that on Monday but looks like it didn't get applied the first time - anyway it has now been applied and seems to have solved the issue. So @RohanM don't worry about testing the email on your instance after all.

**Comment by NickWeir63** [comment] 2015-07-30 18:23
Thanks everyone for all your work on this.  UK staging is looking good (although some of the product images have been replaced with a weird image - see below.
I put in several test orders including a guest shopper and received no emails.  I also tried to reset the password on Carol's account and she did not receive an email.
@pmackay what was the test email that you managed to send - see Aidan's note above?  Maybe I could try the same here and see if we can narrow down why it works for you but not for me?
![screenshot 2015-07-30 19 22 53](https://cloud.githubusercontent.com/assets/10517702/8991447/7beec7e2-36f0-11e5-8a48-7992d1dd31b6.png)

**Comment by aidandunsdon** [comment] 2015-07-30 18:44
So actually @RohanM it still seems that not all emails are working on UK staging despite a test mail being successfully sent - could you still test an order and reset a password to see if emails are sent on your instance. Thanks

**Comment by pmackay** [comment] 2015-07-30 19:11
@NickWeir63 @aidandunsdon I think the email problem is a server configuration issue (https://github.com/openfoodfoundation/ofn_deployment/issues/30) that I've been aware of for a while, but with the producer email and migration stuff I have not got round to. All emails are now managed via a delayed job daemon (except probably the Spree test mail, which confused me a bit). Hopefully if @RohanM can help with a couple of questions on that issue I can sort it out tomorrow...

**Comment by RohanM** [comment] 2015-07-31 03:45
That's correct, a delayed job worker will need to be running for emails to go out. I've replied to @pmackay's questions about setting that up. Paul, let me know if you have any other questions.

**Comment by NickWeir63** [comment] 2015-07-31 07:20
Thanks all.  @pmackay let me know when it is set up and I will test again. thanks very much N

**Comment by pmackay** [comment] 2015-07-31 13:16
@NickWeir63 would be interested if email working for you now. You might have seen a bunch come through that were stacked up.

**Comment by NickWeir63** [comment] 2015-07-31 14:04
Thanks @pmackay YES!!! it is all working.  I got masses of backlog emails and the order i put in just now came straight back with the shopper email and the hub email.  Also when i reset Carol's password her email came through immediately.  Massive thanks to @pmackay @aidandunsdon and @RohanM for all you work on this.  Can we now move this database to production?  Not massively urgent - I dont want to interrupt your flow at the hackathon.

**Closed** 2015-08-01 14:04 UTC
Labels: aus review
