### ISSUE TITLE
Groups menu tab disappears if no content

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2710] opened 2018-09-13 11:27 UTC
If an Enterprise is not in any Groups the Group shop header menu just opens blank and is pointless

Default to not having this menu item appear if the Enterprise is not in any groups

**Comment by daniellemoorhead** [comment] 2019-12-13 04:08
Duplicate of #4533

**Closed by daniellemoorhead** 2019-12-13 04:08 UTC
