### ISSUE TITLE
& symbol (Ampersand) displaying as &amp; 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3193] opened 2018-12-07 03:55 UTC
## Description
On the Inventory page and the OC index page, if a enterprise title contains an `&` then it displays as `&amp;` 
![image](https://user-images.githubusercontent.com/10843056/49626813-9aa96600-fa2f-11e8-80c1-b2cb6db202a1.png)

## Expected Behavior
An `&` should always display correctly.

## Actual Behavior
`&` shows as `&amp;` sometimes.

## Steps to Reproduce
1. Put an `&` in a enterprse name
2. View that enterprise name as a producer in Inventory or on the OC index page.

## Context
Makes some pages look buggy for users who have a title like Fox & Hare Farm

## Severity
s4

## Your Environment
Aus staging and production, Chrome, PC.

**Comment by sigmundpetersen** [comment] 2018-12-07 08:02
🙂 This definitely must be an encoding problem, because I see only correct symbols reading this issue on Slack, but in Github I see some different symbols.

**Comment by Chrisyee22** [comment] 2018-12-28 00:13
Hi, if no one else is currently working on this issue I would love to give it a go.

**Comment by kristinalim** [comment] 2018-12-28 02:35
Welcome @Chrisyee22! :slightly_smiling_face: There's no one working on this, so you may go ahead. If you have any questions, feel free to ask here or in the #dev channel on [Slack](https://openfoodnetwork.slack.com/). Looking forward to your first PR!

**Comment by laka3000** [comment] 2019-01-28 12:44
I'm currently taking a shot at this, however, there's something weird happening, probably me being a noob, but I can't pinpoint what's wrong (and I've tried many different ways to fix this, all with similar results).

Anyway, I'm calling $sanitize (from https://docs.angularjs.org/api/ngSanitize), on coordinator.name, at order_cycles_controller.js.coffee:17

Even though the names are sanitized, the page gets stuck at loading:

![image](https://user-images.githubusercontent.com/7442967/51837047-62b0f780-22e9-11e9-8bdc-4b44f1778d51.png)

console log:

![image](https://user-images.githubusercontent.com/7442967/51837142-a3107580-22e9-11e9-8b37-86fdc1e03619.png)

**Comment by sauloperez** [comment] 2019-02-12 11:38
Have you checked it is available in our arcane AngularJS version? In the Gemfile you can see we use 1.5.5. I bet that must be the problem @laka3000

**Comment by kristinalim** [comment] 2019-02-13 18:15
I updated the issue description. The `&amp;` typed was being rendered just as `&`, which is related to the issue reported.

**Comment by eelcodevlieger** [comment] 2019-05-05 11:15
Managed to reproduce this in the Inventory admin view products table:

![image](https://user-images.githubusercontent.com/44651943/57192856-1949f700-6f2d-11e9-895a-38671b668247.png)


I think this uses Angular to populate the Producer name:
'<td class='producer' ng-bind='::producersByID[product.producer_id].name'></td>'
`angular.module("admin.variantOverrides").value("producers", [{"id":8,"name":"Eel \u0026 Co"}])`

**\u0026 Is the correct unicode code for an ampersand character, so this all looks OK.**


Possible issue:
So I suspect an issue inside Angular binding the values. Quick google shows:

> Currently there is an issue with the sanitize mode, it will double encode UTF-8 characters or special characters. Recommendation: use the 'escape' strategy, until this is resolved.

https://angular-translate.github.io/docs/#/guide/19_security

Not sure if this is what is being used in the code though. I'm not familiar with Angular.

**Comment by RachL** [comment] 2020-03-06 17:49
This is fixed by #4873 :tada:

**Closed by RachL** 2020-03-06 17:49 UTC
Labels: Hacktoberfest, bug-s4, good first issue, socialissues.tech
