### ISSUE TITLE
Orders list not reloaded correctly after cancelling an order

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8806] opened 2022-01-29 00:57 UTC
## Description
We had two issues around cancelling orders recently: #8620 and #8704. Both seem to be fixed now, even though there were no dedicated pull requests for them. But now, after cancelling an order, the list of orders remains blank and needs to be reloaded manually. By clicking on the 'orders' tab the OLD list is displayed, with the cancelled order still present. Only refreshing the whole page displays the updated list. 
Before, the page automatically displayed the remaining orders after a short moment.

## Expected Behavior
When cancelling an order in the user account, the remaining orders should be displayed automatically.

## Actual Behaviour
When cancelling an order in the user account, the page displays no orders at all and the old list of orders when clicking the 'orders tab'.

## Steps to Reproduce
1. As a shop owner open an order cycle and allow orders to be changed or canceled (/admin/enterprises/shop/edit#!/shop_preferences)
2. As a customer place at least two orders
3. Cancel one of the orders in the user account
4. Observe the empty page
5. Click the 'orders' tab
6. Observe the old list of orders
7. Refresh the page
8. Observe the updated list of orders

## Animated Gif/Screenshot

https://user-images.githubusercontent.com/1790176/151640167-e6219058-4d4c-4852-b8b9-6b9a0cefce84.mp4

## Workaround
Reload manually.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v4.1.14
* Browser name and version: Firefox 96.0 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS Desktop

**Comment by alannaemmrie** [comment] 2022-03-22 00:36
Hi,
I am interested in working on this! Sounds like the database is getting updated but not the UI. I am working on recreating the issue, but am wondering how I can access customer/shop owner accounts in order to do so? I am currently signed in using the administrator account listed in the setup guide. Should I create my own shop owner/customer accounts for testing, or are there existing ones I can use? Thanks!

**Comment by drummer83** [comment] 2022-03-22 09:44
Hi Alanna (@alannaemmrie),
so great to have you here! Looking forward to your contributions.
I would recommend to create your own accounts because it is a great way to learn about the software and you know exactly what is going on with those accounts. 
If you don't want to do that, you could add yourself to existing enterprises as a manager. Here is how to do that: https://guide.openfoodnetwork.org/basic-features/enterprise-profile/transfer-ownership
Probably you can recreate the issue when logged in as super admin (as mentioned in the setup guide) as well. You would only need to create a new customer account then.

**Comment by alannaemmrie** [comment] 2022-03-23 01:26
Awesome! I was able to recreate the behavior pretty easily and received "order cancelled" emails.  I noticed that the cancelled orders moved into the "past orders" section of the page - is this the correct final state of the page? (wasn't sure if "past orders" needed to be fulfilled) I am new-ish to Ruby/RoR so I plan on getting familiarized for a little then starting on a solution!

**Comment by drummer83** [comment] 2022-03-23 08:47
Hi @alannaemmrie, cool! 👍🏻
Yes, moving the order to "past orders" is correct.
The problem covered in this issue is that the page remains empty after the cancellation, shows the OLD list when clicking on orders and that the page needs to be refreshed manually.

**Comment by alannaemmrie** [comment] 2022-04-09 14:58
Hi,
I noticed that the blank-page behavior after order cancellation was caused by line 102 ("redirect_to request.referer || main_app.order_path(order)") in app\controllers\spree\orders_controller.rb.  

I fixed the blank-page behavior by changing the line to always redirect to the main app order path.  I noticed that this now gives the same behavior as if you were to cancel the order from navigating to the order and then clicking the cancel order button.  The file I attached has screenshots that show the new flow of the cancellation process.

My question now is if this is the end behavior that you guys would prefer, or do you want to stay on the accounts/orders page after cancellation? (i.e., instead of routing to orders/{order_number} route to account/orders) I wasn't sure since this behavior is now the same as the other way that you can cancel orders which would make sense to me, but wouldn't be exactly the same as the original issue.  Just let me know!
[order cancellation flow.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/8457177/order.cancellation.flow.pdf)

**Comment by drummer83** [comment] 2022-04-11 15:47
Hi @alannaemmrie, 
Thanks for looking at this in detail. In my opinion routing to account/orders would be the best approach here. I get your point though. But I think it is okay that if you cancel the order on the orders/{order-number} page you remain on that page and if you cancel the order on the account/orders page you will remain there. Does that make sense?

I think it would be great if we had any kind of confirmation after cancelling the order and a 'status' column in the 'Past orders' table indicating the 'Confirmed' or 'Cancelled' state would help as well. These are separate issues though.

**Comment by alannaemmrie** [comment] 2022-04-11 16:17
Okay @drummer83, sounds great! I can definitely keep it to route to the same accounts/orders, just wanted an opinion.  As far as the confirmation, I think I'll get this issue fixed and submitted and then maybe I can add some kind of feedback to the user (maybe like an "order canceled!" blurb or something).

**Comment by drummer83** [comment] 2022-04-11 16:21
Yes, that would be great! I have just opened https://github.com/openfoodfoundation/wishlist/issues/216 to discuss solutions for the required feedback.

**Comment by SamKnightGit** [comment] 2022-06-09 21:19
Hey @alannaemmrie! 
It has been a while since there have been any updates here and was wondering whether you created a commit (on a local fork maybe) to fix this issue? I am happy to throw together a commit given the useful context you provided above.

**Comment by saunmanoj888** [comment] 2022-07-17 18:49
hello @drummer83 
Seems there has been no update on this issue lately. Can I pick this issue and work on it?

**Comment by drummer83** [comment] 2022-07-17 22:02
Of course, @saunmanoj888! This would be great! 
Let us know if any requirements from the discussion above are unclear. Always better to ask before implementing! 😉
I have assigned the issue to you! 💪🏻

**Comment by binarygit** [comment] 2022-07-18 09:47
Hey @saunmanoj888 @drummer83 I was just browsing through the issue list and realized that this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/9390 closes this issue.

**Comment by jibees** [comment] 2022-07-18 10:05
`cable_ready` comes from ReactiveRails approach, mainly discussed here: https://community.openfoodnetwork.org/t/reactive-rails/2125

Hope this helps

**Comment by saunmanoj888** [comment] 2022-07-18 11:28
> Hey @saunmanoj888 @drummer83 I was just browsing through the issue list and realized that this PR #9390 closes this issue.

thanks @binarygit 
I can look into some other issues if this one is resolved in #9390
cc @drummer83

**Closed** 2022-08-02 08:10 UTC
Labels: good first issue, bug-s4
