### ISSUE TITLE
Products Sold Exceed Max Stock Level

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5300] opened 2020-04-24 09:22 UTC
## Description

Large UK Hub reported that for their OC 20/04/20 :
1) at least two producers found orders for products in their order cycle summaries which exceeded the max. stock level they placed.
These producers were Hester's Harvest and Hoe Made Acre
2) customer's received invoices containing products listed as purchased with zero quantity:
R781345776 Asparagus Green (250g) Hester's Harvest
R877041463 Sausages- usually frozen- Pork Honey Roast and Mustard 500g Trehill Farm
3) producer found products were left with negative stock levels after the order cycle (Asparagus for Hester's Harvest had stock of -3: initial stock level was 50, OC supplier report says 53 were sold)

There may be other examples not yet found.

## Expected Behavior

Product with finite stock level should not be available for sale once maximum capacity has been reached.

## Actual Behaviour

Finite stock level ('in stock') exceeded during an order cycle.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

![HHarvest](https://user-images.githubusercontent.com/45104035/80196301-19974280-8615-11ea-8e2f-88848683212e.jpg)
![R877](https://user-images.githubusercontent.com/45104035/80196492-6713af80-8615-11ea-9722-94d3c47482e9.jpg)
![R781](https://user-images.githubusercontent.com/45104035/80196510-6e3abd80-8615-11ea-954e-67627f8de8db.jpg)

## Severity

bug S2
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment] 2020-04-24 09:24
![](https://github.trello.services/images/mini-trello-icon.png) [Tamar negative stock](https://trello.com/c/PLpYAc75/944-tamar-negative-stock)

**Comment by luisramos0** [comment] 2020-04-24 10:57
I will not have time to look into this any further until Monday. Maybe another dev will?

I just looked at the stock movement in the DB, it looks like there was a rush to the asparguss, yes. But movements were a few seconds apart... maybe enough to make our concurrency solution to break...

![image](https://user-images.githubusercontent.com/1640378/80205555-b7ddd500-8622-11ea-9d90-ecd28f6faa57.png)

**Comment by tschumilas** [comment] 2020-04-25 20:39
Just had a report from a hub that also had this happen.,  Getting details from her - but she says it was a really popular product -  it happended last week and this week
I'll get details here.

**Comment by emilyjeanrogers** [comment] 2020-05-08 01:12
We received an email from Autarky Farms on April 21st about an instance of overselling that they had experienced. Form the customer "I uploaded only 10 tomato bags but managed to sell 20 which seemed to maybe happen when it was in someone's cart but appeared to be available?"

Still waiting for specific order details but the Order cycle was coordinated by North Arm Farms, OC = "Orders for 22/4/20"and the product was wither Tomatoes Large or Tomatoes Tomatoes 400g

**Comment by luisramos0** [comment] 2020-05-08 07:22
ok, thanks for the info :+1:

In the orders of that OC now they dont have any "Tomatoes - 400g". They have 13 "Tomatoes - Large" in completed orders in that OC and 3 of them are in 3 orders in the cart state.
So, only 13 were sold in this OC.

The checkouts were not very close, only the first two ones with a difference of 30 secs, the last checkouts of Tomatoes were several hours apart.

They sold a few more items in OC "Orders for 6/5/20" and now the stock is zero.

We dont have a way to see when did the stock reach zero and what orders should not have been placed by OFN...
Maybe we need more logging here so we can see what was the stock available for the product at the time of checkout.

**Comment by mbudm** [comment] 2020-05-27 00:23
> Maybe we need more logging here so we can see what was the stock available for the product at the time of checkout.

I can highly recommend structured logging to solve these sorts of problems (providing context to the logged event). I've used honeycomb.io a lot for this.

**Comment by luisramos0** [comment] 2020-05-27 09:08
Interesting, honeycomb is an alternative to ELK, right? We only have bugsnag (it's serving us incredibly well).
Bugsnag supports metada (end of [this page](https://docs.bugsnag.com/platforms/javascript/configuration-options/#metadata)) but it's not the same as having a full distributed logging infra like ELK. I think @Matt-Yorkley is familiar with ELK. I wonder if there's a case for us to switch our logs to one of these systems in OFN.
We have [this nice 3 years old post](https://community.openfoodnetwork.org/t/better-logging-for-helping-to-resolve-production-issues/786) about the topic in discourse.

**Comment by Matt-Yorkley** [comment] 2020-05-27 10:07
I think we can use ELK when we get to Rails 4...

**Comment by RachL** [comment] 2020-07-29 16:25
@luisramos0 do you know what we can do with this issue? Are we closing it or are there bits we can keep as an s3?

**Comment by luisramos0** [comment] 2020-07-29 18:41
Hello @RachL this issue is on my todo list. I want to run some quick tests and check #5784 
I'll get back here soon and share my findings.
I think this will be an S3 to convert the snail to an error message. I believe the user is now seeing a snail when buying at the same item as another user at the same time.

**Comment by luisramos0** [comment] 2020-08-03 16:25
We cant really replicate this problem here....

#5406 is a step forward for sure BUT

actually, in #5406 I found that the auto test we have for concurrent checkout is not really working :face_with_head_bandage: 
https://github.com/openfoodfoundation/openfoodnetwork/pull/5406#issuecomment-648883511

and @sauloperez comment is a very solid theory that says that the solution in #5406 will not be successful in stopping this issue here #5300 from happening :-(
https://github.com/openfoodfoundation/openfoodnetwork/pull/5406#issuecomment-659480718
But maybe, I say maybe, #5406 did make this #5300 less likely to occur....
Based on this we could wait for the next occurrence of this issue...
Or we can continue to work on this, following @sauloperez's suggestion above (change the form to include lock_version).

I am not sure. @sauloperez what do you think? Do you know how to do the lock_version trick on the web form? If it's an easy thing I'd go for it now.

**Comment by sauloperez** [comment] 2020-08-04 06:13
sure, it's just about adding a [hidden form field](https://apidock.com/rails/v4.0.2/ActionView/Helpers/FormHelper/hidden_field) so we provide `lock_version` to the backend. Re the test, I'm not sure it's worth all the effort that would require turning our single-process tests into something that mimics a production scenario.

**Comment by RachL** [comment] 2020-08-04 07:17
Then let's do this? :-)

In regular times I would have suggested to not handle it now. The problem is, the next time it will occur it will be again because we have a massive flow of users hitting our shops at the same time. It will produce even more stress to have to handle this under a flow of other bugs. Also we know how to reproduce it now, so I would take care of it now as we know how to do it.
Thoughts?

**Comment by sauloperez** [comment] 2020-08-04 07:43
Agree. The way I see it is that so far we have only invested resources and until we don't finish that last step we won't get any returns out of it. So far, it's only cost.

**Comment by Matt-Yorkley** [comment] 2020-08-07 14:59
The `lock_version` attribute is on `StockItem` though, right? Wouldn't we need to add a hidden field for every stock item of every variant in the cart?

**Comment by Matt-Yorkley** [comment] 2020-08-07 15:26
The hidden field trick seems to be aimed at updating a single record, but here we're updating multiple records...

**Comment by Matt-Yorkley** [comment] 2020-08-07 15:39
All we need is a little bit of Optimistic Concurrency Control... how hard could it be? :trollface::trollface:

**Comment by luisramos0** [comment] 2020-08-07 15:43
Do you understand if the object needs to be in the form?
Maybe adding this will work even if the form is for some other object?
hidden_field(:stock_item, :count_on_hand)

**Comment by Matt-Yorkley** [comment] 2020-08-07 15:51
So I think the "vanilla" Optimistic Locking applies to all the fields of a single record, but here we're dealing with multiple associated objects of associated objects of associated objects, eg: `stock_items` of `variants` of `line_items`. In this case we're only concerned with the `spree_stock_items.count_on_hand` field.

There's lots of moving parts in the checkout process... I wonder at which point we reduce the stock levels? After payment?

**Comment by luisramos0** [comment] 2020-08-07 16:06
>>>> There's lots of moving parts in the checkout process, it's like an avalanche. I wonder at which point we reduce the stock levels? After payment?

I am taking some time off to finish bye bye spree. IT will make a huge difference as we will be able to simplify some of the craziness :+1: 

In OrderInventory.verify it's where the stock is unstock/restock, it's called on the line_item before_save callback update_inventory.
But this unstocking will only happen (OrderInventory#74) if the order is complete. So, the unstock happens the first time the line is saved after the order is marked as complete. I think that will be on the order.finalize! (which is a checkout workflow callback after complete). (this complexity is nuts!)

**Comment by Matt-Yorkley** [comment] 2020-08-07 16:12
Thanks for the heads-up on `OrderInventory.verify` :smile: I see a few other bits in `Order.finaize!` and `Shipment.finalize!` as well :+1:

**Comment by Matt-Yorkley** [comment] 2020-08-07 16:20
Yeah so I think traditional locking isn't going to help us here in the murky depths of the checkout process. For example, if we've already taken payment and completed the order, and _then_ we do some lock-clash-rescuing on stock levels, we can't really "abort" the sale nicely at that point, right? Given an example scenario where two users order the last carrot at the same time. The idea with optimistic locking is that you can rescue from it (before making lots of database updates) and give the user nice feedback, or retry. The order and lots of associated records are already past that point by the time we get to reducing the stock levels...

**Comment by Matt-Yorkley** [comment] 2020-08-07 16:24
But maybe we can do something at the start of the checkout process that will achieve a similar result...

**Comment by Matt-Yorkley** [comment] 2020-08-07 16:33
I think we do a quick check of stock levels at the point the checkout page is first loaded, but here we're looking at the point that the checkout form is submitted. There's potentially quite a large time window there between page load and form submission, and if two users are checking out at roughly the same time, they will both get processed. 

So I think we need a quick stock-check at the point the checkout is _submitted_ but before the order is processed, and it needs to be able to handle concurrency...

**Comment by luisramos0** [comment] 2020-08-07 16:35
"the last carrot" :rofl: 

yeah, we can make a stock check at the beginning of checkout_controller#update.
Or we can go for a simple order.cancel if we detect a clash when moving the stock? Maybe easier?

How do we detect clashes?

**Comment by Matt-Yorkley** [comment] 2020-08-07 16:39
I don't like the idea of taking payment, completing the order, then immediately cancelling it...

> How do we detect clashes?

That's the fun bit :wink:

I'll have a play around with it. Maybe it's not as complicated as it sounds, and we're just doing a stock check...

**Comment by luisramos0** [comment] 2020-08-07 16:40
With the last PR I thought it would blow up and we could just recover from that.
According to @sauloperez the PR didnt help, are we saying the stock item will go to negative without blowing up? I dont think that's possible with the validation we have now... what do you think will happen?

I am now thinking, if this is not an easy fix, we could just leave as is and we may not have a problem now. I still believe it will blow up for the second customer and the customer will see the generic checkout error message...

**Comment by Matt-Yorkley** [comment] 2020-08-07 16:57
Ah, I see! I guess it blows up then... but after the payment has been taken? I'll give it a try in two browsers and see what happens. I think a stock check when the checkout is submitted would help.

**Comment by Matt-Yorkley** [comment] 2020-08-07 17:18
Well I've just tried replicating this in master 5 times, and it actually looks pretty good. Each time one completed and the other was bounced to the cart page with a nice message and the "out of stock" feedback. 

May be we can close this for now and reopen if it reoccurs?

![Screenshot from 2020-08-07 18-14-45](https://user-images.githubusercontent.com/9029026/89671106-b343e080-d8e2-11ea-92af-437f1a24cf03.png)

**Comment by luisramos0** [comment] 2020-08-07 17:29
yeah, I'd close for now. We can come back to it if it does happen again.
In your tests, do you know if the stock_item.count_on_hand validation was triggered? Because I think there is a stock validation somewhere in the checkout process and that will be a different code path when it fails.

**Comment by sauloperez** [comment] 2020-09-08 09:17
so then, we added the `lock_version` in https://github.com/openfoodfoundation/openfoodnetwork/pull/5406 but is not having any effect :sweat_smile: I'd say we should remove it so we don't cause the false impression to future devs that concurrency is handled that way.

**Comment by luisramos0** [comment] 2020-09-08 09:35
Why do you say it's not having any effect? I'd say we need to build on top of it, not remove.

**Comment by sauloperez** [comment] 2020-09-08 10:04
> Why do you say it's not having any effect?

see https://github.com/openfoodfoundation/openfoodnetwork/pull/5406#issuecomment-659480718.

From what I understood with this discussion is that the existing mechanism is good enough. We have Rails' mechanism half-implemented and we don't plan on continuing it, at least for now :shrug:

**Comment by luisramos0** [comment] 2020-09-17 10:23
I am not sure I follow you here: in one comment you say "is not having any effect" and afterwards you say "the existing mechanism is good enough". I wonder if you are referring to the same lock_version mechanism on stock_items.

I think the current state is "we dont know if it is working or not" and we agree we will leave like this until we see trouble again :-)

**Comment by chezaorchard** [comment] 2020-10-20 02:25
@luisramos0 we have a customer [order number R533682527] who has received an order confirmation email listing a product with quantity 0 and value $0 exactly as above bug - see screen shot. 

![Xnip2020-10-20_13-22-14](https://user-images.githubusercontent.com/68367600/96532334-69f71080-12d7-11eb-9829-3e2fac1b3d13.png)

The producer [2286] has confirmed they do not have a negative value in their stock numbers for the product in question.

I'm not sure if this should reopen, or if I should log a new bug - please advise :)

**Comment by lbwright22** [comment] 2020-11-23 11:39
Orders placed on 18th November (ie after Bye Bye Spree release) show evidence of this competitive stock level issue again.

Hub: Aberystwyth Food Hub 
Order Cycle: 21st November, Aberystwyth

There are several orders effected in the same manner as I found in April. ie customer invoice states products with zero quantity and zeros are also present in reports.

example is order R735665606
![invoicestockzerocustomer](https://user-images.githubusercontent.com/45104035/99957856-40bb1b80-2d80-11eb-8eac-f87f8adbd657.jpg)

The caramel shortbread, marmalade and sourdough brownie are not in the customer's order though.

The presence of the items with zero quantity in reports leads to user confusement (and they contact the support team)

**Comment by lin-d-hop** [comment] 2020-11-23 20:47
It seems this is another case of items not being held during checkout. This is increasing in frequency due to the additional load with lockdown and Christmas warm up.

We're talking about some significant work on this general area of issues in Product Curation on 30/11.

For now I'll close this again and we can continue to comment as and when it pops up again.

**Closed by lin-d-hop** 2020-11-23 20:47 UTC
Labels: bug-s2
