### ISSUE TITLE
Out-of-stock items shown in shop front

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4020] opened 2019-07-09 00:28 UTC
## Description

When an item goes out of stock, it still shows in the shop front. This is not the case when you update the stock as admin. It only happens if the item is bought through the shop front.

## Expected Behavior

If an item is NOT set to on demand, and is out of stock (which includes both 0 and negative numbers) it should NOT show in shop.

## Actual Behaviour

It appears in the shop and doesn't display out of stock message until customer tries to add to cart. Then shows as negative item in shop if the item has negative stock (0 otherwise).

## Steps to Reproduce

1. Open an order cycle with an item with stock `1`.
2. Add that item to your cart and check out.
3. Click on continue shopping.

## Animated Gif/Screenshot

 In this example the stock went down to `-1`:

This item is showing in the shop
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/e5ea2d8b-bf12-41a5-a981-2fa6c14e961d)

When I try to add it to my cart I see this error message
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/c2dfa69d-09ed-4206-afe4-1524c67b8bf9)

and then the stock is shown on the shop page as if it is in my order
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/d9637aa3-c306-4243-aab4-bb08219e38b2)

I can place the order and it is correct i.e. doesn't put -1 cheese in my order or reduce what I pay
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/74313ea8-699a-4788-8dcf-a7464907cca4)

## Context

This was discovered when investigating #3925 but it's not limited to that bug. It's also mentioned in #4018.

## Severity

s3: a feature is broken but there is a workaround

The workaround is to adjust the stock as admin or refresh the cache.

## Your Environment

* Version used: v2

## Possible Fix

I observed that the shop is still retrieving the old/cached products.json file. We have to either refresh the cache or retrieve the stock levels in a different way. This was probably introduced by v2.

**Comment by RachL** [comment] 2019-07-19 13:22
@mkllnk I just tried this scenario on a product sold through inventory and I couldn't reproduce it.

I thought it was worth mentioning. This is only happening for product sold straight from the product catalog.

**Comment by luisramos0** [comment] 2019-08-16 16:58
@mkllnk I cant replicate the part that you manage to put the item in the cart and checkout.
All I can see is that after the checkout of the last item, I go back to the product list and the page still shows the product, but if I add quantity to it I see the "reduced stock" warning after a second and cant see it in the cart.

So, checkout is not updating cache correctly even for this basic test with Freddo's Carrots with on_hand 1.

There were discussions of removing the cache system all together with the pagination solutions we are putting in place both in the shopfront and the admin side...

**Comment by luisramos0** [comment] 2019-08-16 17:03
upgrading to S2 as I suspect this is a duplicate of #4143

**Comment by luisramos0** [comment] 2019-08-16 19:18
ok, I have created a spec to test what I can replicate locally, it fails #4162

I am not sure I'll have time to fix it before holidays but it's a good start ;-)

**Closed** 2019-08-25 20:52 UTC
Labels: bug-s2
