### ISSUE TITLE
Standing Orders - improved order cycle duplication

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1052] opened 2016-06-21 23:18 UTC
### Overview

Order Cycles can currently be "cloned", which creates a brand new OC with identical settings.

The proposed Standing Orders model requires that Order Cycles exist into the future, as far as the shop owner wants customers to be allowed to place/cancel and ultimately edit their future orders. 

In light of this, the capability to copy the list of products, fees and tags from between two existing order cycles becomes desirable.
### Tasks
- [ ] Add a "Copy settings from..." button to the Order Cycles edit interface (potentially in the "Advanced Settings" section?), accessible only to coordinators
- [ ] When this button is clicked, the user is asked to select an order cycle to copy settings from, and on confirmation runs a "copy" action to duplicate all properties duplicated by the "clone" action

**Comment by daniellemoorhead** [comment] 2016-07-01 00:55
@stveep this is your first foray into the world of standing orders work. Have a read of this and if you've got any questions speak with @oeoeaio. Cheers!

**Comment by stveep** [comment] 2016-07-05 07:11
Getting on ok with this so far, just one quick Q - if the existing OC already has products, do we want to overwrite or add?

**Comment by oeoeaio** [comment] 2016-07-08 00:27
Hi @stveep, I think overwrite. From my perspective, the desired functionality is that the 'destination' OC looks exactly the same as the 'source' OC one the copy action has been completed. So I think it is basically just a wipe and rewrite. Does that sound ok?

**Comment by stveep** [comment] 2016-07-17 18:00
Hi @oeoeaio @daniellemoorhead I've had a go at this and think it's nearly there. I've broken something on the OC page though and can't figure it out - think it's probably something quite simple though so maybe one of you could take a look?

It all works ok for me, but only when using cached requests (if I have the debugger open, I need to step over the xhr errors below). Once I disable caching (in Chrome devtools) I can only see the bare `{{ angular bindings }}` so the page does not have data in it (the same happens when running the specs). I have some xhr errors that arise at a line like this `xhr.send(isUndefined(post) ? null : post);`. All the requests on the page now throw these errors (and all their associated specs fail), even the ones I didn't add, so I have probably just generally messed up something around the resource requests.

I also see an error in the server log but don't know if it's related (I think because I don't have some assets locally, I quite often see stuff like this):

```
Started GET "/assets/ofn_logo_black.png" for 127.0.0.1 at 2016-07-17 18:27:13 +0100
Served asset /ofn_logo_black.png - 404 Not Found (20ms)
Processing by CmsContentController#render_html as PNG
  Parameters: {"cms_path"=>"assets/ofn_logo_black"}
   (0.7ms)  SELECT COUNT(*) FROM "cms_sites" 
  Cms::Site Load (0.5ms)  SELECT "cms_sites".* FROM "cms_sites" LIMIT 1
  Cms::Page Load (1.0ms)  SELECT "cms_pages".* FROM "cms_pages" WHERE "cms_pages"."site_id" = 1 AND "cms_pages"."is_published" = 't' AND "cms_pages"."full_path" = '/assets/ofn_logo_black' ORDER BY cms_pages.position LIMIT 1
  Cms::Page Load (0.8ms)  SELECT "cms_pages".* FROM "cms_pages" WHERE "cms_pages"."site_id" = 1 AND "cms_pages"."is_published" = 't' AND "cms_pages"."full_path" = '/404' ORDER BY cms_pages.position LIMIT 1
Completed 404 Not Found in 12.6ms

ActionController::RoutingError (Page Not Found):
  comfortable_mexican_sofa (1.6.24) app/controllers/cms_content_controller.rb:69:in `rescue in load_cms_page'
  comfortable_mexican_sofa (1.6.24) app/controllers/cms_content_controller.rb:62:in `load_cms_page'
  activesupport (3.2.21) lib/active_support/callbacks.rb:484:in `_run__105374043269884429__process_action__906531159800899288__callbacks'
...
```

A few details on the implementation:

- New instance method `copy_settings_from` that takes oc to be copied as an argument [copy products from may be a better name and I have been a bit inconsistent with naming some methods and functions - will fix this].
- This and the clone method now delegate to a class method to DRY up the actual copying.
- Existing exchanges are cleared as part of the `copy_settings_from` method (i.e. overwrites).
- Called by POST to `/admin/order_cycles/:id/copy_settings` and passing `oc_to_copy` id as param.
- New ng controller `AdminAdvancedOrderCyclesCtrl` to allow selection of oc to copy from under advanced settings. Bootstrapping of the `admin.orderCycles` moved so it's before the advanced dropdown (which wasn't previously contained within the app)
- Copying fires an event that prompts update of the order cycle details on the page (by the other controller - needs to be added for the alternative "simple controller" too I think).

You can find it on my fork here: https://github.com/stveep/openfoodnetwork/tree/1067-so-oc-duplication
e.g. spec fails: https://travis-ci.org/stveep/openfoodnetwork/jobs/145380183

Currently several of the order cycle feature specs fail as above.

**Comment by daniellemoorhead** [comment] 2016-08-03 00:40
@stveep have you got this ready in a PR for code review and testing by @oeoeaio and @sstead?

**Comment by stveep** [comment] 2016-08-03 06:28
PR #1111 

There is also an authentication problem that I'm not sure how to fix - it works for a [super] admin user but not for a regular user at the moment. As noted on the PR, I couldn't get my feature test working (it's there but set to "pending") and this might be why. I won't have time to look until the weekend but it's probably an easy fix if you could have a look @oeoeaio ?

**Comment by mkllnk** [comment] 2018-05-29 23:47
The connected PR has been closed. Rob wants to pick this up again once standing orders are launched. I'm moving this back to dev ready.

**Comment by myriamboure** [comment] 2018-10-22 18:32
If we go back to the need, what is it? The need is to enable hub manager to create easily a batch of OC attached to a schedule. To answer that need there are multiple possibilities:
- from OC page duplicate an OC, and when duplicating make sure schedules are also duplicated (not the case for now). So hub manager could duplicate in a row and just update name and open/close date by bulk in the main OC page.
- assume that the hub manager has created "empty or almost empty" OC to be able to create the schedule, and allow her to fill in the OC quickly by importing settings / content from other OCs.
- maybe it's from the "shedule" page that we should be able to "create OCs in batch"
- ...

I would say that given the scoped need described here https://community.openfoodnetwork.org/t/a-hub-manager-can-setup-an-automatic-standing-order-for-a-registered-customer/1462 this issue is out of scope so I will just close it for now.

When we get feedbacks from users saying it's not practical, we can open a wishlist about the need and investigate potential solutions and decide.
We don't know if the need is there, for now the users in France who are using it only create one OC in advance and create the schedule with it, and then create OCs on the flow. But other users might have other behaviors of course, so let's see what users would like to improve first.

@kirstenalarsen I remember you suggested it also in some other GH issue some time ago, so if you have already feedbacks from users about it, please open a wishlist item and we can happily move it forward :-)

**Comment by myriamboure** [comment] 2018-10-22 18:33
@daniellemoorhead if you disagree just SHOUT (gently of course ;-))

**Closed by myriamboure** 2018-10-22 18:32 UTC

**Comment by kirstenalarsen** [comment] 2018-10-23 06:07
I think this is going to be a big issue for village centres - not because of subscriptions but because they are going to want order cycle every day and eventually lots of outgoing hubs - it will quickly become unworkable to open and manually change the delivery/pick-up info in each. But I will create a wishlist when confirmed :)

**Comment by daniellemoorhead** [comment] 2018-10-26 03:32
You're the standing orders boss @myriamboure, I will leave it to you to decide what's needed or not ;)

**Comment by myriamboure** [comment] 2018-11-01 00:21
I think it should be separate and not included in standing order, but I can see the need and it definitely deserve a deeper thinking and UX reflexion a bit broader than just "make it easier to duplicate an OC"... so yes @kirstenalarsen open a wishlist and let's start to understand the need, and start some refined inception and see if we can prioritize sooner rather than later in the tons of things we want to priroitize :-) If you move forward inception chances are higher than the project move forward quicker :-)
