### ISSUE TITLE
[Split Checkout] Failed to reach checkout

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/openfoodnetwork#9131] opened 2022-04-26 11:26 UTC
## Description

Using split checkout for Hub 'Helston Food Hub' in UK with user 930.

When I clicked checkout I got a 500 error.

I then logged out, recreated the same basket and tried to checkout. This time I was redirect to the checkout login screen. I logged in here and successfully reached checkout.

I tried 4 times to replicate the issue with different users following the same steps (see Steps to Reproduce for more details). I could not.

Here is the correspending Bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61addaf4e787680007fb5221?event_id=6267ca31009351914ca80000&i=sk&m=nw

This bugsnag is being triggered a few times around. @filipefurtad0 has experienced and wrote [this issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/9112#issuecomment-1103738553), however when I hit this error I didn't get to see the checkout screen first.

## Expected Behavior

I should have been directed to the checkout pages

## Actual Behaviour

500 error

## Steps to Reproduce

I have not been able to reproduce this.

Steps I took:
- I created myself as a customer just before checking out. 
- I had never shopped with this hub before. No cookies or anything on the first attempt.
- I had a tag for a negative fee associated with the user. 

With 3 different users I tried to replicate aspects of the issue, but never found the 500 on clicking checkout. 

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by jibees** [comment] 2022-04-26 11:47
_Technical note:_ 
It seems to be something around "shipments". I dug around yesterday, and couldn't find anything relevant. Maybe it's worth @mkllnk taking a look at.

**Comment by sigmundpetersen** [comment] 2022-04-26 11:53
A lot of discussion around shipping methods and checkout in this S3 #8219
Could it be related to some of those scenarios?

**Comment by sigmundpetersen** [comment] 2022-04-26 11:55
A lot of discussion on shipping methods and checkout in this S3 #8219
Could it be related to some of those scenarios?

**Comment by jibees** [comment] 2022-04-27 12:07
This (https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61addaf4e787680007fb5221?event_id=6267ca31009351914ca80000&i=sk&m=nw) error come means that nor shipping method is linked to the current order.
Why? It seems that because order has no shipments

https://github.com/openfoodfoundation/openfoodnetwork/blob/6262dc3a2e7dbbe09bebc2b0b64d2ff0ffb6bbc8/app/models/concerns/order_shipment.rb#L27-L31

Will try to debug/look at it this afternoon, but maybe I'll need some help.

**Comment by jibees** [comment] 2022-04-28 15:17
I didn't manage to resolve (or even improve) this one. 
@mkllnk if you could spend some time on it, I'll be grateful 😇

**Comment by filipefurtad0** [comment] 2022-04-29 15:05
So, it seems that starting from a "healthy" account - one which can checkout, on split checkout:
- starting from a fresh order
- choosing stripe SCA payment method, and adding the card 4000000000000002:

![image](https://user-images.githubusercontent.com/49817236/165969763-4acd610d-b2cf-436e-9cae-f88d25a7c46a.png)

- moving to order summary, and clicking "Complete order"
- triggers this bugsnag error (user sees the Snail):

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60db6e8f3ca5f50007ee621a?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging&event_id=626bf5090093ec1ab4bc0000

- at this point the order is left in `state = confirmation`

```
   id   |   number   | item_total | total |    state     | adjustment_total | user_id |         created_at         |         updated_at         | completed_at | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |                 email                 | special_instructions | distributor_id | order_cycle_id | currency | last_ip_address | customer_id | created_by_id | included_tax_total | additional_tax_total 
--------+------------+------------+-------+--------------+------------------+---------+----------------------------+----------------------------+--------------+-----------------+-----------------+---------------+----------------+---------------+---------------------------------------+----------------------+----------------+----------------+----------+-----------------+-------------+---------------+--------------------+----------------------
 454918 | R758126824 |       1.00 |  2.00 | confirmation |             1.00 |    6981 | 2022-04-29 14:23:01.236962 | 2022-04-29 14:24:33.267388 |              |          106027 |          106028 |          0.00 |                |               | xxxxxxxx+ghanoujc@protonmail.com      |                      |           1819 |           3577 | CAD      | 188.251.215.147 |        8216 |          6981 |               0.00 |                 0.00

```
- navigating back, and re-attempting to checkout triggers the error on `app/views/split_checkout/_summary.html.haml:48`, `= @order.shipping_method.name`, each time the customer hits Checkout on cart tab, still while on the `/shop` page, the user sees a snail without seeing any checkout step:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/61addaf4e787680007fb5221?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging&event_id=626bf5220093f6206f290000

**Some additional thoughts:**

Checking out with cards which were previously saved but:
- have expired in the meantime
- generate a declined error from the bank
May trigger this scenario as well...

In principle, this might happen with Paypal as well - this seems to have been reproduced [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9112#issuecomment-1103738553)

**Comment by jibees** [comment] 2022-05-02 08:12
Thanks **a lot** for your investigation @filipefurtad0 ! It's worth its weight in gold!

As: 
 - your scenario comes from a not handled `Spree::Core::GatewayError`
 - and, https://github.com/openfoodfoundation/openfoodnetwork/pull/9057 is here to catch and handle this exception ; and has been reviewed by @mkllnk 

I'd propose to push #9057 into `Test Ready` and see if this could solve this issue too.


What do you think?

**Comment by filipefurtad0** [comment] 2022-05-02 10:09
> I'd propose to push https://github.com/openfoodfoundation/openfoodnetwork/pull/9057 into Test Ready and see if this could solve this issue too.

:100:

**Comment by filipefurtad0** [comment] 2022-05-06 17:41
I keep bumping into this one lately. There are several scenarios triggering it. More findings:

- #9057 indeed prevents one scenario which leads to this issue :+1
- race conditions however, i.e., an order which is not successfully completed (see #9158) can lead to this scenario as well, _but only_ if if the customer gives up the order and clicks "Empty cart", on the `/cart` page.

The error is always the same: `app/views/split_checkout/_summary.html.haml:48`, which as you already pointed out @jibees [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/9131#issuecomment-1110920978) relates to missing shipments :+1: 

If I understand correctly, emptying the cart deletes a bunch of things, including shipments (but not the order itself):

https://github.com/openfoodfoundation/openfoodnetwork/blob/edc0520ce39be4bc5056293691b8378d0e14c331/app/models/spree/order.rb#L430-L435

A shipment is created once the `/summary` page is reached, before the user actually confirms the order and clicks "Complete order":

![image](https://user-images.githubusercontent.com/49817236/167182177-6cec67d0-0408-4ce4-8bf2-31d3c18f4067.png)

The user gets redirected to `/summary` because the order is left in confirmation state:

https://github.com/openfoodfoundation/openfoodnetwork/blob/edc0520ce39be4bc5056293691b8378d0e14c331/app/controllers/split_checkout_controller.rb#L132-L133

I guess my conclusion so far is: Redirected to /summary but no shipment, no shipping method, no page -> :boom: 

I'm not sure what's the best way to fix this. Some possibilities:

**on the order**
- clicking the `empty cart` brings the order back to `cart` state
- clicking the `empty cart` destroys not only the payments, shipments, but also the order itself (why would we keep empty cart orders with zero items in it?)

**on shipments**
- shipments are only created after the customer places the order (as currently, on legacy checkout)
- if so, then the summary page needs to be rendered with some other source for the shipping method

What do you think?

**Comment by jibees** [comment] 2022-05-09 12:28
Thanks for this incredible work/exploration @filipefurtad0 ! 👏 🙏 

I'd vote to destroys the whole order by clicking on `Empty cart`(and by removing all the items in cart?)

I'd invoke @mkllnk opinion on that one too, as I'm not familiar.

**Comment by mkllnk** [comment] 2022-05-10 00:41
> I'd vote to destroy the whole order by clicking on Empty cart

Yes, that sounds simple. There needs to be a check that the order is definitely not completed and doesn't have any successful payments.

It could hide some trails if someone had failed payments and then deleted the order. Actually, thinking of these cases, the order may even have a successful payment but the checkout still failed. How do we resolve this? While emptying the cart is a nice feature to clear things up, I don't think it can replace dealing with error states properly.

So, if emptying the cart can create a problem, maybe we need to restrict it. Otherwise, if it's a simple cart without any processed payments then we can simple destroy it and start fresh.

**Comment by georgethoppil** [comment] 2022-06-13 22:43
@filipefurtad0 are we still seeing issues with this ticket?

**Comment by filipefurtad0** [comment] 2022-06-14 07:34
Hey @georgethoppil ,

Yes, this is still ongoing. I think we can split this into two issues:
- #9299 
- #9168 -> not sure if really a bug. However it is the missing shipment which breaks the summary page, so perhaps worth a thought...

I'll make an epic out of the present issue which I think we can close, after these related issues are addressed.

**Comment by filipefurtad0** [comment] 2022-08-10 10:17
I'd close this issue, as it should be addressed by #9299. We can reopen if this is verified in production again.
I'd keep #9168 open as it seems like the root cause.

 Ok with everyone?

**Comment by RachL** [comment] 2022-08-10 10:20
Yes :muscle:

**Comment by filipefurtad0** [comment] 2023-04-28 15:42
This re-occurred in FR-prod:
https://app.bugsnag.com/open-food-france/coopcircuits/errors/644be783cb13d000081ef944?event_id=644be78300bc7afc335b0000&i=sk&m=nw

Offending line is 
`@order.shipping_method.name`

as described above. Re-opening.

**Comment by RachL** [comment] 2023-04-29 07:49
@filipefurtad0 is it correct that this is the way to reproduce the error we are talking about here: https://github.com/openfoodfoundation/openfoodnetwork/issues/9131#issuecomment-1113427149
?
And that we have only one user that triggered it 8 times? If so I think we can lower to s3. The user is a hub manager - FR team can get in touch with them to understand what they were trying to do.

**Comment by filipefurtad0** [comment] 2023-04-30 19:20
> is it correct that this is the way to reproduce the error we are talking about here: https://github.com/openfoodfoundation/openfoodnetwork/issues/9131#issuecomment-1113427149

No, I could not reproduce the error in this way anymore.

> And that we have only one user that triggered it 8 times? If so I think we can lower to s3.

Yes, still the case as of now - no further occurrences/users. Lowering to s3.

**Comment by filipefurtad0** [comment] 2023-04-30 22:24
This one looks related - OFN-CA:
https://app.bugsnag.com/open-food-network-canada-1/open-food-network-canada/errors/644ed4565400600008fd76b8?event_id=644ed45600bc8808c6e90000&i=sk&m=nw

Offending line:
`%strong= order.shipping_method.name`

```
Unhandled error
ActionView::Template::Error: undefined method `name' for nil:NilClass
Location
app/views/spree/shared/_shipment_pickup_details.html.haml:2 - _app_views_spree_shared__shipment_pickup_details_html_haml__3601739521380450504_13794080
```

I'm confused about the fact, that the request section in bugsnag mentions the legacy checkout URL (`/checkout`):
![image](https://user-images.githubusercontent.com/49817236/235375857-df0fb60a-3333-41e5-9cfb-75a1b99de32c.png)

Not sure what to make of this just yet...

**Comment by filipefurtad0** [comment] 2023-05-02 11:07
As discussed on delivery circle, this last occurrence pointing to `/checkout` could be due to an old session, still on legacy checkout, which - after the latest deployment which enables split checkout - could generate the error, when picking up that old session.

The likely steps reproduce:
- disable split checkout
- begin checkout with a customer: stop at the checkout screen (/checkout)
- enable split checkout
- without refreshing the page, complete checkout (click Place order)

I'll post feedback once I've tried this out.

**Comment by jibees** [comment] 2023-05-02 12:58
Regarding https://app.bugsnag.com/open-food-france/coopcircuits/errors/644be783cb13d000081ef944?filters[event.since]=30d&filters[error.status]=open&filters[search]=summary&event_id=6450d4d900bc9537f8100000

I've the screencast: https://openfoodnetwork.slack.com/files/U0168TVQZJ4/F055UPX9T5G/enregistrement_de_l___e__cran_2023-05-02_a___11.16.00.mov 

(cc @Cecilia-Hn made the screencast)

**Comment by filipefurtad0** [comment] 2023-05-02 15:03
Thanks! That's it :muscle: 
The user is redirected to the `/summary` page... And there is no shipment on the order.

So it seems there is an additional scenario which neither https://github.com/openfoodfoundation/openfoodnetwork/pull/9190 nor https://github.com/openfoodfoundation/openfoodnetwork/pull/9295 prevent...

**Comment by jibees** [comment] 2023-05-03 08:29
I reproduced the bug on staging (with shop https://staging.coopcircuits.fr/release-farm/shop)

It's definitely a bug when submitting details step: the shipping method is not saved. 
1. Selecting a shipping method
<img width="663" alt="Capture d’écran 2023-05-03 à 09 38 00" src="https://user-images.githubusercontent.com/296452/235866638-56279063-0c4d-4bca-bc7b-6232be4717a2.png">

2. Submitting the form
3. On payment step, clicking back to details step
4. See that shipping method is not selected:
<img width="682" alt="Capture d’écran 2023-05-03 à 10 28 39" src="https://user-images.githubusercontent.com/296452/235866868-f92a3c02-1c71-4f7d-ad3b-f9edc1b02832.png">

**Comment by jibees** [comment] 2023-05-03 08:32
@filipefurtad0 Maybe we should open an issue with this _How to reproduce?_ section and the associated [bugsnag](https://app.bugsnag.com/open-food-france/coopcircuits/errors/644be783cb13d000081ef944)? 
What do you think?

**Comment by filipefurtad0** [comment] 2023-05-03 08:42
Awesome that you've nailed it @jibees.
I'll try reproducing it myself and open a new issue (s2).

**Comment by filipefurtad0** [comment] 2023-05-03 08:50
Interesting. This does not happen on my browser/system. On the payment step, clicking back to details step (logged in, Firefox 112):

![image](https://user-images.githubusercontent.com/49817236/235870429-067d1694-196d-4fed-be3c-d673c1aa00bd.png)

On Chrome, as a guest:

![image](https://user-images.githubusercontent.com/49817236/235871185-3b292f62-822d-4f3c-824a-9fd19c22a326.png)


The shipping method is selected. Which browser/OS versions are you using @jibees ? I'll see if I can catch this with browserstack.

**Comment by jibees** [comment] 2023-05-03 08:53
I don't see this issue as related to a browser/OS version problem (but maybe I'm wrong: MacOSx/Chrome112)

I think it's more related to the order itself (products in cart? connected account? something else).

My cart:
<img width="356" alt="Capture d’écran 2023-05-03 à 10 52 04" src="https://user-images.githubusercontent.com/296452/235871692-622c0e25-2aea-48fe-82df-27124bd5d900.png">

I'm connected:
<img width="995" alt="Capture d’écran 2023-05-03 à 10 52 49" src="https://user-images.githubusercontent.com/296452/235871828-b677384a-0aeb-4c3e-80ce-b6abaf74770a.png">

**Comment by filipefurtad0** [comment] 2023-05-03 09:42
Ok, so two orders from you @jibees  - a healthy order (from 2022), and this corrupt order:

```
   id    |   number   | item_total | total |    state     | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |        email        | special_instructions | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id | included_tax_total | additional_tax_total | note 
---------+------------+------------+-------+--------------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+---------------------+----------------------+----------------+----------+-----------------+----------------+-------------+---------------+--------------------+----------------------+------
 2316277 | R748336625 |      10.00 | 10.00 | complete     |             0.00 |   21241 | 2022-02-14 13:28:15.143913 | 2022-02-14 13:29:11.738255 | 2022-02-14 13:29:11.611277 |          856257 |          856258 |          0.00 | pending        | balance_due   | <jb's email> |                      |           2720 | EUR      |                 |           8889 |       22813 |         21241 |               0.00 |                 0.00 | 
 2328680 | R882278226 |      10.00 | 11.00 | confirmation |             1.00 |   21241 | 2023-05-02 13:02:31.305227 | 2023-05-03 08:58:56.019917 |                            |          858000 |          858001 |          0.00 |                |               | <jb's email> |                      |           2720 | EUR      | 88.168.181.35   |           8960 |       23260 |         21241 |               0.00 |                 0.00 | 
(2 rows)
```

The first order has a shipment:

```
openfoodnetwork=> select * from spree_shipments where order_id = 2316277;
   id   | tracking |    number    | cost | shipped_at | order_id | address_id |         created_at         |         updated_at         |  state  | stock_location_id | included_tax_total | additional_tax_total | adjustment_total 
--------+----------+--------------+------+------------+----------+------------+----------------------------+----------------------------+---------+-------------------+--------------------+----------------------+------------------
 183340 |          | H24121655814 | 0.00 |            |  2316277 |            | 2022-02-14 13:28:50.101421 | 2022-02-14 13:29:11.735307 | pending |                 1 |               0.00 |                 0.00 |             0.00
(1 row)
```

The second one does not:

```
openfoodnetwork=> select * from spree_shipments where order_id = 2328680;
 id | tracking | number | cost | shipped_at | order_id | address_id | created_at | updated_at | state | stock_location_id | included_tax_total | additional_tax_total | adjustment_total 
----+----------+--------+------+------------+----------+------------+------------+------------+-------+-------------------+--------------------+----------------------+------------------
(0 rows)
```

Why would an order not create a shipment... :shrug:

**Comment by filipefurtad0** [comment] 2023-05-03 10:19
Closing in favor of https://github.com/openfoodfoundation/openfoodnetwork/issues/10796; I've kept the same severity as here.

**Closed by filipefurtad0** 2023-05-03 10:19 UTC
Labels: epic, bug-s3
