### ISSUE TITLE
Increasing quantity on Bulk Edit Products

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#1004] opened 2016-05-13 05:51 UTC
If you go over the on-hand limit, you get an error message.
Unfortunately, you get the message as well when you try to decrease he quantity again, which makes it impossible to undo the mistake.

**Comment by OliverUK** [comment] 2016-05-16 14:53
Do you mean when shopping in the shop front? 
If I do what you are describing in Firefox 46.0.1 I get the error message and on clicking ok, I get another and then another and so it goes on. BUT, I do also get the option if preventing further messages (a tick box inside the error pop-up. This stops the messages.

**Comment by mkllnk** [comment] 2016-05-17 23:58
Yes, I observed that as well. But not always.

**Comment by RachL** [comment] 2020-06-11 14:14
I can't reproduce this one, so I'm closing it.

**Closed by RachL** 2020-06-11 14:14 UTC
Labels: bug-s3
