### ISSUE TITLE
Make /shops layout on mobile the same as /producers

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#5460] opened 2020-05-19 10:24 UTC
## Description
At the moment, when you're portrait on /shops you can't see the names of the shops at all, but you can see the names on the /producers page.

## Expected Behavior
I can see the shop names on /shops in portrait view on mobile like I can see producers names on /producers/

## Actual Behaviour
The names don't display on /shops like they do on /producers

## Animated Gif/Screenshot
<img width="384" alt="Screen Shot 2020-05-19 at 8 17 19 pm" src="https://user-images.githubusercontent.com/10949052/82315344-82a08900-9a0e-11ea-9ed0-2614b6ec6d75.png">

<img width="393" alt="Screen Shot 2020-05-19 at 8 18 06 pm" src="https://user-images.githubusercontent.com/10949052/82315352-846a4c80-9a0e-11ea-95e6-e888bc8558fe.png">

## Workaround
Turn mobile to landscape.

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
**bug-s3: a feature is broken but there is a workaround**
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

## Possible Fix
Copy whatever the code is on /producers that allows names to display on that page and use it on /shops so that names display there as well.

**Comment by kirstenalarsen** [comment] 2020-05-19 10:33
hmmm maybe, i suspect the problem is the closing time which is an extra field, on most of the shops links above you can't actually see any text, which means if you wrapped it around you could
e
n
d
u
p
w
i
t
h
something like that?

I think it's probably a papercut rather than a bug

**Comment by kirstenalarsen** [comment] 2020-05-19 10:34
but if it's a papercut it is definitely one that needs design eyes, and it's outside the scope of the ones that designers can be pinged on (i.e is not shopfront, cart or checkout)

**Comment by daniellemoorhead** [comment] 2020-05-19 11:53
Assumption that this is an easy fix disproven, sadly, so I'm deleting this.

**Closed** 2020-05-19 11:53 UTC
Labels: bug-s3
