### ISSUE TITLE
Invoices from accounts@ofn.org.uk not arriving at user's email 

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1191] opened 2016-10-20 15:38 UTC
Sara created an invoice through the Accounts@openfoodnetwork,org,uk login.  The invoice copied OK to hello@ofn.org.uk but it didnt come to sara - see email trail below.  

From: Sara Rock [mailto:sara@tamarvalleyfoodhubs.org.uk] 
Sent: 20 October 2016 14:04
To: nick@openfoodnetwork.org.uk
Subject: Re: FW: Open Food Network UK Invoice #R317247883

No didn't come to me, good job we can try this out on ourselves!  

Not sure what the process for this is yet but I generated that manually via accounts@

----- Original Message -----
From:
nick@openfoodnetwork.org.uk

To:
"Sara Rock" <sara@tamarvalleyfoodhubs.org.uk>
Cc:

Sent:
Thu, 20 Oct 2016 13:35:44 +0100
Subject:
FW: Open Food Network UK Invoice #R317247883

Open Food Network UK 
Hi Sara
This came through to hello@
Did it not come to you?
Cheers
N
 
From: hello@openfoodnetwork.org.uk [mailto:hello@openfoodnetwork.org.uk] 
Sent: 20 October 2016 13:02
To: sara@tamarvalleyfoodhubs.org.uk
Subject: Open Food Network UK Invoice #R317247883
 
		OPEN FOOD NETWORK UK 
	
 
	Hi Sara, 
Please find attached an invoice for your recent order from Accounts and Billing 
 
Kind regards, 
Sara Rock 

Accounts and Billing 
01579 208412 
accounts@openfoodnetwork.org.uk 

	
 
	Terms of service | Open Food Network UK

**Comment by Rocksj** [comment] 2016-10-20 16:18
Just sent an invoice to myself for my Tamar Valley Food Hubs order and came through straight away to my personal email address. I think this must be something to do with the way accounts@ is set up?

**Comment by lin-d-hop** [comment] 2016-10-20 16:25
Duplicate of #1190 
I'm in communication with our email provider. Will update with more details when I have them.

**Closed by lin-d-hop** 2016-10-20 16:25 UTC
Labels: uk
