### ISSUE TITLE
Allow for >1 notification email address per enterprise

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1665] opened 2017-07-07 06:45 UTC
Currently the notification email field can only hold one email. 
There are cases where multiple people need to receive notifications relating to an enterprise E.g. https://community.openfoodnetwork.org/t/is-it-possible-to-selectively-notify-producers-in-an-oc/983

Once the 'add manager' functionality of the notifications field has been removed as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/1593, could we allow for the addition of multiple notification email?

It could look something link the current list of managers, but the notifications emails don't neccessarily need to be confirmed users.

**Comment by myriamboure** [comment] 2018-03-30 14:33
I think we need to think a bit and incept on it.
1- We don't want unconfirmed users so I din't think people who receive notification emails (this field send an email each time an order is received by the hub basically) should be a confirmed user as they are probably part of the hub management team
2- Regarding producers receiving or not confirmation emails separately for each order made to them (which is the purpose of this field) this should be set up by the producer himself in his enterprise menu, like maybe he should have the list of all the hubs that have the P-OC right and for each one he could be able to set up useful things like: I want to receive individual confirmation for this hub because I make myself the baskets, but not this one because I sell in bulk. So this is a whole new feature that is for now in the wishlist and will need to be structured in an icebox and prioritized ;-)

SO my question is: do more than one person in the hub coordination team need to receive separate individual emails for each order made? Do we have a real request from users on that?
From the feedbacks I get I have more requests to be able to deactivate notification emails as hubs are spammed with hundreds of useless order confirmations ;-)

What do you think @sstead ?
If you disagree happy to discuss, else please close that issue.
I reference it in the wishlist item for memory.

**Comment by lin-d-hop** [comment] 2020-01-04 15:38
Closing at this is a feature that needs prioritising and incepting

**Closed by lin-d-hop** 2020-01-04 15:38 UTC
