### ISSUE TITLE
Error message when saving product changes

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8385] opened 2021-10-20 15:22 UTC
## Description

As [reported here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1634712165187700) - When editing products on the `/products` page users are getting the message:
`Saving failed. Save failed due to invalid data:undefined`

Changes seem to be saved anyway, so this is confusing.

## Expected Behavior

No error message should be seen.

## Actual Behaviour

`Saving failed. Save failed due to invalid data:undefined` is displayed when saving a product (`/products`)

## Steps to Reproduce

Not sure, it's reproducible but seems a bit erratic. Subsequent changes on the same product: sometimes the error is triggered, some times it is not...

1. Go to the `/products` page
2. Filter products by enterprise (not sure this is decisive for this bug)
3. Change the name of a product. Click Save Changes
4. Repeat till you see the error... -> obviously some detail is missing here. Not sure what could that be....

## Animated Gif/Screenshot

This one would deserve the `wtf` label:

![Peek 2021-10-20 16-57](https://user-images.githubusercontent.com/49817236/138129357-87e89d67-d64b-406c-9555-1271dc23a600.gif)

![image](https://user-images.githubusercontent.com/49817236/138125687-ba4a4ce7-0f3c-432e-b08e-92e7d401366a.png)

## Workaround

The user should ignore the error message.

## Severity

bug-s4: it's annoying, but you can use it

Confusing to the users, and seems to have generated reports to support teams. Worth upgrading to s3?

## Your Environment

* Version used: v4.1.3
* Browser name and version: Observed on Firefox, Chrome
* Operating System and version (desktop or mobile): Linux and other OS

**Comment by adele-ofn** [comment] 2021-10-20 23:09
Hi Filipe, thanks for logging this bug. Confirming that I've also replicated the bug in Chrome (MacOS Sierra 10.12.6):
<img width="1439" alt="Screen Shot 2021-10-21 at 9 55 45 am" src="https://user-images.githubusercontent.com/89006237/138184678-69842e2f-e3ff-480e-9fb6-6e8cfd1162fd.png">
<img width="1436" alt="Screen Shot 2021-10-21 at 9 56 07 am" src="https://user-images.githubusercontent.com/89006237/138184685-021c33e8-74a4-4dff-84c5-c1c90784e3eb.png">
<img width="1440" alt="Screen Shot 2021-10-21 at 9 56 30 am" src="https://user-images.githubusercontent.com/89006237/138184707-4683d3e0-f458-47b9-8ed2-25c5c2024b98.png">

**Comment by georgethoppil** [comment] 2022-04-19 22:35
@filipefurtad0 I tried this a couple of times as well and I cannot reproduce. Can you see if you are able to achieve this now?

**Comment by filipefurtad0** [comment] 2022-04-20 10:42
Hey @georgethoppil ,
This was appearing in very unspecific circumstances... Indeed I can't reproduce it in my test setups.

@adele-ofn: can you still verify this bug in production?

**Comment by RachL** [comment] 2022-07-21 12:21
As we cannot reproduce it for now. I'm closing this one :)

**Closed by RachL** 2022-07-21 12:21 UTC
Labels: bug-s4, AU

**Comment by tschumilas** [comment] 2023-02-06 20:49
I think I can reproduce this one (I've been editing thousands of products today to change some tax cagegories, and I think I see a pattern).   I am finding that this error reliably presents when 2 conditions are met:  (1) a product is deleted from the list  and (2) a product is changed after that deletion.     At least I think so...     Just deleting a product does not give the error.   Just changing a product doesn't seem to give the error.
