### ISSUE TITLE
Unsaved changes in the shop inventory

### ISSUE THREAD

**Issue by SophieDuponcheel** [openfoodfoundation/openfoodnetwork#5131] opened 2020-04-02 11:19 UTC
## Description

On the Oxfam Magasins du Monde Rochefort shop catalogue, I try to modify the stocks of products coming from different producers. These same producers supply other Oxfam stores. Oxfam-Rochefort has full permission to add products and change the stocks of products in its catalogue. Changes to stocks have been recorded each time. Since 2 days it doesn't work anymore for any catalogue (for other stores it doesn't work either). I should be able to change the stocks as I want, but an error message appears at the bottom of the page telling me that the changes have not been saved.

This is a real problem because the sotcks are very different from one store to another, so we need to have the right stock up to date on the catalogue of the different stores.

## Expected Behavior

I should be able to change the stocks as I want

## Actual Behaviour

an error message appears at the bottom of the page telling me that the changes have not been saved.

## Steps to Reproduce

https://www.openfoodnetwork.be/admin/inventory

1. I'm going to the Oxfam Rochefort World Shops store catalogue, 
2. I change the stock of "noodles 250g" to 3
3. I'm saving the changes, it takes a long time to load.
4. An error message appears, the changes have not been saved. 

## Animated Gif/Screenshot

![Screenshot from 2020-04-02 13-51-50](https://user-images.githubusercontent.com/8669848/78251390-2e3a5c00-74e9-11ea-8f64-b94c4b5612b8.png)

504 Error

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 2.8.2
* Browser name and version: Chrome and firefox
* Operating System and version (desktop or mobile): PC windows 10 and ubuntu

**Comment by tschumilas** [comment] 2020-04-02 14:57
Is this French error the same as this English error @RachL ?   If so -  it seems that inventories are broken for this login only.  Add a different manager login and try again @SophieDuponcheel   
It could be a different problem -  I'll test today, I'm doing other inventory testing anyway.  But I've broken inventories and gotten this message 3 times now -   and I have no idea why.  I think something to do with adjusting permissions,  and then inventory?   Anyway here is my issue - is it the same: https://github.com/openfoodfoundation/openfoodnetwork/issues/5090

**Comment by luisramos0** [comment] 2020-04-03 08:11
yeah, reducing permissions for the user doing this change may help as a workaround.
So a workaround **could** be: make sure the user trying to execute the task has only access to the products that need to be changed.

This inventory page completely breaks if there is a single broken variant that the user has access to.

In #5090 we see a 401 unauthorized, here we see a 504 timeout. They look like different problems.
And #4145 will be a duplicate of one of these two.

I will fetch the Belgium database to my laptop and try to replicate.

**Comment by luisramos0** [comment] 2020-04-03 09:56
Hi @SophieDuponcheel 
It would be good to see your network tab on devtools to see how long the request took, probably the server timeout (I believe BE is at the default which is only 30secs). Would be good to confirm this on your side.

Anyway, I think this is a performance issue, the request takes 20seconds on my laptop: the code is very bad at saving the data because all variant overrides (inventory items) of all enterprises the user can see will be fetched and updated when the user hits save....

I believe the fast workaround is to remove yourself from the managers list from one of your enterprises:
"Les Gasticots" or "Magasin du monde-Oxfam Rochefort" or "Magasin du monde-Oxfam Jodoigne commerce équitable" or "Centrale Oxfam-Magasins du monde"

The slower but better workaround here would be to increase sderver timeout to 60 or 90secs (most our servers are at 60 or 90 now because of reports).

The real fix for this is to improve the code.

I think we should go for the performance quick wins now but I wonder if we can increase server timeout as well and make this an S3. What do you think? @lin-d-hop @tschumilas

**Info for devs from this point below:**
The request on my laptop takes 18secs but it's terribly inefficient at saving the data.
3200 SQL queries from which:
- 271 queries - 9secs in VO controller loading products of each VO:
`      @vo_set.collection.each { |vo| authorize! :update, vo }`
- 989 queries from 3secs in variant_override_set loading tags in collection_to_delete
- most of the other 2000 queries - saving the data - 5secs - in model_set.rb:43 saving each VO

We have some work to do here...

**Comment by SophieDuponcheel** [comment] 2020-04-03 10:27
> 
> 
> Hi @SophieDuponcheel
> It would be good to see your network tab on devtools to see how long the request took, probably the server timeout (I believe BE is at the default which is only 30secs). Would be good to confirm this on your side.
> 
> Anyway, I think this is a performance issue, the request takes 20seconds on my laptop: the code is very bad at saving the data because all variant overrides (inventory items) of all enterprises the user can see will be fetched and updated when the user hits save....
> 
> I believe the fast workaround is to remove yourself from the managers list from one of your enterprises:
> "Les Gasticots" or "Magasin du monde-Oxfam Rochefort" or "Magasin du monde-Oxfam Jodoigne commerce équitable" or "Centrale Oxfam-Magasins du monde"
> 
> The slower but better workaround here would be to increase sderver timeout to 60 or 90secs (most our servers are at 60 or 90 now because of reports).
> 
> The real fix for this is to improve the code.
> 
> I think we should go for the performance quick wins now but I wonder if we can increase server timeout as well and make this an S3. What do you think? @lin-d-hop @tschumilas
> 
> **Info for devs from this point below:**
> The request on my laptop takes 18secs but it's terribly inefficient at saving the data.
> 3200 SQL queries from which:
> 
>     * 271 queries - 9secs in VO controller loading products of each VO:
>       `      @vo_set.collection.each { |vo| authorize! :update, vo }`
> 
>     * 989 queries from 3secs in variant_override_set loading tags in collection_to_delete
> 
>     * most of the other 2000 queries - saving the data - 5secs - in model_set.rb:43 saving each VO
> 
> 
> We have some work to do here...

hi @luisramos0 
Thank you for all your input. I changed the manager for those entreprises, and it's work. but in the long term, this is not ideal because normally the manager openfoodnetwork@mdmoxfam.be will (eventually) manage 20 or more counters. Having several users for that it's going to be a crazy management.

about this : It would be good to see your network tab on devtools to see how long the request took, probably the server timeout (I believe BE is at the default which is only 30secs). Would be good to confirm this on your side.
I would like to, but i'don't know how to do it? can you help me?
And to add something else, it's true that the recording time is very long...

Thank you

**Comment by luisramos0** [comment] 2020-04-03 12:21
cool, in the screenshot you shared, you have the devtools showing on the Console tab (top right), you just have to click on the Network tab to the right after Sources.

**Comment by SophieDuponcheel** [comment] 2020-04-03 14:40
> ool, in the screenshot you shared, you have the devtools showing on the Console tab (top right), you just have to click on the Network tab to the right after Sources.

![image](https://user-images.githubusercontent.com/63047606/78372640-ce67b200-75c9-11ea-90cf-51e500c04056.png)

**Comment by RachL** [comment] 2020-04-03 14:57
@SophieDuponcheel here you did with the console tab and @luisramos0 needs the network (réseau) tab ;)

**Comment by luisramos0** [comment] 2020-04-03 15:10
in your case it will be reseau

**Comment by luisramos0** [comment] 2020-04-03 15:16
I have fixed the first of the 3 points above in #5145 - the PR removes the N+1 query on variant_overrides.variant.product  while authorizing each VO. It's a very small improvement, the other two are the biggest offenders.
 
Regarding the two other issues:
- how to remove N+1 on tag_list (acts_as_taggable)? I tried [this](https://github.com/pivorakmeetup/pivorak-web-app/pull/178/files#diff-458443b38c348c04e78913481a3f6fb5R18) and it stops the queries while [checking if tag list is empty](https://github.com/openfoodfoundation/openfoodnetwork/blob/e64d573337241b7a652099ecf629d8b513562325/app/models/variant_override_set.rb#L15) BUT it still runs the tags query for each VO [when saving the VO](https://github.com/openfoodfoundation/openfoodnetwork/blob/e64d573337241b7a652099ecf629d8b513562325/app/models/model_set.rb#L43) :see_no_evil:
- how to save the model_set without generating 1 query per VO? particularly important when most of the times users just change a few of them! Maybe we can use activerecord-import for this?

**Comment by SophieDuponcheel** [comment] 2020-04-03 15:29
> 
> 
> @SophieDuponcheel here you did with the console tab and @luisramos0 needs the network (réseau) tab ;)

Ahaha ok, i thought he was asking me "console" and I didn't find Sources (even in french), so I was confused ;)

**Comment by SophieDuponcheel** [comment] 2020-04-03 15:31
@luisramos0 I hope it's was you were asking me ...
![image](https://user-images.githubusercontent.com/63047606/78378207-f4dd1b80-75d0-11ea-86e7-1c3b013a4435.png)

**Comment by luisramos0** [comment] 2020-04-03 15:34
I think you have to open it before you load the page.

**Comment by sauloperez** [comment] 2020-04-03 15:49
> It was successful but I am afraid this is going to break things...

It all depends on whether we have after_update callbacks and how those play with this gem. We might need to check their codebase but either N or 1 inserts should still behave the same, or that's what I'm hoping.

IMO it's particularly hard to tune VO's performance due to their design. I foresee heaps of effort and little gain. I'd rather rethink them first and when their performance doesn't leave us with other options. That's what the network feature should do anyway, right? so I wouldn't get too caught up.

**Comment by SophieDuponcheel** [comment] 2020-04-07 08:35
@luisramos0 @sauloperez @RachL is there anything more I can do to help you? is there a solution to the problem? or am I organizing something to work around it? so the problem is that there is too much data to manage for openfoodnetwork@mdmoxfam.be? Thank you for your help!! it's precious!

**Comment by luisramos0** [comment] 2020-04-07 10:16
Hi Sophie,

I dont think I was clear with
"I think you have to open it before you load the page."
You didnt send what we needed.
You have open dev tools and network before you load the page so that the information of the request is complete. can you try again please?

are you still experience this problem? if yes, I'd change the BE server timeout to 60secs and that will make this an S3. Does that make sense for everyone?

**Comment by SophieDuponcheel** [comment] 2020-04-07 13:19
![image](https://user-images.githubusercontent.com/63047606/78673967-2d3b6d00-78e3-11ea-9cfb-344b004f2666.png)
there, I think I finally understood ;) 
On the other hand, now the recording is done. Maybe you've done something? On my side, I have tidied up the dashboard of openfoodnetwork@mdmoxfam.be.

**Comment by luisramos0** [comment] 2020-04-09 12:27
I am pretty sure this is fixed by #5184
@SophieDuponcheel let us know if you have any issues again after the next release (should get to BE on Tuesday).

**Closed by luisramos0** 2020-04-09 12:27 UTC
Labels: bug-s2
