### ISSUE TITLE
Error on trying to delete an account

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/openfoodnetwork#621] opened 2015-07-13 16:52 UTC
For testing I was trying to delete a user account via the admin interface and got an internal error screen overlay and this message in logs:

```
ActiveRecord::InvalidForeignKey (PG::Error: ERROR:  update or delete on table
"spree_users" violates foreign key constraint "spree_orders_user_id_fk
on table "spree_orders"
DETAIL:  Key (id)=(200202) is still referenced from table "spree_orders".
: DELETE FROM "spree_users" WHERE "spree_users"."id" = $1):
```

I had previously deleted the account just earlier, which is double weird (not sure how it could have any spree_orders).

@lin-d-hop this is similar to the message appearing when Karen was trying to login. Any ideas as to the cause?

**Comment by aidandunsdon** [comment] 2015-07-13 18:58
Looks like related to previous data issue - assigning to me

**Comment by aidandunsdon** [comment] 2015-07-13 19:01
Can you assign to me - can't from this phone

**Comment by aidandunsdon** [comment] 2015-07-14 08:31
OK -  I think I've found the cause of this and #618 - Its the table spree_tokenised_permissions which is lacking some mandatory created_at updated_at date fields.
@pmackay the copy of production database  you put on dropbox needs to be in  format for pg_restore - syntax sudo -u postgres pg_dump -Fc openfoodnetwork >  foo.sql  - If you could dump that again I could fix it straight away

**Comment by NickWeir63** [comment] 2015-08-16 16:16
@pmackay Following our skype conversation on Friday I tested this one again.  I logged in as superadmin and then tried to delete a user using this screen
![screenshot 2015-08-16 17 11 46](https://cloud.githubusercontent.com/assets/10517702/9294090/571553a8-443a-11e5-931a-6c415b85cee1.png)

I got the grumpy cat (which is a different error from the one reported above (was I doing something different?) but it looks like this bug in not solved as we thought it might be.

**Comment by RohanM** [comment] 2015-08-17 02:21
I can add a bit more detail to this. When a user logs on to the site, their cart is stored in the form of an order with state `'cart'`, so I think that means that any user who has logged on will have an order. The order relation on the user model doesn't have `dependent: :destroy`, so it won't be able to be deleted. I don't think this is a problem with your data import. It might be more fruitful to look at implementing a soft-delete for users.

**Comment by myriamboure** [comment] 2016-09-09 12:15
@pmackay I just reproduced the error but with another case, I just created a test user to create a producer enterprise, just to check UX how products can be added for producer shops. I did nothing, added no product, no order cycle, no order, nothing, but still as an admin, I can't delete that user afterward. I deleted the entreprise first, but the user then can't be deleted.
![screenshot from 2016-09-09 14-11-23](https://cloud.githubusercontent.com/assets/8135376/18386497/d9b1bf32-7697-11e6-88f9-b83a3b57f5c2.png)

**Comment by myriamboure** [comment] 2016-11-14 08:18
Hi there! This is a legal requirement for a user to be able to delete his personal information from any platform. We had a user in France writting to us yesterday that he wante to delete his account but didn't manage to. Technically, we are not following the legislation, this should be possible. Any progress on this "soft delete" option? Technically we are supposed to delete all info regarding the person who asked that...

**Comment by lin-d-hop** [comment] 2017-12-23 03:18
#gitcull2017
https://community.openfoodnetwork.org/t/feat-deletions-on-ofn/1075

**Closed by lin-d-hop** 2017-12-23 03:18 UTC
Labels: australia, bug
