### ISSUE TITLE
"Comment" cells left blank when exporting CSV from Orders and Fulfilments reports

### ISSUE THREAD

**Issue by JulianPla** [openfoodfoundation/openfoodnetwork#9984] opened 2022-11-13 08:36 UTC
## Description

Since the updated reports, comments/delivery notes during checkout don´t make it into the csv file when exporting the "Orders and Fulfilments reports". When printing the report on the screen all comments appear as they should (image 1), but when exporting as csv the cells are blanked out.
So its just an issue with the csv export.

![image](https://user-images.githubusercontent.com/118100739/201513200-5d5fa0bc-2f91-4e8f-aace-e61f25547588.png)

As it can be seen in image 2, no comment in the csv:

![image (1)](https://user-images.githubusercontent.com/118100739/201513209-54a7561e-3ad3-4404-927f-94f364a72eb3.png)

## Expected Behavior

All fields in the on-screen version appear in the CSV

## Actual Behaviour

The delivery notes are missing from the CSV.

## Steps to Reproduce

1. Open the Orders and Fulfillments - Customer Totals report
2. See delivery notes on the screen version
3. DOwnload the CSV
4. See the delivery notes are missing

## Workaround

my workaround for now is to first show the report on the screen checking for comments, and than export as csv for further procedure.

## Severity
 bug-s3

## Your Environment

* Version used: Guess the latest OFN Update, OFN Germany 
* Browser name and version: Firefox 106.0.5
* Operating System and version (desktop or mobile): Windows 10

**Comment by abdellani** [comment] 2022-11-15 09:33
Hi

`Order Cycle Customer Totals` is the only report under `Orders & Fulfillment Reports` that includes the comments column. Please correct me if I'm wrong. 


Also, I noticed many columns don't appear when I select the PDF format.

**Comment by lin-d-hop** [comment] 2022-11-15 09:53
> Order Cycle Customer Totals is the only report under Orders & Fulfillment Reports that includes the comments column.
I believe so, yes

> I noticed many columns don't appear when I select the PDF format.
Does this seem straight forward to fix to you? Any that are easy to fix we can do at the same.

**Comment by abdellani** [comment] 2022-11-15 11:31
@lin-d-hop 
For the main problem, I found that the CSV report prints the `LineItem`s, while the shipping comment is stored in the `Order` model.
In the HTML version, we can see those comments because the summary row is checked, while this is not possible with CSVs.
One way to solve the problem is to copy the order comments to its line items, but this will create confusion because the `LineItem` also has its own `comment` attribute, also there will be a lot of duplication.  
Any ideas?

For the PDF report, I'll check if it's possible to split long tables among multiple pages (see screenshot).
![image](https://user-images.githubusercontent.com/16113997/201907470-220ecc64-c174-4c06-b735-e7d5d0a7aa0e.png)

**Comment by lin-d-hop** [comment] 2022-11-17 09:57
CLosing this issue as adding summary rows to the CSVs would be an enhancement rather than a bug.

**Closed by lin-d-hop** 2022-11-17 09:57 UTC
Labels: bug-s4

**Comment by JulianPla** [comment] 2022-11-22 13:37
Hey, thanks guys for taking up that topic, and so fast. Very sorry for beeing late in the discussion.
@abdellani Yea exactly thats what i meant! -Duplication is not a problem at all (at least from user point of view), when later grouping that data to extract the comments.. 

@lin-d-hop Well my workaround for now is, like described in the report, to first show data on screen, than make the csv report.

The excel report doesn´t work for me.. data is not in a real table design, as it has Name blocks instead of the data inside columns to feed the pivot tables with.. Btw. i also use formulas to cut the names in last and surnames to be able to sort the pick up box alphabetically by lastname.

Workaround is ok, no problem with it. Just uncomfy if you are a new csv using person and need to realize first that one collumn doesnt work. On long term it would be nicer, sounds nice to me at least (not a coder), to copy the order comments to its line items. guess that would do the deal and make sense to have the reports consistant
