### ISSUE TITLE
Enterprises in the same address get overlapped in map

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#1782] opened 2017-08-29 15:27 UTC
When multiple enterprises have the same address, it's impossible to find them all in the map. Their markers get totally overlapped hiding all enterprises but the last one that was created.

At maximum zoom other markers don't show up:
![mapa](https://user-images.githubusercontent.com/762088/29828838-247324cc-8cde-11e7-8f8b-4e0572ab99bb.png)

So, can only click the last one of them:
![mapa_capfoguer](https://user-images.githubusercontent.com/762088/29828845-27dac840-8cde-11e7-96aa-10bce68f8812.png)

And the angular's enterprises collection correctly lists them with the same coordinates:

```js
{
  "name":"Cervesa Capfoguer, SCCL",
  "id":31,
  "description":"Cooperativa de producci\u00f3 i distribuci\u00f3 de cervesa artesana",
  "latitude":41.4461847,
  "longitude":2.2087712,
  ...
},
{
  "name":"Cooperativa de Consum El Cab\u00e0s (Ca la Sisqueta)",
  "id":30,
  "description":"",
  "latitude":41.4461847,
  "longitude":2.2087712,
  "long_description":"Cooperativa de consum de fruita i verdura ecol\u00f2gics. Ens trobem un cop per setmana a Ca la Sisqueta per recollir les nostres comandes.",
  ...
}
```

We need to add some spacing between them so that all markers in the same coordinates are clickable.

**Comment by enricostano** [comment] 2017-08-29 15:32
https://stackoverflow.com/questions/14248365/how-to-render-multiple-markers-at-the-exact-same-coordinates-in-google-maps-api

maybe?

**Comment by sauloperez** [comment] 2017-08-29 15:36
Perhaps it's better to allow users to introduce latitude and longitude manually to fix these cases but that might involve more work than a pure JS solution.

**Comment by Morantron** [comment] 2017-08-29 17:22
![](https://media.giphy.com/media/3o7btV5GAWaGkwjTrO/giphy.gif)

**Comment by Morantron** [comment] 2017-08-29 19:03
Looks like google maps has some clustering options thingies

![image](https://user-images.githubusercontent.com/3304507/29839106-652457ba-8cfd-11e7-86f2-fb6fc179fc64.png)

( still need to center the image properly :sweat_smile: )

Maybe the modal when clicking on a marker can be expanded to showing more than one ( in the case of having many in the _exact same location_ )

**Comment by sauloperez** [comment] 2017-08-30 09:31
Awesome having you onboard @Morantron 💪 !

> Maybe the modal when clicking on a marker can be expanded to showing more than one

definitely, that's the other challenge besides the marker

**Comment by Morantron** [comment] 2017-10-06 13:21
That's already done in the linked PR

**Comment by enricostano** [comment] 2017-10-20 14:22
Should we close this @sauloperez ?

**Comment by sauloperez** [comment] 2017-10-20 14:33
I wouldn't. The problem still exists, although it's not our priority now.

**Comment by sauloperez** [comment] 2017-12-19 06:19
Moved to: https://community.openfoodnetwork.org/t/enterprises-in-the-same-address-get-overlapped-in-map/1157

**Comment by RachL** [comment] 2019-04-26 13:48
Reopening for the upcoming UK dehack

**Comment by lin-d-hop** [comment] 2019-11-05 09:26
Closing

**Comment by RachL** [comment] 2019-11-09 09:29
@lin-d-hop why was this closed? I can still reproduce it and I believe it 's a good first issue

**Comment by kirstenalarsen** [comment] 2020-04-05 05:47
is this an issue or not an issue @lin-d-hop @RachL ?

**Comment by rmklaus12** [comment] 2020-04-22 01:21
Still an issue, yes? Happy to grab this one as my first attempt (the browser back buttons) was a bit much as a first issue!

**Comment by RachL** [comment] 2020-04-22 06:53
@rmklaus12 yes this is still an issue!

**Comment by sauloperez** [comment] 2020-04-22 13:00
I'm not sure the requires are clear for this issue. Last time we worked on it, it was rejected. See https://github.com/openfoodfoundation/openfoodnetwork/pull/1786#issuecomment-336354416

**Comment by Matt-Yorkley** [comment] 2020-04-22 13:11
I had a rummage in the code for this recently, and I think there's some configurable options in the javascript plugin for handling these "clustering" issues...

**Comment by manvil** [comment] 2020-05-04 06:37
Hello everyone monitoring this , I am beginning to work on this, FYI

**Closed** 2020-05-13 18:31 UTC
Labels: AU, enhancement, good first issue, hackathon, socialissues.tech
