### ISSUE TITLE
Standing Orders: User/Customer edits their current order (within current order cycle)

### ISSUE THREAD

**Issue by yukoosawa** [openfoodfoundation/openfoodnetwork#1461] opened 2017-02-22 05:27 UTC
### HIGH LEVEL USER FLOWS:
- [OFN SO Edit User Flows 20170212.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/792200/OFN.SO.Edit.User.Flows.20170212.pdf)

### PROPOSED WIREFRAMES
**_Note:_**
- Wireframes are indicative (am 100% sure I have not captured all scenarios and interactions on pages!).
- All copy/labels/headings should be reviewed for clarity.

**_Homepage (logged in)_**
- Alert User that an SO within current OC is editable
-- Use existing alert bar UI pattern
-- Can be dismissed by User
- Provide message + link to Edit Cart page (for single SO in current OC)
- Provide message + link to My Account page (for multiple SOs in current OCs)

![03 desktop-so page alert](https://cloud.githubusercontent.com/assets/19785399/23197010/51674914-f88b-11e6-9f07-4d579d710bc0.png)

![03 mobile-so page alert](https://cloud.githubusercontent.com/assets/19785399/23197011/54b08644-f88b-11e6-81af-4fd7f0f4baab.png)

**_Edit Cart page_** (#1084)
- User can delete SO items in current order
- User can add non-recurring items to order
- [TBC] User can cancel current SO order
-- How likely is this use case? For MVP will manual delete of individual items suffice?
- [TBC] User can increase/decrease quantity of SO items in current order
-- Considerations around inventory availability, payment adjustments, expectations around modifying for a single instance of an SO vs updating recurring SO
- [Future] User can update delivery/pickup location for current order
- [Future] User can update payment type for current order

![02 desktop-edit cart](https://cloud.githubusercontent.com/assets/19785399/23197890/6cd8403a-f891-11e6-90a7-806821f1eedd.png)

![02 mobile-edit cart](https://cloud.githubusercontent.com/assets/19785399/23198261/4230e668-f894-11e6-94ff-6b5b2242a2b3.png)

**_My Account page_**
- User can access open SOs in the current OC
- User can access fulfilled orders (which may include SO items)
- [Future] User can access future/upcoming SOs (modify individual instance)
- [Future] User can pause/delete/activate recurring SO
- [Future] User can modify items in recurring SO

![01 desktop-my account](https://cloud.githubusercontent.com/assets/19785399/23197895/7519e3ca-f891-11e6-9624-bc191b9c5dcd.png)

![01 mobile-my account](https://cloud.githubusercontent.com/assets/19785399/23197900/793433e8-f891-11e6-9d8a-2c369f64dcd3.png)

**_Email announcing SO is open for editing_**
- Make the 'Order Confirmation Number' in the existing email template click through to the 'Edit Cart' page.

### ASSUMPTIONS:
- User has previously setup a SO with Shop
- Shop has allowed customer SOs to be editable
- User has SOs only with the one Shop (likely use case)

**Comment by oeoeaio** [comment] 2017-03-28 23:34
Hey @yukoosawa,

Thanks so much for laying all of this out. I've been going through and trying to work out how to piece it all together, and I think it mostly should work great, I just have one concern that I'd like to run by you.

I think the use of the existing 'cart' page for displaying and editing open orders is may be problematic. Orders that are "Open" for editing have actually already been completed. Any subsequent additions to the cart in the same OC will represent a new and distinct order. Using a single button (in this case the 'Update' button in the cart page) to update both the incomplete "in cart" order and the complete "open" order feels a but icky, because the first will represent an update that still needs to be confirmed by the customer (by completing checkout), but the latter will represent a save that cannot really wait to be "confirmed" in the same way, it will need to save immediately, without an intermediate step. I would really prefer not to bundle both actions into a single button.

Could I get you to validate a slight tweak to the proposed flow? 

The items listed under "Standing order items included in the current order" are more like "Items that have already been ordered in this OC". At the moment they are probably Standing Order items, but there is not really any reason not to display items from regular orders that have already been placed, but that can still be edited (if this is allowed by the shop). Anyway, could we display those items in the location you have put them on the cart page, but just not allow them to be edited in-situ? Could we instead provide a link to a page where the "open" order(s) can be edited (I am thinking of using the order confirmation page)? We can use the same page to allow edits to orders directly from the Account page.

Does that sound ok to you?

**Comment by oeoeaio** [comment] 2017-03-28 23:53
Something like this on the confirmation page:

![order_confirmation](https://cloud.githubusercontent.com/assets/2067859/24432435/fc325192-146d-11e7-9dd9-3d8dd81dc397.png)

**Comment by yukoosawa** [comment] 2017-03-29 00:29
So am thinking the following:
- It's ok to show the User their SO items with link to take them to edit (need to consider if/how they can return to their cart of yet-to-be-purchased items).
- However confirming SO items in an open cycle feels disjointed in the order confirmation page as the User has just confirmed their purchase.
- If we want to update the SO 'open order' flow in this manner, it might be best to always have the SO edit/confirm in a separate page (therefore the link from the User account page would always take them to this dedicated page).

What do you think? Let me know if I've misunderstood your suggestion in anyway - I tried to log into Staging1 to refresh my memory for the current order flow but it looks like account data has been wiped since I last logged in :)

**Comment by oeoeaio** [comment] 2017-03-29 01:05
@yukoosawa 

Yep, I think point three is what I am suggesting.

Point one (returning to cart) is my main concern also, still not sure how to resolve this. My feeling would be that users actually opting to edit their SO orders would be relatively uncommon, but we still need to work out how to redirect them to the cart if they opt to do this. Perhaps the 'Go Back to Store' link at the bottom of the confirmation page could be 'Go Back to Cart' if there is an incomplete order in the same OC?

With regard to point two, there is no real need to 'confirm' SO items for an open OC, as they are already 'locked in' when the OC opens. I would say the main benefit in displaying them in the cart is as a reminder to the customer that they are there, and to allow them to branch off to edit such orders separately if desired (if we add the edit link).

**Comment by yukoosawa** [comment] 2017-03-30 03:18
@oeoeaio Apologies for the late reply - missed your follow up comment.

Agree that in a Shopping Cart page:
1. User can see SO items in current OC with a link to edit.

In a SO edit page (for open OC):
1. User can cancel current standing order.
2. User can update current standing order.
3. User can return to cart to complete yet-to-be-purchased items in a cart.

In a confirmation page:
1. A link out to a separate SO edit page would work.
2. It doesn't make sense to provide a 'back to cart' link the bottom of the confirmation page given that the User has just completed purchasing the items from that store/cart.
3. A link back to the store (as you have it) makes sense as it allows the User to make more purchases (and typical User behaviour is to consistently buy from the one store).

**Comment by sigmundpetersen** [comment] 2018-08-30 07:01
Close this? @daniellemoorhead

**Comment by myriamboure** [comment] 2018-10-22 17:45
Ok so it seems the flow has changed quite a bit as 1- recurring orders are treated like any other order previously made on a given OC, and 2- At checkout the view is quite different, you can see items previously ordered and can delete them but can't do anything else. We need to clarify the management of "multiple ordering process" which becomes more urgent with the release of standing order feature. But it is broader issue than recurring order, so I will open a wishlist item specifying the issue with current process and proposal to move forward on that. But nothing else as far as standing orders are direclty concerned.

**Closed by myriamboure** 2018-10-22 17:45 UTC
Labels: Q1 2018, Q2 2018, Q3 2018, epic
