### ISSUE TITLE
A user can see in BOM shops that he has not authorizations for

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4087] opened 2019-07-29 08:28 UTC
## Description

An enterprise user can filter results in shop for shops she has no rights for.

## Expected Behavior

In "shops" filter in BOM, a user only can choose among shops she has access rights for (manager)

## Actual Behaviour

User can see shops she has no rights for.
Apparently, it seems it show shop for which the user **USED TO HAVE** manager rights, not all the shops.

## Steps to Reproduce

I tested with one of my own accounts (myriam@ouishare.net), not sure we can reproduce or if the bug only happens with old data.

1. As the user myriam@ouishare.net I had put myself some weeks ago manager of "Jardin de deux'main" entreprise (Guillaume shop!) but did remove myself straight away, it was just to do some support or test.
2. While connected with that account, in BOM I still see "Jardin de deux'main" even if I'm not anymore a manager...
![Capture du 2019-07-29 10-24-21](https://user-images.githubusercontent.com/8135376/62032940-281e0e00-b1eb-11e9-826b-515a83cb84e2.png)
![Capture du 2019-07-29 10-24-21](https://user-images.githubusercontent.com/8135376/62032895-163c6b00-b1eb-11e9-99ae-cfceea326991.png)

## Context

This was reported by Collectif Court Circuit in France

## Severity
I's annoying, polluting the user journey and filters, but doesn't prevent to use the feature.
bug-s4: it's annoying, but you can use it

## Your Environment

* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu 
* OFN Platform instance where you discovered the bug, and which version of the software they are using. French instance  v2.2.1

**Comment by luisramos0** [comment] 2019-07-29 11:07
I thought this would be a navigation of enterprise relationships.
Can you double check enterprise relationships? I think you can see it through being a manager of "Vélo bio bayeux" that can see Le Jardin...

Let me know.

DB query for devs reference:
```
select e.id, e.name, ee.id, ee.name from enterprise_roles er left join enterprises e on (er.enterprise_id = e.id) left join enterprise_relationships err on (err.child_id = e.id) left join enterprises ee on (ee.id = err.parent_id) where er.user_id = 237;
```

**Comment by RachL** [comment] 2022-04-25 13:11
I can't reproduce. Closing :)

**Closed by RachL** 2022-04-25 13:11 UTC
Labels: bug-s4
