### ISSUE TITLE
[Spree Upgrade] Fix ShippingMethods Create page

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#2744] opened 2018-09-18 21:12 UTC
Fix page /admin/shipping_methods/new

Currently broken with an error related to zone id.
It's a heavily defaced page, probably better to use the opportunity to move Spree code to OFN and create a view without deface.
Also, if the approach selected is removing deface, it's probably worth doing it in master and then adapting it to spree 2 in 2-0-stable.
Also, maybe we remove deface not just for new but also for index and edit pages.

This issue is related to #2010, same controller

**Comment by HugsDaniel** [comment] 2018-09-19 08:09
May I take this one ?

**Comment by luisramos0** [comment] 2018-09-19 09:11
Hi Hugo, yes!
You can see what Matt did here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/2675

You need to pick this
../spree/backend/app/views/spree/admin/shipping_methods
mix with this
./openfoodnetwork/app/overrides/spree/admin/shipping_methods
convert to haml
and put it here
./openfoodnetwork/app/views/admin

My only question is that I'd not put it in app/views/spree/admin as Matt did, I'd put it in app/views/admin

**Comment by luisramos0** [comment] 2018-09-19 09:12
You can see better as you go but it's probably better to have one PR per page: new, index and edit.
Also, as I say above, I think it's better to do this in master first.

**Comment by HugsDaniel** [comment] 2018-09-19 13:28
Also with spree step-6a used in master there's no method `zones` for Spree::ShippingMethods, it will end up crashing

**Comment by luisramos0** [comment] 2018-09-19 13:51
I'd check if step-6a is very different from 2-0-4 on this view.
If it is, I'd skip building it in master, but otherwise, I'd use step-6a to do this in master.
And then in 2-0-stable we can adapt to the changes like zone.
If you do it in 2-0-stable from 2-0-4-stable you will have to merge all changes that are done in master from now to the final migration...
What's easier?

**Comment by luisramos0** [comment] 2018-09-19 13:52
>>> I'm not sure rails will use the view if we put it in app/views/admin
yeah, that's true! we would have to change the route and controller. For this one, maybe easier to keep in spree/. Thanks, I was not seeing this problem.

**Comment by HugsDaniel** [comment] 2018-09-19 14:12
@luisramos0 there's a whole bunch of I18n syntax changes and a couple of sections added, it would seem easier to use directly 2-0-4-stable views

**Comment by luisramos0** [comment] 2018-09-19 14:33
all right, lets do that!

**Comment by luisramos0** [comment] 2018-09-19 15:17
Just leaving a note here to address question from #2728

**Comment by HugsDaniel** [comment] 2018-09-20 15:58
The `zone_id` error comes from the fact that there is no `zone_id` anymore in `spree_shipping_methods` table, instead we have a join table called `spree_shipping_methods_zones`.
In the form there's a field for zone_id, I'm not quite sure how to create a new record of `spree_shipping_methods_zones` instead... Nested form ? Do it in the controller ?

**Comment by HugsDaniel** [comment] 2018-09-20 16:05
The `zone_id` error comes from the fact that there's no `zone_id` in `spree_shipping_methods`, instead there's a join table called `spree_shipping_methods_zones`. I'm not quite sure how to create a new record of `spree_shipping_methods_zones` instead... Nested form ? Do it in the controller ?

**Comment by sigmundpetersen** [comment] 2018-09-20 17:29
Sure @luisramos0 no problem! Multiple PRs on one issue is a tricky one scrum-wise

**Comment by luisramos0** [comment] 2018-09-20 17:52
So, after a slack talk with Hugo, we conclude there are a few things to do here now:
- fix create shipping_method page by removing all zone_id section and testing the new version in spree 2 with zones (one important detail is to verify error cases where zone is not selected)
- add new shipping_method category section from spree 2 - in spree 2 at least one category must be selected for a given shipping_method, we can probably create a default category if we dont have it yet
- cover these screens with auto tests
- verify the question from #2728 mentioned above
- also, from #2695, verify associating shipping_methods to enterprises is working (from reading the code everything looks good), needs to be tested after this page is fixed.

I think that's all. makes sense @HugsDaniel ?

**Comment by luisramos0** [comment] 2018-09-22 17:58
I have just realized this issue is a duplicate of #2497. There's more context on this one now that we are fixing it, so I'll close #2497

**Comment by luisramos0** [comment] 2018-09-26 12:34
moving this to in dev to represent reality.
@HugsDaniel you finished most things [from my comment above](https://github.com/openfoodfoundation/openfoodnetwork/issues/2744#issuecomment-423275000) but not everything I believe. correct?

**Comment by HugsDaniel** [comment] 2018-09-27 05:49
@luisramos0 I'm on the question from #2728 , still haven't found out what's wrong here. I'll keep you posted

**Comment by HugsDaniel** [comment] 2018-10-17 14:28
I opened a new issue #2881 for the question in #2728 since it's slightly different from what was intended here. I close this one now.

**Closed by HugsDaniel** 2018-10-17 14:28 UTC

**Comment by luisramos0** [comment] 2018-10-18 14:49
Amazing, OFN v2 is starting to be usable! I gave this shipping methods UI a good try and it just works :-)
well done @HugsDaniel
