### ISSUE TITLE
[Flaky] /spec/system/admin/order_cycles/simple_spec.rb:704

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#9829] opened 2022-10-20 08:58 UTC
### What we should change and why (this is tech debt)

```
 Failures:

  1) 
    As an administrator
    I want to manage simple order cycles
 modify the minute of a order cycle with the keyboard, check that the modifications are taken into account
     Failure/Error: expect(page).to have_content "You have unsaved changes"
       expected to find text "You have unsaved changes" in "Logged in as : yoshiko.larson@faheyarmstrong.us Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS Admin Order Cycles NEW SCHEDULE NEW ORDER CYCLE QUICK SEARCH INVOLVING Any Enterprise SCHEDULE Any Schedule COLUMNS NAME SCHEDULES OPEN CLOSE COORDINATOR PRODUCTS None Enterprise 435 0 variants"
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3287398380/jobs/5416529471

**Comment by sigmundpetersen** [comment] 2022-10-20 10:22
I think this is a duplicate of #9805.
Closing

**Closed by sigmundpetersen** 2022-10-20 10:22 UTC
Labels: tech debt

**Comment by filipefurtad0** [comment] 2022-10-20 16:47
Thanks - I've missed that one :pray:
