### ISSUE TITLE
Customer gets the snail when editing an order marked as 'shipped'

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#9235] opened 2022-05-27 19:44 UTC
## Description

If a customer wants to edit an order which has been marked as shipped, the customer gets the snail. 

## Expected Behavior

The customer should not see the snail.
it shouldn't be possible to edit the shipped order.
## Actual Behaviour

The customer gets the snail.

## Steps to Reproduce

1. As a customer place an order.
2. As a shop manager capture the payment and mark the order as shipped.
3. As a customer go to your account and choose to edit the order.
4. Change the amount of an item.
5. Click Save changes.
6. See the snail.

## Animated Gif/Screenshot

![Peek 2022-05-27 21-31](https://user-images.githubusercontent.com/1790176/170778713-b49ff2d7-c87f-4b2c-a6f4-db59c09a83cc.gif)

## Workaround

No workaround for customers.

## Severity
??? bug-s3: a feature is broken but there is a workaround
??? bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.1.33
* Browser name and version: Firefox 100
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

**Comment by SamKnightGit** [comment] 2022-06-05 19:55
Hey y'all!

I am interested in getting involved with OFN, and am happy to take a stab at this issue. I have reproduced the bug but have a few clarifying questions about the expected state:
- Once an order has been shipped, do we only want to remove the **Edit** capability on the orders overview page and the quantity selector on the order page? 
- Is it possible to cancel an order once it has been shipped? If not, we should also be removing the **Cancel** option on orders overview and the **Cancel Order** button + trash button on the order page? Not sure how this would affect the **Changes Allowed Until** field...

Orders Overview Page:
![ofn_edit](https://user-images.githubusercontent.com/17261464/172067018-b257023e-9f5d-447d-b59c-5d65067987bc.png)
Order Page:
![ofn_order](https://user-images.githubusercontent.com/17261464/172067763-644b01c6-0a57-4444-b532-98539b7182e3.png)

- I have noticed some strange behavior when trying to **Cancel** an already shipped order, shown in the GIF below. Perhaps this should be filed as a separate issue?

![ofn_cancel](https://user-images.githubusercontent.com/17261464/172067651-910f791c-adf3-408d-9d76-313f04dc6426.gif)

Hope I can help!

**Comment by drummer83** [comment] 2022-06-05 20:50
Hi @SamKnightGit,

Great to have you here and WELCOME! :partying_face: :wave: 

It's great to see you digging into this issue! And you are asking very good questions! To my understanding it's a good solution to disable the **edit and cancel** options once an order has been marked as shipped - in real life you don't have a chance to change the order once it has left your enterprise. It should be listed in the list of 'past orders' instead of 'open orders'. It the backend it also doesn't seem to be possible to edit or cancel a shipped order. 
But to be sure let's wait for a comment of our @openfoodfoundation/train-drivers-product-owners to confirm the way forward. 

In the meantime, feel free to choose any other issue you like - like #8806, which I believe is the issue you have encountered during your tests, isn't it?

In case you are not aware: You can always drop a line on our [Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-19u50z3gk-ajGBK4r~iZfs1BAI03PQZQ) for general questions, or just comment here, as you just did!

Looking forward to your contributions! :rocket:

**Comment by aarozh** [comment] 2022-11-16 22:49
Can my partner and I both be assigned this issue?

**Comment by crystalysun** [comment] 2022-11-16 22:50
Hi I am Aaron's (aarozh) partner! Could we both be assigned?

**Comment by sigmundpetersen** [comment] 2022-11-17 07:50
I have assigned you. Thanks 💪

**Comment by sfayyad** [comment] 2022-12-02 05:24
Hi! If there hasn't been any progress on this task, I would love to work on it!

**Comment by drummer83** [comment] 2022-12-05 07:38
Hey @sfayyad,
it seems that @crystalysun is working on this one. Maybe best to have a look at another issue?

**Comment by RachL** [comment] 2022-12-19 14:38
Hello @crystalysun just checkin in: are you still planning to work or working on this issue?

**Comment by crystalysun** [comment] 2022-12-19 20:37
Hi @RachL , unfortunately we no longer have time to work on this issue, so feel free to assign it to someone else! Thanks

**Comment by mgrigoriev8109** [comment] 2023-01-12 15:19
Looks like no one is working on this, I'd like to give it a go.

**Comment by jibees** [comment] 2023-01-12 15:33
Hi @mgrigoriev8109 ! 👋 

I'll assign you. 

Thanks!!

**Comment by murjax** [comment] 2023-09-27 13:02
It looks like no one is assigned to this currently. Can I give it a try?

**Comment by drummer83** [comment] 2023-09-27 14:07
Sure, and welcome @murjax! I'll assign it to you.

Please have a look at the previous comments, there is some valuable information. And don't hesitate to get in touch here or in our Slack in case you have any questions.

Looking forward to your contribution! 🤗

**Comment by murjax** [comment] 2023-09-28 22:24
I have a question on this. Some context first:

The editable state of an order appears to be controlled be a method `Order#changes_allowed?`. This checks if the order meets these conditions:
- Order complete
- Distributor allows changes
- Order cycle is open

It doesn't account for order shipped. I'm thinking of adding a condition to ensure the order is not shipped yet. 

This check is also used in the account orders list to show open vs past orders. If I make the above change, **shipped orders will show as past orders.** 

**Screenshots**
Before shipped, order for $30.80 is open.
![Screenshot from 2023-09-28 18-04-45](https://github.com/openfoodfoundation/openfoodnetwork/assets/14116496/9d262b90-0370-42cd-baee-8fdf12c373c1)

After shipped, order for $30.80 is past.
![Screenshot from 2023-09-28 18-05-21](https://github.com/openfoodfoundation/openfoodnetwork/assets/14116496/42856a72-208b-451f-9da3-3ce6a003bedf)


**My question then is:** Are there any scenarios where we want to show shipped orders as still open?

**Comment by filipefurtad0** [comment] 2023-09-29 11:35
Hey @murjax , welcome - thanks for picking this one :muscle: 

> Are there any scenarios where we want to show shipped orders as still open?

I'd say no; shipped orders are always non-editable from the customers perspective and, as such, are fine to be considered past orders.

The approach you describe, i.e., adding a 4th condition sounds good to me. Orders would then appear as Open Orders, only when all for conditions are met:
- Order complete
- Distributor allows changes
- Order cycle is open
- Order not shipped

Having the order displayed as past order should not allow the customer do access it, and should prevent the error 500 :ok_hand:

**Closed** 2023-10-08 19:42 UTC
Labels: good first issue, bug-s4, hacktoberfest
