### ISSUE TITLE
Subscription Orders Failing for The Goodh Farm

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#5294] opened 2020-04-23 10:32 UTC
## Description

Order Cycle opening 21st April was the second week of generating subscription orders for 5 customers at Goodh Farm (UK).  Orders placed from the first week were generated correctly.
All five customers were sent emails stating that the products in their orders for the second week were out of stock.
Orders R654755880 and R757170603 appeared to be generated in the admin listing order page but unclear whether these were manually generated or placed by the subscription system.  
Enterprise is a shop with settings such that orders can be canceled or changed while the order cycle is open. Hence no payments are taken for subscriptions when the orders are first generated.

Full details of all five orders and failure messages here:
https://docs.google.com/document/d/1ci6KKn43ECXoaH7HgE5wqmWoR0t-pJyL1RuXhjOH6c4/edit?usp=sharing

One theory was :
Products which come up in the subscriptions are called:
Product Name + Variant Name + Display As

Products which system looks for when making an order are:
Product Name + Variant name + Unit Name

If Unit Name isn’t the same as Display As then Sub fails.

Tested this theory but couldn't reproduce.

## Expected Behavior

Order should be generated by a subscription.  Customer should receive an email when the order cycle opens stating the content of their order. If stock levels permit for the items requested then this email should state they will receive the items they want to buy.

## Actual Behaviour

Three out of five orders were not generated by their respective subscriptions this week.  For all five subscriptions the customer was sent an email stating that their products were out of stock and hence wouldn't be received this week.

## Steps to Reproduce

1. unable to reproduce
2.
3.
4.

## Severity

S2
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by lbwright22** [comment] 2020-04-23 10:37
![](https://github.trello.services/images/mini-trello-icon.png) [Issues with order cycle](https://trello.com/c/kH2koUhn/928-issues-with-order-cycle)

**Comment by luisramos0** [comment] 2020-04-23 10:51
both R654755880 and R757170603 are subs orders, you can verify that in the UI by listing the subscriptions and than editing the placed order in the subscription, right? this is an important existing feature I believe.

I cant remember, but arent all subs payments taken only on confirmation (end of the OC)? rather than placement (generation).

Can you be more specific about the "Actual Behaviour" and "Expected behaviour"?
Looking at the database it looks like the orders were correctly placed and then cancelled by the user or manager. The content of the orders looks good, the line items are there as well.
What exactly you think is not correct? Is it just the email to the user or is there something else?

To your knowledge what were the manual actions performed on these orders by the user or manager?

**Comment by lbwright22** [comment] 2020-04-23 10:54
The email to the customer was wrong for all five subscriptions.
Three out of the five didn't generate any order.
I canceled the orders manually. I don't know what the user or hub manager did.

**Comment by luisramos0** [comment] 2020-04-23 11:24
ok, I think I have a clue, at the beginning of the OC when the orders were being placed there were 2 subscriptions for each user in the system (I wonder if this is something easy to do by a user, create a subscription for a customer with a subscription already created **for the same schedule**). The cancellation date of the duplicate subscriptions is after the beginning of the OC (yesterday at 8h43).

Anyway, I see 5 generated orders in the system that look good, are these not correct?
 R325461732
 R550368773
 R477730153
 R236076680
 R754547715

An explanation for this issue could be: the user created 2 subs for each customer and the duplicate subs failed to be placed, the other subs worked well. Important fact: the duplicate subs were cancelled after the OC opened.

**Comment by lbwright22** [comment] 2020-04-23 11:57
The orders on the system are the duplicate subs I created yesterday.

5 subs were meant to generate orders on 21st April- 2 did and 3 didn't.
I canceled all 5 subscriptions on 22nd April and then re-created (so that the customers got their items and to help the hub manager)-> these are the 5 open orders showing which are OK :-)

Sorry, I realise by deleting and recreating I have made things confusing but this is the 2nd week in a row the user has had problems and I know it is causing problems with her older customers fearing they won't get the food they need while self isolating.

**Comment by luisramos0** [comment] 2020-04-23 12:09
That is important information :-)

I have the 5 initial orders now:
 R344278214
 R260881305
 R757170603
 R861000662
 R654755880

The failed 3 are there, they were just not completed because they are empty...

We need to have a look at the managers summary email. Can you ask the manager for that email?

One issue that can come out of this: we should probably store that summary somewhere on our logs, we are not doing that currently. And also we should probably save all changes done to a subscription, we are not doing that yet.

**Comment by sauloperez** [comment] 2020-05-15 10:54
#5333 is already in production and #5334 is included in v2.9.9 so it'll land production next Tuesday. I'm closing this then, as agreed in the delivery train meeting. Next time this happens will have more insights to diagnose the issue.

**Closed by sauloperez** 2020-05-15 10:54 UTC
Labels: bug-s2
