### ISSUE TITLE
Cannot delete a taxon

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1042] opened 2016-06-16 18:07 UTC
We have come up with these changes that we want to make to the taxons on UK production
[Changes to taxons on UK production.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/319042/Changes.to.taxons.on.UK.production.pdf)

But when I try to make the first deletion in superadmin it says 'LOADING" for 1-2 minutes then I get this error:
The server returned an error
The requested change has not been accepted and the tree has been returned to its previous state, please try again.

![screenshot 2016-06-16 18 59 44](https://cloud.githubusercontent.com/assets/10517702/16127640/40a91482-33f5-11e6-9a2b-de9b540b84a1.png)

If we can resolve this by Friday 17th I can make these changes.  If not please could @MagsHall make these changes in superadmin when this error is resolved?  Any queries on the detail of the changes, please ask @OliverUK or @sararock

Thanks and sorry to leave you with this Mags

**Comment by NickWeir63** [comment] 2016-06-16 19:02
I thought i might be getting this message because you can't delete a taxon that is assigned to a product so I edited all the products that were assigned to "oils and vinegars" and moved them to "other foods"...........
![screenshot 2016-06-16 19 59 24](https://cloud.githubusercontent.com/assets/10517702/16129598/3b14a2fe-33fd-11e6-9b08-13d95aa2719b.png)

But then still got the same error message when I tried to delete the "oils and vinegars" taxon

**Comment by OliverUK** [comment] 2016-06-16 20:37
I can obviously only test this for Stroudco products but if I look up our "flour" category as below
<img width="1081" alt="screen shot 2016-06-16 at 21 29 29" src="https://cloud.githubusercontent.com/assets/17590921/16132068/94504dd0-3409-11e6-9420-6b47a46d4dc8.png">
It looks empty but the shop front still shows them
<img width="1189" alt="screen shot 2016-06-16 at 21 29 36" src="https://cloud.githubusercontent.com/assets/17590921/16132082/a634b612-3409-11e6-89a5-00850e2d67db.png">

After I tried to recategorise items in BEP by displaying the category column and changing the category drop-down, I found this only adds another category to the existing one. Although the item disappears from the filtered view as in the first screenshot above, the category remains as shown below. 
<img width="758" alt="screen shot 2016-06-16 at 21 32 04" src="https://cloud.githubusercontent.com/assets/17590921/16132216/20289a24-340a-11e6-90dc-ffb417229f74.png">

Is it possible therefore that that vinegar category still has items in it which are not visible in BEP? Maybe from Tamar Valley?

**Comment by NickWeir63** [comment] 2016-06-16 21:16
Nice thought @OliverUK thanks but i think the reason the Stroudco flours were still showing is because they had not been deleted from the bottom taxon box.  It seems that the way the taxons work is that the category box at the top of this screen allows you to carry on adding categories so that a product can be in multiple categories and if you want to remove it from a category you have to take it out of the TAXON box at the bottom.  So that is what I did with all the Stroudco flours - clicking on the 'X' to the left of "Products>Dry Goods>Flour" to remove it from the TAXON box then updating the product.  After I did this with all the Stroudco flours the category disappeared off the shopfront - see below.
When I did the 'oils and vinegars' test above I was in superadmin and it showed up all products across all UK users so I am pretty sure that nothing is using that taxon now........
But thanks for the thought.  Anyone else got any ideas?  @MagsHall ?
![screenshot 2016-06-16 22 12 52](https://cloud.githubusercontent.com/assets/10517702/16133476/e8225d8a-340f-11e6-8b90-a6700d79a00f.png)

**Comment by NickWeir63** [comment] 2016-06-16 21:52
......ah sorry @OliverUK I have only just got it.....  You are saying that there may be some UK products that are using "oils and vinegars" but I cant see them when I use that filter because @oils and vinegars' is not the latest category to be added to the TAXON box of those products.  Good point!  @lin-d-hop is there any way I can get a listing of all products using a particular taxon?  When I click on the 'All products' report in superadmin (see screenshot) I get the hungry slug error message
![screenshot 2016-06-16 22 49 10](https://cloud.githubusercontent.com/assets/10517702/16134414/f201e1fe-3414-11e6-8c82-793f6c8b61f2.png)

**Comment by OliverUK** [comment] 2016-06-17 08:59
When I try the report, it does work, obviously not giving me all the products in the UK. 

In any case it would still leave me with having to edit each individual product in order to empty a category, right?

**Comment by NickWeir63** [comment] 2016-06-17 13:38
Yes i was just trying to identify the cause of the server error above and if this was it then seem if Lynne might have a clever way of deleting any taxons for the categories we want to delete.

Yes oddly I can also get the 'All Products' report when i use my regular login.  it is just the superadmin login that gets the hungry slug....

**Comment by NickWeir63** [comment] 2016-06-17 13:45
Thanks @MagsHall for picking this one up.  Mags is away from Sunday 19th for a week but has agreed to do the superadmin job of editing the taxon table when she is back the following week assuming that we have been able to resolve the server error above.
Sorry @OliverUK and @sararaock for the delay

**Comment by lin-d-hop** [comment] 2016-06-17 14:31
Looks like a timeout on that page.... 
I can delete empty taxons, or make a list of culprit products and producers. 

Looked at this a little in #813. There is a bug in there but at the moment I'm not sure a proper fix is the best route.

**Comment by NickWeir63** [comment] 2016-06-17 15:38
Thanks @lin-d-hop  Yes please I think it would be good to have a list of culprit products and producers and then if it is not too long we can do some manual editing if this will get round the problem.

**Comment by OliverUK** [comment] 2016-06-20 20:31
@lin-d-hop  I think you described it well in #813. Is the conclusion that for the purpose of deleting categories we have to manually remove them from each product and that bulk product management can't help us here?

**Comment by OliverUK** [comment] 2016-06-21 21:38
@lin-d-hop for Stroudco I have manually emptied some categories now by editing each product individually. This removes the category from the shop front until a producer decides to use it again and I can't stop them do that. Is there anything else I can do to help edit other hubs' listings?

**Comment by lin-d-hop** [comment] 2016-06-29 15:20
Closing as duplicate of #813

**Closed by lin-d-hop** 2016-06-29 15:20 UTC
