### ISSUE TITLE
[Spree 2 Upgrade] undefined method `zone_id` for ShippingMethod

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/openfoodnetwork#2497] opened 2018-07-23 11:56 UTC
## Description
While trying to create a shipping method from `/admin` I got the following error in the Rails server:

```
Completed 500 Internal Server Error in 442.9ms (ActiveRecord: 5.7ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `zone_id' for #<Spree::ShippingMethod:0x00562b39694b40>):
    26:       <%= f.label :zone_id, t(:zone) %>
    27:     </div>
    28:     <div class="omega eight columns">
    29:       <%= f.collection_select(:zone_id, @available_zones, :id, :name, {}, {:class => 'select2 fullwidth'}) %>
    30:       <%= error_message_on :shipping_method, :zone_id %>
    31:     </div>
    32:   </div>
  lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
  lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
```

It seems like the `zone_id` column was moved out of the `spree_shipping_methods` table.

## Expected Behavior
Shipping methods can be created from `/admin`. This deserves some initial investigation which might change the scope of this issue. It could be harder than a simple one-PR fix.

## Actual Behavior
The app displays the error showed above.

## Steps to Reproduce
Visit `/admin/shipping_methods/new`.

**Comment by luisramos0** [comment] 2018-08-24 09:28
To get the top level epic cleaner, I moved this one under the epic #2497 Checkout. This is in the backoffice but the work is closely related to  the shipping methods in the checkout process.

**Comment by luisramos0** [comment] 2018-09-22 18:00
I just realized  #2744 is an exact duplicate of this issue. My mistake, didnt see the duplication. Closing this one as 2744 has now more info and context.

**Closed by luisramos0** 2018-09-22 18:00 UTC
Labels: spike
