### ISSUE TITLE
Variant images not displaying

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#913] opened 2016-04-20 18:30 UTC
we have put images for 3 product variants of Veanda Olive Oil but they are not showing on the shopfront
![screenshot 2016-04-20 19 28 09](https://cloud.githubusercontent.com/assets/10517702/14685872/52ee78c4-072e-11e6-89f2-0ba98fdf4766.png)
![screenshot 2016-04-20 19 28 31](https://cloud.githubusercontent.com/assets/10517702/14685873/52ef274c-072e-11e6-8ea7-23ce77d8cf57.png)

**Comment by lin-d-hop** [comment] 2016-06-30 14:44
@sstead How is this being handled in Aus?
It would take a bit of redesign to handle actually displaying all the variant images nicely in the shopfront. My temptation would be to disable variant images and just use a single product image. This seems to be common practice for other ecommerce sites so I don't feel a problem from a usability perspective.

**Comment by sstead** [comment] 2016-07-01 01:10
Hi @lin-d-hop - this has been picked up previously here in Aus, although we haven't had any users encountering the problem. https://github.com/openfoodfoundation/openfoodnetwork/issues/552 . There are 3 suggested solutions in that issue, one being your idea of getting rid of variant images and just having 1 product image. Currently there would be no real loss in doing this, however I'm not sure whether in future someone might like to have individual variant product detail boxes etc. If so, perhaps option 1 or 3 in #552 could be an alternative.

**Comment by lin-d-hop** [comment] 2016-11-05 14:05
closing as duplicate of #552 and better described there.

**Closed by lin-d-hop** 2016-11-05 14:05 UTC
Labels: bug, uk
