### ISSUE TITLE
Product name and photo corruption

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7839] opened 2021-06-25 10:08 UTC
## Description

Reported by UK food hub ID 201177

Some products owned by the food hub have changed name and image in the past month (only now discovered) without knowledge from the food hub managers.

## Expected Behavior

Unless a product's name and image is edited by a food hub manager they remain constant.

## Actual Behaviour

Changes have occurred to a subset of products owned by Cambridge Food Hub:

- Apples (Spartan) was renamed 'White Mulberry Powder' (a product owned by Mondeco Limited).  The Mondeco product remained unchanged.  Photo removed
- Apples upwell was renamed 'White Quinoa 450g' (products owned by Hodmedods MASTER). Photo of apples remains
- Amisa Crispy Spelt flakes owned by Windmill Organics (managed by Cambridge Food Hub) was renamed 'Totally Cultured Water Kefir Lemon and Caradon' Photo unchanged. product also exists by this name from the enterprise Totally Cultured
- Amisa fussuli owned by Windmill Organics (managed by Cambridge Food Hub) was renamed 'Totally Cultured Water Kefir Lemon and Mint' Photo unchanged. product also exists by this name from the enterprise Totally Cultured
- Amisa dark chocolate owned by Windmill Organics (managed by Cambridge Food Hub) was renamed 'Totally Cultured Water Kefir Lemon and Rose' Photo removed. product also exists by this name from the enterprise Totally Cultured
- apples Blaze owned by Cambridge Food Hub was renamed 'wheat bran organic' 
- apples russet owned by Cambridge Food Hub was renamed 'White mezzi..' (product owned by Hodmedods MASTER). Photo updated to that of the pasta.  Hodmedods product remains unchanged.

In each case 

- The product description not updated.
- Cambridge Food Hub has permission to manage the product listings of all the hubs involved.
- Typically it was Cambridge products starting with 'A' which were affected and have been renamed by products with names from the end of the alphabet.
- Permalink unchanged.

![whitemezzi2](https://user-images.githubusercontent.com/45104035/123409435-17789d00-d5a6-11eb-8d52-c5285e43d90a.jpg)
![whitemezzicamb](https://user-images.githubusercontent.com/45104035/123409438-18113380-d5a6-11eb-9e07-dd6fc46bd3dc.jpg)
![whitemezzihodmedods](https://user-images.githubusercontent.com/45104035/123409440-18113380-d5a6-11eb-9a18-8e76bd11a2e5.jpg)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by tschumilas** [comment] 2021-06-25 15:21
Just a note to say that I had a user last week whose products were scrambled -   the description for product A was attached to product B etc.   I saw the messed up product list.  She deleted and re entered the products and they were fine.  It was about 20 products in her list.  Frankly,  I assumed it was user error until I read this.  Now I wonder...    I have no idea how to reproduce,  except she said she was cloning products -   @lbwright22 do you know if your user was cloning products?

**Comment by lbwright22** [comment] 2021-06-25 15:28
from Evonne (OFN Ireland) 
This is what happened last week here in Ireland when I was changing product listing to fix the unit pricing. At the time it looked to me like product duplications in the very shopfront I was working on. But later when tidying up I realised it was just the product name that had changed, the permalink was for the 'original' product and there were no images in place for any of them so that didn't come into it.

**Comment by lin-d-hop** [comment] 2021-06-26 13:58
This sounds ugly and while we dont know the cause it has the potential to create incorrect orders.

It doesn't instantly seem like something we can debug but reports across three instances is worrying.

I want to putt s2 on this to investigate and see if there is any information we can gather to the cause. 

Possible things to look into:
- Something weird happening when products are cloned
- Could this be a UX bug that results in users doing something that don't realise they are doing

I suggest that a first step here might be a quick brainstorm about what might be causing this.
@Matt-Yorkley is there anything in your recent changes that might cause this?
@filipefurtad0 can you think of anything in the UX that might cause this behaviour. 

**Note the UK user (at least) is a very experienced user.**

**Comment by lin-d-hop** [comment] 2021-06-26 13:58
maybe we discuss this in delivery train if no one gets to it before...

**Comment by Matt-Yorkley** [comment] 2021-06-27 18:03
So everything is untouched except the product's name? I can't think of anything merged recently which would lead to product names being updated in any way... :man_shrugging: 

I'll take a look though.

**Comment by Matt-Yorkley** [comment] 2021-06-27 18:49
**Initial notes:**

Not much to go on here except a symptom that doesn't make sense and doesn't have an obvious cause.

We have reports from UK, CA, and IE, but the latest release hasn't been deployed to UK or CA yet, so... I guess that puts the timeframe at more like 2-3 weeks, which potentially puts the Rails 6.0 upgrade in the frame..? Changes to the basic attributes of multiple products makes me think the bulk edit products page is the most likely vector.

Based on that, I'd say this this is the best cue about where we need to look: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6001f06a51b8140017581069?filters[event.since][0]=30d&filters[error.status][0]=open

**Comment by filipefurtad0** [comment] 2021-06-28 11:12
No luck so far, from my side.

On `/products` page, I tried editing the "display as" field and then (without clicking `Save Changes`):
- cloning products
- clicking "Name" to re-order products according to name - the mix-up seems to relate to alphabetical ordering: reordering removes any edits on the variants but keeps the "Save changes" visible; clicking it does nothing though.

This was done for products managed by a hub (with permisssions), and own produce.

Not sure what else to test...

**Comment by lin-d-hop** [comment] 2021-07-01 16:05
Thanks for these investigations @Matt-Yorkley and @filipefurtad0 

Can you think of anything that we can pass on to support teams that might help us get more information from them?

I don't want to chase a wild goose down a rabbit hole.... so I'm really happy to close this. However with so many reports it's likely we'll be hearing of it again so it would be good to know if there is any way to get more information.

**Comment by andrewpbrett** [comment] 2021-07-01 18:02
@lin-d-hop it would be good to confirm, if we can, what people are doing when they encounter this. In the UK instance it sounds like they didn't notice until much later, but for IE and CA it sounds like they noticed pretty quickly and said they were cloning products (CA) and updating unit prices (IE). 

It would help to know if it's always on the Bulk Edit Products screen that this happens. Cloning can only happen on the Bulk Edit page (I'm pretty sure) but unit prices can be changed from the individual product pages (though I suspect that someone would be doing it from the Bulk screen). 

I think if we find out fast enough, we could probably search the production logs on the right server and look at the parameters coming in to the Admin::ProductsController#bulk_update method, which would be another good clue. 

I looked at the Bugsnag that @Matt-Yorkley and I think it might be a dead end unfortunately - there's also no matching Bugsnag for CA. I suppose they could have different root causes and therefore different signatures though.

**Comment by Matt-Yorkley** [comment] 2021-07-01 18:17
Yeah I didn't manage to find any solid leads to act on. Maybe this bit from @filipefurtad0's investigation is a good place to investigate:
> (the mix-up seems to relate to alphabetical ordering, from the description in the issue): reordering removes any edits on the variants but keeps the "Save changes" visible

**Comment by andrewpbrett** [comment] 2021-07-01 18:21
Hm yeah but if I do this: 
1) make a change, don't save
2) Reorder by clicking on name

I see the Save changes button is still there, but then clicking it gives me "No changes to save". 

There might be something else with reordering that I'm not thinking of though.

**Comment by tschumilas** [comment] 2021-07-01 19:04
This just happened to me while editing my own product list -  so i know what I was doing at the time.....
I was editing a product description -  so was not on the bulk products list -  I was on the secondary edit screen for the product.
I updated the change.
Then I used the back button on my browser (latest Chrome) to go back to where I was in my bulk product list (because I think? using the app's 'back to product list'  button doesn't take me back to exactly where I was.  There are 300 plus products in my list so when I'm editing,  I need to go back to where I left off...)
Something odd happened -  it was like the screen froze for a 5 seconds or so.  Then it went back to my product list -  and I saw duplicate products created -   they were created correctly (prices, units....) except the image was wrong.
It happened to about 6 products -  seemed random.

I deleted the duplicates with the wrong images.

I did did the same thing again -   went to the secondary edit screen,  made a change,  hit update,   use my browser back button ---  and again,  there were products created with images corrupted.


So -  I was not cloning these products -  we can rule that out.

**Comment by andrewpbrett** [comment] 2021-07-01 19:33
Were these the ones that got duplicated? ["Roses Cut - Baroness", "Roses Cut - Charming Plano", "Roses Cut - Lemon Pompon", "Roses Cut - Mariatheresia", "Roses Cut - Midsummer"]

**Comment by tschumilas** [comment] 2021-07-01 19:51
No -  those are products from Palatine Roses -  and she IS the enterprise that firt alerted me to the scrambled products.  That was 2 weeks ago -  and I don't recall which products were her problem ones.    For me   this happened just when I first posted above -  but foolishly perhaps I deleted the problem duplicates.       Allium,  Feverfew,   ... damn it ... I should have made a list.

**Comment by tschumilas** [comment] 2021-07-01 19:51
Its just this is my 'real' product list and the hub opens in 30 minutes so I was racing to get my list fixed.  But I'm going to try to replicate in a demo hub....

**Comment by tschumilas** [comment] 2021-07-01 20:13
I just replicated again -   In Garden Party Flower Farm -  I changed the description for the product 'Bupleurem'.  I updated.  I then used my browser back arrow to go back to the bulk edit product list,  and several products are now scrambled and its telling me 15 products have unsaved changes --- but I only edited bupleurem and I saved the change.   This time there are no duplicates,  but existing products are scrambled:  Calendula -  now has a different picture,  Calla Lily and foliage -  has the wrong image,       and others too.  But I couldn't leave them for you to see  because the shop is opening.    So - I didn't save the changes as prompted,   and when I went back into the product list,  all was well.  the change I made and saved to 'bupleurem'  is fine,   and the mixed up images and my product universe is back to normal.    So....  whatever this is -  its not permanent it seems,  if the user doesn't save the changes as prompted.     I don't understand what a back button on a browser does...   but each time I've replicated this is what I've done.   But I've only been able to replicate in my Garden Party Flower Farm product list so far.....   making me feel like I'm losing my mind....

**Comment by tschumilas** [comment] 2021-07-01 20:30
also just observing -  the products this happened to were also over-ridden in an inventory.     
At least I know we can make it happen in my product list --   so maybe when my current order cycle closes (Monday am) I can experiment more with that list.    Tell me what to try,  what to note,  what screenshots to take....   This might be a quicker way to figure this out,  given we seem to have a product list where we can make it happen.

**Comment by filipefurtad0** [comment] 2021-07-01 20:44
Hey Theresa, thanks for digging in into this. A video would be great, but in case you have troubles in recording one I'd be happy to jump on a quick call, so you can show it live. Hopefully then we can reproduce it in staging/local setups... Feel free to ping me on Monday, if you'd like.

**Comment by tschumilas** [comment] 2021-07-01 23:43
I can't try again until I'm no longer supplying order cycles.  This really messed up all my invoice and product tracking for last weeks orders.  Because when it happened earlier this evening -  i was updating for the order cycle that opened today -   but the corruption changed the name and pic of the product on the order & invoice for last week's orders.  (and then I stupidly made things worse by deleting products that were on those invoices -  so I couldn't just delete the corrupt products from the invoice and enter new ones).  But just to show you --- see this order -  it shows the incorrect product name and pic on the order,  but the two enterprise fees applied to this product  still reference the correct/original product name.

Anyway -  I'll try again with my own product list once the order cycles are closed.   I'll try a video.
![order admin issue -  product naming problem](https://user-images.githubusercontent.com/13171778/124200952-a143d100-daa4-11eb-8a2e-aac2e2ee3b98.png)

**Comment by andrewpbrett** [comment] 2021-07-02 03:40
Thanks for all the details @tschumilas. 

The last screenshot you sent actually looks like a separate bug, in that the (unintended) change to the product name is not reflected in the line item adjustment. CA does not yet have the release with the adjustments work (v3.8.3) so it's possible that this will be fixed in that version (@Matt-Yorkley may know more). 

I looked through the logs some more and I'm not seeing anything jump out at me as far as an explanation. The only thing I noticed is that when you're on the Bulk Edit Products page, you have filters applied, but I don't see how that could be creating a POST request to create/change products.... very puzzling. 

I'm wondering if the other reports from UK/IE match this behavior. I can't imagine there would be two unrelated bugs that both produced the same result, but the one bug might be reproducible in different ways. 

I think that if we can reproduce it this reliably, it should be easy to track down once the shop is closed again, maybe with a video and someone watching the logs at the same time.

**Comment by filipefurtad0** [comment] 2021-07-06 11:25
The pic you display on your last comment is reproducible in staging as well @tschumilas :

![Peek 2021-07-06 11-50](https://user-images.githubusercontent.com/49817236/124588408-aa3ff400-de50-11eb-887e-a2a73a2c5126.gif)

But it does not seem to be breaking or introduce incorrect information on any of the invoice templates, though:

![image](https://user-images.githubusercontent.com/49817236/124588550-d8bdcf00-de50-11eb-9144-d279a57b47a6.png)

The product list also looks ok. So indeed it looks like a separate issue.

**Comment by filipefurtad0** [comment] 2021-07-07 10:35
Hey @tschumilas , if the respective order cycle closed and you're available do feel free to ping me for a quick call on this, at some point this week :+1:

**Comment by tschumilas** [comment] 2021-07-07 11:55
What time zone are you in?   I can look at this  later today (Wed).  The order cycle opens Thursday at 4:00 this week --  so its a small window.

**Comment by filipefurtad0** [comment] 2021-07-07 14:46
Pinging you on Slack Theresa.

**Comment by tschumilas** [comment] 2021-07-08 00:37
I think I've narrowed this one down more......
If a variant is edited and then the browser (I'm using Chrome) back arrow is used instead of the app's 'back to product list' button,  this can cause a corruption in the product list.  In which,  product names and variant names for existing products  -  starting at the beginning of the list alphabetically,  are over-written by product and variant names from the part of the product list around where the trigger edit happened.  The picture is unaffected,  and price is unaffected.  But the names and variant names are over written.   It seems to happen to 11 variants.   You can tell the correct variant name because the permalink is unchanged.    

But this is not a permanent change.   After editing a variant,  updating it,  then using the browser (Chrome) back arrow -  the user is presented with a message that xx variants need to be saved.   If I select 'yes' to save -  then indeed,  I've just over-written the content in my product list.  (And its a mess....)   But if I do not save,  and just 'close'  the list,  or move to the next screen...  the product list is unaffected.

To further complicate....   this only happens if the following conditions are met:
1. The trigger product (the one being edited) has its price  over written in an inventory (not stock)
2. That inventory manager has selected 'coordinator's inventory only' in the order cycle
3. The product has producer set stock on hand

How weird is this????   Solution is simply to always use the app's 'back to product list' button.   But the two of us here in OFN_CAN who experienced this,  use back arrows because we have 12 - 15 pages of products in our list.  When editing,  we go through alphabetically,  page by page,   so we want to return to the last product we were editing,  not the beginning of the list again -  and 'back to product list'  takes you to the beginning again.

Hey @filipefurtad0 - I can show you this tomorrow if you want --- I'm pretty sure this is it.   I think to replicate you need to have products,  where price (not stock) is over written in an inventory,  and the product has stock,  and where the OC is set to 'coordinator's inventory only' -  and edit a product that is over written in inventory and use chrome's back arrows.   (How come I can't find a little celebration giffy from github to paste here now.)

**Comment by filipefurtad0** [comment] 2021-07-08 13:47
Thank you @tschumilas, for all the investigation and taking the time to show this to me. We had a tough time there :sweat_smile: but I think we've finally nailed it.

There are plenty of things happening at the same time. It seems the bug is happening in Chrome only, steps to reproduce:

- a long product list, over several pages
- select the 4th page (or the last page) of your product list
- click the pencil to edit the product
- change the product description (on page `/admin/products/<permalink>/edit`)
- instead of clicking "Back to product list", click on the back arrow
- on `Chrome` you'll need to click twice; on Firefox this is not the case, one click suffices and navigates back to the `/product` page
- on the /product page, a warning should be visible, pointing out the corrupt products

![Peek 2021-07-08 14-31](https://user-images.githubusercontent.com/49817236/124930650-6cca9a80-dff9-11eb-9749-133d8abee285.gif)

Nonetheless, there are two other bugs, which were quite distracting:
- the issue pointed out by Theresa and summed up on [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/7839#issuecomment-874679896) (needs an issue)
- Product appearing twice in the "Incoming" section of order-cycles #7885

I'm tempted to say that the present issue relates to pagination (only?), and that replacing kaminari with pagy would solve this (fingers crossed :crossed_fingers: ) - this is @apricot12 's PR #7823 :muscle: 
I'll test hypothesis and get back to this bug again.

**Comment by lin-d-hop** [comment] 2021-07-08 13:51
Such great detective work! Go team!

**Comment by andrewpbrett** [comment] 2021-07-09 01:29
Thanks for figuring this out @filipefurtad0! Alas, when I follow those steps logged in as a super admin on UK staging, I don't see the message that I have changes to unsaved products... but perhaps that's actually a clue as to what's going on, if it's not happening for all accounts. Could you maybe DM me the credentials for the account you're using so I can see if I can trigger the bug by editing that same product?

**Comment by andrewpbrett** [comment] 2021-07-12 21:22
I think I've made some headway in determining what's going on here. 

In the original report @lbwright22 said:
> Typically it was Cambridge products starting with 'A' which were affected and have been renamed by products with names from the end of the alphabet.

This also fits with the finding from @filipefurtad0 and @tschumilas that to reproduce this, you have to be on a paginated product list and go from a page other than the first page to the edit product page, and then click the browser's back button (twice). 

This returns you to the first page of /admin/products, regardless of what page you were on. 

Here's the fun part: it appears that Chrome "helpfully" remembers the values that were filled in the last time it saw a form that looked like this - but the last time it saw this form, you were on page 2. So, for example, if page 2 of the products list has "Mackerel" in the fifth name field, now, back on page 1, Chrome sticks "Mackerel" in the fifth name field, even though the fifth name field corresponds to a totally different product now because we're on page 1. 

There's no indication that the field has been auto-updated, which is a really great design pattern 🙄 

Firefox and Safari don't seem to reproduce the issue (but there have been a couple times I've tried to reproduce it with Chrome and it hasn't appeared). I believe it's specific to Chrome. 

I thought I remembered seeing some changes to saving people's place on the bulk product list fairly recently, but scanning through the release notes I'm not finding anything. 

One potential way to avoid this issue would be if we *did* save your place on the bulk product list page, by sending you to a url with a param for the page. I'm a little surprised we don't already do this actually. 

It also looks like adding `autocomplete: false` to the form element may do the trick.

**Comment by andrewpbrett** [comment] 2021-07-12 21:59
Yep, this should be fixed now with that PR. I just tested on AU Staging. Pinging @filipefurtad0 and @Matt-Yorkley since this should be pretty straightforward to review and test, we could probably included it in this week's release 🚀

**Comment by andrewpbrett** [comment] 2021-07-12 22:19
@tschumilas you posted above:

> But the two of us here in OFN_CAN who experienced this, use back arrows because we have 12 - 15 pages of products in our list. When editing, we go through alphabetically, page by page, so we want to return to the last product we were editing, not the beginning of the list again - and 'back to product list' takes you to the beginning again.

As far as I can tell nothing has changed recently in OFN around these screens. So when you were hitting the back button, I believe you **were** actually going to the beginning again, but because Chrome was autofilling the names of the products from the last page you were on, it **looked like** you were returning to that page. I'm not positive that nothing has changed, and it could also have changed because you changed versions of Chrome, or some other variable...but seemed worth flagging that if this has been a common workflow for you, you may have been corrupting a lot of products.

**Closed** 2021-07-13 11:22 UTC
Labels: bug-s2
