### ISSUE TITLE
Restyle shop header

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2708] opened 2018-09-13 11:26 UTC
* White background
* Grey menu text
* Blue highlight when selected 

![image](https://user-images.githubusercontent.com/2911176/46518958-ffbecf00-c8b9-11e8-9105-d1d0f233cba3.png)

![image](https://user-images.githubusercontent.com/2911176/46518972-0b11fa80-c8ba-11e8-9c10-7c9d177d8c2b.png)

![image](https://user-images.githubusercontent.com/2911176/46518854-a9519080-c8b9-11e8-8b40-a6c847eac479.png)
zeplin: https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5b957e1fd374679ce5dc587d

**Comment by kirstenalarsen** [comment] 2018-10-05 06:18
see slides for responsive grid etc - https://docs.google.com/presentation/d/10I8-3mRjxnPUXtEk04X3UERVPEPvqPjrEdF37_1KpmE/edit#slide=id.g40ea76c80f_0_18

**Comment by Matt-Yorkley** [comment] 2019-06-20 22:43
I think I was asked to move it because someone started working on it, but I guess it didn't get finished.

**Comment by daniellemoorhead** [comment] 2019-12-13 05:16
Duplicate of #4567

**Closed by daniellemoorhead** 2019-12-13 05:16 UTC
Labels: Hacktoberfest, socialissues.tech
