### ISSUE TITLE
"About" and "producers" sections are empty on the shopfront at basket & checkout stage

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#4275] opened 2019-09-19 13:11 UTC
## Description
When I'm on the shopfront url I see  the "about" and producers" sections :
![Capture du 2019-09-19 15-06-43](https://user-images.githubusercontent.com/8135376/65246575-25ef7600-daef-11e9-99f4-e937eb58b9f8.png)
![Capture du 2019-09-19 15-06-59](https://user-images.githubusercontent.com/8135376/65246583-28ea6680-daef-11e9-9394-180e072821d1.png)

BUT when I click on "basket" and/or "checkout", then those sections disappear:
![Capture du 2019-09-19 15-07-58](https://user-images.githubusercontent.com/8135376/65246664-50413380-daef-11e9-89c9-a3b36a9ae0d8.png)
![Capture du 2019-09-19 15-08-10](https://user-images.githubusercontent.com/8135376/65246679-546d5100-daef-11e9-8c0b-71ae048d1c5e.png)

## Expected Behavior
About and producers sections are visible in all the shopping journey on the shopfront

## Actual Behaviour
They are not

## Steps to Reproduce
1. On the shopfront, click to display the sections
2. Add a product to tje basket, go to basket, click again to see the sections
3. Do the same at checkout stage

## Context
Notices that when doing user onboarding / setting up OC and checking everything was good.

## Severity
bug-s3: I think it's annoying but at basket and checkout we can hope the user have already checked those sections before ? But would be great to fix quite early as front end issue visible to customers.

## Your Environment

* Version used: 2.4.1
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu
* OFN Platform instance where you discovered the bug : French production

**Comment by RachL** [comment] 2019-09-19 13:14
I believe this is a duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/4208 so closing

**Closed by RachL** 2019-09-19 13:14 UTC
Labels: bug-s3
