### ISSUE TITLE
[Spree 2 Upgrade] Soft delete shipping methods and enable destroys

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#2126] opened 2018-03-09 01:11 UTC
As per the detail in PR #1659:

This removes the "hack" that forbids destroying shipping methods from /admin and makes use of Spree's soft delete implementation (`deleted_at` column in `spree_shipping_methods`).

This way admins can disable a particular shipping method, so no one uses it anymore, while still showing the shipping method for past orders in reports.

## TODO
- [x] remove N+1
- [ ] Check `/admin/orders` and `/accounts`
- [ ] QA order_cycle_management and customers reports: They must work like now and shipping_methods should be deletable.

## How is this related to Spree upgrade?

You are right to ask. `app/controllers/spree/admin/shipping_methods_controller_decorator.rb` below references the column `shipping_method_id` from the `spree_orders` table and this won't be longer available in Spree 2.0 aka. step 7.

By shipping this simple change into a release before the step 7 we reduce the chance of introducing bugs and more important, we make that actual step 7 release more lightweight, which people testing will thank.

**Comment by sauloperez** [comment] 2018-03-09 06:25
:clap:

**Comment by sauloperez** [comment] 2018-04-06 10:57
Do you mind if I close this issue, which just copies the PR's description, and we stick to  https://github.com/openfoodfoundation/openfoodnetwork/issues/2010 instead? that one is already linked to its parent epic https://github.com/openfoodfoundation/openfoodnetwork/issues/2011.

**Comment by luisramos0** [comment] 2018-09-06 18:31
Closing this as it is a duplicate of #2010 (please correct me if I am wrong).

**Closed by luisramos0** 2018-09-06 18:31 UTC

**Comment by sauloperez** [comment] 2018-09-10 10:03
I'm not sure. There is a discussion in https://github.com/openfoodfoundation/openfoodnetwork/pull/1659 about it and the conclusion is not entirely clear to me (I just skimmed through the text).
