### ISSUE TITLE
Missing translation: Passwords not matching or too short

### ISSUE THREAD

**Issue by drummer83** [openfoodfoundation/openfoodnetwork#8443] opened 2021-11-02 08:50 UTC
## Description
As discussed in PR [#7693](https://github.com/openfoodfoundation/openfoodnetwork/pull/7693#issuecomment-865297731) the strings for 'password and password confirmation not matching' and for 'password too short' can't be translated into German. It seems to be translated by Rails itself and it is working for some languages (like French). It doesn't work for German though.

There are two places where this can be found:
1. When registering through the login button in the main menu 
2. When changing the password in your account settings 

## Expected Behavior
The strings should be properly translated to German (and all other languages).

## Actual Behaviour
The strings are not translated.

## Steps to Reproduce

**Scenario 'login button'**

1. Go to homepage https://openfoodnetwork.de/
2. Select "Deutsch" (German) as language
3. Click "Einloggen" (login)
4. Click "Registrieren" (register)
5. Enter e-mail address
6. In "Wählen Sie ein Passwort" choose a short password (< 6 characters)
7. In "Passwort erneut eingeben" type a DIFFERENT password
8. Click "Jetzt registrieren" (register now)

**Scenario 'account settings'**

1. Go to homepage https://openfoodnetwork.de/
2. Select "Deutsch" (German) as language
3. Click "Einloggen" (login)
4. Log in with your user data and go to Konto (account) / Kontoeinstellungen (account settings )
5. Leave e-mail address
6. In "Passwort" choose a short password (< 6 characters)
7. In "Passwort erneut eingeben" type a DIFFERENT password
8. Click "Speichern" (update)

## Animated Gif/Screenshot
**Scenario 'login button'**

![grafik](https://user-images.githubusercontent.com/1790176/139827138-7e3e8e8b-99b6-439f-ae96-fa4df8a3798b.png)

**Scenario 'account settings'**

![grafik](https://user-images.githubusercontent.com/1790176/139835021-0757dbd0-8ffb-4391-8dc8-924423aa518f.png)

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.5
* Browser name and version: Firefox 93.0
* Operating System and version (desktop or mobile): Windows 10, Desktop

**Comment by startupboy** [comment] 2021-11-17 00:06
Hi, I'm new to open source development and I'd like to try working on this issue. Can I be assigned this issue? Thanks

**Comment by jibees** [comment] 2021-11-17 08:26
@startupboy : for sure! Thanks!

**Comment by startupboy** [comment] 2021-11-22 06:58
Thanks! Do you have any suggestions for where to start looking? Any ideas about what might be causing this?

**Comment by jibees** [comment] 2021-11-22 08:15
First of all, I'd try to reproduce the issue on my local setup. 
Then, I'd look at this stackoverflow response : https://stackoverflow.com/a/20531038 which might give us a good clue (worth a try at least)

**Comment by drummer83** [comment] 2021-11-25 20:23
I have just realized that there is a third error which is not being translated:
If the password is left empty, there is the message "can't be blank" which also can't be translated.
![grafik](https://user-images.githubusercontent.com/1790176/143496965-274de738-8cb3-4f8b-ab2d-9a34d90d033e.png)

**Comment by startupboy** [comment] 2021-11-26 03:08
> First of all, I'd try to reproduce the issue on my local setup. Then, I'd look at this stackoverflow response : https://stackoverflow.com/a/20531038 which might give us a good clue (worth a try at least)

Thanks for the reply. I opened it on localhost:3000 and the issue doesn't seem to occur with the Castellano language. Do you know how I can test the website in German/Deutsch on localhost? For me, Castellano is the only language I can switch to.

**Comment by jibees** [comment] 2021-11-26 08:14
If you could not reproduce the issue with the Castellano language, trying with another langage is, I guess, useless.
What is strange is that it seems that I can reproduce it in Castellano under certain condition: 

1. simply click on `Iniciar Session` without filling anything:
<img width="856" alt="Capture d’écran 2021-11-26 à 09 10 13" src="https://user-images.githubusercontent.com/296452/143548057-8f20b2cd-c72a-469a-9372-007054183dac.png">
 
2. But not why I'm clicking in `Registrarse ahora` without filling anything:
<img width="311" alt="Capture d’écran 2021-11-26 à 09 12 57" src="https://user-images.githubusercontent.com/296452/143548375-663fe3fd-04a9-4e79-8510-8dbca9fd0eb6.png">

I'd look at those two cases, and try to understand them.

**Comment by drummer83** [comment] 2021-11-26 08:27
@jibees 
Regarding 1: I believe this is not part of this issue. The string "invalid email ..." actually is translated to German.
Regarding 2: Some languages seem to work, German doesn't. Those strings are translated by Rails (see [#7693](https://github.com/openfoodfoundation/openfoodnetwork/pull/7693#issuecomment-865297731)).
@startupboy

**Comment by drummer83** [comment] 2021-11-26 08:46
@startupboy 
To add more languages to your local environment you need to create the file
`.env.development.local` in the root of your project
with the following line (languages are examples and can be found in the config/locales folder):
`AVAILABLE_LOCALES="en,es,de_DE,fr"`

The problem is that in my environment nothing from Rails is translated then (not even the label of the login button etc.).
Maybe @jibees or @andrewpbrett can help here.

**Comment by jibees** [comment] 2021-11-26 08:47
@startupboy By the way, if you want to add Deutsch as a supported langage by the application, simply add 
`AVAILABLE_LOCALES=en,de_DE` to your `.env.development.local` file at the root of the project (if doesn't exist, create it).

On the other hand, even if Deutsch is my selected language, this interface is still in english (not only the error messages):

<img width="548" alt="Capture d’écran 2021-11-26 à 09 46 50" src="https://user-images.githubusercontent.com/296452/143552840-57749a6f-a0c3-4634-9055-b3c3a0899d74.png">

**Comment by startupboy** [comment] 2021-12-01 03:35
Thanks yeh I was able to reproduce it. There are several things that are confusing me on which I could receive some insight:

1) As both of you noted, on the local machine when the language is set to Deutsch, the login, registration, forgot password buttons, and texts "Your email" and "Confirm password" are all in English. The error messages are all in English too
![deutsch](https://user-images.githubusercontent.com/55814205/144166318-e178dfbb-d766-4d9c-9ca8-5fdf95e6d41c.PNG)

However, if you visit openfootnetwork.de and then set the language to be Deutsch, the login, registration, forgot password buttons, and texts "Your email" and "Confirm password" properly appear in Deutsch and how it is presented in the de_DE.yml file. The error messages are in English like in the local machine image, however.
![dot_de](https://user-images.githubusercontent.com/55814205/144166473-848c0346-d1b5-4c69-bffb-36b98ee63b7a.PNG)
I was wondering why these two are translated differently

2) I don't fully understand the use of the en_DE file. Is this only used when visiting openfootnetwork.de and then choosing English as the language? Is there a translation process/relationship between en_DE and de_DE that occurs? If so, in what scenarios?

3) If we look at the de_DE.yml file, we see that the Deutsch version of "cannot be blank" exists. But if we visit openfootnetwork.de and select language as Deutsch, the Deutsch version is not displayed. Is it the case that this variable, 'blank', is not being accessed properly, or the 'blank' variable from a different file is being used? (For example maybe en_DE.yml)
![de_de_not_blank](https://user-images.githubusercontent.com/55814205/144166995-b4eddb33-a611-4f09-8e4b-57559832691d.PNG)

**Comment by drummer83** [comment] 2021-12-01 10:14
I can only comment on no. 2:

>     2. I don't fully understand the use of the en_DE file. Is this only used when visiting openfootnetwork.de and then choosing English as the language? Is there a translation process/relationship between en_DE and de_DE that occurs? If so, in what scenarios?

Yes, en_DE is the English version for the German instance (openfoodnetwork.de). In some places we may want to use different wording or we have different concepts than other English speaking instances, so we need to have our own English translation.

Translations take place using [Transifex](https://www.transifex.com/open-food-foundation/open-food-network/dashboard/) and always use en.yml as the reference. New strings are introduced into en.yml and will then appear as "untranslated" in Transifex. All other language yml files are then updated by translators through Transifex only. 
So for Germany:
en.yml --> Transifex --> de_DE.yml
en.yml --> Transifex --> en_DE.yml

Regarding no. 1 and no. 3 some other @openfoodfoundation/developers need to support, please.

**Comment by mkllnk** [comment] 2021-12-02 03:40
It depends on where the translation is called from. The login modal is in our code base. It's actually an AngularJS template: https://github.com/openfoodfoundation/openfoodnetwork/blob/97751763a7e028c7431d835a5cd39733f9ca1489/app/assets/javascripts/templates/login.html.haml#L1-L10
There are actually several ways of calling translating. `{{'label_login' | t}}` is translating with an AngularJS filter in the browser. `t('devise.confirmations.resend_confirmation_email')` is executed in Ruby code and translating it there. This should be changed to an AngularJS filter or otherwise it will only be translated to the default language but it won't change when the user switches languages because these JS templates are pecompiled. And then you see `{{ errors }}` which is printing errors that come from Rails and have been translated there (I think). Since we use the gem devise for authentication, the error messages are probably generated within that gem.

We allow translations of devise messages through our locale as well but we are probably missing some:
https://github.com/openfoodfoundation/openfoodnetwork/blob/97751763a7e028c7431d835a5cd39733f9ca1489/config/locales/en.yml#L135-L153

For example, I can't find "too short" in our translations. It must be coming from somewhere else. You need to find out which translation key to add to our locale.

**Comment by luisnramos** [comment] 2021-12-06 21:07
Hello, I dont think this is a good first issue. Translations, specially with javascript plus external modules like devise, are not easy. Unless if you have mastered this in some other rails project.

**Comment by chaitali-khangar** [comment] 2023-06-04 13:06
Hello, I'm a newcomer to open-source development, although I do have experience with Ruby on Rails. I'm interested in taking a shot at resolving this particular issue. Is it possible for me to be assigned to it? Thank you.

**Comment by drummer83** [comment] 2023-06-04 13:11
Hi @chaitali-khangar, and welcome!

Sure, I will assign it to you! Looking forward to your contribution(s).
In case of any questions don't hesitate to get in touch here or in our Slack.

**Comment by chaitali-khangar** [comment] 2023-06-05 06:27
Hi @drummer83 
It appears that the Rails internationalization for the `password` is not correctly loaded for the German language. 

We can add the translation to the German YAML file to resolve this issue. I just wanted to confirm if this is the appropriate approach for the OFN (Open Food Network) or if we need to include the translation in all other files.

**Comment by jibees** [comment] 2023-06-05 07:22
Hey @chaitali-khangar 
We don't translate directly the strings in the codebase, but we use transifex to let instance managers manage their instance and their translation. You can see process explained [here](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)) and [here](https://community.openfoodnetwork.org/t/the-transifex-process/831).
Hope it's more clear now!

**Comment by chaitali-khangar** [comment] 2023-06-09 09:05
Hi Guys,
I just wanted to check why we have the file name "de_DE.yml" for German instead of "de-DE.yml".
As Rails internationalization follows the "de-DE.yml" naming culture, this problem gets resolved if we do so.

Reference: https://github.com/svenfuchs/rails-i18n/blob/6eea72cc47bc6edea6ceed5cc0908336190d22c7/rails/locale/de-DE.yml

**Comment by sigmundpetersen** [comment] 2023-06-09 10:10
I would rather suggest renaming "de_DE" to just "de", like we have "fr" for France.
Either way, this would have further consequences for Transifex (copying de_DE to de or de-DE) and ofn-install config (de_DE -> de/de-DE).

**Comment by chaitali-khangar** [comment] 2023-06-13 06:30
We can also do that just wanted to check with @jibees and @drummer83. Will it be okay if we can use only `de.yml` instead of a separate translation for it?

**Comment by mkllnk** [comment] 2023-06-13 23:41
> "de_DE.yml" for German instead of "de-DE.yml."

The underscores are used by Transifex, the tool we use for translations. We can't change it. At least we tried in the past and couldn't resolve the issues raised by this change. While Rails usually uses dashes, it should also work with underscores.

> suggest renaming "de_DE" to just "de"

That is a good idea. It was suggested in the past and it just needs someone to do it. We need to rename it in several places though, including ofn-install and Transifex. It may be good to keep both for a while for backwards compatibility.

> we will need to merge the devise-i18n "de.yml" locale into our current setup

Since we do translations in Transifex, do we need to copy parts of `en.yml` from the gem to our code? Then they will be available for translation into any language by our team. This sounds like the solution to this issue.

**Closed** 2023-08-10 01:40 UTC
Labels: bug-s3
