### ISSUE TITLE
Text of unselected OC invisible (white on white) in Order Cycle Selector

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5291] opened 2020-04-23 01:03 UTC
## Description

When the customer chooses an Order Cycle on the first (red box) screen, both Order Cycles are visible. When the order cycle loads (box turns green), only the selected Order Cycle is visible. The other is white text on white background. You can move between the two order cycles, but only the selected one is visible. 

## Expected Behavior

It should be possible to view the name of both Order Cycles to facilitate moving between the two order cycles.

## Actual Behaviour

It's possible to move between the two order cycles, but the name of the unselected order cycle is invisible until it's selected.

## Steps to Reproduce

Customer can reproduce, and has provided screen shots and details. Unable to reproduce in testing (Note: I don't have same environment)

1. Create two order cycles for an enterprise (The Bicycle Baker)
2. Go to shopfront and select one order cycle from red box
3. View green order cycle box
4. Only the selected order cycle is visible

## Animated Gif/Screenshot

![Screen Shot 2020-04-23 at 10 20 55 AM](https://user-images.githubusercontent.com/47620442/80047753-a4166e00-8551-11ea-8859-31de3ccf1ffe.png)
![Screen Shot 2020-04-23 at 10 21 01 AM](https://user-images.githubusercontent.com/47620442/80047769-a973b880-8551-11ea-9dfe-dfdf07d2a6bf.png)

## Workaround

It's still possible to select both Order Cycles, but customers may not be aware that there is another order cycle, as it is invisible.

## Severity
S3

## Your Environment

Customer has provided the following information about the environment that she experiences the bug in:  

"It’s on our Toshiba laptop, operating system x64 based processor, Windows 10, Chrome browser. It’s fine on our iPhones on Safari. "

Also tested (and can't replicate) on MacBook Pro, OSX El Capitan, Chrome Browser.

**Comment by sigmundpetersen** [comment] 2020-04-23 07:43
I wonder if this is a duplicate of #5077 ?

**Comment by luisramos0** [comment] 2020-05-01 14:46
yes, it's a duplicate.

**Closed by luisramos0** 2020-05-01 14:46 UTC
Labels: bug-s3
