### ISSUE TITLE
Release v2.9.9 Filter Coffee

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#5433] opened 2020-05-15 03:53 UTC
Steps: 

- [x] Include translations
- [x] [Draft new release]
- [x] Notify #instance-managers of user-facing changes.
- [ ] Test: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/2-9-9/builds/2
- [x] Publish and notify #global-community
- [x] Deploy and notify #instance-managers
- [x] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases

**Comment by lin-d-hop** [comment] 2020-05-17 19:56
https://docs.google.com/document/d/1rXLmg7q-wBwnYj7FO6J1KnG172g86Y5k3GPZ5WoBoXA/edit#

Ready to go team. Lovely lovely.

**Comment by filipefurtad0** [comment] 2020-05-18 10:20
Hey @mkllnk and @lin-d-hop ,
I've stumbled across a loss in functionality in the OC selector. Basically, the clickable area of the OC selected is now significantly reduced, which makes the selector appear as not working. In staging, only the green area (pic below) is possible to activate, to see the drop-down list of open OCs:

![image](https://user-images.githubusercontent.com/49817236/82200671-3878b400-98f7-11ea-900c-7a679173dcd2.png)

In production, it's easy to observe that the whole white area is clickable.

I've double checked on different server/browser combination, but could you please confirm these observations @lin-d-hop ?

**Comment by luisramos0** [comment] 2020-05-18 11:24
I can replicate, I am trying to find what caused this problem.
Looks like the mobile search filters PR #5330 is the only mobile PR in this release. It's quite a big PR, I am trying to understand what commit caused the problem.

**Comment by luisramos0** [comment] 2020-05-18 11:34
ok, this is caused by #5330
I have found the commit that introduced this problem. it's the second commit in #5330
https://github.com/openfoodfoundation/openfoodnetwork/pull/5330/commits/f46ca0c5956084bd5a028d8f580c8fc7587941ff

**Comment by luisramos0** [comment] 2020-05-18 11:43
[this line](https://github.com/openfoodfoundation/openfoodnetwork/pull/5330/commits/f46ca0c5956084bd5a028d8f580c8fc7587941ff#diff-5adb00cccb8e23d76783b6c406af4714R12) moves the z-index of the tab buttons on the left over the OC selector making the selecor clickable above the tabs line:
![image](https://user-images.githubusercontent.com/1640378/82209401-2271f000-9905-11ea-92b7-cd84fb8285d9.png)

**Comment by luisramos0** [comment] 2020-05-18 11:52
I see that the z-index was introduced so that the shadow of the tab buttons is still seen over the search bar or the OC selector (when on mobile). So, it's needed.
I tried playing around with z-index of the OC selector but it's position is "absolute".
@Matt-Yorkley thoughts?

**Comment by luisramos0** [comment] 2020-05-18 13:33
ok, so I created a branch for the patch called 2.9.9
I merged Matts commit and I made that last commit the base for the 2.9.9.
I have updated the link to the build in semaphore, that build can be used to re-stage and re-test the issue and maybe make some final verifications of the release. Ready for testing again.

**Comment by filipefurtad0** [comment] 2020-05-18 14:00
I've staged and checked that the whole surface of the OC selector is clickable and works as expected. The issue is solved and the release is unblocked :tada:

**Comment by filipefurtad0** [comment] 2020-05-18 15:39
Blocked label is back on till further clarifications on the issue @Matt-Yorkley found, and in discussion on Slack.

**Comment by filipefurtad0** [comment] 2020-05-19 20:38
Hey @mkllnk,

Issue #5467 was also detected but as far as discussed on Slack in the #testing channel, this should not be a release blocker. So, in this regard, I think it's safe to remove the blocked label, and proceed with the release.

**Closed** 2020-05-20 01:05 UTC
