### ISSUE TITLE
Server error (slug of doom) running reports on SOME order cycles/dates

### ISSUE THREAD

**Issue by WalkingBlackBear** [openfoodfoundation/openfoodnetwork#4016] opened 2019-07-07 00:37 UTC
## Description

When trying to run a report on a past order cycle/date range, the server instantly returns the system error/slug of doom screen.  

I am getting the exact same result when running a packing report, orders and distributors report, and all of the Orders and Fulfillment reports as well.
The payment report returns the expected result on the same time period though.

## Expected Behavior

A report is returned based on the parameters set or OC selected.

## Actual Behaviour

The NO GROW server error screen is shown.  It comes up almost immediately, so there is no chance that it is some kind of server timeout at play.

## Steps to Reproduce

1. Sign in as a hub administrator (regular user, NOT Super User)
2. Go to the Reports tab.
3. Select a report type listed above as returning the error. (IE: Packing report)
4. EITHER: Select an affected date range OR an affected order cycle.  (In my case, for the CLFC test shop, February 17, 2019 to March 4, 2019 OR "Test Cycle 11 (17 Feb 08:00) - 03 Mar 16:00)"
5. Click Search

## Animated Gif/Screenshot

![OFN-Error-PackingReport-ByDate](https://user-images.githubusercontent.com/10343651/60762417-e1425b80-a024-11e9-8b44-b59a0100d855.gif)
![OFN-Error-PackingReport-ByOC](https://user-images.githubusercontent.com/10343651/60762418-e1daf200-a024-11e9-8a48-b617d27b482f.gif)

## Context

I was trying to access order cycle data while testing reports after V2 upgrade to see what/if anything had changed.

## Your Environment

* Version used:  OFN-CAN (I think it's v2.1 now?)
* Browser name and version:  Edge 77 and Chrome 75
* Operating System and version (desktop or mobile): Windows 10 Pro 1903
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by luisramos0** [comment] 2019-07-07 14:43
nicely documented @WalkingBlackBear 
tagging it S2 at least...

**Comment by luisramos0** [comment] 2019-07-10 14:35
main hypothesis for this issue is that deleted products are breaking the reports.

**Comment by RachL** [comment] 2019-07-10 14:37
Yes thank you @WalkingBlackBear I was able to reproduce this during the latest release testing. I guess previously I didn't had deleted products within the database I was using :/ hte next release will correct the orders and fulfillment reports. We still need to work on Bulk-coop, orders and distributors and packing reports.

**Comment by sauloperez** [comment] 2019-07-10 14:44
That's exactly one of the other reports affected by unhandled deleted products. I can tackle it myself or help someone else :point_up:

btw @WalkingBlackBear , "Orders and Fulfillment report" is fixed in the release v2.2.0.

**Comment by Matt-Yorkley** [comment] 2019-07-10 16:30
@sauloperez is this essentially the same issue as #3956 ?

**Comment by Matt-Yorkley** [comment] 2019-07-10 19:01
Also, can't we employ Paranoia's `#with_deleted` scope to get around some of these issues?

**Comment by sauloperez** [comment] 2019-07-11 11:22
That's what I thought @Matt-Yorkley but none of the variants were deleted and I think it's very unlikely they were restored back since the issue occurred (is that even possible from the UI?). I suspect a bunch of other issues.

**Comment by sauloperez** [comment] 2019-07-11 11:24
> @sauloperez is this essentially the same issue as #3956 ?

Yep, read my comment above.

**Closed** 2019-07-12 15:33 UTC
Labels: bug-s2
