### ISSUE TITLE
Error during sign-up

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#3678] opened 2019-04-02 04:06 UTC
## Description

Bugsnag has recorded 60 sign-up errors in less than 4 months.

```
ActiveRecord::RecordNotUnique
user_registrations#create
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "email_idx_unique"
DETAIL:  Key (email)=(...@gmail.com) already exists.
: INSERT INTO "spree_users" ("api_key", "authentication_token", "bill_address_id", "confirmation_sent_at", "confirmation_token", "confirmed_at", "created_at", "current_sign_in_at", "current_sign_in_ip", "email", 
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    from gems/skylight-1.7.2/lib/skylight/vendor/active_support/notifications/instrumenter.rb:20:in `instrument'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in `exec_insert'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    from gems/activerecord-3.2.22.5/lib/active_record/relation.rb:66:in `insert'
    from gems/activerecord-3.2.22.5/lib/active_record/persistence.rb:367:in `create'
    from gems/activerecord-3.2.22.5/lib/active_record/timestamp.rb:58:in `create'
    from gems/activerecord-3.2.22.5/lib/active_record/callbacks.rb:268:in `block in create'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:414:in `_run__2407213920239075702__create__3670657833213799178__callbacks'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:405:in `__run_callback'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from gems/activerecord-3.2.22.5/lib/active_record/callbacks.rb:268:in `create'
    from gems/activerecord-3.2.22.5/lib/active_record/persistence.rb:348:in `create_or_update'
    from gems/activerecord-3.2.22.5/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:436:in `_run__2407213920239075702__save__3670657833213799178__callbacks'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:405:in `__run_callback'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from gems/activesupport-3.2.22.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from gems/activerecord-3.2.22.5/lib/active_record/callbacks.rb:264:in `create_or_update'
    from gems/activerecord-3.2.22.5/lib/active_record/persistence.rb:84:in `save'
    from gems/activerecord-3.2.22.5/lib/active_record/validations.rb:50:in `save'
    from gems/activerecord-3.2.22.5/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:208:in `transaction'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:259:in `block in save'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
    from gems/activerecord-3.2.22.5/lib/active_record/transactions.rb:258:in `save'
    from app/controllers/user_registrations_controller.rb:15:in `create'
    from gems/actionpack-3.2.22.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    from gems/actionpack-3.2.22.5/lib/abstract_controller/base.rb:167:in `process_action',
```

## Expected Behavior

The sign-up doesn't fail and we don't see any errors in Bugsnag.

## Actual Behaviour

The sign-up seems to fail from time to time. Maybe it's double-clicking the button. I don't know.

## Steps to Reproduce

Not known how to re-produce.

## Severity

S3: The feature seems broken in some cases. But people seem to be able to sign up. I'm not aware of any user reports. The error messages contain the email addresses of people. We could follow up.

## Possible Fix

Use pessimistic database locking.

**Comment by mkllnk** [comment] 2019-04-05 06:51
This issue has been linked to an error in Bugsnag
[**ActiveRecord::RecordNotUnique** in **user_registrations#create**](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5c36d19d13ea450019f4c8b0?event_id=5ca6b3870037e71fab940000&i=gh&m=li)

**Comment by Matt-Yorkley** [comment] 2019-04-05 10:12
`DETAIL:  Key (email)=(...@gmail.com) already exists.`
The email is already in use? Maybe we just need to tweak the validation/feedback?

**Comment by luisramos0** [comment] 2019-09-24 14:00
I thought this could be existing users trying to "login" on the registration page :trollface: 
I tried to replicate but the JS code handles it well, I also tried to double/triple click the "registration" button, error messages are appropriate.

**Comment by luisramos0** [comment] 2019-09-24 14:02
I see the last occurrence was with kirsten+sync@openfoodnetwork.org.au (Sep 24th, 04:31:41 WET)
@kirstenalarsen did you notice something weird in the login/registration pages 10 hours ago in AU live? 
do you think you could have tried to login using the registration tab or something like that?

**Comment by luisramos0** [comment] 2019-09-24 14:03
there's only 1 error of these in FR live and none in UK live...

**Comment by RachL** [comment] 2022-09-22 15:48
Closing this one as we are not able to reproduce.

**Closed by RachL** 2022-09-22 15:48 UTC
Labels: bugsnag, bug-s3
