### ISSUE TITLE
Transaction fees charged several times, after using an invalid 3D-card and retrying with valid cards

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5818] opened 2020-07-23 20:09 UTC
## Description

Attempting to pay with Stripe-SCA and the card:

4000008260003178 - _This card requires authentication for one-time payments. All payments will be declined with an insufficient_funds failure code even after being successfully authenticated or previously set up._ 

displays the insufficient funds error as expected, but breaks the checkout process. Further attempts to pay with valid cards do not work and, in case a transaction fee is set, this value is charged several times (as many as one attempts).

## Expected Behavior

After using an invalid card, paying with a valid card should be possible. Transaction fees should only be charged once.

## Actual Behaviour

Transaction fees are charged several times, after checkout is broken by using an "insufficient funds" 3D card.

## Steps to Reproduce

Admin
1. Set up Stripe-SCA and add a transaction fee to this payment method

Customer
2. Place items in the cart, and proceed to check out
3. Choose Stripe SCA payment method an insert the card: 4000008260003178 - a warning "Your card has insufficient funds" should be visible
4. Now attempt to pay with the valid card 4000002760003184 - you will see the same error, although this is a valid card.
5. If you re-attempt, you will see a different error "Invalid payment state"
6. Now press F5 - Refresh the page until the error dissapears
7. Insert a valid card
8. Check the values in the order confirmation

## Animated Gif/Screenshot

After first payment attempt, with **invalid** card 4000008260003178:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/ec4b2c69-bc8e-49ac-a907-4d061c3e1aca)

After second payment attempt, with **valid** card 4000002760003184:
![image](https://user-images.githubusercontent.com/49817236/88377427-0ec88700-cd97-11ea-90a7-02ea3780518b.png)

Order confirmation:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/1298e354-ac6d-4ae8-87bd-e3436c1b4f66)

Order State:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/a1f36ab4-1a67-404b-a970-7029db752415)

Payments:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/9de33d46-c0b1-4e5e-b022-640c5b3f5675)

Stripe Dashboard:

![image](https://user-images.githubusercontent.com/49817236/88377053-7d591500-cd96-11ea-96ae-7caa31ff95ba.png)

## Workaround

As a user, I'm not sure one is aware of any.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: Checked and observed for v3.1.0 - v3.1.3
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop/Ubuntu 20.04

## Possible Fix

Please note, that this bug only happens if transaction fees are set. This situation is observed if the first invalid payment is triggered by a **3D secure authentication card**.

Bug #5816 is perhaps related (fees/Stripe-SCA) but is observed when the first invalid payment is triggered by a non- 3D secure authentication card.

**Comment by RachL** [comment] 2020-07-24 08:41
@filipefurtad0 are we sure this is a v3 regression?

**Comment by filipefurtad0** [comment] 2020-07-24 09:00
No I'm not sure, we would need to test this in a v2.1 server.

**Comment by luisramos0** [comment] 2020-07-24 19:56
This is a good test case. This makes me think we need to improve our test cases, manual or automatic.
We need to regularly test:
- pay with card that needs auth but fails (3178) and then pay with cash
- pay with card that needs auth but fails (3178) and then pay with card that doesnt need auth (4242)
- pay with card that needs auth but fails (3178) and then pay with card that does need auth and works (3184)

There are two cases that can be tested with 3178: you can pass the auth or fail the auth, the card will fail anyway but the code path is different on our side...

Anyway, to the issue at hand: I can replicate this in v3 before and after #5780. And also confirmed it works in v2, so this is a regression. 

In terms of the root cause, I believe the failed previous payments are not being correctly marked as failed and then on the following attempts some parts of the code get confused with several pending payments... I need to get back to it tomorrow.

**Comment by luisramos0** [comment] 2020-07-25 18:51
We dont need an invalid card to see this issue, we can use only a valid card like 4000008260003178 and simply "fail auth" on the first attempt. The behavior will be the same as described in this issue on the following attempts even if you "complete auth".

**Closed** 2020-08-01 14:54 UTC
Labels: bug-s2, v3-regression
