### ISSUE TITLE
Add extra (Instagram) social media links to emails sent to customers and users

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#3509] opened 2019-02-17 12:44 UTC
## Description

***Done***
There are only two social media links are in the footer of emails sent to OFN users: these are Facebook and Twitter.  It would be great to have Instagram added to this.

***To Do***
In the footer of order confirmation emails there are no social media links to OFN itself- just contact details of the hub/shop the customer ordered from.  It would be great to have the same 'Connect with us' footer on all emails.
 
## Expected Behavior

In the footer of emails sent to customers, below 'Cheers, Open Food Network (UK) team' to add the 'Connect with us:' box.
In the 'Connect with us:' box to add Instagram as a third option.

***Done***
Customer registration emails

***To Do***
Order confirmation emails

## Actual Behaviour

Footer of emails to OFN users has two social media links only: Facebook and Twitter.
Emails sent to customers have no social media footer.

## Steps to Reproduce

***Done***
1. Sign up to OFN
2. See footer links in Welcome email are missing Instagram links

***To Do***
1. Place an order in OFN
2. See footer links in Order Confirmation email are missing Instgram links

## Animated Gif/Screenshot

***Done***
welcome email footer/email to OFN users

![image](https://user-images.githubusercontent.com/45104035/52912943-792aed00-32b0-11e9-819c-cb62338efbe2.png)

***To Do***
Order confirmation email (sent to OFN customer)
![image](https://user-images.githubusercontent.com/45104035/52913036-97ddb380-32b1-11e9-8c7c-da992e8cf396.png)

## Context

Prevents effective social media communication and marketing.

## Severity

bug-s5

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by RachL** [comment] 2019-02-18 09:12
Hello @lbwright22 thanks for putting this up! However this is not a bug, this is a new feature. Can you use the feature template rather than the bug template to create the issue?
Besides as it is labeled "good first issue" this can be picked up by anybody, which means also by people who do not know the OFN. So you will need to detail each steps. For example here I would add that the super admin needs to be able to add its own instance link like for the other social network. So a link to the configurations menu in superadmin would be awesome, with a screenshot explaining where the new field should be added.
If you need help doing this do not hesitate to ping me here or on slack ;)

**Comment by sigmundpetersen** [comment] 2019-02-18 09:15
If it's a feature request, shouldn't it rather go to Discourse than here? @RachL

**Comment by RachL** [comment] 2019-02-18 09:19
@sigmundpetersen I've wondered the same. However here it seems to me that this is small enough to be picked up by the community, just like translations. So as long as it is a good first issue, I think we can put it strait up here. But maybe I am wrong on the assessment here. What a dev would say about this issue : @sauloperez @mkllnk ?

**Comment by sigmundpetersen** [comment] 2019-02-18 09:24
Yes I also agree with you @RachL , but I think this is something missing in our process: "What makes it small enough to go straight to GH, where is the limit" Not easy 🙂 
But we should agree on something and write it down somewhere.
I guess something like "It's a small improvement and it's very likely that everybody agrees it should be prioritized", then it goes to GH. Then how and where should we put it, straight to Dev Ready? Questions ... 🤔

**Comment by RachL** [comment] 2019-02-18 09:30
Yes indeed. I guess that the limit is very close to the definition of the "good first issue" label. What do you think @daniellemoorhead ?

**Comment by daniellemoorhead** [comment] 2019-02-18 22:26
I agree with you both @RachL @sigmundpetersen. This need has come up again and again, each time an example comes up (the last time with @kirstenalarsen and Myriam) and we decide that it isn't required and still should go into the wishlist because something small isn't necessarily small when you start speccing it.

I agree that this is tiny and doesn't deserve a wishlist item...but how do we fit it into a column...? 🤔

**Comment by mkllnk** [comment] 2019-02-19 00:09
Does it fit under quick wins?

**Comment by RachL** [comment] 2019-02-19 09:23
@daniellemoorhead on second thoughts maybe it's easier to make everything go through the wishlist except Translations and bugs? But then product curators / owners need to review them often because I think they won't be voted in the process.
In terms of column, I have the feeling sometimes we put translations in dev ready, sometimes not...My guess is that it is by definition dev ready, so I would put them there with the label "good first issue", so that our core dev don't spent time on them?

**Comment by daniellemoorhead** [comment] 2019-02-20 02:44
>Does it fit under quick wins?

We don't have this concept @mkllnk (well, the mobile feature, which was a wishlist item, was supposed to be a quick win but it blew out to be way more....). And I wonder whether annoying bugs can be as much of a quick wins as non-bugs like this?

**Comment by daniellemoorhead** [comment] 2019-02-20 02:46
>on second thoughts maybe it's easier to make everything go through the wishlist except Translations and bugs? But then product curators / owners need to review them often because I think they won't be voted in the process.

@RachL I think this is why the process we have isn't yet working effectively. It's so slow and arduous, which isn't helped by comparing big things to small things like this, not to mention the slowness of our pipe 😬

**Comment by lin-d-hop** [comment] 2019-02-22 16:38
My thoughts are that having small fixes like this as 'good first issues' are useful as I love to have easy issues to point potential new devs toward. I'd love to keep this as an issue simply because of its simplicity. I'm planning on putting some energy toward finding good ways to get 'good first issues' ticked off outside of the usual pipe. So for me issues like this are useful in the full knowledge that we won't be getting to it in the usual pipe.

**Comment by amers185** [comment] 2019-04-10 15:44
Hi! I would like to work on this. I was wondering if someone could delineate the steps to reproduce since they are missing from the descriptor. Further, how would I test for this? I would also appreciate if somebody could talk about the superadmin or direct me to documentation where I can read up on it. Best.

**Comment by daniellemoorhead** [comment] 2019-04-10 23:35
@lin-d-hop are you able to point @amers185 in the right direction for making this change? ☝️

**Comment by lin-d-hop** [comment] 2019-04-11 08:34
Hi @amers185

Great that you are interested in this issue!

I've updated the steps to reproduce. Essentially you just need to complete an order. If you would like to sign up to a staging server eg staging.openfoodfrance.org and then complete an order you should receive two emails like the ones in the description.

To test locally the dev environment opens the emails in your browser rather than sending them.

The user guide for super admin is not very complete (I think... though I might be wrong). There is a lot of information on [Discourse](community.openfoodnetwork.org.uk) and it is worth just searching for things and asking questions on Slack. For this change you'll be looking to take the instagram links specified in https://[insertOFNurl]/admin/content/edit to add the to the email.

It might be best to move this conversation to Slack to get started so ping me on there.

**Comment by amers185** [comment] 2019-05-05 17:07
I would appreciate it if this issue could be assigned to me. I will a solution ready for PR in a day.

**Comment by lin-d-hop** [comment] 2019-05-09 11:13
PR #3790 solves part of this issue but not all of it.... a good indication we should have split this issue into two to begin with ;-) Learning as we go as always!

@amers185 I have updated the description to describe what is done and what is still to do. Basically the order confirmation email does not include any social links at all. So the footer with social links that you have now updated to include instagram should be included in the same way. Would you be willing to take a look at this second part?

**Comment by lin-d-hop** [comment] 2019-05-10 10:37
@amers185 I've moved this back to 'In Dev'.
Are you happy to look at the next steps for completion?

**Comment by luisramos0** [comment] 2019-05-28 19:33
maybe we should move this one back to the bug backlog again?

**Comment by lbwright22** [comment] 2019-09-04 10:00
@lin-d-hop @amers185 
I think this is nearly done. Some emails don't have footers but the ones which do, the link to instagram needs only very slightly tweeking.
It currently goes to : https://openfoodnetwork.org.uk/openfoodnetworkuk
where 'openfoodnetworkuk' is the OFN tag on IG for the UK and entered in super-admin-> configuration-> contents
It should go to : https://instagram.com/openfoodnetworkuk

**Comment by lin-d-hop** [comment] 2019-09-04 10:03
@lbwright22 Am I right in thinking there are two issues:
1) IG links on UK emails not working. 
I believe there is a work around for this though I can't remember it. Maybe someone in #communications will know.

2) Some emails do not have social links on them
Maybe we can open a new issue for this?

**Comment by lbwright22** [comment] 2019-09-04 10:49
@lin-d-hop 
the work around for (1) only works if the url the IG is connected to is ' https://instagram.com/****' (where *** is the string entered in by the user in the super-admin section.

2) I'm not sure which emails have the footers and which don't. Perhaps someone else does?  I think the main emails (those which go to customers rather than just enterprises) do now :-)

**Comment by luchiago** [comment] 2020-04-10 23:45
Hi, I would like to grab this issue.

**Comment by sigmundpetersen** [comment] 2020-04-11 06:00
Hey Lucas and welcome! Yes please go ahead!
Don't hesitate to ask any questions and please join our [slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) if you would like to chat more.
Thanks

**Comment by luchiago** [comment] 2020-04-18 01:42
@sigmundpetersen I'm not able to reproduce with letter opener, it seems the email isn't being sent. But the confirmation email for user is being sent.

**Comment by luchiago** [comment] 2020-04-18 12:01
@luisramos0  I modified the file `app/models/content_configuration.rb`, but my changes do not appear. Do I have to change another file type for the changes to that file to take effect?

**Comment by luisramos0** [comment] 2020-04-18 12:56
Hello, where are you expecting your changes to appear? Maybe easier to share a draft PR so we can discuss with the code?

**Comment by luchiago** [comment] 2020-04-18 12:59
@luisramos0  I made the changes to complete this problem, but the links are not changing. I changed the Linkedin link and the Instagram link, but Linkedin doesn't show any effect (it remains the oldest) and the Instagram link still doesn't appear because it is still blank for the application. I will send a draft PR

**Closed** 2020-04-30 14:01 UTC
Labels: enhancement, good first issue, hackathon, socialissues.tech
