### ISSUE TITLE
Not all products or customer names and order dates displaying in BOM

### ISSUE THREAD

**Issue by karlafalk** [openfoodfoundation/openfoodnetwork#10429] opened 2023-02-13 19:28 UTC
## Description
Customer names (Name) and Order Date (Completed At) columns are blank in the bulk order management orders for SOME orders.  Whether names/dates appear seems to vary depending on whether signed in to super admin or as a manager to the hub account and/or what filters are applied in the search menu, AND still happen when viewing '100 products per page' ([see issue #10363](https://github.com/openfoodfoundation/openfoodnetwork/issues/10363))

When only a date filter is applied: 
<img width="1406" alt="Screenshot 2023-02-13 at 1 28 20 PM" src="https://user-images.githubusercontent.com/88801240/218548264-c3e75be9-365b-4ef2-af1a-ab9961fe98e4.png">
names and dates are NOT appearing for the products associated with the shop 'Bailey's Local Foods', 
<img width="1556" alt="Screenshot 2023-02-13 at 1 45 45 PM" src="https://user-images.githubusercontent.com/88801240/218548488-29b35218-ed7a-454e-b0c4-617124dfe75e.png">
but if I add a shop filter (Bailey's Local Foods)
<img width="1484" alt="Screenshot 2023-02-13 at 1 47 13 PM" src="https://user-images.githubusercontent.com/88801240/218548575-dd151cec-7aad-44ff-a423-4c59989e8ce4.png">

 than those same products are displayed but now have the names and dates associated with them.
<img width="1324" alt="Screenshot 2023-02-13 at 1 47 58 PM" src="https://user-images.githubusercontent.com/88801240/218548797-2b038413-64ab-4198-a652-9cd8c75fcf78.png">

(this was experienced when logged in as super admin, less total names/dates appear when logged in as a hub manager on the account).

Additionally, all the products do not seem to be visible in BOM.  For one of our larger hubs with 80 orders for one order cycle (some with 10+ products) only 78 products total are showing in the BOM screen for that order cycle.  There are some customers with orders on the orders screen that are not showing up in the BOM page.

## Expected Behavior

To consistently be able to view the names/dates associated with products in the BOM

## Actual Behaviour
Names and dates are missing for some products.

## Steps to Reproduce

1. Go to BOM and filter for recent orders dates (Feb 2023).
2. View if names/dates are displaying for all products
3. Apply filters of shop/order cycle to see if the names/dates visible changes.

## Severity
bug-s3

## Your Environment
Experienced in chrome and firefox, and also by the hub owner.

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile): Mac Ventura 13.0

## Possible Fix
Possibly related to - https://github.com/openfoodfoundation/openfoodnetwork/issues/10363 but in this case seems to be happening even when viewing '100 products per page'.

**Comment by jibees** [comment] 2023-02-13 19:58
If I'm not mistaken, I think this one is a duplicate of : https://github.com/openfoodfoundation/openfoodnetwork/issues/10363 

What do you think?

**Comment by RachL** [comment] 2023-02-14 17:21
Hello @karlafalk can you retest now that the fix for https://github.com/openfoodfoundation/openfoodnetwork/issues/10363 is in production? that would indicate quickly if this is another problem we need to fix.

**Comment by karlafalk** [comment] 2023-02-14 18:53
Yes @RachL  - that worked!  All these issues have disappeared now and things are displaying as expected.  Including it looks like all the products that should be, are now displaying in BOM. Thanks!!

**Comment by RachL** [comment] 2023-02-15 08:42
yeepeee!

**Closed by RachL** 2023-02-15 08:42 UTC
