### ISSUE TITLE
[Email Deliverability] Email provider used for org.uk email is blacklisted on backscatterer

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4492] opened 2019-11-25 15:33 UTC
## Description
![Screenshot 2019-11-25 at 15 32 37](https://user-images.githubusercontent.com/1640378/69553893-d4ed7980-0f98-11ea-9eba-fd263f0c5e5e.png)

I think the only way to avoid this is to stop using this email provider... it's their domain that is blacklisted, not the OFN domain.

**Comment by lin-d-hop** [comment] 2019-11-25 15:39
This is where our domain is hosted....
We use their mail forwarding to facilitate all of our emails :woman_facepalming:

**Comment by luisramos0** [comment] 2019-11-25 15:53
associated with this issue, they dont announce support for TLS and that's flagged by mxtoolbox as a problem:
![Screenshot 2019-11-25 at 15 53 16](https://user-images.githubusercontent.com/1640378/69555896-c81e5500-0f9b-11ea-9538-2e68621b19cd.png)

**Comment by lin-d-hop** [comment] 2019-12-07 11:03
So the problem is in the way we've been doing emails in the UK - set up originally as a free hack to get unlimited email accounts. We use Vidahost mail forwarding to gmail SMTPs to set up all our personal emails. Obviously this is not a suitable solution anymore and costs WAY more money than it saves :-) :woman_facepalming: 

So we need a new plan for our personal emails. I am very open to suggestions and want to go for the method that will cause us the least headache in the long term. If you have suggestions please let me know. Happy to do the work getting these set up with the whole team.

**Comment by RachL** [comment] 2020-10-28 13:58
@lin-d-hop I'm going to close this one as I believe you have moved to sendgrid now. Please reopen if I'm wrong :)

**Closed by RachL** 2020-10-28 13:58 UTC
