### ISSUE TITLE
Add a message for superadmin when changing users email.

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4031] opened 2019-07-12 08:53 UTC
## Description
In the backoffice, when editing a user as super admin requires a confirmation on the new email. However the superadmin may not know that and see only that his email changes have not be taken into account. A notification / message should be added.

## Expected Behavior
Admin should understand easily that changing an email requires a new confirmation in order to be taken into account.

## Actual Behaviour
After changing the email and saving the form, the user email remains the same and the message says that it has worked.

## Steps to Reproduce
1. Go to `admin/users` 
2. Click on an email
3. Change the email (with a mailbox you have access to)
4. Hit update
5. A green message will tell you that it has worked. But nothing has changed: the old email is still there. However the new email got a confirmation request email.
6. Click on the confirmation email and validate the new email
7. Go to `admin/users` 
8. See that the new email is correctly there

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/6525576/62130532-7f9aa780-b2d9-11e9-8306-088b4d8fb35a.png)

## Context
Found when moving spree_auth_devise code to ofn.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v2 
* Browser name and version: chrome
* Operating System and version (desktop or mobile): macos
* OFN Platform instance where you discovered the bug, and which version of the software they are using. Katuma live v2.1.0

## Possible Fix

Add a message saying "The account will be updated once the new email is confirmed."

**Comment by Matt-Yorkley** [comment] 2019-07-12 12:31
When we changed emails to require confirmation, some of the logic changed. I think this is correct. Their email will update when it has been confirmed. I think the "new" unconfirmed email gets temporarily stored in a different row in the table.

**Comment by luisramos0** [comment] 2019-07-12 13:08
ok, that's cool, we need to confirm the new email gets the confirmation link email.
I think the admin user still needs to be informed here, otherwise, it looks like a failed update.

**Comment by Matt-Yorkley** [comment] 2019-07-30 13:18
This was duplicated by #4094, which was marked as `s2`...

**Comment by luisramos0** [comment] 2019-07-30 13:24
@RachL have you checked Matts comment above? if you confirm the new email, the user email gets changed.

**Comment by RachL** [comment] 2019-07-30 13:37
(◑‿◐)

Yes sorry I marked as s2 as I thought it was working in v1 AND it was blocking any user wanting to delete its account.

I've just tested and it is working in UK staging. I will do it in production as well now. 

Thank you so much for this feedback @Matt-Yorkley !!

Shall we close this or transformed it so that the superadmin gets a friendly message?

**Comment by RachL** [comment] 2019-07-30 16:44
Alright I went ahead and change the description (otherwise this is stuff I forget easily). To me this is not a bug (the feature is working as expected) so it qualifies as an improvement. 

However I'm wondering if a quick fix wouldn't be to tackle it through translation. Is the translation key for that message unique to this page?

**Comment by luisramos0** [comment] 2019-07-30 18:35
good idea Rachel! Almost, "account updated" is shared with when the user changes the pwd in the frontoffice... but it would be very easy to make them 2 translation keys.

anyway, changing the message is a fairly easy change, I tag this as good first issue.

basically, it's a if clause [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/75c7e0b939e1b195f744ead87329c80c003bf6f5/app/controllers/spree/admin/users_controller.rb#L45)
if email has changed instead of "account updated" show a different translatable message "account updated, email change will be made when new email address is confirmed by user. Please ask user to check mailbox".

**Comment by RachL** [comment] 2019-07-31 12:27
@luisramos0 I did the message in "possible fix". But I guess from your message it's not visible enough :)  I should have change the template here from a bug template to a story template. I just didn't want to mess to much with the original issue...

**Comment by luisramos0** [comment] 2019-08-02 13:17
what is the request?
1. replace the flash "Account Updated" with the new text (very very easy to do)
2. have a pop up with that message (easy to do)

**Comment by RachL** [comment] 2019-08-02 13:23
I think we can go with 1.

**Closed** 2019-09-30 12:19 UTC
Labels: Hacktoberfest, good first issue, improvement
