### ISSUE TITLE
Can't see inventory,  hidden inventory or new inventory products

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4246] opened 2019-09-09 00:37 UTC
## Description

As both hub manager and as super admin,  I am unable to see products I know are in inventory,  hidden,   or new products added to inventory.   

## Expected Behavior

User should select the shop,  and the inventory should load

## Actual Behaviour

User selects the shop,  gets a message that inventory is loading.  The message stops.  But no inventory products show.  I've waited 10 plus minutes for them.  There has often been a delay in inventory products showing - sometimes 15 seconds -  in the past,   but now they are not showing at all. 
## Steps to Reproduce

1. set up an enterprise with inventory (My inventory is large, over 100 products)
2.try to load the inventory --  see that no products load
3.
4.

## Animated Gif/Screenshot

![can't manage inventory](https://user-images.githubusercontent.com/13171778/64496929-ee273980-d277-11e9-8b79-c25d452f70d8.png)

## Context

Impossible to manage a shop and sell products.   Once a user has been using inventory -  they can't just  use their product list in a shop,  because the shop keeps drawing from the 'unmanaged' inventory.  So -  this bug means its impossible to manage a shop.

## Your Environment

* Version used:  I think -  2.4.1 ??
* Browser name and version:  Chrome
* Operating System and version (desktop or mobile):
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 

## Possible Fix

Create a new hub enterprise supplied by the enterprise with the unmanageable inventory.  Then just use product lists  to set up the OC,  thus by-passing inventory all together.  But - not perfect - doesn't allow for tailoring of pricing, stock...  that inventory does

**Comment by RachL** [comment] 2019-09-09 11:02
@tschumilas I believe this is a duplicate of #4243 and that it is fixed on your server. Please reopen if I'm wrong.

**Closed by RachL** 2019-09-09 11:02 UTC
