### ISSUE TITLE
If I uncheck the 'ask' button in BOM I should no longer get asked to confirm when I delete an item.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#925] opened 2016-04-26 23:51 UTC
[Updated by Myriam 26/07/2018]

## Description
The ask checkbox in BOM is supposed to dictate whether or not I get asked for confirmation before I delete a product. 
Currently I get asked for confirmation (regardless of the ASK checkbox's state) when I delete using the trash can button. 
When I delete by selecting product checkboxes and delete by going Actions > Delete Selected, I'm never asked for confirmation.
All these behaviours are confusing and unconsistent and get users lost.

## Expected Behavior
- I don't see any confusing "ask" checkbox
- When I delete a single product I get a confirmation popin asking for confirmation
- When I delete a bulk selections of product with action command, I get a confirmation popin asking for confirmation

## Actual Bevahior
- I see a confusing "ask" checkbox that also is not working
- When I delete a single product I get a confirmation popin asking for confirmation (this is ok)
- When I delete a bulk selections of product with action command, I don't get any confirmation popin

## Steps to Reproduce
1. Go to bulk order management (https://www.openfoodfrance.org/admin/orders/bulk_management). 
2. You see the ask button, you can test/check and uncheck and see it doesn't change anything
3. Try deleting one single product, see confirmation popin
4. Try selecting multiple products and using action command, no confirmation popin

## Animated Gif/Screenshot
![image](https://cloud.githubusercontent.com/assets/10843056/14837590/1a423cc0-0c5d-11e6-9bba-72b01a26bbbf.png)

## Context
We raised the deletion UX topic again while working an the image deletion issue.

## Severity
S3, a bit disturbing on UX side and dangerous for the bulk action not to have the confirmation popin

## Possible Fix
- remove the "ask" checkbox
- ensure the popin is there when bulk deleting action

**Comment by sineadfenton** [comment] 2017-07-18 07:32
Hey,

We've had a couple of users over in the UK having issues with this button too.

Just want to check in regarding the assignment of this issue and whether we can look to getting a quick fix? Either removing it or having the functionality put behind it?

I also wonder if there is better terminology that we could use rather than Ask? Or perhaps we can have a tooltip that explains what "Ask" does so the users isn't tempted to toggle it on and off without know the implications.

Cheers,

Sinead

**Comment by sauloperez** [comment] 2017-07-18 08:04
> I also wonder if there is better terminology that we could use rather than Ask?

Totally agree. A user trying out our local instance had the same problem because it's not clear what is that checkbox about. I suggest we replace it with a better copy.

**Comment by enricostano** [comment] 2017-07-18 12:48
Related https://community.openfoodnetwork.org/t/ask-checkbox/995

**Comment by capiscuas** [comment] 2017-07-18 13:19
Hi, here is my 2cents to the subject, I believe the most intuitive UI would be to not have that checkbox. It is hard to summarize the behaviour ' do not ask for future deletes' with just the workd 'ask'. 

I think for users that want to do multiple deletes, it is better to just select multiple items ande delete them from the Actions dropdown button. again is just my opinion.

**Comment by sineadfenton** [comment] 2017-07-18 13:28
I would agree @capiscuas. I think not having it would be the best solution all in all. 

I think it also eliminates potential user error with having this ticked, deleting a load of items and not meaning to. The prompt to verify is useful

S

**Comment by enricostano** [comment] 2017-07-18 13:46
Would be great to have the whole "ask" feature described somewhere, like user stories. And then decide what's the best UX approach.

**Comment by capiscuas** [comment] 2017-07-18 14:17
Good idea @enricostano , althought if the interface needs to describe or explain a feature, it's already not intuitive UX-wise.

**Comment by daniellemoorhead** [comment] 2017-07-19 08:02
@capiscuas I think @enricostano meant for us to use in the redesign of the feature, rather than as something to display for the user 😄 

@sineadfenton perhaps you can have a go at describing the way the feature works now and how we could possibly change it? In a user flow or with stories?

**Comment by sineadfenton** [comment] 2017-07-27 11:58
![](https://github.trello.services/images/mini-trello-icon.png) [Ask tickbox](https://trello.com/c/M8YmsZY3/61-ask-tickbox)

**Comment by myriamboure** [comment] 2018-07-13 09:55
@RachL @mkllnk here is another behavior connected to the way we treat deletion. We need to have some standardized way to treat them throughout our system. So the rule would be:
- by default when you try to delete: confirmation pop-in
- that should be for both single and bulk actions
- then we can have a  feature to enable the user to choose not to be asked for confirmation when she deletes items (the current unclear "ask" button) but maybe as a first iteration we should just get rid of that button?
@RachL if you want to write some UX rule proposal that we can all agree on regarding that it could be useful maybe? We could document that somewhere?

**Comment by RachL** [comment] 2018-07-18 16:19
@myriamboure I sure can start writing some rules. The question is where would it be the more useful ? A wiki here on github ?
FYI if you have several pop-ins appearing for confirmation (like if you do several single delete in a short period of time) your browser already ask you if you do want to see the popin or not. So I don't think we need to manage that.

**Comment by myriamboure** [comment] 2018-07-27 12:54
Ok I changed the issue description given the discussion above. Is the solution proposed fine with you @sineadfenton ? @sauloperez ?

**Comment by lin-d-hop** [comment] 2021-07-29 14:06
No comments since 2018... closing #gitcull2021

**Closed by lin-d-hop** 2021-07-29 14:06 UTC
Labels: bug-s3

**Comment by RachL** [comment] 2021-07-29 14:26
It's still reproductible however. We should maybe consider removing the checkbox?

**Comment by RachL** [comment] 2021-07-29 14:33
That's why I wonder if we shouldn't just remove it... less code?

**Comment by lin-d-hop** [comment] 2021-07-29 14:35
I meant writing that issue is more work than benefit :shrug: This conversation is more work than benefit :joy: 
As you wish ;-)
