### ISSUE TITLE
Cannot add item to cart for no apparent reason

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5934] opened 2020-08-20 01:30 UTC
## Actual Behaviour

Cannot add item to cart, I get an error message
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/1f262406-16f1-4ddc-8154-2381d3945f8d)

and cart is frozen
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/2e4836d7-f644-4410-bc11-1a8af6e6a017)

## Steps to Reproduce

1. Open a shop in a tab
2. Open a different shop in a different tab
3. Place an item in cart in first shop (should be ok)
4. Go to tab with 2nd shop, place item in cart
5. freezes
6. Close cart, reload page, now ok 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment] 2020-09-08 16:30
@kirstenalarsen are you still experiencing this? I can't reproduce it...

**Comment by RachL** [comment] 2020-10-28 13:54
I'm closing here, we can reopen if we find a way to reproduce 👍

**Closed by RachL** 2020-10-28 13:54 UTC
