### ISSUE TITLE
Email confirmation | User sign up (checkout)

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1587] opened 2017-05-28 05:50 UTC
**Who:** Any user wanting to register on the OFN.
**How they access the sign up process:** by clicking 'sign up' (via login modal) at the following points in their journey on the site:
- From a shopfront (once they've added items to their cart)
- From the edit cart page
- From the 'log in or guest checkout?' page
- From any page on the OFN, if they have items in their cart (homepage, a groups page, a /sell page, etc).

Note: This story is almost identical to https://github.com/openfoodfoundation/openfoodnetwork/issues/1586, the only difference is that these users need the email confirmation link to return them to the site where they initiated sign up and ensure that the items they put in their cart persist.

-------
**Step 1(a): User signs up**
The new user accesses the sign up tab and submits their email and password.
After submitting the modal will display this text:

![image](https://user-images.githubusercontent.com/10843056/26961738-65c8d7d6-4d24-11e7-8d23-a7ef26257b6b.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  They can close the modal and display the original page underneath (existing functionality).
-  The green success banner does not show (existing functionality).

**Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent.
2. A message to display below the 'resend email confirmation' saying 'We resent the email, check your inbox'.

![image](https://user-images.githubusercontent.com/10843056/27938908-98aacf92-6304-11e7-8217-61da4ac743c9.png)

-------
**Step 2: System requests email confirmation**
The completion of step 1 will trigger the system to do 2 things:
1. System creates a user record, flagged as unconfirmed.
2. System sends a confirmation email to the user that includes a unique confirm link for that user.

![image](https://user-images.githubusercontent.com/10843056/26962736-b14cbc48-4d2b-11e7-8c5d-35a6e25cdd0f.png)

-------
**Step 3: User confirms email**
The user clicking on the confirmation link in the email will trigger the following:
1. System flags the user record as confirmed.
2. System sends the user a 'Welcome' email (same generic email as in #1585).

![image](https://user-images.githubusercontent.com/10843056/26961956-1cf2b84a-4d26-11e7-9d2a-d1056df698b8.png)

3. Browser window opens and displays the page they were on when they signed up, with their active cart, with the login tab open with a 'thanks for confirming message' displayed in the login tab. 

![image](https://user-images.githubusercontent.com/10843056/26961899-aa44def4-4d25-11e7-82fa-339673802628.png)

-------
**Step 4: User logs in**
Successful login from this screen will then close the modal and allow the user to continue browsing or checkout process (existing functionality).

-------
EXCEPTIONS

- If the user attempts to login without clicking on the confirmation link in the email, they will not be able to login and will be directed to confirm (#1616)

- If the user tries to create an account using an email that is already signed up on OFN the existing functionality will apply: 
![image](https://cloud.githubusercontent.com/assets/10843056/26711793/4cee6132-47a6-11e7-8c5b-79338acbe771.png)

- If the user is a previous guest checkout, their customer record will be connected (#1592).

-------
SPIKES / TO BE DETERMINED

- Can the user continue to edit their cart after they've signed up and closed the modal / prior to confirming? How will this impact the items in the cart when they do confirm their email? Will it be the cart when they signed up, or will it reflect changes made after signing up? 

- What is the impact if the user signs up and then checks out as a guest prior to confirming? How would this impact their confirmation?'

**Comment by myriamboure** [comment] 2017-05-29 16:51
The only different I see from https://github.com/openfoodfoundation/openfoodnetwork/issues/1586 is the redirection page after clicking the validation link, it should send back to the checkout page.

I see 3 things to develop here:
- [ ]  1- When sign-up form submitted, email confirmation sent to user and display "check confirmation link in your mailbox" pop-in/banner still on the checkout page.
- [ ] When user click on validation link, open current checkout page in new tab + send welcome email
- [ ] Force login if guest checkout email is already a registered user (would solve https://github.com/openfoodfoundation/openfoodnetwork/issues/907 and https://github.com/openfoodfoundation/openfoodnetwork/issues/1159)

**Comment by sstead** [comment] 2017-06-02 05:46
Existing signup flow:
This is where new users can sign up during checkout:
![image](https://cloud.githubusercontent.com/assets/10843056/26712362/e3f48c3e-47a9-11e7-89a0-7aa6a38e781d.png)

If they choose to login/signup, they see the usual login/signup modal, with their shopping session in the back.

If they signup, they see the green banner and can continue checking out. In the background a welcome email is sent to them.
![image](https://cloud.githubusercontent.com/assets/10843056/26712409/18e645ea-47aa-11e7-8b7e-62e6bd0409a8.png)

**Comment by daniellemoorhead** [comment] 2018-02-09 00:15
Success message on modal when user has clicked on confirm link still not done. Is this in another PR? Note: this is in Step 3, screenshot for point 3.

**Comment by myriamboure** [comment] 2018-03-14 04:14
I just retested and still not done
![screenshot from 2018-03-14 05-12-30](https://user-images.githubusercontent.com/8135376/37383031-65a17e96-2746-11e8-829d-f20f160e8de7.png)

@Matt-Yorkley can you make that small fix? Add the "success message" in the login modal when you are redirected to login modal after having confirmed your email. Thanks :-)

**Comment by Matt-Yorkley** [comment] 2018-03-15 13:43
This should be covered in #2083. Looks like it got merged at 2am?

**Comment by myriamboure** [comment] 2018-03-15 13:50
Awesome, closing then :-)

**Closed by myriamboure** 2018-03-15 13:50 UTC
Labels: australia, france
