### ISSUE TITLE
setup development server got issue : ERROR: [Errno 21] Is a directory: 'bin'

### ISSUE THREAD

**Issue by joysydney** [openfoodfoundation/openfoodnetwork#10099] opened 2022-12-05 12:40 UTC
hi all, i tried to setup the openfoodnetwork in ubuntu 22.0.4 machine, i followed the steps to setup all necessary dependencies from here https://github.com/openfoodfoundation/openfoodnetwork/wiki/Development-Environment-Setup%3A-Ubuntu

while trying to run "foreman start" in visual studio (https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md#get-it-running), i got a message "ERROR: [Errno 21] Is a directory: 'bin'", does anybody know what could be the issue?

**Comment by joysydney** [comment] 2022-12-05 12:42
![image](https://user-images.githubusercontent.com/100510055/205639840-8d04a95f-8f5d-424b-838b-2674e8f59089.png)

**Comment by mkllnk** [comment] 2023-03-07 23:45
I'm sorry that nobody could help you with this. I can't reproduce the issue either. Since it has been a while since you asked this question, I'll close this issue. But feel free to try again with the latest updates and re-open this issue if it's still a problem.

**Closed by mkllnk** 2023-03-07 23:45 UTC
