### ISSUE TITLE
[Checkout] Impossible to checkout on shop 3570

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9610] opened 2022-08-30 11:46 UTC
## Description
Clients can't checkout on shop 3570 
https://coopcircuits.fr/lafermemaraichette/shop#/shop
It doesn't work whether choosing to pay with bank card or with cash. 

## Expected Behavior
You should be able to checkout.

## Actual Behaviour

When trying with voluntary contribution or bank card, same error:
"The checkout failed. Please let us know so we can proceed your order". 

Request URL: https://coopcircuits.fr/checkout.json
{"errors":{},"flash":{"error":"The checkout failed. Please let us know so that we can process your order."}}

Then, after trying once with bank card and trying again, the error is different:
"Payment could not be processed, please check the details you entered"

Request URL: https://coopcircuits.fr/checkout.json
{"errors":{},"flash":{"error":"Payment could not be processed, please check the details you entered"}}

## Steps to Reproduce
1. Try to place an order in the shop https://coopcircuits.fr/lafermemaraichette/shop#/shop

## Animated Gif/Screenshot
![Screen Shot 2022-08-30 at 13 46 09](https://user-images.githubusercontent.com/28386648/187428604-bbbe5a53-4bed-477e-ab68-7af7b24c035a.png)
![Screen Shot 2022-08-30 at 13 45 40](https://user-images.githubusercontent.com/28386648/187428608-be1a3e67-ada7-4650-aa1a-44c4ad4af760.png)

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Additional context
The shop manager indicated that the first issue was reported on Friday by one user, then yesterday at least 2 clients reported not being able to checkout. Before that she never had any issue. (can it be linked to the downtime on CoopCircuits ? https://github.com/openfoodfoundation/openfoodnetwork/issues/9596)

**Comment by filipefurtad0** [comment] 2022-08-30 11:55
It looks like this bugsnag error:
https://app.bugsnag.com/open-food-france/coopcircuits/errors/62ecc2b4c7b65f000c45d1d2?filters[event.since]=30d&filters[error.status]=open&event_id=630dfa3600963db5be290000

**Comment by audez** [comment] 2022-08-30 12:00
thanks! yes indeed, i see me in the request details :) do you know where it can come from?

**Comment by audez** [comment] 2022-08-30 12:09
oh oh !

![Screen Shot 2022-08-30 at 14 08 56](https://user-images.githubusercontent.com/28386648/187432897-5abc4624-6f32-47e7-83f4-3b28d8a162cf.png)

**Comment by audez** [comment] 2022-08-30 12:14
ok I get it: if you choose the option "back office only" in the shipping methods, it displays the previous error in the shipping info, and then you can't checkout 
![Screen Shot 2022-08-30 at 14 13 14](https://user-images.githubusercontent.com/28386648/187433856-b751b94e-00d3-4689-981f-c8511f4fcd3e.png)

**Comment by filipefurtad0** [comment] 2022-08-30 12:17
Whoa - awesome and quick investigation @audez :zap: :raised_hands: 

This are some related S3s on this, it appeared before... I'll look for them.

**Comment by RachL** [comment] 2022-08-30 12:18
well done @audez then I guess we can close here? This switch is intended for people to be able to disable their shipping methods from time to time. There are already issues covering the fact that we need to improve the error messages :+1:

**Comment by audez** [comment] 2022-08-30 12:18
no actually it's a fail 😂 i still can't checkout, even with the other option, or after creating new shipping method and payment method

**Comment by RachL** [comment] 2022-08-30 12:21
@audez I can checkout fine. Can you detail the step you do to reproduce?

**Comment by audez** [comment] 2022-08-30 12:28
oh ok cool, in fact it works for me too. It's because i kept the same cart than when i first had the issue. I was able to reproduce only with the same cart with which I had the bug. When i added something to the cart, it was OK!

**Comment by filipefurtad0** [comment] 2022-08-30 12:39
Should we double check if those customers were not charged, after the first failed checkout attempt? We had something similar [here](https://github.com/openfoodfoundation/openfoodnetwork/issues?q=is%3Aissue+is%3Aclosed+label%3Abug-s2+stripe+debited). We did have a recent Stripe upgrade...

**Comment by filipefurtad0** [comment] 2022-08-30 12:42
I think this might be the same or very closely related to this issue:
https://github.com/openfoodfoundation/openfoodnetwork/issues/8219

**Comment by RachL** [comment] 2022-08-30 12:43
> We did have a recent Stripe upgrade...

I don't think it was deployed on FR?

**Comment by filipefurtad0** [comment] 2022-08-30 12:44
> I don't think it was deployed on FR?

Right! - it didn't - we can scratch that :+1:

**Comment by audez** [comment] 2022-08-30 14:55
You're right @filipefurtad0 I just checked and there has been Stripe payments 😢 and i'm a victim too!

**Comment by RachL** [comment] 2022-08-30 15:28
shall we update 8219 or do we want to open a new issue that merges the two?

**Comment by filipefurtad0** [comment] 2022-08-31 15:49
Ok, tried to sum up everything here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/9614

Closing here and 8219.

**Closed by filipefurtad0** 2022-08-31 15:49 UTC
Labels: bug-s2
