### ISSUE TITLE
Inherited product property override doesn't work as expected

### ISSUE THREAD

**Issue by JenRSmith** [openfoodfoundation/openfoodnetwork#4466] opened 2019-11-15 04:35 UTC
## Description
Inherited product property override advises that properties will be inherited from the producer unless overridden above. This suggests that if a property is added to the product it will replace the inherited property. What actually occurs is that the added property appears in addition to the inherited property. 

## Expected Behavior
Based on the wording adding a property to a product should replace the inherited property with the newly added property.

## Actual Behaviour
The newly added property appears in addition to the inherited property. 

## Steps to Reproduce

1. https://staging.katuma.org/admin/products/cardamomo/product_properties

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: Katuma
* Browser name and version: Chrome Version 78.0.3904.97 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): PC

## Possible Fix
Change the wording so that it is clear to the user that adding a property to a product which has inherited properties will not remove the inherited property but rather display both properties.

**Comment by lin-d-hop** [comment] 2020-02-03 15:48
Hi @JenRSmith,
We've just been sitting in Brussels looking at future papercuts and chatting about this issue.

From your description we're not exactly clear on what the issue is so we can't decide if it is a papercut or not.

In future it would be really helpful if you would add a screenshot or gif AND add the steps to reproduce. These really help make issues more clear.

Our main question here is:
1) Is ADDING the property the expected behaviour? Thus we need to change the translation from Override to something more suitable?
2) Is OVERRIDE the expected behaviour. Thus we need to change this functionality. Are we sure users are not currently using it in the existing way and thus we will be breaking the functionality for them? In this case this is likely too big to be a papercut.

**Comment by JenRSmith** [comment] 2020-02-03 23:55
Hi @lin-d-hop 

This was just an issue with the wording, hence the reason it was considered a papercut. 

Apologies for the lack of supporting info. This was the first papercut I have submitted and I recall being a little pressed for time.

**Comment by lin-d-hop** [comment] 2020-05-07 10:37
Great. So this issue can be resolved by updating the translation.
Ask in #instance-managers if you need more help :-)

**Closed by lin-d-hop** 2020-05-07 10:37 UTC
Labels: bug-s5
