### ISSUE TITLE
Managers of enterprises cannot update the Notifications field for managed enterprises (irrespective of their profile type)

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7964] opened 2021-07-22 17:05 UTC
## Description

Managers of enterprises currently cannot update the `Notifications` field, under the Users tab, for the enterprises they have received permissions to manage. In these cases, the page appears broken, and the settings cannot be changed.

The `Users` tab appears correctly though, when logging in as the enterprise owner.

## Expected Behavior

Logging in as a manager of a given enterprise (i.e., having the required permissions been granted) accessing the `Users` tab should displays the page correctly (below), with settings which can be edited, namely the `Notifications` field:

![image](https://user-images.githubusercontent.com/49817236/126677602-ba6f82b1-fc3f-4364-895c-115a365bb389.png)

## Actual Behaviour

Logging in as a manager of a given enterprise (i.e., having the required permissions been granted) accessing the `Users` tab displays a partially broken page (below), with settings which cannot be edited:

![image](https://user-images.githubusercontent.com/49817236/126677670-b9d3a2fe-a34d-4331-a2c4-80a2894465f8.png)

## Steps to Reproduce

1. Log in as a producer profile only (or a hub) or enterprise (A)
2. Grant permissions to another enterprise (B) to manage/edit your profile
3. On a different session: log in as the managing enterprise (B) and edit the details of enterprise A: navigate to `Users` section of the Dashboard.
4. See the incorrectly displayed page; notice these cannot be edited.

## Animated Gif/Screenshot

![Peek 2021-07-22 14-57](https://user-images.githubusercontent.com/49817236/126679554-297b20d8-ca13-4536-96f2-fab567a605ed.gif)

See also the sections **Expected vs. Current behavior** above.

## Workaround

None.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3.8.7
* Browser name and version: Tested for Chrome 91 and Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

**Comment by RachL** [comment] 2021-07-23 08:46
For the record, this is a feature :D https://guide.openfoodnetwork.org/basic-features/enterprise-profile/enterprise-settings#users

**Comment by lin-d-hop** [comment] 2021-07-23 08:56
The point remains that the system distrust that was created by the Notifications field disappearing is the cause for this.

This was highlighted by two different experienced users. It was highlighted because people were on holiday so they were accessing from different account. But the fact that two users pointed out a problem (rather than looking at what had changed themselves) is because these users suddenly didnt trust this part of the system as it had just broken.

**Comment by filipefurtad0** [comment] 2021-07-23 09:50
Humm indeed @RachL :eyes: 

That link clearly reads:

> Only the owner can nominate the user who will receive the notifications, among the enterprise managers list

However, from the Permissions section I got the impression this was indeed a bug:

https://guide.openfoodnetwork.org/basic-features/enterprise-profile/enterprise-to-enterprise-permissions-e2es#enterprise-permissions

> Permission to edit profile: one company allows another to modify details in their Enterprise Profile (contact details, address, description, ...).

So, it allows another company to modify everything on the Profile... except the `Users` section.

**Comment by jaycmb** [comment] 2021-07-26 20:04
> However, from the Permissions section I got the impression this was indeed a bug:

Looks a bit weird indeed or at least not clearly indicated by the UI to the user that they do not have the permission, because it´s not a disabled notifications field.

**Comment by lin-d-hop** [comment] 2021-07-29 17:09
Closing as this wasnt actually an issue :sweat_smile:

**Closed by lin-d-hop** 2021-07-29 17:09 UTC
Labels: bug-s2
