### ISSUE TITLE
Payment Method Description dropped off Invoices

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#6359] opened 2020-11-10 22:46 UTC
## Description
Payment Method Description information was dropped off invoices by the resolution of Issue #5208 

Issue #5208 changed invoices so that payment details were displayed in a table. The decision was made to leave the Payment Method Description out of this table as it can include lengthy content which would throw out the layout of the table. Payment Method Description was not moved to another section of the invoice however, and it now no longer appears on Invoices.

One of the main uses cases for the Payment Method Description field is to provide How to Pay information such as bank details for making a deposit. This information appeared at checkout and also in invoices. There is not currently a formal way for Enterprises to include How to pay information in Invoices so this was a common workaround **NOTE: there is an open issue exploring a resolution of the How to Pay issue (#5209) which may overlap this issue.**

Enterprises previously used the Payment Method Description field to provide How to Pay information, which would then be displayed at the bottom of the invoice. Now that this field no longer appears on Invoices, Enterprises currently have no way of including additional payment details relating to the Payment Method on Invoices.

## Expected Behavior
Prior to issue #5208 the Payment Method Description field appeared in invoices. Enterprises that relied on this feature have now lost it. This is how the Invoice used to look:

![Screen Shot 2020-11-09 at 12 46 36 PM](https://user-images.githubusercontent.com/47620442/98741692-37859280-2401-11eb-839a-5ab14cc11b3f.png)

## Actual Behaviour

The invoice now looks like this

![Screen Shot 2020-11-11 at 9 40 03 AM](https://user-images.githubusercontent.com/47620442/98742198-1d987f80-2402-11eb-8564-678d902190ed.png)

## Steps to Reproduce
1. Create an Order / access a shop with existing orders
2. Log in as a Manager of the Enterprise
3. Go to Orders
4. Select the checkbox next to an Order
5. Click Print Invoice

## Workaround
The Enterprise can manually provide additional details such as How to Pay information to customers by email or as a handwritten note in posted invoices.

## Severity
S3

-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix
Under Payment Summary there is a field called Payment Description at Checkout: which then prints the description info, not in the table just width of the page

**Comment by emilyjeanrogers** [comment] 2020-11-10 22:57
FYI @tschumilas 

Also @kirstenalarsen solving this has a link / dependency with #5209. If including How to Pay information is the MAIN use case of the Payment Method Description field on Invoices, then a resolution to #5209 would make this issue less of a priority to resolve.

**Comment by kirstenalarsen** [comment] 2020-11-11 06:57
I think we need to look at fixing this (which is likely a papercut (rather than waiting on #5209 - which is definitely not) unfortunately. I don't think we can assess as papercut tonight though as it doesn't have a proposed solution @emilyjeanrogers 

Would it work to have the Payment Method Description displayed just for the 1st and/or last Payment method or something?  I think probably the first - the one used when the order was placed. This would fix the problem that we have created and would likely be very easy to do. 

For purposes of papercut tonight that's what I'm proposing. Under 
Payment Summary there is a field called Payment Description at Checkout: which then prints the description info, not in the table just width of the page

**Comment by tschumilas** [comment] 2020-11-11 16:15
likely too late with this -  but just saying I like the solution you propose @kirstenalarsen

**Comment by kirstenalarsen** [comment] 2021-02-03 23:19
I have just had pushback from the Aus customer support team about this being our papercut nomination as they argue that it is a regression introduced by #5208 and was picked up straight away. I think this is a valid point and arguably should be fixed in delivery pipe without being an AU voted papercut. This proposal would mean it potentially goes into dev ready above proposed papercuts or s3s? Thoughts @RachL @lin-d-hop @jaycmb ?

**Comment by RachL** [comment] 2021-02-04 09:17
@kirstenalarsen we don't have a process for "regressions". I know it can be confusing because when doing rails upgrade we have a time frame during which we tackle non s1/s2. The rest of the time its our s3/papercuts process that deal with s3 (all our s3 are regressions ;) ).

The quickest if you want this fixed, is to change your vote for your current s3 that is in dev ready: https://github.com/openfoodfoundation/openfoodnetwork/issues/5018

**Comment by kirstenalarsen** [comment] 2021-02-04 10:13
ok cool. no we’ll just leave it as our next pick papercut. Thanks

**Comment by jibees** [comment] 2021-05-04 11:34
I've submitted a PR, and now here's the new invoice template (see `Payment Description at Checkout` part at the bottom):
<img width="755" alt="Capture d’écran 2021-05-04 à 13 33 20" src="https://user-images.githubusercontent.com/296452/116997652-5cd2c980-acdd-11eb-87cf-05f7a0ac3706.png">

I hope it suits you.

**Comment by jibees** [comment] 2021-05-05 07:59
@kirstenalarsen @RachL 
Re.
> Would it work to have the Payment Method Description displayed just for the 1st and/or last Payment method or something? I think probably the first - the one used when the order was placed.

When you said _the one used when the order was placed_, do you think about `Payment State = Failed` for example? 
In the screenshot below, I've made 2 payments with credit cards that failed, and then I chose "Cash on collection". The Payment Description at Checkout is linked to the first one, ie. "Credit card (fake)". What to you think?
<img width="744" alt="Capture d’écran 2021-05-05 à 09 54 36" src="https://user-images.githubusercontent.com/296452/117111757-5f3e2d80-ad88-11eb-94c2-45534e2d8368.png">

Should the Payment Description at Checkout part be linked to the first payment, or the first that is actually in `CHECKOUT` state? Is there any other states? How can I replicate it to test each cases?

Thanks. 🙏

**Comment by kirstenalarsen** [comment] 2021-05-05 20:41
I think it should be the one that is connected to the order in checkout
state i.e. the one actually used. Does that work?

**Comment by tschumilas** [comment] 2021-05-05 22:54
Just a reminder that there are 2 invoice templates to consider.  They are different.  Below is an example of the current invoice template used in instances where tax is not included in prices.  Here is a google sheet that compares the 2 invoice templates and what info is extracted - https://drive.google.com/file/d/1fVSUbJ6KaNY782bNN3GISiJzc1gk_aYz/view?usp=sharing
![image](https://user-images.githubusercontent.com/13171778/117219426-3e4efa00-add3-11eb-84e9-ce5af462f32b.png)

**Comment by jibees** [comment] 2021-05-06 08:03
> I think it should be the one that is connected to the order in checkout state i.e. the one actually used. Does that work?

Yes, I guess too. Then, I'll ask core-devs team what this means in term of `state` in code base.

> Just a reminder that there are 2 invoice templates to consider.

I saw this, what as far as I understood they both use the same template to generate Payment summary (and then payment description at checkout). Thanks for pointing me that out! 🙏

**Closed** 2021-05-27 09:01 UTC
Labels: AU, bug-s3
