### ISSUE TITLE
Email confirmation | Enterprise sign up

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#1585] opened 2017-05-28 05:49 UTC
**Who:** Enterprises wanting to register on the OFN.
**How they access the sign up process:** via the 'Register' link on the homepage and on the dropdown the displays at the top of the screen when you first arrive.

-------
**Step 1(a): User signs up**
The new user accesses the sign up tab on /register and submits their email and password.
![image](https://user-images.githubusercontent.com/10843056/26958500-75ff614e-4d0e-11e7-95d8-c57c4e694775.png)

After submitting, the modal will display this text:
![image](https://user-images.githubusercontent.com/10843056/26959822-a7b21ab8-4d15-11e7-95b5-34bc31672c5a.png)

And the following conditions are in place:
-  User remains logged out (new functionality). 
-  Closing the modal takes them to the homepage (existing functionality).
-  The green success banner does not show (existing functionality).

Step 1(b): User resends confirmation email**
If the user needs the confirmation email to be resent, and clicks on the link in the model (screenshot above), this triggers:
1. The same confirm email to be sent.
2. A message to display below the 'resend email confirmation' saying 'We've resent the confirmation to email address, check your inbox'.

![image](https://user-images.githubusercontent.com/10843056/27938779-9835b4a6-6303-11e7-8e00-7b82a714a30c.png)

-------
**Step 2: System requests email confirmation**
The completion of step 1 will trigger the system to do 2 things:
1. System creates a user record, flagged as unconfirmed.
2. System sends a confirmation email to the user that includes a unique confirm link for that user.
![image](https://user-images.githubusercontent.com/10843056/26959070-8f39aaf4-4d11-11e7-86ac-4f5501a166ea.png)

-------
**Step 3: User confirms email**
The user clicking on the confirmation link in the email will trigger the following:
1. System flags the user record as confirmed.
2. System sends the user a 'Welcome' email.

![image](https://user-images.githubusercontent.com/10843056/26959402-62449cc8-4d13-11e7-8e25-6f7d7ab68da7.png)

3. Browser window opens and displays the /register screen with the login tab open with a 'thanks for confirming message' displayed in the login tab.

![image](https://user-images.githubusercontent.com/10843056/26960844-b2b219ec-4d1d-11e7-8b97-c4ff3d477d15.png)

-------
**Step 4: User logs in**
Successful login from this screen will then allow the user to progress to the 'Hi there, You can now create a profile for your Producer or Hub' screen of the /register wizard (existing functionality).

-------
At this stage in the process the user is now email verified and able to create their enterprise profile. There are changes to the flow within this process, as you can see on this flow diagram.

![enterprise-signup](https://cloud.githubusercontent.com/assets/10949052/26708351/a7ce771c-478e-11e7-859f-07653b614a6f.JPG)

Current flow: the enterprise is created at the 'add enterprise type' step and the confirm email process is triggered.

Change flow to be: the enterprise is created at the 'add enterprise type' step and an 'Enterprise created' email is sent to the user.

-------
**Step 5: Create enterprise profile**
The user goes through the same steps for the profile creation process - add details > add contact > add enterprise type > add about > add photos > success, go to home.

When the user selects their enterprise type:

![image](https://user-images.githubusercontent.com/10843056/26959569-fd94e638-4d13-11e7-9611-d7bacd666538.png)

1. They will continue through the wizard to the 'Add About' form.
2. They will be sent a 'Enterprise created' email. Note this is Australian centric content but can be translated by instances to suit their needs.
![image](https://user-images.githubusercontent.com/10843056/26959719-ea3eb162-4d14-11e7-8c23-61d6c7f6fdb6.png)

As part of this change to the flow, copy on the following screens will need to be changed:

The 'Add About' form
![image](https://cloud.githubusercontent.com/assets/10843056/26709256/b9d78e02-4794-11e7-87b5-2ea2884ded65.png)

The 'Success' page
![image](https://cloud.githubusercontent.com/assets/10843056/26709102/892c919a-4793-11e7-87e0-0bc873dedd94.png)

-------
EXCEPTIONS HANDLED IN OTHER ISSUES
- If the user attempts to access the /register wizard to create an enterprise user without clicking on the confirmation link in the email, they will not be able to login and will be directed to confirm (#1615).

- If the user is a previous guest checkout, their customer record will be connected (#1592).

-------
SPIKES / TO BE DETERMINED
- If we remove the confirmation step from the profile creation process will it break it? Will it break when an enterprise user attempts to create another profile that does not require the confirm step anymore? How does the 'create another profile' flow fit into the current flow? And the future flow? Is it a link once you've added the photos? Or is there a link (or many links) in other places?)

-------

**Comment by daniellemoorhead** [comment] 2017-05-28 06:04
@sstead and @oeoeaio can you please have a look at the flow (which on your drawing of the profile creation Sally).

Outstanding questions:

- [ ] Is the 'thanks and select a package' email in the right spot in the new flow?
- [ ] How does the 'create another profile' flow fit into the current flow? And the future flow? Is it a link once you've added the photos? Or is there a link (or many links) in other places?
- [ ] Do we need to worry about exceptions here (1. email address already in use; 2. previous guest check out; 3. previously signed up but didn't confirm)?

**Comment by myriamboure** [comment] 2017-05-29 15:29
If a user is logged in with an unconfirmed email before starting entreprise creation (ex: all existing uses), the system needs to resend the confirmation email and the user needs to click on confirmation link before she can create the entreprise. So about exceptions, IMHO, on 3: yes you need an exception.

**Comment by myriamboure** [comment] 2017-05-29 17:04
> It would be better if it wasn't a dead-end page so having a means of getting back to the OFN homepage or the userguide or somesuch thing would be good.

IMHO  when the user clicks on valiation link, it should directly redirect to the “enterprise creation form” so that the user can start fill in the profile information that he was about to start when signing up.

**Comment by myriamboure** [comment] 2017-05-29 17:07
Listing what needs to be adapted from existing:
- [ ]  1- When sign-up form sent, email confirmation sent to user and display "check validation link in your mailbox" pop-in/banner still on enterprise registration page
- [ ] 2- If unconfirmed user try to create an enterprise, re-send email confirmation + display message “you need to validate your email before you can create an enterprise, check your mailbox!”
- [ ] 3- When user click on validation link, open current enterprise registration page in new tab + send user welcome email
- [ ] 4- When entreprise form complete, send entreprise welcome email.

**Comment by sstead** [comment] 2017-05-31 00:05
Is the 'thanks and select a package' email in the right spot in the new flow?
- I think the 'thanks' email that branches off the Confirmation email is still correct. It lets the user know that they have successfully confirmed their email. 
- The 'select a package' page currently shows when the user logs in to /admin for the first time, after creating their enterprise profile. It will continue to show until they select a package. They may have been directed by their confirmation link, or they may have just tried to access /admin from the homepage. They may or may not have confirmed yet. Under the new flow, the user can confirm their email but not have an enterprise profile yet. So the confirmation link shouldn't link to /admin, instead just to the homepage. If they land at the homepage, it's ok because they won't be able to access /admin until they have an enterprise profile, at which point it's correct to then show them the 'select a package' screen. So in summary yes, I think it's ok that the 'select a package' screen continues to be triggered the first time a enterprise owner (with an enterprise that has no package selected) goes to /admin. We just need to make sure the confirmation link doesn't go to /admin because new users may not have enterprises yet (i'm not certain if it currently does?).. this is what the link looks like, it must then redirect to /admin- 
(i'm not certain if it currently does?).. this is what the link looks like, it must then redirect to /admin- http://staging2.openfood.com.au/enterprise/confirmation?confirmation_token=Ybr3PrsMAxohprSEkeZX

**Comment by sstead** [comment] 2017-05-31 00:22
How does the 'create another profile' flow fit into the current flow? And the future flow? Is it a link once you've added the photos? Or is there a link (or many links) in other places?
- Currently a user needs SuperAdmin permission to create >1 enterprise, so no, we don't prompt them to create more profiles in the wizard after they've created one.
- There is a[ github issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/683) to remove this requirement, as it was agreed to be redundant/pointless. 
- Currently, you'd need to email us to ask for permission to create additional enterprises, then the guide suggests, and I usually do too, that users just create another profile from the back end, not using the wizard. But they could also create another profile using the wizard.
- I've just checked whether confirmation is required for each new enterprise:
I create my first profile and don't confirm my email account.
I get permission to create >1 enterprise. I create a second enterprise and get an email confirmation link for it too.
I validate the first entperprise confirmation email. That profile is then valid. 
The second enterprise I created isn't valid until I validate the confirmation link. 
Once I have 2 valiadated enterprises, if I create a third enterprise I don't need to confirm my email for it. 
So it seems you need to validate additional enterprises only if you have another pre existing non-validated enterprise.

**Comment by daniellemoorhead** [comment] 2017-06-02 01:37
>IMHO when the user clicks on validation link, it should directly redirect to the “enterprise creation form” so that the user can start fill in the profile information that he was about to start when signing up.

Hey @myriamboure this page is not the one that appears when the user has clicked on the confirm link in their email, but is the one that needs to appear when they have submitted the sign up form. On submit, the system will send them an email but there also has to be a resulting page telling them to go check their inbox and confirm it before they can create an enterprise.

**Comment by daniellemoorhead** [comment] 2017-06-02 02:55
@myriam - @sstead and I sat down and completed what we see as the scope for this issue. All this is listed underneath the flow picture alongside of the screenshots sally has added of the existing flow.

Please review and tell us if you agree with scope. :)

**Comment by myriamboure** [comment] 2017-06-03 11:49
@daniellemoorhead I had another proposal in mind:
- at the begining of the flow, the user click on "create entreprise", he is not signed up so the sign up form opens, (like it is done now)
- when submit, two things happen:
1- Confimation mail sent
2- View : message telling "a confirmation email has been sent, please validate to continue entreprise creation" (so we force validation email un a gentle way ;-)
- SO when the user click on confirmation email he is redirected back to the entreprise creation flow
As it's a new "confirm entreprise email" page, we shoud be able to customize the redirection link when click on "confirm" and sent to entreprise registration wizard?
So I disagree with your point 4, it's strange in UX if the user strated creating an entreprise, sign up, confirm email, and is sent back to home page and has to start again the create entreprise process.

**Comment by daniellemoorhead** [comment] 2017-06-16 03:50
View of steps in flow:
![enterprise-signup](https://cloud.githubusercontent.com/assets/10949052/26708351/a7ce771c-478e-11e7-859f-07653b614a6f.JPG)

**Comment by myriamboure** [comment] 2018-05-21 13:13
Oki doki I'm going through the remaining stories on email confirm to check what we still need to do.
I went through this one and here are my testing notes: https://docs.google.com/document/d/1Bucf917QpXYJrJ3J-Oy7Ntr0nN4UfVpymvYITOgOGBI/edit?usp=sharing
The process is slighty different from the one described here on one detail (the user creation / email confirmation / login process within the registration wizard) but the result is smooth and easy to understand and really clear so satisfying for me. All emails are sent at the right moment in the process, etc. So I close this story, shout if you are not happy @daniellemoorhead @sstead . 

**Remains to be done connected to this (separate issues already opened):**
- If the user is a previous guest checkout, their customer record will be connected (#1592 issue still open).
- and I created another small issue to add the small sentence that disappeared to tell "“If you exit the wizard at any stage, you can continue to create your profile by going to the admin interface” (#2303)

**Closed by myriamboure** 2018-05-21 13:13 UTC
Labels: australia, france
