### ISSUE TITLE
[Spree Upgrade] Shop showing incorrect products (product cache in v2)

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#3391] opened 2019-01-25 00:21 UTC
## Description
On the French staging server, which now holds the Spree Upgrade I created an order cycle for a hub shop. The OC contains Apple products. But when I get to the shop I see a list of random products that this shop doesn't even have permission to sell. I'm not sure where this product data is coming from - is it seed data for the new Staging server? I can't see these products in the backend as Super Admin....?

Either way I can't place an order, and it's not possible to meaningfully test checkout if I can't put the right products in the shop.

Update: I created a second OC and that OC correctly shows the right items, however I can't checkout in that OC, or others.

## Expected Behavior
The products in the shop should reflect the products in the Order Cycle.

## Steps to Reproduce
1. Open OC on French staging and see if the shop holds the correct items

## Animated Gif/Screenshot
This shows OC#1 - full of incorrect products
https://www.useloom.com/share/9e3ea68323764329a9ff0e9d207a6869

This shows OC#2 which correctly shows the Apple related products
https://staging.openfoodfrance.org/winery-district-food-hub/shop

## Severity
Because this bug is only on Staging, related to the Spree upgrade, I'll assign it s4
bug-s4: it's annoying, but you can use it

## Your Environment
https://staging.openfoodfrance.org/winery-district-food-hub/shop
Spree testing, desktop, Chrome, PC

**Comment by luisramos0** [comment] 2019-01-28 15:12
It's a cache error Admin - Configuration - Cache Settings (Mise en Cache):
![screenshot 2019-01-28 at 15 11 43](https://user-images.githubusercontent.com/1640378/51845226-0bbe1900-230f-11e9-9187-9ad0d5e6f21c.png)

**Comment by luisramos0** [comment] 2019-01-28 16:19
I spent an hour or so trying to find the problem but I couldnt find the cause yet. It's a cache issue for sure, and #3392 looks like it's also a cache issue.

**Comment by luisramos0** [comment] 2019-01-30 15:21
I now understand well the products cache code but it is not easy ([cache invalidation is one of the 2 hard problems in computer science](https://i.imgur.com/lJpH5nX.jpg)) because different events will trigger the cache invalidation (aka refresh_cache). After 6 hours or so trying a few things I'll leave this one for the next dev who wants to have a look at it.

Meanwhile I built a little feature to help debug the product cache: see #3404

**Comment by sauloperez** [comment] 2019-02-12 11:31
I'd like to take a look at it but I first want to get the green build

**Comment by tschumilas** [comment] 2019-03-03 19:59
Is this really an s4 bug?  On the Canadian site now -  it is next to impossible for any aggregator (hub) to run a shop.  Changes they make to OCs,  and changes suppliers make to stock are not articulating into the shopfront.    A shopper can checkout -  if they just click through the stalled 'saving' message when they try to checkout.  And the resulting order does accurately reflect the correct products (ie even if a ghost variant that shouldn't be in the OC is in their cart,   the resulting order drops these ghosts).   I think this is the problem I was having last week when I posted in slack about the ghosts and assumed it was all because I was using some 'recycled' enterprises.  So - its not the enteprises - I think its this.  Two calls from shoppers already today telling me the shop isn't working.  Don't know a workaround. Doesn't that make it a s1?

**Comment by luisramos0** [comment] 2019-03-03 22:53
Hi @tschumilas this is a problem with cache in version 2 branch (everything that has [Spree Upgrade] is not live yet). So, you problem is not in this context for sure.

Having said that, Product cache can well be broken in v1...
So I think you should create a separate issue for your problem. Please provide specific details on how to see it in ofn-can live or how to replicate it. Thanks!

**Comment by sauloperez** [comment] 2019-03-19 15:21
I created https://github.com/openfoodfoundation/openfoodnetwork/issues/3621 to make it easier to spot the actual reason of the failure.

**Comment by sauloperez** [comment] 2019-03-22 12:34
For the record, something worth considering in the future is to add a second DJ worker serving from queue dedicated to products cache, given the importance of these jobs. So far, we only have one and it is a common best practice to have purpose-specific queues.

**Comment by sauloperez** [comment] 2019-04-04 12:29
I created all necessary issues that stem from this and the PRs got merged so we can close.

**Closed by sauloperez** 2019-04-04 12:29 UTC

**Comment by luisramos0** [comment] 2019-04-04 12:39
I am not sure I understand what was the problem and what was done to fix it, can you please make a quick summary of it? probably useful for other people as well.
