### ISSUE TITLE
Shopfront message - INCORRECT TEXT #step6 #spree_upgrade

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1647] opened 2017-06-29 11:48 UTC
This issue has been found by @sstead while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1524, more info [here](https://community.openfoodnetwork.org/t/spree-testing-june-2017/976).

![](https://community.openfoodnetwork.org/uploads/default/optimized/1X/12c3dad5eb29c29e9e68b30441684f0a8cd70518_1_690x331.png)

**Comment by enricostano** [comment] 2017-06-29 11:55
@sstead how did you create the hub? I created a hub from scratch using the UI and I don't see that text. Only the usual placeholder for the input textareas:

![2017-06-28-142824_1366x768_scrot](https://user-images.githubusercontent.com/748971/27686292-7322b3f8-5cd2-11e7-8d5e-967f8e7051d7.png)

Furthermore I could not find any copy with that text in Spree. Any seed data in place?

**Comment by sstead** [comment] 2017-07-07 04:02
@enricostano I created the profile via the /register wizard. I just did the same process again, and the issue did not happen again. I'm not sure what Seed Data is? I'll keep my eyes peeled to see if this problem occurs again.

**Comment by enricostano** [comment] 2017-07-10 12:13
> I'm not sure what Seed Data is?

https://community.openfoodnetwork.org/t/seed-data-development-provisioning-deployment/910

> I just did the same process again, and the issue did not happen again.

@sstead can we close this issue for now and open it again if someone is able to reproduce it?

**Comment by enricostano** [comment] 2017-07-14 11:02
@sstead @kirstenalarsen I guess that the issue didn't show up again since in that server there was something else deployed. Can you please give a look again as soon as we have step 6 deployed again somewhere?

Thanks!

**Comment by enricostano** [comment] 2017-07-20 12:27
@sstead could you please test this again? Thanks!

It is deployed at https://staging1.openfood.com.au

cc/ @sigmundpetersen @OliverUK

**Comment by sstead** [comment] 2017-07-21 02:29
This happened for me again for the first enterprise I created on the new deploy on Staging1... I'm not sure if this is related to 'seed data'

![image](https://user-images.githubusercontent.com/10843056/28446744-2d1d65f2-6e10-11e7-9ed4-922f28a78053.png)

**Comment by enricostano** [comment] 2017-07-21 10:21
Yeah @sstead it seems pretty related to seed data to me. Can @oeoeaio or @RohanM please shade some light here? Thanks!

**Comment by oeoeaio** [comment] 2017-07-27 02:34
Wow, this is super weird. I have never seen that text before. It can't be from Spree though...

**Comment by oeoeaio** [comment] 2017-07-27 02:47
No record of it anywhere in the codebase, doesn't appear in any other Aus staging or production database... WTF

**Comment by oeoeaio** [comment] 2017-07-27 02:49
We don't seed our staging databases, so I don't think seed data is the answer, unless I'm missing something...

**Comment by enricostano** [comment] 2017-08-04 13:18
@mkllnk @oeoeaio I don't think this is related to Spree upgrade, can we close it or move out of the step 6 milestone?

**Comment by mkllnk** [comment] 2017-08-10 08:05
This is weird. I just searched for "Gumbo beet greens corn soko endive gumbo gourd" on Google and found 45.000 demo stores that seem to run on Wordpress. I'm wondering if that's a version of "Lorem ipsum".

It's not in the code base, it's not in the database, could it be something that Sally's browser auto-filled?

I don't like to make decisions on things I don't understand, but yes, I guess we can remove this issue from the milestone. But since we are all surprised, finding out the reason could be really interesting.

**Comment by daniellemoorhead** [comment] 2017-08-11 02:42
@sstead see above ☝️

**Comment by enricostano** [comment] 2017-12-19 05:48
@sstead @daniellemoorhead  can we close this?

**Comment by mkllnk** [comment] 2017-12-20 04:44
I vote for closing this until this has been reproduced by another person or by Sally with another browser.

**Comment by myriamboure** [comment] 2017-12-20 05:15
I tried to reproduce it as well on our staging and couldn't... but this is definitely strange... hope it's not someone trying to hack us ;)

**Comment by sauloperez** [comment] 2017-12-20 05:19
Let's close it then

**Closed** 2017-12-20 05:34 UTC
