### ISSUE TITLE
'When would you like your order' cropped in mobile view

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1296] opened 2016-12-07 01:55 UTC
Devices: Mobile/tablet
Where: Shopfront

![image](https://cloud.githubusercontent.com/assets/10843056/20951792/14574538-bc7c-11e6-9337-377f3dab7d75.png)

**Comment by myriamboure** [comment] 2018-03-29 11:07
Not a bug as "mobile ready" not yet a feature we really offer, too many things bugging on mobile. So captured in icebox https://community.openfoodnetwork.org/t/customers-easily-go-through-the-whole-placing-order-process-on-mobile/1244 and new feature "mobile ready" started to be worked on, so closing for now.

**Closed by myriamboure** 2018-03-29 11:07 UTC
