### ISSUE TITLE
Simple producer profile - user is redirected to the list of shops 

### ISSUE THREAD

**Issue by EartlingIB** [openfoodfoundation/openfoodnetwork#6140] opened 2020-10-06 09:13 UTC
## Description
I have checked this on ES and FR instances.
I create a new producer profile, and I select Simple (for producer who doesn't want to have a shop).
I go to the admin panel, and I click on the button Votre Profile en ligne (see attached). This button leads me to the list of shops. My new profile doesn't appear in this list - because it is not a shop, only a producer simple profile. This means that i am unable to verify that my profile has been created successfully.

## Expected Behavior

After clicking on the 'Votre profil en ligne' button (see attached) the user should be redirected to the list of producers (not the list of shops)

## Actual Behaviour
After clicking on Votre Profil en ligne button, user is redirected to the list of shops, where his profile is not visible 

## Steps to Reproduce

1. Log in and go to the admin area of your account
2.Click on 'change package'
3.Select 'Simple profile' (FR) or 'Producer Profile' (EN), then click on Change Now
4.Click on 'See OFN4 live' (OFN4 is my profile name)
5. the next page that shows is this https://staging.coopcircuits.fr/shops#/?show_closed=1 which is a shop list, and my profile doesn't show in there. 

## Animated Gif/Screenshot
![Screenshot 2020-10-06 at 11.05.41.png](https://images.zenhubusercontent.com/5f589eccea2def38d941e38a/0e655714-9126-4ce5-b7ba-2c4a0efd747b)

## Workaround
The user can find a link for list of Producers in the footer 

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:3.2.8
* Browser name and version:Firefox 81.0.1
* Operating System and version (desktop or mobile): Desktop, Mac, Catalina 10.15.6

**Comment by zuccamia** [comment] 2020-10-14 23:18
I'd like to help with this. Could you assign this to me if no one else is taking it?

**Comment by sigmundpetersen** [comment] 2020-10-15 06:44
Yes of course, thank you @zuccamia 🎉 
Please have a look at [getting started](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md) and [contributing](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md) pages if you haven't 👍

**Comment by zuccamia** [comment] 2020-10-16 13:16
Thank you for the pointers to the 2 pages @sigmundpetersen! I am going through the code and will ask you if I have any questions.

**Comment by zuccamia** [comment] 2020-10-18 09:38
Hi @sigmundpetersen, I am trying to set up the Docker package but keep coming into these errors when running `$ docker/build`
`Step 14/15 : COPY . /usr/src/app/
 ---> Using cache
 ---> c7a1ffc0b93f
Step 15/15 : RUN bundle install --jobs="$(nproc)"
 ---> Running in 693297ed2b08
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
You must use Bundler 2 or greater with this lockfile.
Service 'web' failed to build : The command '/bin/sh -c bundle install --jobs="$(nproc)"' returned a non-zero code: 20
##############################
FINISHED: docker-compose build
##############################`
Could you please advise me on how to work around this?

**Comment by RachL** [comment] 2020-10-19 07:30
Hello @zuccamia ! Can you join our #dev channel [on Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) ? There you will find more people able to help you out :-)

**Comment by zuccamia** [comment] 2020-10-20 00:27
I'm in. Thanks @RachL!

**Comment by RachL** [comment] 2020-11-11 09:50
hello @zuccamia how are you doing? Are you still planning to work on this?

**Comment by zuccamia** [comment] 2020-11-12 01:50
Hi @RachL , yes I am still working on it. I am sorry it has been slow on my end; I was struggling to set up the my local environment and with my other full-time commitments. I would like to continue working on this until the end of this month, as long as it does not impede others' progress. Please do go ahead and reassign if another developer can help you faster.

**Comment by RachL** [comment] 2020-11-12 17:54
hi @zuccamia no worries at all! Take all the time you need! If you want to open issues also with the problems you had setting up your local env don't hesitate: we should fix them.
In general feel free to ask us for anything you might need :+1:

**Comment by zuccamia** [comment] 2020-11-17 15:12
Thanks so much @RachL ! I almost got the docker build successful before running into an insufficient storage problem which is a local problem that I am currently resolving on my end.

**Comment by RachL** [comment] 2021-01-06 17:01
Hello @zuccamia I'm just checkin' in: have you managed to fix your docker setup? Don't hesitate if you need help :)

**Comment by sinansonmez** [comment] 2021-09-04 21:15
Hello. 

I would like to help on this issue. 

I am trying to reproduce the issue but unfortunately I couldn't. 
When I logged in with default user ( 'ofn@example.com' with the password 'ofn123'), I didn't see "change package" button. Can anyone support me on this?

**Comment by RachL** [comment] 2021-09-06 07:47
hello @sinansonmez I'm not super familiar with the test dataset, but it might be that the user you are trying to login with is a superadmin. The "change package" button does not appear for super admins on the dashboard.

However you should be able to reach it through the enterprises menu, like this:

https://guide.openfoodnetwork.org/basic-features/enterprise-profile/package-types#changing-your-profile-type

let me know if that helps.

**Comment by sinansonmez** [comment] 2021-09-06 18:58
Thanks @RachL. 

I was able to track down where to do the change. The issue is related"single_enterprise_dashboard", since I am entering as a super admin, I couldn't reproduce the exact issue. to be 100% sure, I wanted to makes sure that, I reproduce and test the changes. Unfortunately, I have two problems
- I created new user but I couldn't activate it, because in development environment no activation e-mail is sent. I also tried to manually activate the user but I couldn't. 
- The other is I have is related to development environment. I installed docker. I can start running the server, I can actually open the website etc. Everything is working as expected. However, when I try to run tests I get error `Your Ruby version is 2.6.6, but your Gemfile specified 2.7.3`

Any idea how to solve these problems

**Comment by RachL** [comment] 2021-09-07 07:53
ping @openfoodfoundation/core-devs can anybody help @sinansonmez ☝️

**Comment by andrewpbrett** [comment] 2021-09-07 18:13
Hi @sinansonmez - it looks like you figured out the second part, but on the first one, did you try doing: 

```
u = Spree::User.create(email: "foo@email.com", password: "password"
)
u.confirmed_at = Time.now
u.save
```

That seems to work for me. Also the #dev channel on the OFN Slack is good for more real-time help, we might not always see Github issue comments right away - thanks @RachL :)

**Comment by sinansonmez** [comment] 2021-09-08 19:23
Thanks @andrewpbrett for the support. I was able to recreate the issue and created a pull request

**Comment by andrewpbrett** [comment] 2021-09-08 19:29
Great, thank you! I've moved it into the code review column, someone should be able to look soon.

**Closed** 2021-09-15 16:22 UTC
Labels: good first issue, bug-s4, hacktoberfest
