### ISSUE TITLE
Impossible order due to order shipping method

### ISSUE THREAD

**Issue by Cecilia-Hn** [openfoodfoundation/openfoodnetwork#8219] opened 2021-09-21 16:42 UTC
A client try to order on an OFN shop (2236), when he arrived at the validation, the order is not finalised because of shipping method error : 

<img width="1416" alt="Capture d’écran 2021-09-21 à 18 39 39" src="https://user-images.githubusercontent.com/67476305/134211857-ae95a059-030d-4b82-a1d2-c7a3d4a28e13.png">

<img width="718" alt="Capture d’écran 2021-09-21 à 18 39 44" src="https://user-images.githubusercontent.com/67476305/134211870-c286ddb8-10be-4145-aecc-bcf202ab0feb.png">

**Comment by Cecilia-Hn** [comment] 2021-09-21 16:49
We've got exactly the same behaviour for shop 1265 

- The client go te the shop
- Select products
- Go to checkout 
- Place order and the following message appeared
<img width="1124" alt="Capture d’écran 2021-09-21 à 18 48 51" src="https://user-images.githubusercontent.com/67476305/134213243-1b00eef0-ea55-45bc-8d23-968da006d61f.png">

**Comment by filipefurtad0** [comment] 2021-09-21 16:52
This might be occurring because those hubs have all shipping methods set to `backoffice only`, as an example:
![image](https://user-images.githubusercontent.com/49817236/134213128-b68cc5c7-ba31-400e-b2df-622200492671.png)

The workaround could be to visit `/admin/shipping_methods/<shipping_method_id>/edit`and set at least one shipping method as : 
![image](https://user-images.githubusercontent.com/49817236/134213423-f00a69e5-8f2e-4ecf-a5e2-4ab4d158d230.png)

Another reason could be tags are being used and those customers don's `see` any options in the UI and click checkout.

It seems related to https://github.com/openfoodfoundation/openfoodnetwork/issues/6137

**Bugsnag**
https://app.bugsnag.com/open-food-france/coopcircuits/errors/61422936acb0e600075e8cf5?event_id=614a09750080d77bf5150000&i=sk&m=fq

If confirmed I think we can then downgrade to S2.

**Comment by filipefurtad0** [comment] 2021-09-21 16:58
This is confirmed in staging:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/614a0e96f3fa8e0008cd2936?event_id=614a0e960080dd9956940000&i=sk&m=nw

The workaround of hubs setting **at least one visible shipping method** should work, downgrading to s2.

**Comment by Cecilia-Hn** [comment] 2021-09-21 17:02
Thanks a lot @filipefurtad0, this is it, I panicked !

**Comment by filipefurtad0** [comment] 2021-09-21 17:09
Thank you for reporting! :pray:

**Comment by filipefurtad0** [comment] 2021-09-22 19:42
It seems that if the customer tries to checkout, on a hub with `shipping methods set to backoffice` only and uses `Stripe as a payment method`:

- that user will see the snail / error 500
- the payment goes through -> seen on Stripe Dashboard as `authorized` and `captured` (!)
- if the user then navigates back (using the back button of the browser) a new payment for that order can be submitted
- again, it appears in Stripe as completed
- the order remains in state `payment`

![image](https://user-images.githubusercontent.com/49817236/134409939-28954d41-ad6a-4e07-8f49-c99ee09c698b.png)

This pic is taken from staging-UK. But it could explain issue #8218, and that order with 13 payments... What do you think?

**Comment by lin-d-hop** [comment] 2021-09-27 08:13
Note that this can also happen when shipping methods are set to have specific shipping categories and items in the order do not align with the categories (eg a shipping method that does not accept refrigerated produce but the order contains refrigerated items.)

Just posting in case someone searches for this in the future.

**Comment by filipefurtad0** [comment] 2021-09-27 10:31
I've investigated this a bit further: So far I see three potential scenarios in which shipping methods can be hidden from checkout. I had another look to see how each scenario is impacted by different payment methods:

1) non-matching shipping categories

> when shipping methods are set to have specific shipping categories and items in the order do not align with the categories

I've tried to reproduce that scenario @lin-d-hop , but could not hide shipping methods from the checkout screen in this way. Is this expected? If so I can open an issue on it. Checkout proceeded as usual despite non-matching categories between products and shipping methods. Maybe I'm missing something here...

2) setting as backoffice only (as mentioned [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/8219#issuecomment-924171902))

With **both** Stripe and Paypal, the payments seem go through, but the user sees an error. We can see the successful payments on the respective dashboards (below Paypal):

![image](https://user-images.githubusercontent.com/49817236/134890121-555b1c13-7438-4eaf-b3a6-d77fcad6ceea.png)

Paypal however, prevents adding additional payments to orders, it displays this warning:

![image](https://user-images.githubusercontent.com/49817236/134889883-a7d6d963-6bc3-47a5-b7d3-0512face008e.png)

Stripe seems to allow adding more payments (dashboard below); The type of card used with Stripe seems to make a difference on whether the payment is captured or not:

card x-3184 -> generates a captured payment
card x-3155 -> generates an uncaptured payment

This is seen here:

![image](https://user-images.githubusercontent.com/49817236/134889088-18cc6d3f-8566-401f-9853-0c1770d892f4.png)

3) hiding shipping methods with tags

`pick up` shipping method seems to be assigned by default - although not displayed to the user - and checkout proceeds with all payment methods: the user gets redirected to the order confirmation screen, no error is displayed. Random assignment of shipping methods seems to be reported in [this issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/6029) -

**Comment by filipefurtad0** [comment] 2021-09-27 17:30
I think we just had another occurrence here: https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1632759072058900 (checkout with cash).

**Comment by filipefurtad0** [comment] 2021-09-29 14:42
Additional data, from the feedback from CA [here](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1632923763105700?thread_ts=1631824275.068900&cid=CG7NJ966B):

Different card types generate slightly different outcomes (card x-3184, card x-3155 described above):

- x-4242 - valid `no 3D-auth required` -> checkout fails for the customer, payments go through `on Stripe and OFN`:

![image](https://user-images.githubusercontent.com/49817236/135290071-7360f48e-37a6-46d2-ba9c-64dc65cf2f4a.png)

**Comment by filipefurtad0** [comment] 2022-08-31 15:49
Closed in favor of #9614.

**Closed by filipefurtad0** 2022-08-31 15:49 UTC
Labels: bug-s3
