### ISSUE TITLE
[Flaky] spec/system/consumer/shopping/shopping_spec.rb

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#8830] opened 2022-02-03 04:47 UTC
### What we should change and why (this is tech debt)

```
rspec ./spec/system/consumer/shopping/shopping_spec.rb:481

  1) As a consumer I want to shop with a distributor Viewing a distributor adding and removing products from cart when a variant is soft-deleted adding the soft-deleted variant to the cart handles it as if the variant has gone out of stock
     Failure/Error: expect(page).to have_selector selector
       expected to find css "#variant-644" but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_a_consumer_i_want_to_shop_with_a_distributor_viewing_a_distributor_adding_and_removing_products_from_cart_when_a_variant_is_soft_deleted_adding_the_soft_deleted_variant_to_the_88.png

     
     # ./spec/support/request/shop_workflow.rb:89:in `within_variant'
     # ./spec/support/request/shop_workflow.rb:52:in `click_add_to_cart'
     # ./spec/system/consumer/shopping/shopping_spec.rb:484:in `block (6 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:38:in `block (2 levels) in <top (required)>'
```

### Context

https://github.com/mkllnk/openfoodnetwork/runs/5046907286?check_suite_focus=true
https://github.com/openfoodfoundation/openfoodnetwork/runs/5090479493

Previous issues:

- #7677
- #7669

**Comment by RachL** [comment] 2022-02-22 08:14
Delivery circle meting today: we close it for now as we can't reproduce it.

**Closed by RachL** 2022-02-22 08:14 UTC
Labels: tech debt
