### ISSUE TITLE
Missing translation key en.admin.price (p.)

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5967] opened 2020-08-28 15:20 UTC
## Description

In path '/admin/orders/bulk_management'

## Expected Behavior

In Price field some mistake

## Actual Behaviour

Should display Price

## Steps to Reproduce

1. go to /admin/orders/bulk_management
2. Columns -> Price
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/91584289-14e3f180-e95b-11ea-82fe-c8ba58aa0540.png)

## Your Environment

* Version used: 3.2.4
* Browser name and version: Firefox 78.1.0esr (linux)
* Operating System and version (desktop or mobile): Desktop

**Comment by arku** [comment] 2020-09-08 02:02
This is a duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/5853 and the issue has been fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/5892.

@sauloperez Can we close this?

**Comment by sauloperez** [comment] 2020-09-08 08:47
oh, thanks!

**Closed by sauloperez** 2020-09-08 08:47 UTC
Labels: bug-s3, good first issue
