### ISSUE TITLE
Release v4.4.1 - Tomato Scrambled Eggs

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#11143] opened 2023-06-29 22:36 UTC
## Preparation on Thursday

- [x] Merge pull requests in the [Ready To Go] column
- [x] Include translations: `tx pull --force`
- [x] [Draft new release]. Look at previous [releases] for inspiration.
- [x] Notify [#instance-managers] of user-facing changes.

## Testing

- [x] [Find build] of the release commit and copy it below.
- [x] Move this issue to Test Ready.
- [x] Notify `@testers` in [#testing].
- [x] Test build: ~~https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/4575~~ https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/4576

## Finish on Tuesday

- [x] Publish and notify [#global-community] (this is automatically posted with a plugin)
- [x] Deploy the new release to all managed instances.
  <details><summary>Command line instructions</summary>
  <pre>
  cd ofn-install
  git pull
  ansible-playbook --limit all-prod --extra-vars "git_version=vx.y.z" playbooks/deploy.yml
  </pre>
  </details>
- [ ] Notify [#instance-managers]:
  > @instance_managers The new release has been deployed.
- [ ] Nudge next release manager

The full process is described at https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing.

[Ready To Go]: #zenhub
[Transifex pull request]: https://github.com/openfoodfoundation/openfoodnetwork/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+head%3Atransifex
[Draft new release]: https://github.com/openfoodfoundation/openfoodnetwork/releases/new?tag=v&title=v+Code+Name&body=Congrats%0A%0ADescription%0A%0A%23%23+User+facing+changes+:eyes:%0A%0A%0A%23%23%23+Experimental+features+for+testing+:sunglasses:%0A%0A%0A%23%23+Technical+changes+:wrench:%0A%0A
[releases]: https://github.com/openfoodfoundation/openfoodnetwork/releases
[#instance-managers]: https://app.slack.com/client/T02G54U79/CG7NJ966B
[#testing]: https://openfoodnetwork.slack.com/app_redirect?channel=C02TZ6X00
[Find build]: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master
[#global-community]: https://app.slack.com/client/T02G54U79/C59ADD8F2

**Comment by filipefurtad0** [comment] 2023-06-30 11:33
Ok, the release looks good to go - found no issues.

Browsing through bugsnag, I did found this error - not triggered during release testing, so I'm not sure if relevant:

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/649da007fc68d5000829f088?filters[event.since]=30d&filters[error.status]=new&filters[app.release_stage]=staging&pivot_tab=event

It seems to relate to the code changed on

**Comment by mkllnk** [comment] 2023-07-03 00:43
That bug was not introduced by #11109. The new invoice code contains a bug. To reproduce:

* You need a distributor with logo.
* The distributor needs to activate displaying the logo on invoices.
* You need to activate the new invoices.
* The instance needs to have the alternative invoice template activated.

I created a new issue:

* #11149

**Comment by jibees** [comment] 2023-07-04 20:08
I could not handle deployment on hu-prod.

**Comment by jibees** [comment] 2023-07-07 15:08
Closing here, since we started a new release cycle.

**Closed by jibees** 2023-07-07 15:08 UTC
