### ISSUE TITLE
Reports resulting in an error page - Delivery & Payment Methods Reports for users with multiple enterprises

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#3365] opened 2019-01-21 09:42 UTC
## Description

Particluar reports and particular users are finding that reports are resulting in an error page. Reported by Oliver at Stroudco and we suspect it is something to do with the amount of data being processed.

- Delivery Report
- Payments Method Report

UK team discussed and are logging here as part of  speed improvement work?

## Expected Behavior

Using an account with few enterprises, the reports come up as expected and download as expected.

## Actual Behavior

For accounts with larger amounts of data associated with them are unable to load the page at all and it results in a error page - Oliver for instance and Stroudco having a lot of data - 

## Steps to Reproduce

1.  User with a multiple enterprises
2. Go to reports
3. Download Delivery or Payment Methods report
4.

## Animated Gif/Screenshot

http://recordit.co/YGdm17ebjJ

## Context

Using the reports - Oliver is able to use customer addresses report as a workaround

## Your Environment

* Version used:
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): W 10

## Possible Fix

Data processing

**Comment by sineadfenton** [comment] 2019-01-21 09:42
![](https://github.trello.services/images/mini-trello-icon.png) [Delivery report broken](https://trello.com/c/9Zuxye2T/321-delivery-report-broken)

**Comment by lin-d-hop** [comment] 2019-06-06 12:27
Closing. This is a duplicate of #3834

**Closed by lin-d-hop** 2019-06-06 12:27 UTC
Labels: bug-s5
