### ISSUE TITLE
Missing favicon in production

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#5922] opened 2020-08-19 00:13 UTC
## Description

![Screenshot from 2020-08-19 09-50-09](https://user-images.githubusercontent.com/3524483/90576389-712f6e80-e201-11ea-9c3b-d9a95f9b45e1.png)

Most websites show an icon in the browser tab. The OFN used to do that as well but it disappeared in production. The screenshot above shows an icon of a staging server on the left and a tab without icon on the right.

## Expected Behavior

A browser icon (favicon) should always be present. The HTML should refer to `/favicon.ico`.

## Actual Behaviour

The icon is only shown on staging. The code differs for staging so that testers can easily distinguish between staging and production. The production code points to `/images/favicon.ico` which doesn't exist. Staging points to `/favicon-staging.ico`.

## Steps to Reproduce

1. Visit any production server.

### For developers

1. Precompile assets in production environment: `RAILS_ENV=production bundle exec rake assets:precompile`
2. Start the server: `RAILS_ENV=production bundle exec rails server`
3. Open the home page in a private window.

## Animated Gif/Screenshot

See above.

## Severity

bug-s4: it's annoying, but you can use it

I guess that this is a v3 regression and a papercut and a good first issue.

## Your Environment

* Version used: v3.2.3

## Possible Fix

I propose to simplify the code so that staging and production are showing the same icon. That will enable us to test this issue on staging. It also enable testers to notice a problem like this before a regression is deployed to production.

**Comment by luisramos0** [comment] 2020-08-19 00:31
Hey Maikel, this is duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/5700 right?

**Comment by Matt-Yorkley** [comment] 2020-08-19 08:00
> this is duplicate of #5700 right?

Yep. Fixed by #5904 (in code review).

**Closed by Matt-Yorkley** 2020-08-19 08:00 UTC
Labels: bug-s4, good first issue, v3-regression

**Comment by mkllnk** [comment] 2020-08-20 06:58
Yes, I searched for `favicon` on Github but it doesn't find `fav icon` used in that issue.
