### ISSUE TITLE
Uber dropdown remembers close

### ISSUE THREAD

**Issue by daniellemoorhead** [openfoodfoundation/openfoodnetwork#880] opened 2016-04-06 04:18 UTC

**Comment by bingxie** [comment] 2016-04-06 05:21
So the implementation will be: if the user clicks the close, we will use cookie to remember it.

**Comment by myriamboure** [comment] 2018-07-13 09:57
We have not specified the need for now, a,and it doesn't seem like users are complaining about it, so I'm closing that issue for now. It is not a bug anyway so if it is a UX improvement should go through other process.

**Closed by myriamboure** 2018-07-13 09:57 UTC
Labels: bug
