### ISSUE TITLE
BE and FR product images missing

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5841] opened 2020-07-29 15:48 UTC
## Description

Product images seems missing from BE . Example : https://openfoodnetwork.be/symbiooz-la-terre-nous/shop

I've searched bitwarden to get the info to the AWS account but didn't find any. Are BE images even on AWS?

## Steps to Reproduce

Check BE instance.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.2
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

**Comment by SophieDuponcheel** [comment] 2020-07-30 10:34
as manager of OFN Be, is there anything I can do? (with my skills at zero for IT stuff ;))

**Comment by luisramos0** [comment] 2020-07-30 11:28
BE images are on AWS S3, can someone get the BE AWS credentials on bitwarden?

**Comment by RachL** [comment] 2020-07-30 12:07
@SophieDuponcheel do you have the AWS BE credential?

**Comment by RachL** [comment] 2020-07-30 12:07
I'm closing this one as product images are back but there is still problems with _some_ enterprise images. I will document this on #5844

**Comment by luisramos0** [comment] 2020-07-30 12:24
ok, but let me re-open this one so that I have a placeholder to fix the quickfix I used.

Basically, the s3_images_bucket config entry is not coming through to application.yml. It must be a problem somewhere between ofn-install and the initializers on ofn. My quick fix was to add the entry manually to the application.yml file on the server :see_no_evil:

**Comment by luisramos0** [comment] 2020-07-30 15:02
I have managed to get the s3_images_bucket config to staging FR now.
This is a problem with WHAT secrets file is used when we deploy from our computers with what commands (some commands dont have the secrets file to use explicitly).

I am no longer sure what is the order of priority of the secrets files used, could be github's secrets, my local secrets, the secrets file in the ofn-install project...

Maybe I just messed up my local ofn-install config with export FETCH_OFN_SECRETS="TRUE" in my profile.

I think @Matt-Yorkley if the best dev to clarify this.

**Comment by SophieDuponcheel** [comment] 2020-07-31 07:50
> 
> 
> @SophieDuponcheel do you have the AWS BE credentials? Can you send them to me by PM?

Hey Rachel, I'm sorry for the delay in answering, I was in a meeting all afternoon yesterday. But I wouldn't have been much help, because I have no idea what AWS credentials is. Sorry for that and thank you for what you have done.

**Comment by RachL** [comment] 2020-07-31 08:19
@SophieDuponcheel AWS is a server provider where your images are. Someone must be paying for this server currently. Can you find out who? Then this person must have the credential to login the server as well 👍

**Comment by SophieDuponcheel** [comment] 2020-07-31 11:26
@RachL 

Ok, I'm gonna make an inquiry. I'll keep you in touch.

**Comment by Matt-Yorkley** [comment] 2020-08-06 13:36
Ok @luisramos0 , I'm catching up here. So to recap: 

- S3 image settings were broken on FR and BE (after provisioning I'm assuming?) for a while
- It's now been manually fixed on those two servers and is mostly fine?
- A small number of images that were uploaded during the time it was broken are still missing (as expected, because they're not actually in S3)

And the cause was some of the configs from secrets not being applied properly during provisioning?

> Basically, the s3_images_bucket config entry is not coming through to application.yml. It must be a problem somewhere between ofn-install and the initializers on ofn. My quick fix was to add the entry manually to the application.yml file on the server

**Comment by Matt-Yorkley** [comment] 2020-08-06 13:56
> This is a problem with WHAT secrets file is used when we deploy from our computers with what commands (some commands dont have the secrets file to use explicitly).

> I am no longer sure what is the order of priority of the secrets files used, could be github's secrets, my local secrets, the secrets file in the ofn-install project...

> Maybe I just messed up my local ofn-install config with export FETCH_OFN_SECRETS="TRUE" in my profile.

When you use the `provision` playbook does it run the `fetch_secrets` tasks at the beginning?

**Comment by Matt-Yorkley** [comment] 2020-08-14 18:12
I've tried provisioning `be-prod` and checking the configs written to `application.yml`, and the secrets were all correct. Images are working.

**Comment by luisramos0** [comment] 2020-08-16 16:12
Hello Matt,

I have just read the fetch_secrets task and now I see it fetches secrets from github. It is irrelevant what I have on my local ofn-secrets project. I think that's what I mixed up.
The secrets used are the ones on the local ofn-install project and these are overriden if the fetch secrets task is executed :+1: 

I see the secrets were updated on the first v3 rollout: https://github.com/openfoodfoundation/ofn-secrets/pull/40

I am now convinced this was caused by the state of my local secret files where I thought the secrets in ofn-secrets was being used but there was an outdated secrets file on ofn-install
I am closing this issue now.

**Closed by luisramos0** 2020-08-16 16:12 UTC
Labels: bug-s2, feedback-needed
