### ISSUE TITLE
Paypal Checkout error 400

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#8364] opened 2021-10-15 12:45 UTC
## Description

To be investigated:

There is a log for an error in FR which seems to relate to checkout, Bugsnag:

```
PayPal::SDK::Core::Exceptions::BadRequestspree/paypal#express
Failed. Response code = 400. Response message = Bad Request
```

https://app.bugsnag.com/open-food-france/coopcircuits/errors/6169742bfc29c10008bb11ea?event_id=6169742b008585d8d1890000&i=sk&m=nw

## Expected Behavior

?

## Actual Behaviour

?

## Steps to Reproduce

?

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by RachL** [comment] 2022-01-20 15:28
@filipefurtad0 I'm closing this one as we can't reproduce it for now.

**Closed by RachL** 2022-01-20 15:28 UTC
