### ISSUE TITLE
[Subscriptions] If I have more than one OC planned with a same schedule, incoming orders shows wrong Order Cycle name

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#2877] opened 2018-10-16 20:03 UTC
## Description

If I have more than one OC planned with a same schedule, incoming orders for the second, third, etc OC shows in the Order Cycle column "Close date not set" instead of the OC name.

## Expected Behavior

Hub manager can check the recurring orders planned for the next OC easily.

## Actual Behavior

She can't as she can't see the name of the next OC concerned.

## Steps to Reproduce

1. Create three OC with the same schedule, starting one after the precedent is ending.
2. Make sure you have a subscription setup for products in those OC with this schedule.
3. Check subs page to see the "orders" to come for your customer https://www.openfoodfrance.org/admin/subscriptions

## Animated Gif/Screenshot

![capture du 2018-10-16 21-57-22](https://user-images.githubusercontent.com/8135376/47043895-19e88f00-d18f-11e8-8f6b-198b79124afb.png)

"Date de fin non renseignée" in french means "Close date not set".

## Context

Reviewing the remaining things to be done to consider standing order v1 as done.

## Severity
S3, but not so relevant here as included in standing order project anyway

## Possible fix
It might be that this is connected to the fact that the subscription for that customer has no end date? Can it be?

**Comment by kristinalim** [comment] 2018-12-27 01:36
Estimated time: 1 hour

**Comment by luisramos0** [comment] 2019-07-16 12:19
the date text "Date de fin non renseignée" is correct.
what seems to be missing is the OC name above it.

I cant replicate this.
![Screenshot 2019-07-16 at 12 33 54](https://user-images.githubusercontent.com/1640378/61291309-1b9abe00-a7c6-11e9-8c6e-6206e0ffba12.png)
![Screenshot 2019-07-16 at 12 33 42](https://user-images.githubusercontent.com/1640378/61291310-1b9abe00-a7c6-11e9-954c-93a37a9d23fb.png)

then I remove the close date of the OCs and see this:
![Screenshot 2019-07-16 at 13 18 58](https://user-images.githubusercontent.com/1640378/61293763-5273d280-a7cc-11e9-9eca-90af05697623.png)

**Comment by luisramos0** [comment] 2019-07-16 12:20
@kristinalim did you manage to replicate this one?

**Comment by RachL** [comment] 2019-07-18 16:22
@luisramos0 when I tried to replicate I saw the issue we have in https://github.com/openfoodfoundation/openfoodnetwork/issues/3544  with Firefox:

![image](https://user-images.githubusercontent.com/6525576/61474173-4fbddc80-a988-11e9-9dae-a77d4c07edf0.png)

Because with Chromium, no problem:

![image](https://user-images.githubusercontent.com/6525576/61474265-8f84c400-a988-11e9-881d-3798d657a98a.png)

So I think we can close this one. @myriamboure or @kristinalim please reopen if you manage to reproduce it in v2

**Closed by RachL** 2019-07-18 16:22 UTC
