### ISSUE TITLE
Shoppers think they have submitted an order - but haven't

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1465] opened 2017-02-22 17:53 UTC
When shoppers click on 'Next' during the checkout they bounce down to the bottom of the page past Payment Methods and the Place Order button and shoppers think they have submitted the order but they haven't. 

Both Tamar @sararock and Stroudco @OliverUK have had regular customers complaining about this.

![screenshot 2017-02-22 17 48 27](https://cloud.githubusercontent.com/assets/10517702/23224680/3572e8a2-f927-11e6-8dce-a3817d45e801.png)

**Comment by lin-d-hop** [comment] 2017-02-22 17:58
@stveep or @Matt-Yorkley if either of you find some time to look into this it would be great to find a solution. Turns out this has been popping up repeatedly and customers, expecting their order was placed, are getting annoyed :-/

**Comment by Matt-Yorkley** [comment] 2017-02-24 00:12
@lin-d-hop I've played around with this as much as I can but I can't quite fix it.

**Comment by lin-d-hop** [comment] 2017-02-24 08:49
Ut oh... maybe you could share some of your thoughts and logic and we could see if other brains have anything to add?

**Comment by Matt-Yorkley** [comment] 2017-02-24 09:56
So the main files to look at are: 
**`app/assets/javascripts/darkswarm/controllers/checkout/accordion_controller.js.coffee`** 
`app/assets/javascripts/darkswarm/mixins/fieldset_mixin.js.coffee` 

and to a lesser extent the views and controllers under:
`app/views/checkout/`
`app/assets/javascripts/darkswarm/controllers/checkout/`

It comes down to the way the accordion tabs' content shifts the other page content around when they open/close, and is dependant on how much content is in each tab, which is relative to the number of shipping/payment methods an enterprise has. It's slightly tricky to replicate the issue, and resolving it is really fiddly. I spent ages playing around with a number of different ideas, including re-using the angular `scrollTo` library functions to get the page to move to the top of the next tab when closing the previous one, but couldn't quite get it to work satisfactorily.

**Comment by lin-d-hop** [comment] 2017-07-27 11:18
@Matt-Yorkley Might you have the opportunity to stick your head into this again. Perhaps in the past months your new skills might give you a new take?

**Comment by sineadfenton** [comment] 2017-07-27 11:21
Ah hadn't seen this has been logged before (different terminology).

This was brought up again recently and it would be good to get it seen too

#1702

**Comment by sineadfenton** [comment] 2017-07-27 12:01
![](https://github.trello.services/images/mini-trello-icon.png) [Checkout Page Jumps to the Bottom](https://trello.com/c/FfnczmVi/60-checkout-page-jumps-to-the-bottom)

**Comment by daniellemoorhead** [comment] 2017-08-11 04:54
@sineadfenton would suggest closing #1702 if it's a duplicate of this.

**Comment by daniellemoorhead** [comment] 2017-08-11 04:54
@enricostano @sauloperez any insights on this for @Matt-Yorkley given how in depth you've gone into the code these past few months? @mkllnk how about you?

**Comment by sineadfenton** [comment] 2017-08-12 08:39
![](https://github.trello.services/images/mini-trello-icon.png) [Checkout Page Jumps to the Bottom](https://trello.com/c/FfnczmVi/60-checkout-page-jumps-to-the-bottom)

**Comment by Matt-Yorkley** [comment] 2017-08-13 18:41
I'm pretty sure this is a duplicate of the issue @stveep just fixed with #1747.

**Closed by Matt-Yorkley** 2017-08-13 18:41 UTC
Labels: p - critical, uk, ux
