### ISSUE TITLE
Remove `new_products_page` feature and its associated page, components, ... 

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/openfoodnetwork#11153] opened 2023-07-04 07:46 UTC
### What we should change and why (this is tech debt)
We now use `admin_style_v3`

### Context
This came up in PR https://github.com/openfoodfoundation/openfoodnetwork/pull/11007#discussion_r1251547475

**Comment by sigmundpetersen** [comment] 2024-05-24 08:19
@RachL @dacook is this still relevant?
Shall we close, or add to BUU2?

**Comment by RachL** [comment] 2024-05-24 09:00
I thought we did remove it but indeed I can't find the related PR, so I guess it's still relevant? Maybe David knows more.

**Comment by dacook** [comment] 2024-05-26 23:32
Yep, all done long ago:
- duplicate of https://github.com/openfoodfoundation/openfoodnetwork/issues/11273

**Closed by dacook** 2024-05-26 23:32 UTC
Labels: tech debt
