### ISSUE TITLE
Restyle Order Cycle element

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#2711] opened 2018-09-13 11:27 UTC
mobile  https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5ba1bcdb364ae5a211c2d0a2
![image](https://user-images.githubusercontent.com/2911176/46519319-2af5ee00-c8bb-11e8-9570-da8c92752547.png)

tablet https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5b957e21e9050a63b3781ce6
![image](https://user-images.githubusercontent.com/2911176/46519332-3a753700-c8bb-11e8-9965-b57b23e29240.png)

desktop https://app.zeplin.io/project/59532764a6c78ff3c534b372/screen/5b957e215c445b2453b6be94
![image](https://user-images.githubusercontent.com/2911176/46519347-43fe9f00-c8bb-11e8-872f-d9235ed30198.png)

**Comment by daniellemoorhead** [comment] 2019-12-13 05:57
Duplicate of #4574

**Closed by daniellemoorhead** 2019-12-13 05:57 UTC
Labels: Hacktoberfest, socialissues.tech
