### ISSUE TITLE
Can't set product stock level

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#1182] opened 2016-10-08 16:37 UTC
When user tried to set stock level to 5 the level reset to infinity after update.  Because this was a live shopfront and the user needed a quick solution I have since deleted this product and replicated a similar one to replace it so am sorry we can't go back to their shopfront to see the problem, but here are the screenshots
![screenshot 2016-10-08 17 06 22](https://cloud.githubusercontent.com/assets/10517702/19214514/d2b74786-8d7d-11e6-93b1-eef50f1285f5.png)
![screenshot 2016-10-08 17 06 28](https://cloud.githubusercontent.com/assets/10517702/19214515/d2be2038-8d7d-11e6-8739-a394e46ea09e.png)
![screenshot 2016-10-08 17 06 33](https://cloud.githubusercontent.com/assets/10517702/19214516/d2bf2ea6-8d7d-11e6-92e9-2d3748f937e1.png)
![screenshot 2016-10-08 17 06 22](https://cloud.githubusercontent.com/assets/10517702/19214533/13a10336-8d7e-11e6-9b29-6634e77c0fd6.png)

**Comment by lin-d-hop** [comment] 2016-11-05 14:01
Another user has reported this issue. This needs investigation.

**Comment by NickWeir63** [comment] 2016-11-06 10:20
It would be god to get more detail from this latest user reporting this problem because I deleted the product that caused me to report this issue in the first place.  Did they try editing stock from the 'bulk edit products' screen?  On reflection and having just done a bit more testing I realise that the first user and I were trying to edit the stock level using the 'Editing Product' screen below instead of in 'Bulk Edit Products'.  Even so - this needs sorting because it seems logical that it should be OK to edit stock levels in this screen.  But in the short term we all need to know that this doesn't work and that stock can only be updated from BEP
![screenshot 2016-11-06 10 12 56](https://cloud.githubusercontent.com/assets/10517702/20036798/56a29878-a40a-11e6-989b-865ade459c43.png)

**Comment by Matt-Yorkley** [comment] 2016-11-21 01:50
Confirmed that when the "TO ORDER" box is checked and a product is saved, the product stock value gets set to "Infinity" regardless of whatever number is entered in the "In stock" box. 

Is this not the expected behaviour?

**Comment by Matt-Yorkley** [comment] 2016-11-21 16:29
I think it's working as intended. It could do with some UI improvement to make it more clear though.

**Comment by lin-d-hop** [comment] 2016-11-23 17:10
Thanks @Matt-Yorkley. I'll write up the issue with more clarity.

**Comment by lin-d-hop** [comment] 2016-11-23 17:24
Closing, now detailed in #1228

**Closed by lin-d-hop** 2016-11-23 17:24 UTC
Labels: uk
