### ISSUE TITLE
Improve admin to simplify group set-up

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#757] opened 2015-12-23 10:22 UTC
@sstead can you work with Serenity to define what these improvements should be?

**Comment by sstead** [comment] 2016-02-04 23:05
Hey @mkllnk, here's problem behind this request....
Currently when a group is set-up one person (OFN or from the group) creates lots of profiles for all the group members. We usually assign all of these to a single user (not the producers' actual email), because we don't want the members getting confirmation emails until we're ready to launch the group. When time comes to 'launch' the group page, we must changes each 'contact' email to the correct email, this has the effect of sending them a confirmation email, and IF they confirm that email, a new user is created, and that user automatically becomes a manager of that enterprise. If each producer doesn't confirmt their email, the change won't take effect and the enterprise remains in the ownership of the original email. 

To make this process smoother, we want a user (non super admin) who owns a group, and has permission to create >1 enterprise, to be able to create many enterprises, assigned to the correct producer email (the contact email field), but we do not want confirmation emails sent to all of these users. Instead, the user will be created and validated in the system automatically. So the enterprise will be owned by the group owner, but managed by the contact email that was put in. Thus, when the time comes to launch, these users will be able to login, without confirming an email. I'm not sure how to deal with the need for a password? You could assign all users the same password, such as password123, or their email address, and we could instruct them to change that?

**Comment by sstead** [comment] 2016-02-04 23:31
Also, I'm not sure how important it is that some form of confirmation occurs. If we skip this step, there is the risk that some enterprises will be registered to emails that are incorrect or don't exist? Worth thinking about.

**Comment by sstead** [comment] 2016-02-05 01:11
There profile set up will change. 
The existing 'contact' field will be reframed to be 'select the email address where all correspondence from the OFN, relating to this enterprise will go' - (incl. email confirmations, receival instructions, etc). This email will no longer display on profiles. This email must be confirmed. When confirmed this email will become a user in the system, and be a manager of that enterprise (this is the current mechanism, no change).

A second email field will be added. This is simply an email to be displayed on the profile, much like the phone number. Has no ties to other OFN functionality. For pre-existing profiles, this field will be populated with the existing 'contact' email.

The page where the group manager creates profiles will change, and they'll be able to put in the correct email for that producer, which will show on the profile from the get go.
![image](https://cloud.githubusercontent.com/assets/10843056/12835019/80d72fd8-cc00-11e5-8d90-4d41f6c9afcb.png). The 'contact' will default to being the owner's email, with no option to over-ride it here. 

There will be a button created. Either a mass button, or a single button on each profile called 'invite this email to become a manager'. This triggers the same process as when you currently change a 'contact'. That person gets an email confirmation. If they confirm it, they will become the 'contact', they will become a user and they will become a manger of that profile.

**Comment by mkllnk** [comment] 2016-02-05 06:03
Ok, and here is the technical plan.

1. Introduce a new field `email_address` which is the public email address to display on the profile. It is optional. Populate it with the old email value.
2. Add the new field `email_address` to the enterprise creation form.
3. Remove the current `email` input from the enterprise creation form and set it to the owner's email address automatically.
4. Change the enterprise edit form. *Contact -> Email* becomes the new public *email_address*. The old internal contact email address will be displayed under *Users -> Notifications*.

Optionally in the future:

* Identify all old email addresses that have no user account associated with them. Reset the email address so that the email address has to be confirmed and a user account is created.
* Wait a reasonable amount of time for people to create user accounts (maybe a few months).
* Change enterprises to have a contact user instead of a notification email address. Link the user associated with the notification email address. If there is no user associated, then link the owner.

**Comment by mkllnk** [comment] 2016-02-23 23:22
Related to this are:
 - #632 Enterprise User: should be able to add a new manager without creating a user first
 - #429 New enterprise creation (from admin) needs red asterisks to signify required fields

They should be solved at the same time.

**Comment by mkllnk** [comment] 2016-02-24 05:43
We should leave #632 for #833, but I merged #429 into the groups branch. It's ready for staging now.

**Comment by sstead** [comment] 2016-02-25 23:42
![image](https://cloud.githubusercontent.com/assets/10843056/13338451/992d6c66-dc75-11e5-9e8d-287f31361751.png)

**Comment by sstead** [comment] 2016-02-26 00:03
Hey @mkllnk , I've just placed an order and didn't receive any email confirmations (not as the customer, or the enterprise). I'm trying to see that emails are getting directed to the correct person.

**Comment by sstead** [comment] 2016-03-02 06:45
Initial testing notes... Sorry maikel, couldn't quite test it to the point of being sure everything is working properly, will finish testing on Friday :)
1) Is new email field populated for pre-existing profiles? Yes I think so.
2) New field to +New Enterprise form. Yes this was the old form... 
![image](https://cloud.githubusercontent.com/assets/10843056/13451779/5e0bdbac-e096-11e5-9a6d-7a6e67ed712b.png)
The new form just says email address, with no warning box about confirmation.
The email typed in here doesn't get a triggered email when the new enterprise is created. It's just for show.
3) Yes, the Notifiactions email is automatically populated with the email of the user who made the enterprise. They receieved an email, but it did not require confirmation, just a welcome email. They were also made owner and manager.
4) Yes, the contact email address can be changed to anything (doesn't need to be a user) and will show instantly on profiles (no confirmation required).

Additionally:
If I as the owner/manager of a group change the 'notifications' email from my own, to someone elses, they will get sent an email confirmation. Until they confirm, this is what you see the below. Until confirmed the initial email will remain, and it will receive confirmations/notifications from OFN.
![image](https://cloud.githubusercontent.com/assets/10843056/13451937/730d846e-e097-11e5-8f0a-338a89498163.png)
Need to confirm that this user becomes manager upon confirmation. 
- Need to check that the /register process populates the profile correctly... For /register... we want the contact field to be the 'display onlyl contact email', and the notification email should get populated with the user's email

Also, The 'user' field seems to be blank for pre-existing groups. Will this impact our existing groups on production? We can just remember to type them in when we push this.

New enterprise group button is still there.

**Comment by mkllnk** [comment] 2016-03-02 10:02
Sally, you are great. If I read your notes correctly, then everything is fine, except:

* The registration still needs testing. That was not in my focus at all. So please check and tell me if it should do something different.

* The new enterprise group button is still there. True, I didn't change it. Who should be able to see it? Only super admin?

**Comment by sstead** [comment] 2016-03-04 00:13
When I put an email into the Notifications box that's different from the enterprise owner/manager
- an email confirmation is sent to the email
upon confirmation of that email....
- If the email is an new non-OFN user, they confirm, set a password and are then made the manager. 
- If the email is a pre-existing OFN user, they are still sent a confirmation, which they need to confirm (do we want this as they have already confirmed?) and when they do confirm, they are not made the manager automatically (this is a bit inconsistent).

**Comment by sstead** [comment] 2016-03-04 00:15
The new user process is working though, which is most important to group set up... here is a screenshot, this is as much for my reference as yours Maikel
![image](https://cloud.githubusercontent.com/assets/10843056/13514141/5dbdd186-e1fa-11e5-9e37-c44266fbc807.png)

**Comment by sstead** [comment] 2016-03-04 00:30
Here's what needs to be changed to the /register process....
![image](https://cloud.githubusercontent.com/assets/10843056/13514390/81ab3fb4-e1fc-11e5-8044-0aa69ee6225c.png)

**Comment by sstead** [comment] 2016-03-04 00:34
Yes, only superadmin should be able to create groups- but you're right, it's broken on production too, so I'll just create a github issue for it seperately?

**Comment by sstead** [comment] 2016-03-04 00:35
The other thing is that when I first logged into staging, none of the groups had owners, is it sort of wiping ownership? When it goes to production, if it also wipes ownership, we can just reinstate ownership, but I just wanted to make sure that's not a problem.

**Comment by mkllnk** [comment] 2016-03-04 03:35
My current todo list:

- [x] hide create button
- [ ] check that group owners are not wiped out
- [ ] set email address in registration
- [ ] make existing users manager after email confirmation?

**Comment by sstead** [comment] 2016-03-09 01:42
![image](https://cloud.githubusercontent.com/assets/10843056/13622634/2e159fb0-e5f4-11e5-994b-f7b9cb6e8f79.png)

Hey maikel, I was expecting that this email field would be the 'display only' email address. And that the notification email would default to the login email, and that the confirmation/welcome email would also be sent to the login email.

**Comment by sstead** [comment] 2016-03-09 01:43
Also, the notification field doesn't have my login email as the placeholder until the .com.com.com email is confirmed... the .com.com.com just went in.... that's a problem because it's not a confirmed email...?
![image](https://cloud.githubusercontent.com/assets/10843056/13622691/893f83ba-e5f4-11e5-89bc-a946f6f72c31.png)

**Comment by sstead** [comment] 2016-03-11 01:45
@mkllnk I'm happy with this! The /register is improved and all other changes seem to still be in place! Yay!

**Closed** 2016-03-11 02:27 UTC
Labels: groups
