### ISSUE TITLE
Reports not loading after multiple clicks/not loading on screen

### ISSUE THREAD

**Issue by amidaOFN** [openfoodfoundation/openfoodnetwork#12746] opened 2024-08-07 00:35 UTC
## Description
User reports having to click 40 times to get a report to load, and only receiving reports as downloaded csv by email rather than on screen. 

User reports: "On average I probably need to click the generate report on screen (pack by supplier) button about 15 times until it actually shows up on screen. I will then receive 15 emails saying ‘report ready for download’… but I don’t want to download it, I just want to view it on the screen.

They have also subsequently said that they both click 20 times *and* then refresh and re-click, our understanding is they are able to reclick the load button without refreshing but do both.

## Expected Behavior
Reports should load in a reasonable time according to the format selected. User should not be able to reclick the button multiple times? 

## Actual Behaviour
Reports do not load or do not load for so long the user reclicks and/or refreshes the screen many times before receiving a report on screen or by email.

## Steps to Reproduce
Have not been able to reproduce. 

Reported environments: 
Safari on an iPhone 10, 
Safari on MacBook Air 2024

## Severity
s1

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
Safari on an iPhone 10 and MacBook Air 2024

**Comment by amidaOFN** [comment] 2024-08-07 05:37
unclear whether this is related to [#11752 ](url), have created a new issue per Rachel's suggestion

**Comment by RachL** [comment] 2024-08-14 14:16
WOOOOOOT I've managed to reproduce the fact that the GO button does not get disabled. "Fun" fact: even if it does not get disabled, and there is no loader/spinner, the report IS generated.

Server : coopcircuits.fr
User ID: 21323
Report: OC customer total
time: 4:10ish pm CET

i was on Firefox (and a private browsing window, so no extensions could have interfered)

I've clicked twice on the button before noticing I was reproducing the bug, so I assume a normal user would just click 100 times, and then they are also confronted to the fact that maybe 100 reports are generated? Which I assume makes the loading time even worse.

![image](https://github.com/user-attachments/assets/fc802f34-6d00-4da6-a406-1a40ded328be)

![image](https://github.com/user-attachments/assets/6f81a079-5c0a-446b-b0fc-b1571f7ec4b5)

**Comment by RachL** [comment] 2024-08-14 14:34
Staying on the page I now have a variant: the button does not get disable, but the loader appears (but users on smaller screens might miss it)

![image](https://github.com/user-attachments/assets/0e5ac444-3288-4de4-a6b4-e9c9d4b0a45a)

**Comment by rioug** [comment] 2024-08-21 01:29
1. User reports: "On average I probably need to click the generate report on screen (pack by supplier) button about 15 times until it actually shows up on screen. I will then receive 15 emails saying ‘report ready for download’… but I don’t want to download it, I just want to view it on the screen.

This is normal behaviour, we automatically email the user if the report takes more than 5 seconds to generate. It seems it's not well communicated to the user. Even if the report takes more than 5 seconds to generate it will displayed on screen when ready, but currently they are scenario when it might not happen. 

Maikel just finish a PR that should fix this : https://github.com/openfoodfoundation/openfoodnetwork/pull/12782

I think we should wait for the PR to be released and check if the issue is resolved before investigating this further.

**Comment by drummer83** [comment] 2024-08-22 13:54
I just came across another way to reproduce this on our AU staging server.

## Steps to Reproduce





1. Log in as user 7990 on staging AU (happy to provide the login details).
2. Go to the 'All products' report.
3. Run the report without filling in any fields in the report filters.
4. You should see the error message `This report failed. It may be too big to process. We will look into it but please let us know if the problem persists.`
5. The 'Go' button remains disabled.
6. Immediately reload the page.
7. Set the distributor to 'Konrad Testhub staging AU'
8. Click 'Go'

This reproduced the bug almost every time I tried. There may have been single times where it didn't.

**Comment by dacook** [comment] 2024-09-02 04:33
Hi @amidaOFN , I think the originally reported issue will be resolved as of last week's deployment. 
Are you able to confirm with the user if it's still a problem? If so, can you please find out the parameters that cause it? (IE user name and report filters)

Regarding @drummer83's report, I can still replicate this. I think the failure message is appropriate for an excessively large report (all products on the entire system).
But I think the "Go" button could re-enabled once you change the report parameters. What do you think Konrad?

**Comment by amidaOFN** [comment] 2024-09-02 22:41
Hi @dacook Checking with the main customer experiencing it whether there is any improvement but I have a new report of no report loading from a different user. 

It's the pack by customer report on Windows 11 latest version, browser Microsoft Bing. Filtered for Preston Ridge Farm as Producer

**Comment by dacook** [comment] 2024-09-03 00:27
Thanks Amida. I wonder if that new one could be this: https://github.com/openfoodfoundation/openfoodnetwork/issues/12835

**Comment by dacook** [comment] 2024-09-09 00:03
I'm unable to replicate using Konrad's steps above (using my own super admin user which I think would have the same effect). 
So @amidaOFN if you haven't heard anything further, I think we can close this issue.

**Comment by dacook** [comment] 2024-09-18 23:21
FYI @amidaOFN I'm closing this, assuming it was:
* Fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/12782

**Closed by dacook** 2024-09-18 23:21 UTC
Labels: bug-s2, feedback-needed
