### ISSUE TITLE
[Admin][Order] "Balance due" state after payments with a transaction fee

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#5574] opened 2020-06-09 16:16 UTC
## Description

The price shown in backoffice orders does not include transaction fees, for the respective payment methods. After payment is made, there is always an amount still to be charged and the order is in a "balance due" state. Attempting to pay for the open amount leads do an additional charge of the fee.

## Expected Behavior

The transaction fee should be included in the total price: it should be updated according to the choices made on Payments section allowing to pay the full price (fee included).

## Actual Behaviour

The transaction fee is not included. Paying for orders with transaction fee always renders the order to be in a  "balance due" state.

## Steps to Reproduce

Admin:
1. Set up a payment method with a fee.
2. Start placing an order in the backoffice, inserting items and customer details.
3. Proceed to Payments and check the total amount to be paid.
4. Choose the previously set payment method and perform the payment. 
5. Check the state of the order: it should be in "Balance due" with an amount corresponding to the value of the transaction fee.
6. Attempt to pay this open amount with that payment method - an additional fee will be charged...

## Animated Gif/Screenshot

Before payment:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/3a1c041b-5dfe-4e0f-a1ac-5cf55145be88)

After payment:
![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/e9cf2c8f-192a-4bed-bb4b-2394b02bb1b7)

## Workaround

If you know, in advance, what the value of the transaction fee is, then you can add this value manually, as a "prediction" of what the total cost will be. This allows to pay for the total amount with one payment.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v2.10.0
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Desktop Ubuntu 18.04

**Comment by RachL** [comment] 2020-06-09 16:48
@filipefurtad0 I wonder if this isn't a duplicate of: https://github.com/openfoodfoundation/openfoodnetwork/issues/3490

**Comment by filipefurtad0** [comment] 2020-06-09 18:11
Hey @RachL ,

I did not see #3490 as a duplicate as it deals with refunds, but it's surely related. Where I really stopped to wonder was this one:
- Payment Fee adjustment after order completion #1168

But @lin-d-hop describes a this also from the perspective of performing adjustments, so I didn't consider it as a double either. I thought I'd open this issue despite the pre-existing ones since it describes a  straightforward case: no refunds, no adjustments, just a plane backoffice order. Would you agree to keep it, or rather close it?

Also, the root problem seems related to these:
- Enterprise fee lingering on order when item is removed from order by making QTY=0 #1629
- Voiding payment does not remove transaction fee #3584

Perhaps addressing the root cause can contribute to solve all of them. Other than cross-mentioning/referring these issues (as above), what would be the best way to group them, so the dev who picks this up is aware of all the implications... Any ideas?

**Comment by RachL** [comment] 2020-06-09 18:22
@filipefurtad0 awesome! we could create an epic to group them. Otherwise mentionning and linking them in description is already nice. At least somewhere we document that they might be linked. So you did the right thing of opening a new issue 👍

**Comment by amidaOFN** [comment] 2024-08-28 01:37
We have several reports of this from a key user, and looking at the payment gateway, it is not only that the amount does not display correct, but is not charged correctly either - the lesser amount is charged, so the full transaction fee is not being paid.

**Comment by rioug** [comment] 2024-09-10 06:06
@amidaOFN I wasn't able to reproduce the issue. I tried with both a flat fee/percentage fee with a Stripe payment.  

Can you confirm it's happening with the described scenario above ? or give more details on the producer set up ?

**Comment by rioug** [comment] 2024-09-25 00:44
Step to reproduce: 

- Set up a Stripe payment method with a fee
- Start placing an order, selecting the Stripe payment method and stop at Confirmation step
- Continue shopping by clicking on the shop name next the cart
- Add or update the quantity of an item
- Continue checkout, you should land back on the Confirmation step
- Confirm the order 
- Confirmation page and email should have Balance due equal to the payment fee incurred by the new product or updated quantity

**Comment by rioug** [comment] 2024-09-25 06:58
Related change https://github.com/openfoodfoundation/openfoodnetwork/pull/12538, this probably fixed the transaction fee being wrong on the confirmation step in the scenario above.

**Comment by drummer83** [comment] 2024-10-11 14:58
The original issue cannot be reproduced anymore. It seems to be fixed already.
The steps pointed out in the comment above are a different issue, described in #12907 now.

Closing here.

**Closed** 2024-10-16 19:16 UTC
Labels: bug-s2
