### ISSUE TITLE
Can't add Star Anise to Stroudco order cycle on UK Production

### ISSUE THREAD

**Issue by NickWeir63** [openfoodfoundation/openfoodnetwork#875] opened 2016-03-29 12:56 UTC
We have set up a new producer (Star Anise Cafe) and added their products and given Stroudco permission to do everything for them but they still don't appear in the list of suppliers when we try to add them to the order cycle - see screenshot
![screenshot 2016-03-29 13 46 44](https://cloud.githubusercontent.com/assets/10517702/14108562/e7f7f510-f5b5-11e5-8895-e191979f0bdf.png)

**Comment by lin-d-hop** [comment] 2016-03-30 08:45
Hi @NickWeir63 
The issue was that all of Star Anise's products were set use inventory with 0 products 'on hand'. This meant they were effectively all 'sold out'.

You can fix this by going to the products page and ticking 'on demand' if the supplier is just supplying whatever is needed. Otherwise you can set to a number 'on hand' if the supplier is setting a specific availability. 

Note only do this for suppliers StroudCo is fully managing. If suppliers are selling into multiple hubs there is a different way to do this.

Closing as not a bug ;-)

**Closed by lin-d-hop** 2016-03-30 08:45 UTC

**Comment by NickWeir63** [comment] 2016-03-30 09:03
thanks Lynne.  SOrry about that.  we have a new volunteer doing manual updates.  I will pass that on
