### ISSUE TITLE
[Checkout] Impossible to checkout on certain shops in Safari

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#10003] opened 2022-11-16 17:10 UTC
## Description
When adding products to the cart on Safari, for some shops with one of my accounts i got the error "That product is not available from the chosen distributor or order cycle" and the cart is stucked on "Updating cart". 
It's not possible to checkout.

## Expected Behavior
Checkout must be possible everytime.

## Actual Behaviour
On Safari only, for one of my account only, in most of the shop I visited I had the error "That product is not available from the chosen distributor or order cycle". On some other, no problem. I tested the same shops in Chrome or Mozilla with the same account and there's no error. Refreshing the page solves the issue.

`URL: https://coopcircuits.fr/cart/populate
Status: 412
Source: Network
Address: 51.38.38.32:443
Initiator: 
all-3134b035699a57a47ba4393d41e72eee1da6194c13eeb24b6a59ff14bf50869d.js:39071

`

## Steps to Reproduce
I don't know

## Animated Gif/Screenshot
![Screen Shot 2022-11-15 at 10 29 36](https://user-images.githubusercontent.com/28386648/201884701-c7081ad4-46d4-41a9-9bce-f31f197e6a8a.png)
![Screen Shot 2022-11-15 at 10 30 31](https://user-images.githubusercontent.com/28386648/201884735-28c36d86-619e-4b05-97e8-6066a9def7f0.png)

## Workaround
Refreshing the page and checking out again solves the issue.

## Severity
s3 or s4 ?

## Your Environment
Safari Version 13.1.2 (13609.3.5.1.5)
high sierra 10.13.6

**Comment by RachL** [comment] 2022-11-16 17:41
@audez can you share the safari version and device?

**Comment by audez** [comment] 2022-11-16 18:30
yea sorry i add it to the issue thanks :)

**Comment by RachL** [comment] 2022-11-16 18:38
Browserstack does not allow us to test on 13.1 with High Sierra, only 11.1... so we can't reproduce I'm afraid. 

I've tested with High Sierra / 11.1 and Catalina / 13.1 but checkout worked fine in both version.

I will close it, if we get more insights in the future we can always re-open.

**Closed by RachL** 2022-11-16 18:38 UTC

**Comment by audez** [comment] 2022-11-16 18:40
I don't think High sierra matters.. But anyways i guess it'll be hard to reproduce because i could only see that with 1 of my OFN accounts. I'll check if we have this 412 error a lot on cart populate
