### ISSUE TITLE
[Admin][Order Cycles] Infinite loader displayed below the OC list

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9511] opened 2022-08-03 14:50 UTC
## Description
In the admin dashboard, when a producer opens the OC tab after its distributor has created an order cycle, there is an infinite loader below the OC list. It seems to only apply to Producer Profiles enterprises.

## Expected Behavior
Once the OC list has been loaded, the loader should disappear.

## Actual Behaviour
An infinite loader is displayed. If the enterprise is switched from Profile to Shop, the loader disappears. It reappears if switched to Profile again.

## Steps to Reproduce
1. Create a Producer Profile account, add a product
2. Create a Shop or Hub profile account (producer or non-producer)
3. Give the permission from Producer Profile to Shop/Hub to add products to order cycle
4. Add an order cycle from the Shop/Hub account, with the Producer Profile product
5. Connect to the Producer Profile and click on the "Order cycles" tab 
6. See the infinite loader
7. In Enterprise tab, switch Producer Profile to Producer Shop
8. Open "Order cycles" tab, see that the loader disappeared
9. In Enterprise tab, switch Producer Shop to Producer Profile 
10. See that the loader reappeared

## Animated Gif/Screenshot

![infinite-loader](https://user-images.githubusercontent.com/28386648/182638889-5ff67ffb-dcb4-4717-83d7-0e26ad291f4b.gif)

## Severity
bug-s4: it's annoying, but you can use it

**Comment by RachL** [comment] 2022-08-03 15:59
Duplicate of: https://github.com/openfoodfoundation/openfoodnetwork/issues/5831

**Closed by RachL** 2022-08-03 15:59 UTC
