### ISSUE TITLE
Appears that two adjustments are deleted when you delete just one.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1828] opened 2017-09-14 05:07 UTC
It appears that 2 lines of adjustments are deleted after you first delete a single adjustment. This could confuse a user, and make them worry that more adjustments have been deleted than they intended.

![image](https://user-images.githubusercontent.com/10843056/30412906-4e719164-995e-11e7-8304-2781994ece05.png)

**Comment by myriamboure** [comment] 2019-01-17 12:42
I'm not able to reproduce this error. I tried in different circumstances, so I'm closing it for now and we will reopen if it show up again.

**Closed by myriamboure** 2019-01-17 12:42 UTC
Labels: bug-s3
