### ISSUE TITLE
'Notify producers' includes cancelled orders

### ISSUE THREAD

**Issue by sigmundpetersen** [openfoodfoundation/openfoodnetwork#864] opened 2016-03-10 21:49 UTC
The email that is sent out includes all cancelled orders as well as standing orders.

**Comment by lin-d-hop** [comment] 2016-03-17 13:21
Hi Sigmund,

I haven't been able to replicate this issue, either through manually creating and cancelling orders on UK servers or by replicating the issue through the unit tests.

Are you able to give more information? Was this as a producer or a hub? Was the order cancelled by producer/hub/superadmin? Does this happen every time for you?

Thanks for helping track this down.
Lynne

**Comment by sigmundpetersen** [comment] 2016-03-17 13:30
It was reported from a Hub so I really don't have more information. I'll return your questions to the Hub for further testing and ask them to be more specific. We could just put this on hold for now.

**Comment by lin-d-hop** [comment] 2016-03-17 13:34
It would be great if you could replicate yourself. That is really useful before creating a bug on github to ensure that the issue is not just user error.

**Comment by myriamboure** [comment] 2016-03-18 12:47
@lin-d-hop @sigmundpetersen I had already created a documented issue on this: https://github.com/openfoodfoundation/openfoodnetwork/issues/811 I suggest to close this one @sigmundpetersen

**Closed** 2016-03-18 13:57 UTC

**Comment by sigmundpetersen** [comment] 2016-03-18 13:59
@myriamboure can you give me labelling rights etc here on github if I am to take over backlog management for Norway?

**Comment by myriamboure** [comment] 2016-03-19 23:32
@mkllnk is it you who give labelling rights? @sigmundpetersen needs to be able to label Norway :-)

**Comment by mkllnk** [comment] 2016-03-20 00:03
Everybody in the @openfoodfoundation/administrators team can do that, including me. I gave @sigmundpetersen write permissions so that you can change issues. But it is important that you do *not* commit code to the repository. Open pull requests as usual. We never use the merge button on pull requests. It all goes through our build pipeline with extensive testing. Is that alright?

And @myriamboure, do you still need to change issues or are you giving all the responsibilities to Sigmund?

**Comment by sigmundpetersen** [comment] 2016-03-20 02:31
Thanks @mkllnk. I'm not going to commit or merge any code, just managing the reporting of issues from Norway, mostly labelling...

**Comment by myriamboure** [comment] 2016-03-20 09:03
@mkllnk I still need to do that for France, I'm passing it over for Norway :-)
