### ISSUE TITLE
Snail when attempting to change Supplier of Product when Product is in Order Cycle

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#4189] opened 2019-08-27 00:46 UTC
## Description
Admin can make changes to a Product, even when it's in a current or past order cycle, however when attempting to change the Supplier of a Product, the snail appears. This happens when the product is in a past or current Order Cycle.  

## Expected Behaviour
Either it should be possible to change the supplier of a product, or an error message appears explaining why this change can't be made.

## Actual Behaviour
Snail appears when Admin attempts to change the Supplier of a Product, if that product is in a past or current order cycle.

## Steps to Reproduce
1. Log in as Admin of an account that manages more than one Enterprise Shop
2. Edit a product that has been in a previous order cycle, or is in a current order cycle
3. Attempt to select a different supplier in the Supplier field.
4. Snail

## Context
Customer has been trying various set up scenarios in a test enterprise that they manage. Many products have been set up in this test enterprise and added to test order cycles. They now want to move the products into the 'live' enterprise rather than setting them up again.  

## Severity
bug-s5

Impact is minimal. The customer will not know why the change was not possible and will not know how to resolve it. An appropriate error message will improve customer experience. The work around is to re-enter the products. 

## Your Environment

Version used: v2.2.2
OFN Platform instance: OFN Australia

**Comment by emilyjeanrogers** [comment] 2019-08-27 00:57
I was able to replicate the issue several times between approx 10.15am - 10.45am on Tues 27th August.

**Comment by RachL** [comment] 2023-11-17 16:34
I can't reproduce this one anymore - closing :tada:

**Closed by RachL** 2023-11-17 16:34 UTC
Labels: bug-s5
