### ISSUE TITLE
New products are not showing up in shopfront

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4113] opened 2019-08-01 03:09 UTC
## Description

To add or delete a new product to an existing order cycle in V2,   the manager must remove the producer from the OC,  then re-add them.   Product additions or deletions can't articulate into the shopfront by simply using 'select all' in the OC incoming and outgoing sections.  

## Expected Behavior

In  V1 --  a hub with lots of suppliers and products uses stock on hand to determine what shows up in the shop.  And in the OC they 'select all' (rather than scrolling through lists of hundreds of products for each supplier)   In V1 - if a producer deleted or added a product in an active OC,  the hub manager simply re-selected 'select all' and the product appeared or disappeared in the shopfront. 
## Actual Behaviour

In V2 -   re selecting 'select all' in the OC,  does not pick up the new product and add it into the shop, and if a producer deletes a product in an active OC,  re-selecting 'select all' does not eliminate the product from the shop.

## Steps to Reproduce

1. open an OC
2.create a new product for one of its suppliers and give it stock on hand
3. go to the OC and 'select all'  in both incoming and outgoing
4.see that the product does not show in the shop
5. go back to the OC - remove the producer -   re-add the producer and 'select all' products.  Select all in outgoing.   See that the product now shows in the shop

repeat for trying to delete the product

## Animated Gif/Screenshot

![shopfront with products from active order cycle](https://user-images.githubusercontent.com/13171778/62263066-ed81c480-b3e8-11e9-9c93-86c9b3112d73.png)
![select new products in incoming and in outgoing](https://user-images.githubusercontent.com/13171778/62263123-199d4580-b3e9-11e9-99a6-26f4a14288b4.png)
![new product not showing in shop](https://user-images.githubusercontent.com/13171778/62263128-1dc96300-b3e9-11e9-9058-367a3abec0fc.png)

then remove the producer from the OC and re-add them

![now product shows in shop](https://user-images.githubusercontent.com/13171778/62263154-333e8d00-b3e9-11e9-8792-e7584f9140fa.png)

## Your Environment

* Version used:  2.1 (??)
* Browser name and version: Chrome
* Operating System and version (desktop or mobile):  Win 10 desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by RachL** [comment] 2019-08-01 12:10
I could not reproduced in staging neither on French production :/ This is weird.

Were you in super admin or admin @tschumilas ?

**Comment by tschumilas** [comment] 2019-08-01 12:27
I was a regular admin.  I'll try with another hub and different producer,  and I'll try with super admin.

**Comment by tschumilas** [comment] 2019-08-01 12:47
Logged in as super admin -  and V2 works the same as V1 - That is: 'select all' will caputure a newly added product and show it in the shopfront,    and  deleting a product during an active OC removes the product from the shop .   But logged in as hub manager -  neither of these work.  To add a new product or delete a product from the shop during and active OC,  manager needs to remove the supplier and re-add the supplier back into the OC.     If no one else can replicate this - it must be something unique here -  what should I test?   I can set up a new hub and test again - but will be later today.

**Comment by sauloperez** [comment] 2019-08-01 14:51
I guess you checked this today, right @tschumilas ? in that case the version used is v2.2.1 according to https://github.com/openfoodfoundation/ofn-install/wiki/Current-deployment-status

**Comment by luisramos0** [comment] 2019-08-08 17:04
I'd tag this S2 at least until some investigation is done...

**Comment by luisramos0** [comment] 2019-09-24 13:43
this must be a cache problem, when the OC is saved, the cache is updated. If something goes wrong and the cache is not updated correctly, no errors will show and the product will not show in the shopfront.

**Comment by lin-d-hop** [comment] 2019-10-28 08:59
@tschumilas Will you test this again after the release tomorrow and close if it has stopped?

**Comment by tschumilas** [comment] 2019-10-28 18:02
Yes -  now when a user adds a new product,  AND the order cycle 'select all' is re-selected,  the product shows up in the shopfront.   (ie: producer does not have to be removed and then re-added to the OC) So this can be closed.

**Comment by luisramos0** [comment] 2019-10-28 21:19
hmmm... the release has not been done yet. so you are saying that the issue was not present in current version.
We should probably retest after the release.

**Comment by tschumilas** [comment] 2019-10-28 21:48
Ha!! -  I assumed the release was done and tested as @lin-d-hop suggested and it worked.   So - WTF?  Yes - I guess this issue was not present in the current version.  Not sure when it repaired itself.  Or why.  Will re-test after the release again.

**Comment by lin-d-hop** [comment] 2019-10-28 22:34
Sorry @tschumilas In future I'll be more clear.

I said _'test this again after the release tomorrow'_
I meant _'watch out on the #deployment or #instance-managers channels for notification of the release. Once the release has been done, will you test again?'_

**Comment by RachL** [comment] 2020-09-10 09:48
I still can't reproduce this one. So I'm closing and we can reopen if needed 👍

**Closed by RachL** 2020-09-10 09:48 UTC
Labels: bug-s3
