### ISSUE TITLE
New Order in Admin Pages - Customers do not appear in customer list

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#2354] opened 2018-06-02 05:31 UTC
Creating new orders and adding payment details via Admin results in error page.

Edit for clarity: there are two issues here;
- **Issue One:** Snail (error) page showing when adding payments on an order created via admin due to a validation error, as the order was sometimes being set to "guest checkout" whilst being placed by an admin on behalf a registered user. This issue is addressed in PR #2368.
- **Issue Two:** Customer search dropdown when adding customer details to an order placed via admin on behalf of another user is not returning results as expected, possibly due to enterprise permissions. 

## Description
When working through the new order section as enterprise administrator you receive the error page when adding payment details for a registered user. Since https://github.com/openfoodfoundation/openfoodnetwork/pull/2073

On the initial screen you are unable to search of an existing user
When creating an order you then receive the slug page when adding the payment.

## Expected Behavior
You can complete a new order in Admin without having an error message for both registered and non register customers. 
If a registered user they should come up in the search fields.
You should be able to define whether the user is a guest or not
There should be better error reporting as the slug page is not helpful in understanding the cause of the issue.

## Actual Behavior
1. Search field is unable to find any email addresses that are entered
2. You cannot set the email address you type as NOT being a guest i.e setting No
3. When adding a payment the page crashes with error message in the logs:
StateMachine::InvalidTransition (Cannot transition state via :next from :cart (Reason(s): This email address is already registered. Please log in to continue, or go back and use another email address.)):

## Steps to Reproduce
1. Search for a registered user - if they are register they should show up, if not, I should then manually enter the email address below
2. I can select whether or not they are a guest using the toggle buttons
3. fill in details and go to the next page - shipping information
4. continue through shipping page and select payments
5. on the payment page select payment method and then continue
6. proceed as normal and register the new payment and order

This process works for a non registered user

## Animated Gif/Screenshot
http://recordit.co/3Uk476JjRb
(slow loading but bare with it - the error can be seen at the end)

## Context
Some enterprises are adding orders on the behalf of customers - for instance they may take them over the phone. This is stopping them from doing that. 

## Severity
s2 - This has rendered OFN useless for one UK user. They cannot run their enterprise currently.

## Your Environment

* Version used: 1.15.1
* Browser name and version: chrome
* Operating System and version (desktop or mobile): windows desktop

**Comment by sineadfenton** [comment] 2018-06-02 05:32
![](https://github.trello.services/images/mini-trello-icon.png) [Exeter veg share order problems](https://trello.com/c/uk2RuIJY/183-exeter-veg-share-order-problems)

**Comment by Matt-Yorkley** [comment] 2018-06-08 17:50
This should just need a quick modification to the changes in #2073, but I'll add some tests as well for this ordering via Admin case, which obviously isn't covered already in the specs.

**Comment by Matt-Yorkley** [comment] 2018-06-09 01:44
There's lots to unpack in this issue. 

Firstly it looks like the customer search dropdown only shows details for existing customers of your enterprise and not all registered users. I think this is probably correct (especially in light of the GDPR rules), you can't look up email or delivery addresses of customers from other people's enterprises. It seems to be working and correctly retrieving customer records, as far as I can tell.

The "guest checkout" radio buttons are set to "yes" and disabled if you don't select an existing customer using the search field (working as intended), but the buttons shouldn't really be there any more since #2073, as registered user can't use guest checkout any more. I've made a PR to set the guest checkout field automatically based on whether or not the customer is registered and remove the radio buttons. I think that's the best option, as the choice to use guest checkout with a registered user no longer exists, so having that choice in the UI doesn't make sense. 

As well as simplifying the UI it also fixes the order validation error which was causing the snail page when adding payments.

**Comment by sineadfenton** [comment] 2018-06-09 09:57
So with the customer search dropdown seems a bit temperamental and I wonder if its something to do with how many customers there are - Just done another test and some observations below:

When I try for my enterprise Audacious Veg which has one customer, I can search for that one customer - AV1 and AV2. 

When I try with the OFN UK Demo shop, I can't search anyone on that list - I've tried both customers that may possibly be associated with other accounts and unique customers to that enterprise only and nothing is found - AV3.

Out of interest however I tried adding a new customer to Audacious Veg to see if having a couple did anything, and then also added them to OFN UK Demo - I could see them in Audacious Veg, but not OFN UK Demo

AV1
![av1 - customer](https://user-images.githubusercontent.com/28807449/41190298-ddfd7ac6-6bd3-11e8-82d8-9098fdb6c935.PNG)

AV2
![av2 - customer found](https://user-images.githubusercontent.com/28807449/41190301-e1cd0ef0-6bd3-11e8-931d-18f9c6e86e6d.PNG)

AV3
![av3 - customer larger org no matches](https://user-images.githubusercontent.com/28807449/41190304-eed40eb4-6bd3-11e8-8748-43b1dfebe7b4.PNG)

AV4
![av4 - one match no math](https://user-images.githubusercontent.com/28807449/41190310-f47a862c-6bd3-11e8-9e37-7c5a27b8da9b.PNG)

**Comment by Matt-Yorkley** [comment] 2018-06-09 11:06
Very strange, I'll do some more investigating...

**Comment by Matt-Yorkley** [comment] 2018-06-09 12:00
I've found another issue whilst investigating this on UK production, the orders page in admin often gives me the snail if I deselect "show only completed orders". It looks like one of the spree-core views is expecting a completed date, but our incomplete orders don't always have them?

![screenshot from 2018-06-09 12-50-18](https://user-images.githubusercontent.com/9029026/41191274-ed3432da-6be4-11e8-87f5-2fc387a1a0ac.png)

**Comment by Matt-Yorkley** [comment] 2018-06-09 12:51
The customer search works in my dev environment with latest `master`, but not at all on UK production. There's nothing in the logs that indicates any errors, and the request is apparently completing successfully each time, but returning no results. 

It might be nicer to create a new issue for the customer search so we don't get too tangled up, and maybe check this on other instances to see if it's just UK prod or everyone that's effected?

**Comment by lin-d-hop** [comment] 2018-06-09 12:57
Updated this issue to reflect the actual problem.
@myriamboure @sstead Can users with enterprises that have large customer bases see their customers in the drop down list of customers when attempting to add a New Order from the Admin->Orders screen?

**Comment by Matt-Yorkley** [comment] 2018-06-09 13:12
I tried it with the old Dean Forest enterprise (~7 customers) on UK production and the result was the same. Individually tried each email in the list, and got no results. I manually checked the DB to make sure the customer records were all present and correct (they were). Checked the git history on all the files related to the customer search, and none have been changed in the last year. The odd thing is that it works fine in my dev environment. I cross-checked the production DB with my dev DB and there aren't any discernible differences in the data...

**Comment by lin-d-hop** [comment] 2018-06-09 14:10
@Matt-Yorkley Is your dev env a prod dump?

**Comment by Matt-Yorkley** [comment] 2018-06-09 15:14
I think it's a pretty old prod dump. Some of the old unused enterprises are the same in my dev DB as the UK prod DB though.

**Comment by myriamboure** [comment] 2018-06-12 06:51
I got it @lin-d-hop @Matt-Yorkley !!!
It has nothing to do with the number of customers in my opinion.
I tried to connect as a manager of "hub demo open food france" shop, I add a new order from admin for the user "fredprofile", his user entry appear when I start typing his name in the dropdown menu.
Then I logout and login again as a Open Food France admin, I try to do the same, no record is shown in the dropdown menu for "fredprofile" SO I guess the problem is that super admins can't see records for existing users in the dropdown menu while making an order from backoffice :-)

**Comment by Matt-Yorkley** [comment] 2018-06-12 12:34
Ah, interesting! I was tested as an enterprise user, and as a superadmin, but the superadmin user was also the owner of the test enterprise. So a superadmin without explicit permission can't see customer details...

**Comment by myriamboure** [comment] 2018-06-18 21:53
@Matt-Yorkley can you fix that? Or is it included in your fix #2368? Super admins should be able to see customers in any dropdown menu for any enterprise I guess (they anyway have access to all customer lists), so that they can assist in making orders from back office if needs be. I guess your fix will fix the issue as super admin will still be able to make an order with the email of the registered user even if doesn't use the dropdown menu... am I right? In that case I can open a separate issue that we can solve later.

**Comment by Matt-Yorkley** [comment] 2018-06-19 22:21
I've edited the description for this issue to try to clarify it a bit, as there are 2 bugs being reported simultaneously that don't have the same cause or the same solution.

The first bug should now be fixed by #2368, which I think is the `s2` part. Regarding the second bug relating to customer search results:

It seems that enterprise users that directly have permissions can search within their own enterprise's customers, but admin users don't get the same search results because they don't explicitly manage those enterprises. I think this is working as intended?

**Comment by myriamboure** [comment] 2018-06-19 23:10
I don't think it works as intended @Matt-Yorkley for me "admin users should get the same search results because even if they don't explicitly manage those enterprises, they have super admin powers and can see customers from any enterprise". But I propose we open a separate issue and fix it later if it appears still to be annoying for admins doing support. Maybe it is not so let's not spend more time on it. I'll put that in my todo.

**Comment by Matt-Yorkley** [comment] 2018-06-20 15:18
Primary issue closed via #2368, and secondary issue captured in #2397.

**Closed by Matt-Yorkley** 2018-06-20 15:18 UTC
Labels: bug-s2
