### ISSUE TITLE
Missing/wrong translation key in admin / new order

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5094] opened 2020-03-27 17:33 UTC
## Description

When creating a new order as an admin, the word is not correct in French, so I suspect that we reuse another key here instead of having a dedicate one.

## Steps to Reproduce
1. Go to `/admin/orders/new`
2. The translation key for the title is not correct

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/77783163-ac65b100-7058-11ea-8a9c-47470583fe63.png)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.8
* Browser name and version: Firefox 73
* Operating System and version (desktop or mobile): Desktop

**Comment by sharonfruit** [comment] 2020-04-03 17:09
Looking into this issue.

**Comment by sigmundpetersen** [comment] 2020-04-04 18:59
Great thanks @sharonfruit. I moved it to In Dev for you.
Please don't hesitate to ask if you have any questions. 

There's also a section on i18n in the wiki here https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29#development

**Comment by RachL** [comment] 2020-04-25 16:17
Hello @sharonfruit I hope you are doing fine. Are you still planning to work on this?

**Comment by sharonfruit** [comment] 2020-04-25 20:12
Hi @RachL , I did track the root cause of this issue down to the app/views/spree/admin/orders/set_distribution.html.haml file (unexpectedly not app/views/spree/admin/orders/index.html.haml) where the translation for "new" is being prepended to the page_title and order number that is set in the shared app/views/spree/admin/shared/_order_tabs.html.haml.  

A translation key for "new order" does exist but removing the "order" translation from the _order_tabs.html.haml page_title affects every other page that renders this shared element. At that point I was unsure of the preferred way to resolve the issue and was sidetracked by other work.

I will ask in the #dev channel for advice on the best way to resolve.

**Comment by RachL** [comment] 2020-05-14 13:44
hey @sharonfruit ! Did you get any feedback? Are you still planning to work on this?

**Comment by RachL** [comment] 2020-05-18 07:47
As there seem to be no activity here, I'm moving it back to the list of available issues.

**Comment by rmklaus12** [comment] 2020-05-18 08:56
I'll grab this!

**Comment by sharonfruit** [comment] 2020-05-18 13:02
@rmklaus12 My Docker image is broken at the moment, but I made a pull request for what I had. Feel free to trash and start over or to use it and modify. 

@RachL sorry I couldn't devote as much time to this as I wanted. I agree it's best that you re-assigned.

**Comment by rmklaus12** [comment] 2020-05-19 00:39
Happy to take over @sharonfruit. :-)

**Comment by rmklaus12** [comment] 2020-05-21 07:17
I believe a solution is in place...on the new order page in French I am seeing 'Nouvelle commande', the other tabs on Order seem to be still correct. @RachL - can you please confirm based on these screenshots
<img width="1203" alt="Screen Shot 2020-05-21 at 5 10 52 pm" src="https://user-images.githubusercontent.com/30268789/82533243-3a0bdb80-9b86-11ea-8390-19749509e396.png">
<img width="1141" alt="Screen Shot 2020-05-21 at 5 11 00 pm" src="https://user-images.githubusercontent.com/30268789/82533249-3b3d0880-9b86-11ea-94f0-87f2f3a6af81.png">

?

<img width="1098" alt="Screen Shot 2020-05-21 at 5 10 39 pm" src="https://user-images.githubusercontent.com/30268789/82533231-35dfbe00-9b86-11ea-8ed3-8f26102dacad.png">

**Comment by rmklaus12** [comment] 2020-05-21 07:33
I believe the fix is in place. @RachL - can you please confirm based on these screenshots, that this is the wording you want? I have changed other files based on @luisramos0 suggestion to the other dev, so will push all changes and open a PR if you are happy with this bit. Thanks!
<img width="1098" alt="Screen Shot 2020-05-21 at 5 10 39 pm" src="https://user-images.githubusercontent.com/30268789/82534814-29a93000-9b89-11ea-9403-58d284824d62.png">
<img width="1203" alt="Screen Shot 2020-05-21 at 5 10 52 pm" src="https://user-images.githubusercontent.com/30268789/82534820-2d3cb700-9b89-11ea-9bb7-a16995c4d14b.png">
<img width="1141" alt="Screen Shot 2020-05-21 at 5 11 00 pm" src="https://user-images.githubusercontent.com/30268789/82534824-2e6de400-9b89-11ea-9774-0168be92285e.png">

**Comment by RachL** [comment] 2020-05-21 16:11
looking good thanks @rmklaus12 !

**Closed** 2020-06-11 11:23 UTC
Labels: bug-s3, good first issue
