### ISSUE TITLE
ActiveRecord::StaleObjectError in spree/admin/products#bulk_update

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#599] opened 2015-06-10 01:12 UTC
## Exception in OpenFoodNetwork

**ActiveRecord::StaleObjectError** in **spree/admin/products#bulk_update**
Attempted to update a stale object: Spree::Variant

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/55763451ea1b57dee7482737?event_id=5576345157c511dc0ccc85f1)
## Stacktrace

```
app/models/spree/product_set.rb:32 - update_variant
app/models/spree/product_set.rb:25 - block in update_variants_attributes
app/models/spree/product_set.rb:24 - each
app/models/spree/product_set.rb:24 - update_variants_attributes
app/models/spree/product_set.rb:18 - update_attributes
app/models/spree/product_set.rb:45 - block in save
app/models/spree/product_set.rb:44 - each_value
app/models/spree/product_set.rb:44 - each
app/models/spree/product_set.rb:44 - all?
app/models/spree/product_set.rb:44 - save
app/controllers/spree/admin/products_controller_decorator.rb:42 - bulk_update
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/55763451ea1b57dee7482737?event_id=5576345157c511dc0ccc85f1)

**Comment by mkllnk** [comment] 2015-06-10 01:31
I can't reproduce that at the moment. Maybe it's a race condition when someone deletes and changes a product at the same time.

**Comment by RachL** [comment] 2019-03-28 14:07
As it is not reproductible and looks like it didn't happened since 2015, I'm closing this. Feel free to reopen if needed!

**Closed by RachL** 2019-03-28 14:07 UTC
Labels: bugsnag
