### ISSUE TITLE
Group seems to be created - no error -  but it's not created

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/openfoodnetwork#7487] opened 2021-04-26 16:20 UTC
## Expected Behavior
The group should be created so the owner can be assigned and the owner can start managing it.

## Actual Behaviour
Group does not seem to be created and is not found in groups list.

## Steps to Reproduce
1. Log in as admin
2. Click "groups", then "new enterprise group"
3. Fill in name and description for group
4. click "create"
5. return to groups page, group does not appear, other already-created ones do.

## Animated Gif/Screenshot

![No group sad face](https://user-images.githubusercontent.com/37803238/116116949-9322a000-a670-11eb-956b-7bdd06d2c77a.gif)

## Workaround
No workaround 

## Severity
Instances rely on the groups feature to support many farmers markets, who are just now signing on in the northern Hemisphere. 

bug-s2: a non-critical feature is broken, no workaround - does not affect everyone but impacts many new enterprises

## Your Environment
Chrome on Chromebook and PC

## Possible Fix
No suggestions. Not sure when this started happening but I noticed it a few days ago and thought it was a mistake on my part.

**Comment by tschumilas** [comment] 2021-04-26 17:07
I'd suggest this is a critical feature and an s1?   stopping new farmers markets joining ofn.

**Comment by andrewpbrett** [comment] 2021-04-26 20:09
Thanks for reporting this @lauriewayne. I think I've tracked this down and will have a fix shortly. The issue is with the address for the enterprise group being blank, so as a temporary workaround I was able to create a group by filling in the address fields on the Contact tab after clicking New Enterprise Group.

**Comment by lauriewayne** [comment] 2021-04-26 20:13
Thank you @andrewpbrett to the rescue again! 

![Underdog_cartoon](https://user-images.githubusercontent.com/37803238/116144347-16ec8480-a691-11eb-99f0-531b26993191.jpg)

**Comment by lauriewayne** [comment] 2021-04-26 20:32
Thanks @RachL ! Appreciate the guidance!

@andrewpbrett I am noticing that in the contact screen, even when I select United States as country and have a real zip code, I am not able to select state. I will log this as a separate bug with a low severity unless you believe it is related. Thank you! 
![Screenshot 2021-04-26 1 28 41 PM](https://user-images.githubusercontent.com/37803238/116146832-cde9ff80-a693-11eb-9190-da759a08a6bd.jpg)

**Comment by andrewpbrett** [comment] 2021-04-26 21:15
> I will log this as a separate bug with a low severity unless you believe it is related.

Yes please - I noticed that as well, I think it's unrelated.

**Comment by andrewpbrett** [comment] 2021-04-26 21:17
I created a draft PR to address this - it's a little strange because I'm not actually seeing it happen locally, only production, so I'm not sure why that might be. It'll need a test or two for sure but in case anyone else wants to pick it up that PR is the place to start.

**Comment by tschumilas** [comment] 2021-04-26 21:28
Feeling rather sheepish here that (1) I didn't notice the address had to be filled in (sorry @lauriewayne )  and (2) that my panic response said s1.   Its just that its spring,  and all the farmers markets are wanting to form groups here......    Thanks all.

**Comment by filipefurtad0** [comment] 2021-06-09 15:37
I think PR #7647 solved this as well - it's not necessary to add the address to the group, as the country and state are of the instance are now selected by default :+1: 
Closing.

**Closed by filipefurtad0** 2021-06-09 15:37 UTC
Labels: bug-s3
