### ISSUE TITLE
Multilingual language listing

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#2113] opened 2018-03-05 17:30 UTC
With multilingual, the displayed languages can't be controlled, and the default language gets appended to the available languages listed in the `AVAILABLE_LANGUAGES` list. 

![screenshot from 2018-03-05 16-20-13](https://user-images.githubusercontent.com/9029026/36989474-bea948e2-2099-11e8-918a-c4cdf15da7b0.png)

## Description
`en` is being added to the languages list when it shouldn't be.

## Expected Behavior
A list of available languages can be defined in `application.yml`, and the languages shown should not be different from that list.

## Actual Behavior
Extra languages get added in, possibly just the default/fallback language.

## Steps to Reproduce
![screenshot from 2018-03-05 17-22-48](https://user-images.githubusercontent.com/9029026/36989579-fdd42eba-2099-11e8-9582-4d24af75d846.png)

## Context
Instances using multilingual.

## Severity
S2

## Possible Fixes
1. Add another env variable, which lists the languages to be shown?
2. Using the order in exisitng `available_locales` e.g. `[en, en_GB]` means that `en` is the fallback

**Comment by daniellemoorhead** [comment] 2018-03-05 22:43
@myriamboure @lin-d-hop I've given this a severity 2 and assigned it to @Matt-Yorkley and @mkllnk to fix given they were working on multilingual project. Feel free to change if this isn't correct 😄

**Comment by enricostano** [comment] 2018-03-06 11:58
Please share the suggested solution before starting to code 🙏

**Comment by mkllnk** [comment] 2018-03-07 03:19
Okay, so we use `I18n.available_locales` in three files:

- `config/application.rb`
- `app/views/shared/menu/_large_menu.html.haml`
- `app/views/shared/menu/_mobile_menu.html.haml`

The application config is correct adding the default locale and `en` to the `available_locales`. These are used for building assets and having `en` as last resort fallback.

As Matt pointed out, the problem is that the views use the same `available_locales` object. But we should base this data on `ENV["AVAILABLE_LOCALES"]`. This is just a string that needs some transformation to become an array.

What I would do:

- Create `lib/open_food_network/i18n.rb` as a central place for logic around this.
- The lib provides `OpenFoodNetwork::I18n.selectable_locales` to use in views.
- The lib provides `OpenFoodNetwork::I18n.available_locales` to simplify `application.rb` and make it agnostic to where these values come from.
- The lib also provides `default_locale` to complete the encapsulation.
- It can also contain `source_locale` which is hardcoded `en` and is used in `config/environments/test.rb`.

If we decide later to store these values in the database instead of environment variables, we have to change only that one lib class to get the information from somewhere else.

I know a bit about OOP and design patterns, but I'm not the most proficient Rails architect. Would it be better to have this lib class as a model since it's about stored data? We could call it `I18nConfig`.

Your thoughts are very welcome. Once we decided on a solution, it should be a matter of minutes to implement it. And an hour to test it properly. ;-)

**Comment by sauloperez** [comment] 2018-03-07 08:08
I do like it and I would definitely call it `I18nConfig`. As for the folder, `models/` is where our business logic lives, regardless of persistence, while `lib/` is for things orthogonal to the domain model. In this case, it feels more like a lib but I'm not sure.

**Comment by enricostano** [comment] 2018-03-07 17:47
I like the idea, agree on `I18nConfig`, vote for `lib/`.

**Closed** 2018-03-23 14:06 UTC
Labels: bug-s2
