### ISSUE TITLE
Embedding group pages

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1783] opened 2017-08-30 00:10 UTC
Users want to be able to embed group pages into their own websites. This feature should be based on the existing work around [embedding shopfronts](https://github.com/openfoodfoundation/openfoodnetwork/pull/1557), with some modifications.

@mkllnk I understand the plan is that you should spend 2 hours on this, and see how far we can get. I've listed some 'nice to have' elements, but it's ok if they don't get done in the first version.

**Group page functionality to keep the same:** (essential)
- Existing map search and zoom
- Existing search and filters on the profiles and hubs tabs
- Expando collapso of the mini profiles in Our Producers and Our Hubs

**Display of profile modals** (not essential)
When a visitor clicks on a profile icon on the map, the modal should open. Ideally the background of the webpage (not just the embedded section) should be greyed (as pictured below). The webpage scroll bar is also disabled, so the user can just scroll in the modal.
![image](https://user-images.githubusercontent.com/10843056/29848884-b5f2c5d2-8d66-11e7-8a32-11cbf5e0701d.png)
If this is not possible, just the embedded section should be greyed, as happens if you open the product modal in an embedded shop - see [here ](https://openfoodnetwork.org/user-guide/advanced-features/demo-embedded-shop/)

**Embedded header** (not essential)
- I'd suggest that the Login (or gear symbol if already logged in) and Cart links could be removed from the header- I imagine the directory will primarily be for the purpose of browsing profiles, not shopping. Therefore we don't need these functions to be at the top, where they'll potentially confuse people.
- Could we move the 'powered by open food network' to somewhere lower on the page? It takes up a whole row of header space, which is probably not neccessary.
![image](https://user-images.githubusercontent.com/10843056/29849036-a8c9e920-8d67-11e7-9306-352fdb32173b.png)

**Contact details** (not essential)
If possible it would make sense to remove the contact details 
![image](https://user-images.githubusercontent.com/10843056/29849252-e194cc92-8d68-11e7-9eae-04d5610b4880.png)

**Remove the logo, banner and Description text fields.** (not essential)
Because the group page is being embedded, the group owner can add whatever images and text they want above their embedded group. Therefore if we remove these fields, it gives the group owner more flexibility to decide what sits above the directory.
![image](https://user-images.githubusercontent.com/10843056/29849362-95a01700-8d69-11e7-846b-7e8289555d9f.png)

**Links to Shops.** (not essential)
If a profile modal for a shop contains a link to their OFN shop, it would be great if this could open in a new tab, rather than regular functionality, which directs the user to the shop in their current tab. These links are found on the 1) map 2) Our Producers tab and 3) Our Hubs tab.
![image](https://user-images.githubusercontent.com/10843056/29849309-40493282-8d69-11e7-8774-829ab4bfc904.png)

**Comment by lin-d-hop** [comment] 2017-11-14 16:01
YAY all of this would make group pages so much better to embed!!

**Comment by daniellemoorhead** [comment] 2017-11-14 23:57
List of Sally's suggestions and what's done (as of Wednesday 15 November):

- [x] the Login (or gear symbol if already logged in) and Cart links could be removed from the header
- [ ] move the 'powered by open food network' to somewhere lower on the page (*the element got removed*)
- [ ] remove the contact details
- [ ] Remove the logo, banner and Description text fields
- [ ] Links to shops open a new window

If you pick up and run with any of these please tick them off as you create and merge PRs so that we know where the issue is at in terms of completion.

**Comment by KeirOsborn** [comment] 2017-12-15 11:26
@sstead @mkllnk @lin-d-hop @daniellemoorhead @Duende13 
Hi all, Just starting to look into this. 

So i've got the embedded-group-preview.html working locally. I just created a group and added localhost:3000 to the external domains whitelist on the general settings page and it worked.
 
I've hit an issue though. I can see that the 1st task on the list "the Login (or gear symbol if already logged in) and Cart links could be removed from the header" Is done. But the change appears whether the page is embedded _or_ viewed normally. This is because ":embedded_shopfront=>true" is added to the session hash at some point before it's set in the check_embedded_request method (line 73 application_controller.rb) and so @shopfront_layout = 'embedded' is _always_ true. I don't know when or why ":embedded_shopfront=>true" is prematurely set.

I'm pretty sure this can be fixed easily by just setting session[:embedded_shopfront] = false at the beginning of the check_embedded_request method in application_controller.rb, that way it'll be false by default and only set to true if embedded_shopfront comes through in the params, which is how it's supposed to work. This might not be desirable though, as it doesn't really get to the bottom of why ":embedded_shopfront=>true" is added to the session erroneously in the first place. If anyone has any info on this issue, please let me know, maybe i've misunderstood what's going on entirely, or maybe this is already being worked on. 

Thanks,
Keir

**Comment by KeirOsborn** [comment] 2017-12-19 17:40
Hi all, @sstead @mkllnk @lin-d-hop @daniellemoorhead @Duende13

I've got a question about testing. I guess it's mainly for @mkllnk. 

So currently there are tests for embedded content but they all refer specifically to embedded shopfronts. i.e. embedded_shopfronts_spec.rb and embedded_shopfronts_headers_spec.rb. Do you think it would make sense use the same tests to test embedded groups (only making minor additions)? Under normal circumstances the answer would obviously be no, they should have their own tests, but the thing is embedded groups, are using the embedded shopfronts functions and nomenclature. For example, enable_embedded_shopfronts is called in the groups_controller which checks the embedded_shopfronts_whitelist and the enable_embedded_shopfronts variable.  

I can abstract the embedding code out so that each controller calls it's own specific embed methods, but this is obviously beyond the scope of this task and is a bit of a bigger job (although not huge).

If people don't think that's a good idea, my instinct is that for the time being it should also be tested using the same tests (only differentiating where necessary). If, later on, we decide to abstract out the embedding functions, that's the time to separate the tests. What do people think?

Thanks 
Keir

**Comment by Matt-Yorkley** [comment] 2017-12-20 00:55
@KeirOsborn there will probably be a lot of overlap between the two, so putting them in one file for testing embedded pages would make sense.

**Comment by mkllnk** [comment] 2017-12-20 22:54
I don't have a strong opinion on where to test. It just has to be clear when someone is looking for the tests where to find them.

Regarding why `:embedded_shopfront=>true` is added: did you test in a private window or did you view the pages from the same browser session? The page tries to remember in which context you are so that we don't have to pass on a parameter with every request.

**Comment by KeirOsborn** [comment] 2017-12-21 11:05
Ah great ok that must be it then. Only checked it in the same browser session. 

I mean, I still think it's a bug because obviously a user could be looking at one group embedded and another one on the website and they would see the embedded layout in both cases, but it isn't that serious I guess. 

How does the context remembering happen?

Cool thanks for the advice on testing, in the end I decided to separate out the tests for that exact reason.

**Comment by mkllnk** [comment] 2017-12-21 23:49
> How does the context remembering happen?

Good question, I would need to look into the code. I think it's in the session, but may be saved via cookie as well.

**Comment by KeirOsborn** [comment] 2017-12-22 16:24
"move the 'powered by open food network' to somewhere lower on the page (the element got removed)"

Pull request submitted for this. Pull request #2025

**Comment by KeirOsborn** [comment] 2017-12-26 23:47
@daniellemoorhead 

"Remove the logo, banner and Description text fields" I'm assuming we still want to keep the name field though, even though it's in the middle of these other three. Just checking this is right.

Thanks,

**Comment by lin-d-hop** [comment] 2017-12-27 00:17
@KeirOsborn No, please do remove the name as well.
The reason for this is that it will be embedded, so by removing it we give more flexibility to the user to surround with the necessary information. Since readers will already be on the user's website, we can assume that they know who the group is and probably don't need to see the name here.

**Comment by KeirOsborn** [comment] 2017-12-27 10:59
Ok cool thanks Lynne!

**Comment by KeirOsborn** [comment] 2018-01-16 17:31
PR submitted.

**Comment by sstead** [comment] 2018-06-22 05:37
This issue is partially complete.

Fixes that are done:
- Contact details removed
- Header images/text removed
- Links to shops on OFN open in new tab.

Outstanding minor issues:
- [ ] Some links are not opening in new tabs. Specifically hyperlinks in profile about us text
- [ ] The 'powered by OFN logo' isn't always shown clearly, sometimes falling off the bottom of the page.

**Comment by daniellemoorhead** [comment] 2018-08-20 07:46
Hey @kristinalim have a look at this one and see whether the remaining minor issues are small and easy enough for you to quickly do (once you've sorted out the other things on your to do list 😄 )

**Comment by myriamboure** [comment] 2018-10-16 17:22
@sstead I think the two remaining things mentioned here are done, so I'm closing this issue. If you disagree please reopen or preferably, open a small issue just for the small thing that remains to be done, to avoid having to read again whole the history of what has been done. Cheers!

About links fixed: https://github.com/openfoodfoundation/openfoodnetwork/issues/1348

About the footer: seems stable:
![capture du 2018-10-16 18-57-34](https://user-images.githubusercontent.com/8135376/47034774-902dc700-d178-11e8-99db-b2b29bcd5d65.png)

**Closed by myriamboure** 2018-10-16 17:22 UTC
