### ISSUE TITLE
Items Added to Order and Charged to Stripe without Shopper Knowing

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#5982] opened 2020-09-03 01:52 UTC
## Description
Two shoppers have complained that items were added to their order that they didn't add to the cart. Both customers were charged for these extra items and received an order confirmation email that listed them. 

Both customers are certain the additional items (and charges) were NOT shown in the order confirmation screen before confirming payment. Both customers WERE charged in Stripe and did not know until they received their order confirmation email.

## Expected Behavior
Random items should not be added to cart! 
Customer should not be charged for amounts that they have not confirmed at checkout.

## Actual Behaviour

**Customer 1** 

Date: August 26th
Order no: R428222545
Enterprise:Willunga Farmers Market (2545)

Customer says: _"I’m really not sure what happened because I remember seeing the total $68 just before I paid and now it’s 120 plus $5 for packing but also $12 for shipping?? "_

We assumed customer error. The Enterprise adjusted the customer's order and provided a refund through Stripe. (NOTE: account is still in credit and we are working with the Enterprise to adjust the order - this is unrelated to the issue though)

The Order confirmation email matches what is in OFN Orders and the amount charged to Stripe. 

Products incorrectly added:
- 1 x Bag Pink Lady Apples
- 1 x 2L Greed Lid Milk
- 1 x 1L Yellow Lid Milk
- 1 x 250g White Mushrooms
- 1 x Dill
- 1 x 1L Pouring Cream

**Customer 2**

Date: September 2nd
Order no: R332700224
Enterprise: Prom Coast Food Collective (1965)

Customer ordered on an Android phone.

Customer says _"Something strange happened to my order. I am sure I only ordered 3 yoghurt,  3 eggs,  and no chocolate and the numbers are different in my confirmation. Not sure how it happened. The order total was one hundred and twenty something when I went to pay before the shipping and extra costs. Only noticed in the confirmation because of the chocolate and the price "_

The Order confirmation email matches what is in OFN Orders and the amount charged to Stripe. 

The Enterprise is going to adjust the order and refund the customer.

Products incorrectly added:
- 2 additional Butterfly Factory Yoghurts
- 1 additional Certified Organic Eggs from Ruby Hills
- 1 Daintree Estates Chocolate Block

Customer confirms she didn't click on the chocolate at any time, and is confident she didn't order the additional yoghurt and butter.

## Steps to Reproduce

Have been unable to reproduce. No other customers for these enterprises have had problems. 

## Severity
S1 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by emilyjeanrogers** [comment] 2020-09-03 06:49
Customer 2 confirmed:

- they had never clicked on the chocolate product that was added
- they were quite certain they had not entered the additional quantities of yoghurt & eggs
- they were quite certain they had not had any other windows open with the shopfront
- they had not placed any orders with other shopfronts on OFN or had another shopfront open on their phone. 

Awaiting answers to same questions from Customer 1

**Comment by luisramos0** [comment] 2020-09-03 13:49
This must be related to PR [#5905](https://github.com/openfoodfoundation/openfoodnetwork/pull/5905/files#diff-62b0038c43289c6a6c8ff6761fafb4cfR80) and issue #5936

One important thing I see is the time the line item was created:
![image](https://user-images.githubusercontent.com/1640378/92122584-84426100-edf3-11ea-8af6-77598b86b0a2.png)

Let's call this the "Chocolate Issue"! The Chocolate line item was created on the 19th of August.

One question I would ask the customer is if they logged in just before checkout.
When the user logs in with items in the cart, I think we are now merging the items on the cart with the items on the cart saved in the cart with their account. This implies the customer did add chocolate on the 19th of Aug.

The created_at of the order is the 2nd of September... I wonder if the order is really being merged (this is code from spree that we decorate to not do that).
To fix this problem (I am not sure this is the cause but it looks like) once and for all, I think we can just rename the method before_filter :set_current_order to something specific to OFN so that the spree code is never called. Thoughts?

This is complicated, I'd like to get @sauloperez or @Matt-Yorkley to also look at this.

**Comment by luisramos0** [comment] 2020-09-03 14:31
I thought of changing the controllerhelpers class or method name in OFN but then I realized the easier way is to remove it from spree like this: https://github.com/openfoodfoundation/spree/pull/47/files
What do you think?

**Closed** 2020-09-04 16:18 UTC
Labels: bug-s1
