### ISSUE TITLE
Payment status of 'Failed' but Stripe show a successful payment

### ISSUE THREAD

**Issue by lbwright22** [openfoodfoundation/openfoodnetwork#7130] opened 2021-03-16 10:03 UTC
## Description

Order R063002374
Enterprise Sole of Discretion (ID: )

Customer places order on 5th March and pays by Stripe.
Payment recorded for £121 on 5th March associated with the order is complete in Sole of Discretion's Stripe account
![sodstripe](https://user-images.githubusercontent.com/45104035/111290136-bf90d880-863d-11eb-9635-fd80a283171f.jpg)

Email sent to sole of discretion and customer states the payment was complete
![sodemailpayment](https://user-images.githubusercontent.com/45104035/111290197-d0414e80-863d-11eb-800c-bc9d78469ecf.jpg)

An adjustment was made to the order on 11th March
![sodadjustments](https://user-images.githubusercontent.com/45104035/111290263-e0f1c480-863d-11eb-8598-bf3f51cb5e77.jpg)

Payment status of the order is currently showing as failed
![sodpayments](https://user-images.githubusercontent.com/45104035/111290309-ed761d00-863d-11eb-993c-111e32c8816a.jpg)

## Expected Behavior

The payment status of an order on the OFN platform should reflect the status of the transaction in the hub's Stripe account.

## Actual Behaviour

The payment status of an order does not reflect the payment status of the transaction in the hub's Stripe account.

## Steps to Reproduce

1. Checkout paying via Stripe.
2. When Stripe redirects you back to OFN, quickly reload the page. The timing can be tricky here and it's difficult to tell if you got it right.
3. Check the order as admin and observe the state to be "payment" and the payment to be failed.

## Workaround

Never reload during payments. A developer can reset the state of the order.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
**bug-s2: a non-critical feature is broken, no workaround**
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

These categories don't fit well but s2 seems apt.

## Your Environment

* Version used: v3.5.12
* Browser name and version: Chrome 89
* Operating System and version (desktop or mobile):

## Possible Fix

This method ignores the possibility that the payment may be complete already:
https://github.com/openfoodfoundation/openfoodnetwork/blob/06deab9605ca67a024911f576d113e415be63475/lib/stripe/payment_intent_validator.rb#L25-L29

We should log the status here. If the intent is complete, we should either ignore it here or further up the caller chain. We don't want to capture again but gracefully return in this method:
https://github.com/openfoodfoundation/openfoodnetwork/blob/06deab9605ca67a024911f576d113e415be63475/app/models/spree/gateway/stripe_sca.rb#L36-L48

**Comment by lin-d-hop** [comment] 2021-03-16 10:19
Here is the relevant bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fc6b73a959e1c0017b8bb3e?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[search][0][type]=eq&filters[search][0][value]=bellicchi%40hotmail.com

**Comment by RachL** [comment] 2021-03-16 10:35
On my side I have something equivalent.

For hub 922 in French production order R720865210 shows a refund on stripe, but no refunds on OFN. Therefore the total of the order is wrong on OFN. In theory this can happen because the hub went directly on stripe to do the refund. Yet this hub claims they don't know how to do that.

**Comment by mkllnk** [comment] 2021-03-17 04:58
I'm trying to understand this issue. So chronologically:

- User#209456 checks out and pays via Stripe.
- The payment is successful and Stripe redirects the browser back to OFN.
- OFN tries to update the order but it doesn't complete.
- A Bugsnag error is triggered which indicates that `payment_intent_response.status != 'requires_capture'`. We don't know the status though.
- Stripe shows the payment as successful and OFN sent emails thinking that the payment was successful.
- I can only conclude that the payment was processed successfully but that we tried to process it a second time, didn't find it in the right state and therefore marked it as failed.

I looked in the server logs for the request and indeed found two requests for the same payment:
```
xxx.180 - - [05/Mar/2021:20:16:58 +0000] "GET /checkout?payment_intent=pi_1IRk4xxx&payment_intent_client_secret=pi_...
...
xxx.180 - - [05/Mar/2021:20:17:43 +0000] "GET /checkout?payment_intent=pi_1IRk4xxx&payment_intent_client_secret=pi_...
```

One minute later the user logged out.

I don't know why the request was sent twice. There are 45 seconds between the requests. My best theory is that the site was busy and the user tried to reload the page at some point. The UK server has slow response times regularly and one of the slow phases was in that time (according to Wormly).

Actions:

- Manually update payment record.
- Record payment intent status.
- Handle multiple payment intent requests gracefully.

**Comment by Matt-Yorkley** [comment] 2021-03-17 05:02
This issue has been linked to an error in Bugsnag
[**RuntimeError** in **checkout#update**](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5fc6b73a959e1c0017b8bb3e?event_id=604942e70072eaf382ac0000&i=gh&m=li)

**Comment by mkllnk** [comment] 2021-03-17 05:17
I just confirmed my theory with data from the database:
```
openfoodnetwork=> select * from spree_state_changes where created_at > '2021-03-05 20:15:00' and created_at < '2021-03-05 20:18:00';
    id    |   name   | previous_state | stateful_id | user_id |         created_at         |         updated_at         | stateful_type | next_state  
----------+----------+----------------+-------------+---------+----------------------------+----------------------------+---------------+-------------
 13153237 | payment  |                |     1677815 |  209456 | 2021-03-05 20:17:15.203644 | 2021-03-05 20:17:15.203644 | Spree::Order  | paid
 13153238 | shipment |                |     1677815 |  209456 | 2021-03-05 20:17:15.773123 | 2021-03-05 20:17:15.773123 | Spree::Order  | ready
 13153240 | shipment |                |     1677815 |  209456 | 2021-03-05 20:17:16.822011 | 2021-03-05 20:17:16.822011 | Spree::Order  | ready
 13153242 | shipment | ready          |     1677815 |  209456 | 2021-03-05 20:17:18.526524 | 2021-03-05 20:17:18.526524 | Spree::Order  | ready
 13153244 | shipment | ready          |     1677815 |  209456 | 2021-03-05 20:17:20.181403 | 2021-03-05 20:17:20.181403 | Spree::Order  | ready
 13153245 | order    | cart           |     1677815 |  209456 | 2021-03-05 20:17:22.253732 | 2021-03-05 20:17:22.253732 | Spree::Order  | complete
 13153254 | payment  | paid           |     1677815 |  209456 | 2021-03-05 20:17:33.75475  | 2021-03-05 20:17:33.75475  | Spree::Order  | failed
 13153255 | shipment | ready          |     1677815 |  209456 | 2021-03-05 20:17:33.791365 | 2021-03-05 20:17:33.791365 | Spree::Order  | pending
 13153256 | shipment | ready          |     1677815 |  209456 | 2021-03-05 20:17:35.677581 | 2021-03-05 20:17:35.677581 | Spree::Order  | pending
 13153257 | shipment | pending        |     1677815 |  209456 | 2021-03-05 20:17:37.268803 | 2021-03-05 20:17:37.268803 | Spree::Order  | pending
 13153258 | shipment | pending        |     1677815 |  209456 | 2021-03-05 20:17:39.255617 | 2021-03-05 20:17:39.255617 | Spree::Order  | pending
...
```

**Comment by mkllnk** [comment] 2021-03-17 05:24
I'll execute this code on UK production to fix this issue:

```rb
Spree::Order.find_by_number("R063002374").payments.first.update(state: "completed")
Spree::Order.find_by_number("R063002374").update(state: "complete")
```

After that, the shipment will be ready and the payment will display "credit owed". I guess that's because the shipping fee has been waived with the adjustment.

**Comment by mkllnk** [comment] 2021-03-17 05:26
@lbwright22 Does the order now display as expected?

**Comment by lbwright22** [comment] 2021-03-17 10:10
@mkllnk yes, thank you .
I actually refunded the payment last night for the user manually (ie via their Stripe account) and so have documented this on the order.

**Comment by luisramos0** [comment] 2021-03-23 19:57
It doesnt look like a problem in stripe sca code, it looks like a checkout controller problem. I say this because the payment state updates are 17 seconds apart. Looks like a user action.
Looks like the user payed successfully but when redirected back to OFN, the checkout code did not recognize the redirect and showed the checkout page again. This sent the user to try again.

So, I think the root cause could be in checkout_controller#valid_payment_intent_provided? where the redirect url data is validated.
I hope this is useful.

**Comment by luisramos0** [comment] 2021-03-23 20:00
I think we need better logging in the checkout_controller for these cases. I'd add a log message to valid_payment_intent_provided? with the data used there params and the last_payment.

**Comment by mkllnk** [comment] 2021-03-25 03:10
> Looks like the user payed successfully but when redirected back to OFN, the checkout code did not recognize the redirect and showed the checkout page again. This sent the user to try again.

I believe that the page was loading very slowly and the user clicked reload before seeing the result. So the request was sent twice without any error in the display.

I tried to write a spec for this but the controller actually checks at the beginning if an order is already complete. From that I can guess that the first request wasn't finished yet when the second request started. A while ago I tried to solve race conditions with pessimistic locking. We deactivated the spec recently though because it was failing. People thought that the spec was wrong for newer Rails versions but maybe our locking is wrong and the spec was correctly failing. I'm looking into that.

**Comment by mkllnk** [comment] 2021-03-25 03:14
Uh, actually, this action happens in `edit` while we lock the order only when calling `update`. This is because Stripe redirects to a `GET` request and that routes to the `edit` action. We probably should have a different controller for this. But with this implementation we should lock on `edit` as well.

**Closed** 2021-03-29 11:36 UTC
Labels: bug-s2
