### ISSUE TITLE
Pointer on map does not reflect changes made on address

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#2765] opened 2018-09-24 09:18 UTC
## Description
If you change an enterprise's address, the pointer on the map does not change position.

## Expected Behavior
The pointer should be at the correct address

## Actual Behavior
The pointer stays at previous address, although the profile of the enterprise still shows the correct address.

## Steps to Reproduce
1. Log in as an admin or an enterprise manager
2. Change the company address in profile
3. See changes on map

## Animated Gif/Screenshot
On French production the profile says demo hub is located in the town of Metz (east of France):
![image](https://user-images.githubusercontent.com/6525576/45944647-33147a80-bfeb-11e8-93a1-3452221fdd12.png)

But on the map, it is still located in Paris (previous address):
![image](https://user-images.githubusercontent.com/6525576/45944706-5f2ffb80-bfeb-11e8-93b2-a42596fe1363.png)

## Context
Seen while testing #2738 

## Severity
bug-s4: it's annoying, but you can use it
I think not so many enterprises will change their addresses

## Your Environment

* Version used: v1.18
* Browser name and version: Firefox Quantum 62
* Operating System and version (desktop or mobile): Ubuntu 18 LTS and Android mobile

**Comment by RachL** [comment] 2018-09-24 10:38
@lin-d-hop what are the steps to make it use the correct address ?

**Comment by myriamboure** [comment] 2018-09-24 18:29
I can confirm @RachL and @lin-d-hop I just rested with various addresses all checked in Google Maps first, they are not picked up. Confirm the bug.

**Comment by mkllnk** [comment] 2018-09-24 21:55
@RachL What about new enterprises? Doe they work? You have some enterprises on the map already, so there is either a way to place an enterprise on the map or it used to work and got broken recently.

**Comment by sstead** [comment] 2018-10-12 04:36
This bug has come up for me a few times while trying to 'clean up' the Australian database. Things I'm encountering:
- If a profile was initially created with a faulty address (e.g. a typo which prevents pin placement), but then the address is corrected, the pin won't get dropped at the new location. There is no pin for the enterprise. 
- I'm finding that for past profiles which had an address such as "corner Smith Street and Green Street" they are correctly placed, but for new profiles they system is not placing these addresses. This makes it hard to place enterprise such as farmers markets which are held in parks/schools (no street number)
![image](https://user-images.githubusercontent.com/10843056/46848095-a9124180-ce33-11e8-8502-2645cb47a362.png)
- Pins generally being off the mark on addresses. I'm not sure if this only occurs after a profile was first created with an incorrect address (these are the cases I'm seeing), but I'm finding when I try to move pins they don't go to the right place.
![image](https://user-images.githubusercontent.com/10843056/46848231-6f8e0600-ce34-11e8-8faa-d52228afbef5.png)

**Comment by myriamboure** [comment] 2018-10-15 13:13
I also hit again the issue while creating a demo group to convince a local territory to join OFFrance... demo is happening on Thursday :-( The enterprises are not shown on the group map. We created 4 enterprises and NONE of them has a pin on the map, either it is not shown at all, either it is in the middle of the ocean... There is no workaround and all enterprises and instances are affected, so this is S2.

**Comment by mkllnk** [comment] 2018-10-16 05:05
Whenever we change the address of an enterprise, it calls `geocode` on its Address object. The geocode method is provided by the geocoder gem version 1.1.8.

Geocoder supports several geocoding services and uses Google Maps by default. Since Google shut down public access to their API we now don't get locations any more:

```
> enterprise.address.geocode
Google Geocoding API error: over query limit.
=> nil
```

We may be able to pass our API key on:

```ruby
# config/initializers/geocoder.rb
Geocoder.configure(
  api_key: ENV.fetch('GOOGLE_MAPS_API_KEY')
)
```

**Comment by kirstenalarsen** [comment] 2018-10-16 08:36
Thanks @mkllnk - can you fix this for @myriamboure before her demo on Thursday? or knowing that you are likely to not work weds, could someone else do it - @Matt-Yorkley @luisramos0 ?

**Comment by luisramos0** [comment] 2018-10-16 10:12
"I hope that it doesn't become too expensive."

Looking at Matomo FR and AU have 8k visits per month. If 2 to 5% of visits go to the map, you get between 160 and 400 requests per month.
According to https://developers.google.com/maps/documentation/geocoding/usage-and-billing
It's 5 usd per 1000 requests, you pay between 0.8 and 2usd per month.

**Comment by myriamboure** [comment] 2018-10-16 11:16
Thank you @kirstenalarsen :heart: yes if one of you can do it for French production server today that would be great ! @pacodelaluna for info or if you have time but needs to be done today (or tomorrow morning latest) so @luisramos0 or @Matt-Yorkley might have more time in the coming hours. We need also to merge this and upgrade to master after that (we gonna test now the PR). Do we need to open any account for the billing? I can do it but I don't know what/where to do it. The dev who will do it can contact me on Slack and we can organize that together. We will see later one to switch to Open Street Map, one priority at a time.

**Comment by sauloperez** [comment] 2018-10-16 11:45
> Activate Geocoding API in developer console.

could we doc this?

**Comment by pacodelaluna** [comment] 2018-10-17 10:43
@myriamboure Sorry I missed the notification but @sauloperez ping me on Slack! I am adding Payment method on Google Account to avoid this issue as suggested.

**Comment by daniellemoorhead** [comment] 2018-10-19 03:44
Ok, so where to next with this issue? I assume France is updated and the demo went marvelously (because how couldn't it when @myriamboure is in the house!), and we need it included in the documentation for new instances  set up. Is there anything beyond that?

**Comment by daniellemoorhead** [comment] 2018-10-19 03:46
Actually, I see the PR. It's in code review. 

Nothing to see here...

![](https://gifimage.net/wp-content/uploads/2017/10/move-along-nothing-to-see-here-gif-7.gif)

**Closed** 2018-10-22 14:44 UTC
Labels: bug-s2

**Comment by sineadfenton** [comment] 2018-10-23 19:18
![](https://github.trello.services/images/mini-trello-icon.png) [Producer icon not displaying in correct place on map](https://trello.com/c/OcuKCv5W/268-producer-icon-not-displaying-in-correct-place-on-map)

**Comment by sineadfenton** [comment] 2018-10-23 19:18
![](https://github.trello.services/images/mini-trello-icon.png) [Producer icon not displaying in correct place on map](https://trello.com/c/OcuKCv5W/268-producer-icon-not-displaying-in-correct-place-on-map)

**Comment by sineadfenton** [comment] 2018-10-24 18:45
![](https://github.trello.services/images/mini-trello-icon.png) [Map issue](https://trello.com/c/1O1QP1Vm/269-map-issue)

**Comment by lin-d-hop** [comment] 2018-11-09 10:35
Is there a place where the google console changes are documented @mkllnk?

**Comment by sigmundpetersen** [comment] 2018-11-09 10:53
Maybe here @lin-d-hop https://github.com/openfoodfoundation/ofn-install/wiki/Google-Maps ?
