### ISSUE TITLE
Snail when running Payment Totals Report 

### ISSUE THREAD

**Issue by emilyjeanrogers** [openfoodfoundation/openfoodnetwork#4977] opened 2020-03-12 02:34 UTC
## Description

Aus customer Prom Coast Wholefoods Collective are getting a snail when running the Payment Totals Report. Snail is generated when including a date more than 12 months before today (11th March 2020). The snail comes up when trying to run this report as both a Manager of the Customer and as Superadmin. Have also tested for other Enterprises with no problems.

## Expected Behavior
Report should run successfully for any date range.

## Actual Behaviour

It shows a snail. The error has been logged:
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5e68221b18c0ef00177d7370

## Steps to Reproduce

1. Log in as Superadmin (or add yourself as a manager for Prom Coast Wholefoods Collective)
2. Go to Reports
3. Select Payment Totals Report
4. Set Date range for a date including more than 12 months prior to today's date  
OR  
set date range to include dates prior to 11th March 2019

## Workaround
No workaround.

## Severity
S2

bug-s2: a non-critical feature is broken, no workaround

## Possible Fix
It looks like a payment method is missing. The safe navigation operator `&.` may help here:

```
NoMethodError · undefined method `name' for nil:NilClass 
lib/open_food_network/payments_report.rb:106
```
```rb
proc { |orders| orders.sum { |o| o.payments.select { |payment| payment.completed? && (payment.payment_method.name.to_s.include? "EFT") }.sum(&:amount) } },
```

**Comment by RachL** [comment] 2020-04-17 14:50
@emilyjeanrogers I already had this because there was a particular problem with an order. Have you tried narrowing the search and see for which set of dates the error occurs?

**Comment by kirstenalarsen** [comment] 2020-06-09 22:52
@emilyjeanrogers is this an s2? or is an s3 - not sure why it got downgraded? Seems likely connected to https://github.com/openfoodfoundation/openfoodnetwork/issues/5572

**Comment by lin-d-hop** [comment] 2020-06-10 06:40
Very unlikely to be connected to #5572

#5572 is specific to payment methods report and is related to an order not having a payment associated. It is a data corruption issue and renders this report totally unusable ALWAYS for any user that is associated with that order.

I fail to see how they can be related.

**Comment by emilyjeanrogers** [comment] 2020-06-17 01:48
I have reproduced this error today and been able to narrow it to a more specific date range. The snail occurs for any Payment Totals Report run for Prom Coast Food Collective prior to March 12th 2019.

**Comment by sigmundpetersen** [comment] 2020-06-17 12:38
The prioritization was discussed here https://openfoodnetwork.slack.com/archives/CAVTM01QB/p1587133992174900

However, @filipefurtad0 has observed this when testing #5595 and I think is in favor of upping it to an S2. Filipe, maybe you could summarize your findings here?

**Comment by lin-d-hop** [comment] 2020-06-17 12:46
There are two things happening here:
1) Inconsistent data on orders
2) Reports that won't load if there is not payment

@sauloperez helped us find the orders with inconsistent data in #5572 so we could remove them and make the report work again. 

I would say that you could do an s2 for that, and that since this seems to occur very rarely we could make an s3 for the underlying issues.

**Comment by filipefurtad0** [comment] 2020-06-17 15:19
Yes, as @sigmundpetersen points out, I bumped into this issue checking something else.

I agree with points 1. and 2. @lin-d-hop. So I tried to narrow it down to such cases, and cancel these orders, so they don't appear in the reports - and this works to some extent, but not always. There is something else breaking the report other than the integrity of orders (points 1. and 2.) and the time-frame (in the description of this PR). 

For example, in staging-katuma, these orders were placed in May, and have a cash payment, customer info, they seem like regular orders:
![image](https://user-images.githubusercontent.com/49817236/84913603-a1984680-b0b2-11ea-9d83-3c7f2c5b9a4d.png)

However, setting the date range in the Payment Totals to include only these orders breaks the report anyway. 

In staging-UK I tried to cancel out apparently broken orders, but same thing - report was broken anyway for all the dates. So, going day-by-day, I narrowed down to this day, which has the order(s) breaking the report:
![image](https://user-images.githubusercontent.com/49817236/84916189-a7435b80-b0b5-11ea-8670-944dc1b6a9f5.png)

I can't explain these so far - these look like perfectly regular orders - so that makes me argue for an S2. Perhaps this is what @emilyjeanrogers observed by increasing the time range to generate the report?

**Comment by filipefurtad0** [comment] 2020-06-17 15:42
Below are the entries on DB from the 3 orders from staging-uk. I can't spot anything unusual here either. Thoughts?

```
   id   |   number   | item_total | total |  state   | adjustment_total | user_id |         created_at         |         updated_at         |       completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |               email               | special_instructions | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id 
--------+------------+------------+-------+----------+------------------+---------+----------------------------+----------------------------+---------------------------+-----------------+-----------------+---------------+----------------+---------------+-----------------------------------+----------------------+----------------+----------+-----------------+----------------+-------------+---------------
 701995 | R254238635 |      80.00 | 80.00 | complete |             0.00 |  208000 | 2020-05-17 21:36:38.923795 | 2020-05-17 21:37:13.847052 | 2020-05-17 21:37:13.56881 |          424100 |          424102 |         80.00 | ready          | paid          | filipefurtado+haciendac@gmail.com |                      |         201389 | GBP      | 127.0.0.1       |         203888 |        7395 |        208000
```

``` 
 id   |   number   | item_total | total |  state   | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |               email               | special_instructions | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id 
--------+------------+------------+-------+----------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+-----------------------------------+----------------------+----------------+----------+-----------------+----------------+-------------+---------------
 701994 | R740217288 |      20.00 | 20.00 | complete |             0.00 |  208000 | 2020-05-17 21:36:03.377958 | 2020-05-17 21:36:38.844988 | 2020-05-17 21:36:38.596334 |          424097 |          424099 |         20.00 | ready          | paid          | filipefurtado+haciendac@gmail.com |                      |         201389 | GBP      | 127.0.0.1       |         203888 |        7395 |        208000
```
``` 
id   |   number   | item_total | total |  state   | adjustment_total | user_id |         created_at         |         updated_at         |        completed_at        | bill_address_id | ship_address_id | payment_total | shipment_state | payment_state |               email               | special_instructions | distributor_id | currency | last_ip_address | order_cycle_id | customer_id | created_by_id 
--------+------------+------------+-------+----------+------------------+---------+----------------------------+----------------------------+----------------------------+-----------------+-----------------+---------------+----------------+---------------+-----------------------------------+----------------------+----------------+----------+-----------------+----------------+-------------+---------------
 701993 | R822265384 |      40.00 | 40.00 | complete |             0.00 |  208000 | 2020-05-17 21:35:07.035622 | 2020-05-17 21:36:03.254395 | 2020-05-17 21:36:02.868835 |          424091 |          424095 |          0.00 | pending        | balance_due   | filipefurtado+haciendac@gmail.com |                      |         201389 | GBP      | 127.0.0.1       |         203888 |        7395 |        208000
```

**Comment by sauloperez** [comment] 2020-06-18 08:41
Thanks this Sherlock work! it made my job a piece of cake!

It turns out that the only failure in UK, Katuma and FR stagings is

```
NoMethodError (undefined method `name' for nil:NilClass):
  lib/open_food_network/payments_report.rb:106:in `block (3 levels) in columns'
```

Particularly, from these orders from UK staging that you report, it's only due to 701994. Its only payment has no payment method :warning: I'll check payments to Prom Coast Wholefoods Collective now.

**Comment by Matt-Yorkley** [comment] 2020-06-18 09:49
Nice, we can just adapt it for soft-deletion :smile:

**Comment by sauloperez** [comment] 2020-06-18 09:51
yes, that's what I'm about to do but first I'm finding out whether this is the issue this hub is experiencing. It could also be because a) payment is missing b) payment has a missing method.

**Comment by sauloperez** [comment] 2020-06-18 10:15
@emilyjeanrogers I couldn't find of the potential root causes directly affecting orders distributed by either Prom Coast Food Collective or Prom Coast Food Collective Wholesale Market.

However, I did find that [these](https://gist.github.com/sauloperez/b0ca5cf0178af709908ee9d18adb4b06) orders are affected by a deleted payment method. So, I'm moving on with the fix.

**Comment by sauloperez** [comment] 2020-06-18 10:26
For the record, this is how I found the potential root causes of this failure:

### Complete orders without payment                                                             
                                                
```sql
select count(*)                                                                                 
from spree_orders                                                                               
left join spree_payments on spree_payments.order_id = spree_orders.id
where spree_payments.id is null
and spree_orders.state = 'complete';
```                   

### Payments whose method is deleted
                                                
```sql
select count(*)                                                                                 
from spree_payments                                                                             
inner join spree_payment_methods on spree_payment_methods.id = spree_payments.payment_method_id
where spree_payment_methods.deleted_at is not null;
```   

### Payments without method        

```sql
select count(*)
from spree_payments
left join spree_payment_methods on spree_payment_methods.id = spree_payments.payment_method_id
where spree_payment_methods.id is null;
```

**Comment by emilyjeanrogers** [comment] 2020-07-16 03:40
> @emilyjeanrogers I couldn't find of the potential root causes directly affecting orders distributed by either Prom Coast Food Collective or Prom Coast Food Collective Wholesale Market.
> 
> However, I did find that [these](https://gist.github.com/sauloperez/b0ca5cf0178af709908ee9d18adb4b06) orders are affected by a deleted payment method. So, I'm moving on with the fix for it.

@sauloperez So, does this mean we have identified a fix that is helpful in other cases, but not in the case of this specific customer (Prom Coast Food Collective) ie. reports will still fail for this customer?

**Comment by sauloperez** [comment] 2020-07-22 08:06
sorry for my late response @emilyjeanrogers . Yes, that's it. Chances are that they were affected by this and we missed it though. Is this still happening?

**Comment by RachL** [comment] 2020-08-07 07:48
@emilyjeanrogers Pau will be on holiday tonight and won't look at this for the next 2 weeks, so I'm unassigning him and move this back to all the things. Please feel free to close if this is solved.
Or raise to s2 if this is really a blocker. Thanks!

**Comment by emilyjeanrogers** [comment] 2020-08-12 01:40
I have reproduced this error again today and it hasn't changed. Attempting to run the Payment Totals Report for Prom Coast Food Collective for any date prior to March 12th 2019 will generate a snail. 

![Screen Shot 2020-08-12 at 11 38 49 AM](https://user-images.githubusercontent.com/47620442/89965548-74ba7700-dc90-11ea-9ae6-ba100fd54897.png)

**Comment by lin-d-hop** [comment] 2022-11-21 16:37
Closing. Can be reopened if it pops up but I suspect resolved in reports refactorring

**Closed by lin-d-hop** 2022-11-21 16:37 UTC
Labels: bug-s3
