### ISSUE TITLE
Back from view cart empties cart

### ISSUE THREAD

**Issue by RohanM** [openfoodfoundation/openfoodnetwork#1213] opened 2016-11-18 00:19 UTC
## Description
When shopping **as a guest**, my cart get emptied if I hit the "backward" browser button.

## Expected Behavior
If I am logged in, or if I am shopping as a guest, if I put products in my cart and go to the basket page, when hitting the browser "backward" button, my cart should remain with the products I put in it, and I should just be sent back to the shopfront page.

## Actual Behavior
When I shop as a guest, I add products and then go to cart page, if I hit the browser "backward" button, I'm sent back to shopfront page BUT my cart is emptied.

## Steps to Reproduce
1. Do not log in, and open any shopfront. Add products to your cart and click on "view cart" button (either from bottom of product lists, or small right corner "cart" button)
2. When on cart page, hit the browser "backward" button and see what happens.

## Animated Gif/Screenshot
https://www.useloom.com/share/1e4de54bbbf04944ac8147e2d15232ce

## Context
Reported originally from Rohan when testing previous spree upgrade, re-tested and updated by Myriam.

## Severity
S2, all guest users are affected, and placing order is a big feature, and pretty big UX impact that has no really workaround?

## Your Environment
- Version used: 1.10.1
- Browser name and version: Version 64.0.3282.167 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Ubuntu 16.04 LTS

## Possible Fix
?

**Comment by daniellemoorhead** [comment] 2016-12-01 23:25
@lin-d-hop is this is something worth of the UK Current backlog?

**Comment by lin-d-hop** [comment] 2016-12-08 12:22
Again, UK could take a look if this hasnt been assigned in Aus yet? 
No assignees, but moved to a milestone... what does that mean? :-)

**Comment by lin-d-hop** [comment] 2016-12-08 12:22
@Matt-Yorkley another one to keep an eye on and pick up if @daniellemoorhead is happy.

**Comment by daniellemoorhead** [comment] 2016-12-09 00:09
Full steam ahead @lin-d-hop @Matt-Yorkley :)

**Comment by Matt-Yorkley** [comment] 2016-12-09 16:24
I've had a quick look at this and can't replicate the bug. Any tips?

I have noticed that a hub's payment options have to be set to "testing", "development", "production" or "staging", and if there are no payment methods assigned to a hub with the correct environment set, it assumes the hub has no payment options. Then when I click view cart I get bounced to the home page with an error message about the hub being "temporarily closed", which is not very informative as the hub definitely appears to be open. It seems it happens when the hub either has no valid payment options or no valid delivery options. Maybe that check should be made before the user starts interacting with the hub's products rather than after the cart is filled up. Maybe this is a separate issue though.

**Comment by lin-d-hop** [comment] 2016-12-19 16:34
@RohanM Do you think this might have been caused in line with @Matt-Yorkleys thoughts above? If so now covered in #1343. 
If not would be great to get some more detail.

**Comment by Matt-Yorkley** [comment] 2016-12-19 18:48
It doesn't appear to be the same issue. I can't replicate this bug though, so it's hard to figure out.

**Comment by lin-d-hop** [comment] 2017-11-23 11:46
Noticed this one while looking through issue list.
Has anyone else experienced?
I feel like this would be pretty big priority if happening at outlined in the description so inclined to close it unless anyone is experiencing....?

**Comment by daniellemoorhead** [comment] 2017-11-23 21:11
@sstead are you able to confirm if this is still occurring? If you can't replicate it then feel free to close the issue :-)

**Comment by myriamboure** [comment] 2018-02-28 16:01
Pretty easy to replicate, I modify the first thread to expose clearly the issue and will delete useless comments here to clean it up a bit.

**Comment by stveep** [comment] 2018-03-25 13:43
So I was able to reproduce this a few times, on chrome, via both "edit cart" buttons. However now (with no changes to the code) it seems to work fine...I've cleared cookies, disabled cache and still ok. Even when I try on other browsers (Firefox, Safari) it is working ok.

I've also attempted to reproduce this in a feature test - but again, this works ok:
https://github.com/stveep/openfoodnetwork/commit/644bd7b93d40691406abf99187d69c48de3dec58

I'm not that familiar with how the cart is persisted so just thought I'd check weather anyone else has ideas before I dig into it. I planned to see if the clear function was being called as I went through the navigation above (there are various points where this can happen, such as changing OC) - but obviously not being able to reproduce it is not helping with this.

On the gif above, the login screen also pops up after pressing back - this doesn't happen for me.

**Comment by myriamboure** [comment] 2018-03-26 09:15
I reproduced again https://www.useloom.com/share/ab9547267f3f48b99612325bd54ca4b7 and interestingly I tried that time both as logged in (first) and then logged out. You will see in both cases it goes back to the cart status that was previously. When logged in I had 2 items in my cart from before, add 2, goes to cart, then hit "previous page" button and you will see the cart is back to 2. I can't help more on the tech side but seems easy to reproduce, don't understand why you can't @stveep ...

**Comment by stveep** [comment] 2018-03-26 22:18
Hah ok I think I have a start on this. In Chrome I now get the bug. In Firefox (v 59.0.1) though, everything seems to work ok. In Chrome, the bug goes away if I open the javascript console (this was obviously why I couldn't reproduce when investigating further!). I had caching disabled when using dev tools - if I turn caching back on, the bug reappears. So I guess it probably reloads a cached version of the shop page or something. Any easy suggestions from anyone about how to stop that? Otherwise I will investigate more...

It's hard to debug bugs that don't happen when you use the console 😆

**Comment by sauloperez** [comment] 2018-03-27 10:46
Does refreshing the page fix the problem? do you see the items in your cart then?

**Comment by myriamboure** [comment] 2018-03-27 10:58
If I click on backward and refresh the page it doesn't change anything items are still lost and not anymore in cart.

**Comment by sauloperez** [comment] 2018-03-27 11:17
what if you perform a "hard" refresh pressing `Ctrl + Shift + R`? we need to clarify if this is just browser cache or something else.

**Comment by myriamboure** [comment] 2018-03-27 13:54
I tried this and no change, products still don't reappear in the cart...

**Comment by myriamboure** [comment] 2018-04-18 12:27
Any progress on this @stveep ? We said it's s2 bug so we are want to solve it quickly... if the problem is deeper we can rediscuss but we need to agee on a path to achieve the user experience we want to offer (cart should remain if you hit backward button).

**Comment by daniellemoorhead** [comment] 2018-04-27 06:40
@stveep 

![bueller](https://user-images.githubusercontent.com/10949052/39348181-5f5bf852-4a39-11e8-9253-fee61a107e7a.gif)

If life got too crazy and there's no time at the moment then let's unassign you for now and then you can pick it (or something else) up when you are back online. OK?

**Comment by stveep** [comment] 2018-05-07 10:36
I am a bit out of my comfort zone with this but after a bit of shameless Googling have implemented this solution to force the page to refresh:

https://jacopretorius.net/2014/01/force-page-to-reload-on-browser-back-in-rails.html

This seems to have fixed it for me. It might make navigation generally feel a bit less slick as the page will reload everything each time so needs some testing. Let me know what you think about it.

A few more notes from this issue in case they are useful:
- The order is still in the database (in "cart" stage) after the back button is pressed, so it's a front end issue.
- If you go back and put more items in the cart after it gets emptied, it overwrites the original order in the database. I think this is linked to the session?
- The Angular Cart service is also emptied of the added items when the back button is pressed.

**Comment by daniellemoorhead** [comment] 2018-05-11 05:56
@mkllnk @oeoeaio @sauloperez @enricostano @Matt-Yorkley @KeirOsborn @HugsDaniel and everyone else actively helping out in the developer community, any assistance you can offer @stveep with the above (considering what has already been discussed in the PR #2268) would be most gratefully accepted.

![help](https://user-images.githubusercontent.com/10949052/39908920-b4de6fb2-5533-11e8-8f66-86231391537a.gif)

**Comment by stveep** [comment] 2018-05-12 15:39
Just doing a bit more investigation - this does seem to be Chrome specific. I don't get the bug in Firefox or Safari (On UK production site and in dev). Anyone know any differences in browser behaviour that could explain it?

In Chrome: Adding items and clicking edit cart results in currentOrder (injected in the script tag) with correct items (on edit cart page). Then pressing back empties the cart, and the currentOrder injection has no items [this is used to populate the Angular cart service]. Refreshing this page doesn't result in the items being in the cart, but the same order id is injected (with no items).

In Safari and Firefox: Adding items and clicking edit cart results in currentOrder (injected in the script tag) with correct items (on edit cart page). Pressing back does not empty the cart, but the resulting page has the incorrect currentOrder script (no items). Refreshing the page results in the correct currentOrder (and correct items in cart).

**Comment by myriamboure** [comment] 2018-05-14 07:27
I just test in Firefox @stveep and I get exactly the same result as in Chrome: on French production I put items in cart and go to cart, then press the "backward" button, it empties cart. I tried on uk production as well and get the same result. @sstead has tested your fix #2268 and it seems to work, which is good! I'm not sure how to test about performance, I had a check on Aus staging and don't see that it is slowing down the process really, but maybe it does, I have nothing to compare, we need data for that I guess. How can we measure impact of this PR on performance? @sauloperez @mkllnk ? Cause if it doesn't impact performance we can just merge Steeve PR I guess as it solves the problem...

**Comment by mkllnk** [comment] 2018-05-15 05:26
We can't measure the real impact on performance without using it in production. And the only data I have for that is response time.
![screenshot from 2018-05-15 15-15-38](https://user-images.githubusercontent.com/3524483/40038156-fbaf628e-5853-11e8-9fb4-6f45fc6dffaf.png)

I'm not sure if other instances have other tools to measure their server load.

So I think we can merge Steve's pull request and see what happens. If it's a problem, we can either revert it or do a better implementation.

**Comment by sauloperez** [comment] 2018-05-15 06:09
I agree. We set up Skylight to monitor performance some time ago and we can watch it to spot any performance degradation.

**Comment by daniellemoorhead** [comment] 2018-05-25 00:48
Reopen as @stveep has an alternative fix that may be better.

**Comment by myriamboure** [comment] 2018-07-14 09:40
Ok I'm closing this as solution has been merged and alternative other solution has not been approved, the problem seems solved anyway so if we see performance issues we will open another issue.

**Closed by myriamboure** 2018-07-14 09:40 UTC
Labels: bug-s2
