### ISSUE TITLE
"Order Adjustments" and "Order Total" not centered in Order/Edit (Firefox only)

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5955] opened 2020-08-27 11:18 UTC
## Description

On Edit Order page, some elements are not centered.

This happens on Firefox, but is working on Chrome.

## Expected Behavior

"Order Adjustments" and "Order Total" should be centered?

## Actual Behaviour

They are not

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/928628/91436012-f35a0b80-e86f-11ea-9f96-8cb641d1f94b.png)

## Your Environment

* Version used: 3.2.4
* Browser name and version: Firefox 78.1.0esr (linux)
* Operating System and version (desktop or mobile): Desktop

**Comment by kirtirajsinh** [comment] 2020-08-27 11:36
I want to work on this issue. How can I get started?

**Comment by sigmundpetersen** [comment] 2020-08-27 11:46
Welcome @kirtirajsinh 🎉 Please go ahead 😊 
You can submit a PR with your suggested solution and it will be reviewed.
Have a look at [Getting started](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/GETTING_STARTED.md) if you haven't setup your environment yet.

**Comment by sigmundpetersen** [comment] 2020-09-23 07:28
Hey @kirtirajsinh how are you doing with this issue?
Please don't hesitate to ask if you have any questions and you can connect with us on [slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) if you want to chat directly 👍

**Comment by tsara27** [comment] 2020-10-06 01:40
Hello @sigmundpetersen 

I am sure that I can help working on this issue. Can you please assign me this issue if no one take this issue?

Thanks!

**Comment by sigmundpetersen** [comment] 2020-10-06 08:33
Yes @tsara27 thank you.
Assigning you and moving to In Dev 👍

**Comment by RachL** [comment] 2020-10-28 13:38
Hello @tsara27 I'm just checking: are you still planning to work on a PR for this issue? Thanks :)

**Comment by tsara27** [comment] 2020-10-28 14:06
> Hello @tsara27 I'm just checking: are you still planning to work on a PR for this issue? Thanks :)

Hello!

Yes, I will work on this tomorrow. Still working on other issues related with unit price error, because there are few broken specs that should be fixed. 

I am sorry for the delay. My husband is sick and it spreads  almost to  the whole family members.  :cry:

**Comment by RachL** [comment] 2020-10-28 14:20
don't feel any pressure @tsara27 I was just checkin. Take all the time you need! Good luck to your husband.

**Comment by sigmundpetersen** [comment] 2020-10-28 14:26
One advice @tsara27 would be to pick up one issue at a time from the backlog. This way they won't get "stuck" in the In Dev column for too long. (We are using the Zenhub browser extension to manage our pipe if you haven't installed it already).

Anyway, thank you for all your contributions so far 🎉

**Comment by tsara27** [comment] 2020-10-28 14:28
> don't feel any pressure @tsara27 I was just checkin. Take all the time you need! Good luck to your husband.

Thank you @RachL!



> One advice @tsara27 would be to pick up one issue at a time from the backlog. This way they won't get "stuck" in the In Dev column for too long. (We are using the Zenhub browser extension to manage our pipe if you haven't installed it already).
> 
> Anyway, thank you for all your contributions so far

Great advice! Thank you, @sigmundpetersen, for that. I will do that next time.

**Comment by tsara27** [comment] 2020-10-30 00:30
Hello @RachL  and @romale 

I could not reproduce this issue. Here's the screen on my local development environment.
 
![image](https://user-images.githubusercontent.com/3486644/97646197-ab2eb380-1a81-11eb-8937-7644e79ec23e.png)

Probably it's solved already.

**Comment by tsara27** [comment] 2020-10-30 04:19
I am sorry. The problem is only of firefox. I changed my browser and the alignment was broken.

**Comment by romale** [comment] 2020-10-30 07:58
Hi @tsara27 , thank you for your work!
Yes, the Chromium has no such problem

**Closed** 2020-11-05 17:33 UTC
Labels: Hacktoberfest, bug-s5, good first issue
