### ISSUE TITLE
Can't create a product that has been created and deleted by another user

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#3983] opened 2019-06-27 16:07 UTC
## Description
User (or super admin) cannot create a product that has been previously created and deleted by themselves,   or by another user.

 ## Expected Behavior
User and super admin should be able to create new products -  even if these are the same products as a different user previously deleted.  User A has no knowledge for what products User B had previously created and deleted -  so they can't possibly avoid the same product name.

 ## Actual Behaviour

If a user tries to re-create a product they previously deleted from their product list -  they get a slug error.
If a different user tries to create a product that was previously in a different user's product list,  they get they slug.

If a user tries to create a product that currently exists in another user's product list ?  (haven't tested yet)?

## Steps to Reproduce

1. as enterprise user or as super admin,  fill in the details to create a new product with a name that could hot have been used previously. I used the product  'never before 1'
2. Delete that product
3. Logout,  login as a different user and try to create a product with the same name -  get the slug.

I then went further and did it again:   I created 'never before 2'  OK.  deleted it.   logged out.  Logged in as super admin.  Tried to create 'never before 2'  on a different product list -  got the slug. 

## Severity
I think this is S1 -  isn't it?   Being able to create products for users is critical in my view.  Although - a work around is to clone and edit existing products (which seems to work).  

## Your Environment

* Version used:  2.1 (I think?)
* Browser name and version:  Chrome
* Operating System and version (desktop or mobile):  Win 10
* OFN Platform instance where you discovered the bug, and which version of the software they are using.   OFN-CAN

**Comment by tschumilas** [comment] 2019-06-27 16:16
Closed this as soon as I opened it.  I figured it out.  In the price field of the new product creation screen,  user must enter just the digit -  as in "2"  for $2.00     I was entering '2.00'   and kept getting the snail. Sorry.

**Comment by tschumilas** [comment] 2019-06-27 16:32
So I've re-opened.  I thought the problem was about the decimal in the price but it doesn't seem to be that.  As a user,  I cannot create a product.  Screenshot  of product creation screen below -   everything filled in correctly I think (?).  Hitting create gets the slug.    I still don't know why I managed to create a product as super admin a few minutes ago -  and now I can't.     Still experimenting.   Someone tell me if I'm missing something.  (Weird -  I've created hundreds of products - thought I knew what I was doing.)

![can't create new product](https://user-images.githubusercontent.com/13171778/60283611-91062380-98d7-11e9-9abb-e00db2c6166f.png)

**Comment by tschumilas** [comment] 2019-06-27 16:49
As super admin - have tried:  2 different producer's lists -   and tried changing:  shipping category -   made no difference;   tax category - made no difference.  I also tried dropping the decimal from the price -  didn't work (but I think this DID work earlier -  very strange).   All these trials  have been with a 'items' product type.  I'll try different product types now.  And I'll try other logins.

**Comment by tschumilas** [comment] 2019-06-27 16:49
Sorry - still learning github -  accidently closed when I submitted my comment.  Bear with me as I learn please.

**Comment by tschumilas** [comment] 2019-06-27 17:07
Update -  have tried to create new products with multiple logins and enterprises,  including super admin login -  and am continually getting the slug.   And,  I can't figure out why -  one time -  a few minutes ago,  i was able to create a product as super admin,  and now I can't.  I've varied: shipping methods, tax categories -- no difference.   I AM able to clone products as user and as super admin.  So the work around at the moment is to clone and edit existing products versus creating new ones.

**Comment by RachL** [comment] 2019-06-27 17:33
From some quick tests with my producer account, I hit an error 500 only once and I didn't took a screenshot of the content I've put it :sob: I have to go now, but will test again later.

**Comment by RachL** [comment] 2019-06-27 17:41
@tschumilas ah wait I have another idea : is it possible that you already have a product called "test product" and that in all your tests you've put in "test product" as a name. Because if this is it, it causes an error 500 / slug. I was meaning to open an issue about this in order to have a clean error message but didn't do it yet. I thought the case for it to happen for real users was very small.

**Comment by tschumilas** [comment] 2019-06-27 17:49
Its a good thought -  I used 'test product' several times.  BUT I first had this issue,  and the user who reported it had this issue,  creating new products with other names.      I also have had the experience that it suddenly works (both as super admin and as a user) and I can't replicate.  I just created a product for my farm -  no problem.  And then couldn't do a second one.   But you could be on to something -  there are a lot of products and maybe I'm replicating.  I'm going to do some testing with completely new product names.      I also had the strange experience of deliberately prompting an error on the product entry screen (like missing some of the information)  and then fixing it,  and it worked - the product was created.

**Comment by tschumilas** [comment] 2019-06-27 18:04
So - just managed to create a product  - logged in as a user (not super admin),  completely new product - never used by any enterprise before that I know of.   Maybe it is something to do with previously created products -  even if they were deleted previously?   Will test this.

**Comment by tschumilas** [comment] 2019-06-27 18:17
I think you are right @RachL .  I created one for Garden Party Flower farm called 'never before 1'.    It created fine.   Then I deleted the product.   Then I tried to create a new product with the same name and same producer -   got the slug.    I just want to test a few more variations of this -  but i think its possible all the problems are because users have tried to create products that existed previously.  the user reporting the bug was trying to create 'bok choy'.   Its a common product -  so its possible it had been created and deleted previously.   When I tried to replicate her error,  I was using my own farm and 'allium' -  which I think is also quite possibly a product that existed previously.    So - now I'll test a few more variations of this,  and update this error description.

**Comment by tschumilas** [comment] 2019-06-27 20:05
Did the above testing again (created a first ever product, deleted it,  tried to create it with another login -  and slugged).   But I also learned:   If I change the name (like add a number or character) -  it will create,  and then I am able to edit the name after the product is created fine.    So -  I tried to create 'spearmint' and slugged.  Assumed it must have been created and deleted before.   I created 'spearmint1'.  Fine.  I edit the name to 'spearmint'.  Fine.   now spearmint exists again.  So this is a workaround.

**Comment by sigmundpetersen** [comment] 2019-06-27 21:34
Could this possibly be caused by the same as #3844 which is fixed by #3915? From the PR's release notes

"Fixed: Creating new products could fail if a product with the same name was deleted before."

Can be verified by someone checking error logs to see if they match.

**Comment by mkllnk** [comment] 2019-06-27 22:53
Yes, that sounds exactly like the issue I fixed in https://github.com/openfoodfoundation/openfoodnetwork/pull/3915.

**Comment by RachL** [comment] 2019-07-12 05:09
@tschumilas the latest release was deployed to Canada. I've tested this and it is solved, so I'm closing this. Please reopen if you think otherwise.

**Closed by RachL** 2019-07-12 05:09 UTC
Labels: bug-s1
