### ISSUE TITLE
Changes to incoming/outgoing products lists triggering 'failed to update order cycle' error

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/openfoodnetwork#9292] opened 2022-06-10 10:58 UTC
## Description

Banc Organics are seeing an error when they try to make changes to their incoming and outgoing product lists on order cycles with schedules attached. The error 'Failed to update order cycles' is triggered _but_ changes are in fact saving. The user raised this as they thus believed the changes were not being saved and it was only from testing we realised they were. This is disconcerting for the user.

## Expected Behavior

User should be able to add and remove products and have them save successfully when an order cycle has a schedule attached without an error message being displayed.

## Actual Behaviour

Attempts to save any changes to product lists when a schedule is attached are triggering an error message, making it seem to user that changes are not being saved. This is only happening when a schedule is attached.

## Steps to Reproduce

1. Go to Banc Organic's order cycles
2. Select edit on an open order cycle with a schedule attached
3. Add an in stock product to the incoming and outgoing products list, click save _(N.B. christmas box in screen capture below is not in stock, use 'Test product' under Banc Organics producer to see product displayed on shopfront)_
4. Observe 'failed to update order cycle' error triggered
5. Observe in stock product now displaying on shopfront

## Animated Gif/Screenshot

![Kapture 2022-06-10 at 11 32 12](https://user-images.githubusercontent.com/100226210/173048510-1f2ddea1-8f18-4309-824c-81da02297322.gif)

## Workaround

Product list changes are indeed being saved, but are triggering the error. Removing the schedules and clicking save, then making product list edits does not trigger the error, which suggests the issue may be with schedules.

## Severity

bug-s4: it's annoying, but you can use it

Assigning as S4 as the concern is that this could mask other issues, i.e. whilst changes are saving despite the error being shown, should there be a 'real' error the user will not be aware of this. It is also unnerving for the user to not have confirmation that changes to a large product list are being saved.

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used: UK prod
* Browser name and version: Chrome & mozilla both showing same bug
* Operating System and version (desktop or mobile): Mac & windows

**Comment by amidaOFN** [comment] 2022-06-14 03:27
Southern Harvest (Australia) has today also reported this issue when creating order cycles with schedules.

**Comment by BethanOFN** [comment] 2022-08-01 09:42
Also getting reports of this issue from other UK customers (Down Farm)

**Comment by abdellani** [comment] 2022-10-21 07:52
I failed to reproduce the problem

https://user-images.githubusercontent.com/16113997/197142907-1923f660-0b58-4262-9ab7-a89b364731b4.mp4

**Comment by amidaOFN** [comment] 2022-12-09 01:19
This issue has become more of a problem for the user who reported it to us. 

She is finding that some changes actually don't save, and she is then having to double check whether the error message is real or false. 

The user has confirmed the problem only occurs on OCs with schedules attached.

Environment is Firefox on Linux.

The user also got two different error messages when updating the OC - screenshots below.

The first was 'Failed to update Order Cycle' - in this case the changed dates of a cloned order cycle did not save. 

The second error was when she changed the dates again and saved. She got a different error message 'Oh no, I was unable to save your changes', but upon refreshing the page, the changes had saved. 

![Screenshot-from-2022-12-08-17-04-58](https://user-images.githubusercontent.com/95382608/206600865-340bf7fa-9485-49be-be7e-2e343c2b2c3d.png)
![Screenshot-from-2022-12-08-17-05-30](https://user-images.githubusercontent.com/95382608/206600894-dff39fbe-7b40-4301-8556-3a583ea9dc12.png)
![Screenshot-from-2022-12-08-17-06-14](https://user-images.githubusercontent.com/95382608/206600926-ec636f0a-16e6-49b6-8555-3f93d1c0f748.png)
![Screenshot-from-2022-12-08-17-05-59](https://user-images.githubusercontent.com/95382608/206600957-faf40fb2-4c32-4719-b619-63de5999a6ec.png)

**Comment by filipefurtad0** [comment] 2023-02-24 14:31
I've observed what I believe could be the same error in staging, when trying to tag an order cycle with a schedule which was in use for a closed order cycle. I think it is a follow-up from [this issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/9100).

For the dev picking this up:

Following the [Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/633f427adcc1580009612df1?filters[event.since]=30d&filters[error.status]=open) leads me to think this was introduced with [this code change](https://github.com/openfoodfoundation/openfoodnetwork/pull/9174).

**Comment by audez** [comment] 2023-03-02 15:30
I think this one is a duplicate:
https://github.com/openfoodfoundation/openfoodnetwork/issues/9959
I'll close it, these are the things I did test:

> 

    The OC only triggers the error if it is linked to this specific schedule (hebdo Beauvoir) and its subscriptions. If the OC is linked to another schedule from the same hub, there will be no error.

    The subscriptions corresponding to this schedule could be the origin of the issue. Only 3 are active, and 2 are weird with a order total amount = 0 (I couldn't reproduce this)

    I wasn't able to reproduce the case in staging.

**Closed** 2023-03-08 14:45 UTC
Labels: bug-s3, AU
