### ISSUE TITLE
Get Product and Product tax status in Order Cycles Supplier Totals report

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#9963] opened 2022-11-09 10:12 UTC
## Description
**- As a Enterprise (Hub)
**- On page: Reports: Order Cycle Supplier Totals
**- I want to be able to do: 
easily identify the correct tax that needs to be reported in payments to Producers. 

I am not concerned about fees, I just want to know if the Producer is registered for tax, and if the product is taxable. This information is contained in the Producer profile (in Aus 'Charges GST - Yes or No' in Enterprise Settings) and the Tax Category connected with the Product. 

This information currently sits in a number of places, but there is no combo that just tells me which producers need to report tax i.e. Xero report has the product tax but doesn't list the Producer

## Acceptance Criteria & Tests
1. Create / use a Producer that is 'GST registered' and one that is not
2. For each Producer, create / use a Product that has GST and one that is not
3. Open order cycle, create order with all four products
4. Go to Reports, Order cycle - Supplier Totals
5. Two additional columns for each row. the first called "XX TO BE CONFIRMED" says True/False whether the Producer has ticked the 'charges Gst /tax' setting. The second lists the Tax Category of the Product

**Comment by RachL** [comment] 2022-11-09 10:38
Closing as duplicate of #9962

**Closed by RachL** 2022-11-09 10:38 UTC
Labels: Potential Papercut
