### ISSUE TITLE
Actions buttons are displayed on several lines in admin

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#6006] opened 2020-09-09 08:39 UTC
## Description

This problem was probably introduced here: https://github.com/openfoodfoundation/openfoodnetwork/pull/5811

We used to have all buttons on the same line from left to right.

## Expected Behavior

![image](https://user-images.githubusercontent.com/6525576/92575238-60b26700-f288-11ea-9ab3-c735c81b5747.png)

## Actual Behaviour

![image](https://user-images.githubusercontent.com/6525576/92575267-690aa200-f288-11ea-96cf-37a88bdf15f2.png)

![image](https://user-images.githubusercontent.com/6525576/92577249-bd168600-f28a-11ea-8b23-791620eb226c.png)

![image](https://user-images.githubusercontent.com/6525576/92577275-c30c6700-f28a-11ea-825e-0c9b4c005e93.png)

## Steps to Reproduce

1. Log in as an admin
2. Go to `/admin/orders?q[s]=completed_at+desc`
3. clic on the pencil to edit an order
4. See the buttons are piled up

## Animated Gif/Screenshot

See above

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment
* Version used: v3.2.6
* Browser name and version: all browsers
* Operating System and version (desktop or mobile): Desktop

**Comment by sigmundpetersen** [comment] 2020-09-09 08:43
Duplicate of #5956 ?
Maybe we can merge information if there is something missing from the original?

**Comment by RachL** [comment] 2020-09-09 08:53
ah thanks @sigmundpetersen I've missed it! Merging the two!

**Comment by luisramos0** [comment] 2020-09-09 21:20
@sigmundpetersen #librarian :superhero_man:

**Comment by andresgutgon** [comment] 2020-09-13 10:44
While working on this fix I noticed the layout is not adapted for mobile
![image](https://user-images.githubusercontent.com/49499/93016037-7d1f0e00-f5be-11ea-87f7-3652271bdb0d.png)


What I mean adapted is not that is perfect on mobile. I mean it doesn't resize. Is missing this tag in the head of the HTML
``` html
<meta content="width=device-width, initial-scale=1" name="viewport">
```

With this meta tag it allows html to resize on small screens:
![image](https://user-images.githubusercontent.com/49499/93016067-bb1c3200-f5be-11ea-81c2-47d6ce0c845b.png)

The css needs work to be usable on mobile. But I wanted to know if we don't have that meta tag for some reason.

**Comment by luisramos0** [comment] 2020-09-17 10:19
Hey @andresgutgon great finding, I think no one has ever tried to make the backoffice work on mobile! Can you create a PR with that html tag? It's a great improvement even if there will still be lots of trouble using the BO on mobile. Thank you!

**Closed** 2020-10-07 20:24 UTC
Labels: Hacktoberfest, bug-s4, good first issue
