### ISSUE TITLE
As a shopper, I can have a better feedback on cancelled orders

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#9304] opened 2022-06-14 08:45 UTC
## Description
**- As a:** shopper
**- On page:** `/account#/orders`
**- I want to be able to do:** See when orders are cancelled

-  Replace the "view" column by "status" column,
-  Add a link on confirmed status only, to view the order.
-  Remove links from order numbers
-  Add a flash error after cancelling

Previously: 

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/b98859ed-e603-4f06-a03e-70536c124ae2)

New mockup:

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/bc9a04e2-bc48-40e3-a389-5a3781024176)

also note the transaction tab is out of scope here.

## Acceptance Criteria & Tests

*Scenario 1 : the shopper just visit the page*

1. Cancelled orders are visible and cannot be displayed
2.  Completed orders can be displayed by clicking on the status
3. Links are removed from order number

*Scenario 2 : the shopper is the one cancelling the order*

1. As a shopper cancel an order
2. See a flash message confirming the order is completed
3. See the correct status on your account
4. check that you still get the usual cancelling email.

**Comment by jibees** [comment] 2022-07-01 06:59
hi @binarygit 👋 
And welcome to OFN! Sure I can assign it to you! Feel free to ask for question, learning HAML shouldn't take to much time ;)

**Comment by binarygit** [comment] 2022-07-03 05:33
Hey @jibees
The flash message after shopper cancels an order is not displaying. I think that this function is responsible for displaying the flash: 

```js
    # Callback when a new flash message is pushed to flash service
    show = (message, type)=>
      if message
        $scope.flashes.push({message: message, type: typePairings[type]})
        $timeout($scope.delete, 10000)
```

But this function is not being called. I tried to follow the program execution using debuggers and execution does not stop here after order is cancelled. Execution does stop here for other flashes, like the one after a user logs in.

I'm not sure but I think that this method hands over the flash to Angular. 
```ruby
  def inject_rails_flash
    inject_json "railsFlash", OpenStruct.new(flash.to_hash), Api::RailsFlashSerializer
  end
```
This method is called and the flash contains the right value. 

I am not sure what I am missing, so I thought I would share what I learned about the codebase here in hopes I might get some insight.

**Comment by binarygit** [comment] 2022-07-03 05:46
Strangely,
if I change the code in ` /app/views/shared/_flashes.html.haml` to display the flash, like so:
```ruby
#flashes
  - if flash.any?
    - flash.each do |type, msg|
      %alert.animate-show{"data-controller": "flash"}
        %div{type: "#{type}", class: "alert-box #{type == 'error' ? 'alert' : type}"}
          %span= msg
          %a.small.close{"data-action": "click->flash#close"} ×
```
The flash is displayed correctly after an order is cancelled. But for the other flashes, expect after cancelling an order, TWO instead of one flash is displayed.
I am guessing that this file is here to display flash _after_ the front end has been converted from Angular to Hotwire. But it seems to me, that somehow for order cancellation a function call to use the Angular flash is disabled(?)

**Comment by jibees** [comment] 2022-07-04 09:45
Hey @binarygit 

I'm not that familiar of this part of code, but what I've saw:

- `shared/flashes` file render `flashes` object (event if it's `flash` in the ruby code, like `flash[:error] = I18n.t(:orders_could_not_cancel)`

```
replace("#flashes", partial("shared/flashes", locals: { flashes: flash }))
```

- Flash message render when redirecting to `main_app.order_path(@order)` but not when redirecting to `request.referer` (ie.  spree.account_path `/account#/orders` aka.)


--> _conclusion_: i'm wondering if this is not related to the way that we use a link.
 - In account setting (`account#/settings`) we use a submit and it works
 - In credit cars (`/account#/cards`), on card deletion, we use a `window.location.reload()` after the delete

**Comment by binarygit** [comment] 2022-07-06 01:03
@jibees Thanks for your input :) I was able to make the flash render on redirect using
```
 render operations: cable_car.redirect_to(url: request.referer || main_app.order_path(@order))
 ```
 This is what the page looks like rn
 
![orders](https://user-images.githubusercontent.com/87677429/177440547-e35c7707-8b95-4518-8af7-f309e7834dae.png)

I wanted to ask if these requirements are to be applied to the Open Orders table too, as you can see I have only changed the styling in Past Orders table 

1. Replace the "view" column by "status" column,
2. Add a link on confirmed status only, to view the order.
3. Remove links from order numbers

**Comment by jibees** [comment] 2022-07-06 07:52
Let's ask @openfoodfoundation/train-drivers-product-owners ;)

**Comment by binarygit** [comment] 2022-07-06 09:10
@RachL Hey! :smile: 

![openorder](https://user-images.githubusercontent.com/87677429/177513236-4840a2b3-ad51-4a83-84cc-57faddaa53d8.png)

is this fine? I just removed the links from Order Number in Open Orders. I realized the other two requirements don't apply here as there's no status column.

**Comment by binarygit** [comment] 2022-07-06 09:19
Have already added the flash error. Will open a PR now. Thanks!

**Closed** 2022-08-02 08:10 UTC
Labels: papercut
