### ISSUE TITLE
When creating an OC in SuperAdmin, incorrect products (not belonging to the set coordinator) are loading 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#496] opened 2015-04-15 00:05 UTC
When logged in as SuperAdmin, I tried to create an order cycle for Amber Creek, setting them as the coordinator. But when the order cycle page loaded, products from Andrew Jones Organics came up, not Amber Creek's products. 
- There are not E2E permissions between Amber Creek and Andrew Jones.
- Amber Creek is a producer, selling own.
- When logged in as a non-superadmin, this was not a problem.
- At the time of trying to create this order cycle, there were no payment methods attached to Amber Creek.... could be linked to #495

**Comment by myriamboure** [comment] 2018-03-01 14:07
@sstead I'm closing this issue as it is very old and not easy to reproduce, couldn't reproduce it. So let's see if that reappears, and as only super admin no big impact anyway on users.

**Closed by myriamboure** 2018-03-01 14:07 UTC
Labels: australia, bug
