### ISSUE TITLE
Product Table Behaviour: Enable Edit/Delete/Clone/ Create Product + Variant  

### ISSUE THREAD

**Issue by jaycmb** [openfoodfoundation/openfoodnetwork#7204] opened 2021-03-24 16:58 UTC
**- As a enterprise user**

**- On page:** Product List Page https://openfoodnetwork.org.uk/admin/products 

**- I want to be able to do:** 

For each of my products and its variants,...

...1**. I want to be able to select to edit **(products + variants), **delete** (products + variants) & **clone** (products only)
(Designs _**Producer - edit fields**_ https://www.figma.com/file/kBvKYXnaNU0thSnKJUoyup/Product-List-UI-uplift?node-id=10%3A1352 )

**1.1.Edit**
- Scenario 1: User has not selected a checkbox, clicks on a **product´s or variant´s individual action dropdown** and chooses 'edit' -> user gets to product or variant detail page
- Scenario 2: User **edits 'inline'** on page input fields/dropdowns (and saves via _"save changes"_ bar or dropdown process described below below)

**1.2.Delete** 
- Scenario 1: User has not selected a checkbox and clicks on **individual action dropdown** of a product or variant and chooses 'delete' -> product or variant gets deleted
- Scenario 2: User has selected checkbox  of one or multiple products / variants and clicks on **global action dropdown** and chooses 'delete' -> product(s) or variant(s) get deleted

**1.3.Clone**
- Scenario 1: User has not selected a checkbox and clicks on **individual action dropdown** of a product (not variant!) and chooses 'clone' -> product gets cloned
- Scenario 2: User has selected the checkbox of one or multiple products(not variants!) and clicks on **global action dropdown** and chooses 'clone' -> product(s) or variant(s) get cloned

**...2. I want to be able to create a new variant.**

- When user clicks on _"+New Product"_ Button, user gets directed to _New Product Page_ (Old UI Page) 
- When user clicks on _"+New Variant"_, a line gets added to the product on _Product List page_ (@Kirsten to confirm)

**Product + Variant Block**
![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/3d02fc0d-62ff-4c55-ae71-8c7ab231ee43)![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/27fb4e55-704b-4306-a940-f174913cb52d)

(Designs _**Product- create first product**_ https://www.figma.com/file/kBvKYXnaNU0thSnKJUoyup/Product-List-UI-uplift?node-id=0%3A1)

## Acceptance Criteria & Tests

1. User can add a new product or an new variant 
2. User can edit existing products' / variants' input fields 'inline' or on product edit page. _Editing behaviour of the various dropdowns and inputs is described in detail in Eriol´s comment below_

**3. (Global) actions dropdown**
  3.a If multiple products and or variants are checkmarked, the global action button only enables _delete, edit_ and _clone_ are disabled
3.b If one or multiple products are checkmarked, the global action button enables _delete,  and _clone_ , edit is disabled
3.c If a variant is checkmarked, the individual action displays _edit_ and _delete_ only  

4. User has to save changes. 
4a. When a user saves via the bottom bar (@Kirsten to be confirmed when?),  'saving message' is displayed or if the user cancels, the product list page refreshes.
4b. The saving process for **editing info in dropdowns is different to the 'bottom bar' process**: 'while the dropdown controls are 'open' you change the details and when you click 'outside' of the box it saves and changes in the UI.
5. Validation if user changes the 'weight type', e.g. from items to weight (g), that the value field needs to be updated -> field becomes blank with an '-' in the field and giving them a red outline, see screenshots in Eriol´s comment under **Unit**
6. Some more specific behavior is described in Eriol´s comment (_producer, unit, on hand etc fields_)

**Designs are here:**
https://www.figma.com/file/kBvKYXnaNU0thSnKJUoyup/Product-List-UI-uplift?node-id=10%3A1351

**Comment by jaycmb** [comment] 2021-03-24 17:13
@kirstenalarsen (and maybe @Erioldoesdesign) this needs your input on the behavior, as I could not  find indication in the designs 

What is supposed to happen if a user clicks on the 'dropdown arrows' we have for 
- Producer
- Unit
- On Hand
- Category
- Tax Category
- Inherit Property

![image.png](https://images.zenhubusercontent.com/5f2c695b310b603896851306/32496d98-459b-455f-b530-38ef91a0990c)

Do all of them open a **dropdown** with 'fixed options'?
I assume that for Producer, Category or Tax Category, these are pre-defined on enterprise level but should weight/volume or 'on hand' not be something that can be free input / edit in line like the _price_ field?

Also, can the users edit these fields by clicking on them?
Or do they have to select the product by 
1. Click on checkmark on the left hand side
2. Then choose 'Edit' in the _Actions Field_?

And does lead click on 'Edit' lead to the product/edit page or is editing happening always inline now on the product list page?

**Comment by kirstenalarsen** [comment] 2021-03-26 08:13
I think this is a design question - I think/thought I had seen this in designs but perhaps that was earlier version

for the Weight (g) it should be the pre-defined options in the system, and include a text field if Items is selected - I'm sure I've seen this somewhere

The 500g I think opens with an editable field where you would change the 500 to another value

The 5000g should be automatically correcting to display 5kg,  as  the system currently does, we wouldn't intend to lose this functionality

The onhand field opens to an editable field with the option to turn on 'on demand' - I'm almost certain I've seen this somewhere .. have you @Erioldoesdesign ? if not I am either losing my mind (possible) or @mariocarabotta may be able to help?

They SHOULD NOT have to select checkbox and choose edit in actions, I don't think there is a group edit in actions and is not in scope to be at the moment

**Comment by jaycmb** [comment] 2021-03-29 16:25
> They SHOULD NOT have to select checkbox and choose edit in actions, I don't think there is a group edit in actions and is not in scope to be at the moment

So to be 100% clear:
does that mean editing happens **purely** on the product list page in future, there is no product edit page anymore (https://openfoodnetwork.org.uk/admin/products/avocado-38/edit)?

Or the user can chose to 
- either edit 'inline' on product list page by click on the field or
- select a variant by checkbox and then the action 'edit' which leads to the product edit page

Asking because that also affects the AC of
https://app.zenhub.com/workspaces/dev-pipe-54b840c6a249c8781446d4b2/issues/openfoodfoundation/openfoodnetwork/7203

**Comment by Erioldoesdesign** [comment] 2021-03-31 10:00
> What is supposed to happen if a user clicks on the 'dropdown arrows' we have for
> 
> Producer
> Unit
> On Hand
> Category
> Tax Category
> Inherit Property

I'm going to drop screen grabs of what happens in UI uplift when you click on these fields and then write out what happens or use screengrabs of the current BO to explain :)

### Producer 

UI uplift:

![Screenshot 2021-03-31 at 09.32.36.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/6cfdb3ed-2b6a-4e5c-9f3e-ff4e16ec2702)

Should show a list of producers that are available for the user to 'swap' the product to:

![Screenshot 2021-03-31 at 09.30.48.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/842e48ea-e4d3-42a1-a1f1-707a5ddf198e)

User then gets the bottom confirm changes bar (old):

![Screenshot 2021-03-31 at 09.30.55.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/5e031bcb-3949-42fb-81ef-4dea2f8c5eac)

Bottom confirm changes bar (new UI uplift):

![Screenshot 2021-03-31 at 09.47.04.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/e43d395e-ebda-434f-9efc-42cb0c1e9a59)

When a user saves the bottom bar displays a 'saving message' or if the user cancels the product list page refreshes.

![Screenshot 2021-03-31 at 09.54.17.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f5725fbb-5b81-498b-9982-8d3721b66917)

### Unit
When you click Unit you get a tick list of different unit weights to change to:

![Screenshot 2021-03-30 at 16.28.33.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/e6d16980-5a05-418b-acc7-450477904169)

We discuss this briefly Jana, but we talked about the current BO *not indicating when a variant has had a weight change that the text entries remain 'connected to the old wieght type' so we spoke about making the field blank with an '-' in the field and giving them a red outline as above

Here's an example of the current UI where I change Quiche from 'items' to 'weight (g)'

![Screenshot 2021-03-31 at 09.54.45.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/d0c1c2bd-b457-40a7-b9ff-ec9caf3b02ef)

![Screenshot 2021-03-31 at 09.54.52.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/2a0dc200-889c-468e-8b30-962505b5c433)!

[Screenshot 2021-03-31 at 09.55.12.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/ec379214-fa91-4875-82d6-587b89fb71b6)

If I don't noticed that the Quiches are now all 1g (because they were 1 item) I can save them as 1g...So we wanted to include validation in the product list to avoid that mistake:

![Screenshot 2021-03-31 at 09.57.37.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/58d392e3-0e4a-40e7-856c-96733a7a469c)


### On Hand
On hand is new and on click, brings up this visual:
![Screenshot 2021-03-31 at 10.03.08.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/02f12565-f304-4158-9ee4-9d00ad50c6f9)

Where users can change the stock levels e.g. 'On hand' or make the product on demand which is the new version of the existing 'unlimted'. 
The process for saving this info when changed is different to the 'bottom bar' process as above and I believe was intended by Mario to be a 'while the dropdown controls are 'open' you change the details and when you click 'outside' of the box it saves and changes in the UI.

### Category

Is a drop down but with a search
UI Uplift
![Screenshot 2021-03-31 at 10.18.24.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/7b9eec64-8ecb-46ed-a59d-31d69880fad7)

Older UI
![Screenshot 2021-03-31 at 10.06.01.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/b4a625ee-22c3-476e-a6db-08a823bc9110)


### Tax Category

Simple drop down tick list:

![Screenshot 2021-03-31 at 10.28.11.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/10c063db-fb0a-4441-87f6-832675ddcf57)

### Inherit Property

Simple on/off switch:
![Screenshot 2021-03-31 at 10.23.57.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f6d19f0b-cb8c-4276-8bb9-3b266ac1ac92)!


### Edit page

So I understand the confusion here with how to access a single edit page for a product when there is new functionality to multiselect products via teh checkboxes. Here's how I think it should work:

**Scenario 1**
1. I do not select any check boxes
2. I click the 'actions' drop down on a single parent product
![Screenshot 2021-03-31 at 10.37.44.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/39db8cc1-1370-470b-a135-3e90ed9b3332)

3. I see a drop down with: Edit, Clone, Delete:
![Screenshot 2021-03-31 at 10.51.25.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/308c4925-135a-455e-8ca9-5f986ac7809b)

4. I click 'Edit' 
5. I am taken to the seperate 'edit product page' that is away from the prouct list.

If the above is done with a **Variant** then the user does not see 'Clone' they only see 'Edit and Delete':

![Screenshot 2021-03-31 at 10.53.54.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/8151d64c-ba8f-43a9-9883-1be989f12c5f)

**Scenario 2**
1. I select **more than 1 checkbox** of either parent products or variants
2. The individual action buttons inline with each product are 'deactivated'
3. The user click on the 'global action button':
![Screenshot 2021-03-31 at 10.56.03.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/1632ace7-faac-4dff-b8ae-2c3b30db9b4b)

4. The only option current via global action button is 'Delete':
![Screenshot 2021-03-31 at 10.58.24.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/4ced98c6-1793-4c59-9206-63fa473af66a)


### Summary notes:

I think one thing that wasn't considered was the 'saving bar' that pops up at the bottom. There's design's in the file for that now but it wasn't something that was in Mario's original files and I beilieve it's something to design away from, there will be a bit of a strange transistion where some edits save automatically by changing them and some still need the confirmation from the bar - but that's the nature of a project like UI uplift, there will be some functional disparity before full roll out.

We know that a 'flow' for BO users to multi-select parent products and avriants and then 'edit' from global actions and cycle through the 'deeper' edit product pages is wanted, but we've already decided it's out of scope for 'Feature Parrot'
The next round of UI uplift would need to pick one of this follow up critical work flows to improve.

**Comment by dacook** [comment] 2021-07-20 05:28
I have a comment about images which I hope is useful. Hide/move it if necessary!

I think it would be really handy for users to be able to **upload an image with one click, or drag/drop** on this bulk edit page. I think the image icon could be used for both cases. A standard file upload element (`<input type="file">`) can handle this natively I think -- the 'Attach files' section of GitHub comments is a great example of this:
 - Contains a dotted line which helps indicate a droppable area
 - When dragging a file over it, it highlights to confirm it's a droppable area.
     - I'm sure I've seen other sites that highlight the droppable area when you start dragging a file over _any_ part of the window, which is even better.
     - Also I've seen a plus icon appear over the droppable area when dragging; I think that's a great visual indicator also.
 - You can also click on it to select a file
 - It shows uploading status
 - It uploads automatically, without having to make any more clicks to confirm.
    - I think there should be a confirmation if an image exists, but skip the confirmation if no image yet.

![Screen Shot 2021-07-20 at 3 25 54 pm](https://user-images.githubusercontent.com/4188088/126266439-6335b2a4-3c95-4d9a-9111-fb1bdc205c11.png)

**Comment by jaycmb** [comment] 2021-08-17 14:20
There have been some questions around the Saving of Edits.
As it will be confusing if some changes will require the user to confirm via the "save changes" button at the bar on the bottom while others will automatically apply we should unify.
Either
1)  all changes require the user to confirm (they can edit multiple things, while the bar is shown but have eventually to hit _"Save changes"_
or
2) All edits are saved automatically.

If we go towards 2) automatic save, the UX would need to be slightly different than currently: 
**Currently:** when user clicks on dropdown and ticks a different option → dropdown closes immediately and save changes bar appears 
**New:** when user clicks on dropdown and ticks a different different option → dropdown should remain open so user can see what has been changed. They need to click somewhere outside to close the dropdown and this will automatically save changes at the same time.

-> We might need an alert _"Your changes have been saved"_ so the users knows

**Closed** 2022-02-24 17:33 UTC
Labels: blocked
