### ISSUE TITLE
BE & FR enterprises images missing

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5844] opened 2020-07-30 11:59 UTC
## Description

Examples on BE:

https://openfoodnetwork.be/magasin-du-monde-oxfam-wereldwinkel-brussels/shop#/shop

https://openfoodnetwork.be/electron-libre-services/shop#/shop

Damn. On this one a **product image i**s missing as well:

https://openfoodnetwork.be/au-champ-des-colibris/shop#/shop

Examples on FR: 

https://www.openfoodfrance.org/le-jardin-de-deux-main/shop#/shop

https://www.openfoodfrance.org/fans-de-carottes1/shop#/shop

https://www.openfoodfrance.org/les-jardins-de-champlecy/shop#/shop

## Steps to Reproduce

See URL example :point-up:

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.2
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by RachL** [comment] 2020-07-30 12:12
@luisramos0 I've updated with examples on FR and BE. I found one occurence where a product image didn't showed up on BE even with the fix you did. Maybe there is still something wrong?

**Comment by RachL** [comment] 2020-07-30 12:23
@luisramos0 re my comment on slack that it was not all enterprises. I didn't find enterprises on FR with images at all yet. But on BE this one has one:

https://openfoodnetwork.be/symbiooz-la-terre-nous/shop

Strange.

**Comment by luisramos0** [comment] 2020-07-30 13:48
that enterprise in BE is the exception, that image is on the server, not S3.

Enterprise images are being fetched from the server where there are no images (except that enterprise in BE). I need to find out how to make it fetch enterprise images from S3.

**Comment by luisramos0** [comment] 2020-07-30 14:08
So, I have cleared cache and restarted BE and the everything looks good.

I did the same for FR but the enterprise imageas are still being fetched from the local server, i.e., broken.

**Comment by luisramos0** [comment] 2020-07-30 14:12
oh gosh, in FR I had to stop unicorn and start (stop start is not exactly the same as restart). The enterprise images are now back.
I believe this was a cache problem resulting from the original problem #5841 
I think we can close this one and fix the config issue in #5841

**Closed by luisramos0** 2020-07-30 14:12 UTC
Labels: bug-s2

**Comment by RachL** [comment] 2020-07-30 14:24
@luisramos0 tahnk you ❤️ it looks good!

However this shop on BE still has 1 product image missing: https://openfoodnetwork.be/au-champ-des-colibris/shop#/shop

Should the BE team just ask them to re-upload it?

**Comment by luisramos0** [comment] 2020-07-30 14:47
Hmm... I am not sure what's happening. We have another product without image just below on that shop... maybe the problem is not properly fixed...

**Comment by luisramos0** [comment] 2020-07-30 14:51
ok, these images are on the server... they were uploaded on the 24th of June (BE v3 rollout date) or today, when AWS S3 was not working.
I think it would be a bit of work to recover this ourselves. If we can ask the user to re-upload it will be easier for us :-(

**Comment by luisramos0** [comment] 2020-07-30 14:55
in BE, these are the enterprises that may have this problem:
 id  |            name             
-----+-----------------------------
 102 | Box gaume
 151 | Coopérative Bio de Hesbaye
 138 | Ferme de l'Escafène
 116 | Coprosain S.C.
 139 | Raviolart
 100 | Ferme de la Tortue BIO
 118 | Ferme de la Coulbrie

I dont see any images in FR so maybe we dont have this problem in FR.

**Comment by RachL** [comment] 2020-07-30 15:20
ping @SophieDuponcheel these enterprises ☝️ might have product images missing on _some_ products. We might not be able to find them again. Can you see with these users if they can re-upload them easily?
