### ISSUE TITLE
[mobile ux] Browser error message shown on Desktop, not shown on Mobile.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1299] opened 2016-12-07 02:05 UTC
## In a feature branch or master?
This can be merged directly to master 🎉  

## Description

The browser error message shown on Desktop (telling Users that they can only add items to a single shop/cart) isn't shown in Mobile. The cart just empties as the User moves between shops.
Device: Mobile/tablet
Recommendation: (Understand this is a low use/edge case right now)
![image](https://cloud.githubusercontent.com/assets/10843056/20952041/a7e00d84-bc7d-11e6-92dc-9d008f899bef.png)

**Comment by myriamboure** [comment] 2018-03-29 11:08
Not a bug as "mobile ready" not yet a feature we really offer, too many things bugging on mobile. So captured in icebox https://community.openfoodnetwork.org/t/customers-easily-go-through-the-whole-placing-order-process-on-mobile/1244 and new feature "mobile ready" started to be worked on, so closing for now.

**Comment by luisramos0** [comment] 2020-05-08 14:38
this is working in the old safari of my iphone 4 :-)
![index](https://user-images.githubusercontent.com/1640378/81416492-b7c0f780-9141-11ea-9ed0-aed83a089fb0.jpeg)

Maybe broken in some other devices/browser?
I'll move this to test ready. This needs some investigation in browserstack.

**Comment by sigmundpetersen** [comment] 2020-05-08 15:56
Tested and error also shown on S9/Android/Firefox

**Comment by daniellemoorhead** [comment] 2020-05-09 05:53
Awesome, I’ll test this next week.

**Comment by daniellemoorhead** [comment] 2020-05-15 03:42
No longer happening, tested on iPhone SE / safari as well. Closing.

**Closed by daniellemoorhead** 2020-05-15 03:42 UTC
Labels: bug-s3
