### ISSUE TITLE
Admin cannot create shipping or payment method for users 

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/openfoodnetwork#4009] opened 2019-07-04 14:51 UTC
## Description

Admin cannot create payment or shipping methods for an enterprise

## Expected Behavior

Admin should be able to create shipping/payment methods for any enterprise

## Actual Behaviour

Logged in as admin -  created payment and shipping methods (screenshot below) - saved -  no error.   Opened an order cycle for the enterprise.  Shopfront displays the closed message (screenshot below) and error message says the enterprise does not have shipping/payment methods.        Added a different login to the enterprise.  Logged in as the non-admin user,  added shipping/payment methods.  Deleted the original methods.  Shopfront opens fine.

## Steps to Reproduce

1.logged as admin -  create payment & shipping methods for enterprise
2. open OC -  see that the shop will not open,  see error statement
3.add non-admin user to the enterprise as manager
4.Non-admin user adds new payment/shipping methods and deletes the first ones -  shop functions fine.

## Animated Gif/Screenshot

![set up shipping as super admin](https://user-images.githubusercontent.com/13171778/60674931-3aee2e80-9e49-11e9-8563-3d541541ad88.jpg)

![shopfront orders are closed](https://user-images.githubusercontent.com/13171778/60675028-75f06200-9e49-11e9-8d75-2f0a527e7693.jpg)

## Context

inconvenient - need to add non-admin manager to enterprises for setup, demo & orientation

## Your Environment

* Version used:  V2 (I think?)
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Win 10
* OFN Platform instance where you discovered the bug, and which version of the software they are using.

**Comment by luisramos0** [comment] 2019-07-04 14:58
I labelled this s2, it may be hiding a more serious problem, we need to investigate the cause now at least.

**Comment by RachL** [comment] 2019-07-04 21:06
Thank you for the super admin bump @tschumilas . I've managed to add shipping and payment method to my own hub and checkout fine.
I left my shop opened if you want to test.
The payment method I was using was stripe, but it wasn't displayed on the shopfront. Looking closely I've noticed that the "environment" field was displaying development by default.
This is the case already in v1 but I forgot it as I'm rarely opening shops as super admin (France's production is so slooowww, yours in comparison is fast :D ).

This field does not show up for admins, but super admins only. When I've turned this field from development to production, my payment method showed up correctly in shopfront.

Could this be linked @tschumilas ? Anyway I still have to create a hub with a different email address and try from super admin. Will keep you posted.

**Comment by tschumilas** [comment] 2019-07-04 22:42
I thik this was it  -  when I changed the 'environment'  to 'production'  -  I'm able,  as super admin,  to create payment methods for an enterprise    I'll just wait until I hear further from your other testing @Rachel.  But I suspect we can close this.

**Comment by RachL** [comment] 2019-07-05 09:52
Yes now even with a new and different enterprise, I'm able to do this as super admin. So I'm closing, but feel free to reopen if you see something else in the future.

**Closed by RachL** 2019-07-05 09:52 UTC
Labels: bug-s2
