### ISSUE TITLE
Tagged variant displaying to not logged in user

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#5130] opened 2020-04-02 09:16 UTC
## Description

We have an order cycle open that includes tagged variants that should only be visible to Customers tagged to that variant.

Variants tagged 'milk-3-month' and 'milk-1-month' are invisible by default
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/f7e70b6a-fafd-4bf3-aa8e-3fa477633bef)

Customers with those tags should then be able to see those variants
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/d9561fd6-d66c-4cbd-9260-d7de8b5a8154)

I am one of those customers 
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/bc6d2fa3-6a0a-448a-9c95-96980aee43f5)

So I can see the variants - CORRECT
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/1d4d296d-cedd-4dac-808c-046197ab60ec)

and if I remove the tags from my Customer, I cannot see them - CORRECT
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/7562b13f-baac-45b3-bfc8-baee95c1fc94)
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/ddb703f2-1d06-4573-891f-ee470e4acdfb)

BUT if I logout I can see the milk-1-month product [note login button]
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/d8c760ef-3149-443a-8914-fe351cda310f)

I have tested this with all the possible combinations of Order Cycle / Inventory settings and the problem is persistent - a user visiting this shop and order cycle that is NOT logged in can see a product they should NOT be able to see :(

I am perplexed :(
Shop is [Harcourt Organic Farming Co-op](https://openfoodnetwork.org.au/harcourt-coop/shop#/shop)

## Expected Behavior
When a tagged variant is default to invisible, Customers how are not logged in should not be able to see it

## Actual Behaviour
Customers at the shop who are not logged in can see the variant
When Customers login the tags work correctly and they only see it if they should

## Steps to Reproduce
I don't know how to reproduce it but I can show you where it is - https://openfoodnetwork.org.au/harcourt-coop/shop#/shop

## Severity
S2? I realise this is something not everyone uses, but we have a massive uptake of tagging right now and I think this could become a significant problem beyond this one (quite annoyed) user

It's a non-critical feature, but I can't find any workaround . . help?!?! 

## Your Environment
Mac, Chrome, Safari

**Comment by tschumilas** [comment] 2020-04-02 13:51
You just haven't completed the tag rule -  I know this because -  do you see how in this   screenshot has some of the tags as black on blue (vs white on blue)  -- it tells me a tag hasn't followed all the way through.

And when I look at the first screenshots from your tag rules,  I see this too.  You have first tagged the milk-3-month as invisible.   Then you have identified the customers  - for customers tagged milk-3-month is visible.  BUT there needs to be a new tag rule - that then makes the milk-3-month visible for these tagged customers.    Just remember when you are creating the tag rules -  the tag needs to show up 3 times  on this tag rules page:  1. make it invisible.  2. link it to the customer. 3. make it visible .   As it stands -  you've made it invisible.  You've identified the customer.  But you haven't made the milk visible to them.

Tags work in 2 sets of 3.
Set a tag rule
Tag the customer
Tag the OFN feature (OC, shipping, payment, variants)

But the tag rule -also has a set of 3 elements:   make it invisible.  tag to the customer.  make it visible.


![image](https://user-images.githubusercontent.com/13171778/78256564-b3f8e000-74c6-11ea-8372-70265cb5ac6f.png)

**Comment by RachL** [comment] 2020-04-02 13:59
Ok so definitely not s2. @kirstenalarsen I let you close this if it works :)

**Comment by tschumilas** [comment] 2020-04-02 18:18
Sorry -  at first I thought it was an incomplete tag - but just looked again and I think the tagging is correct.   What is the shop's inventory settings -    can new products be put into the inventory?  Because I'm wondering if its to do with product list vs inventory list?  It seems like for this product, the public shop (non tagged user) is pulling a product tagged in inventory.  Would that happen if there is stock in the product list (vs inventory) for this item?   I'm wondering if:  with a tagged product, the shop pulls the over=ride from inventory,    but also will pull stock on hand from the product list for a non-tagged user.

If you make me super admin on Aus temporarily -  I can take a look for you if you want.  I'd like to solve this too.

**Comment by tschumilas** [comment] 2020-04-03 13:07
I've just re-done the tagging on this product.  I re-created the product in the producers list. Deleted the old one.  Re-entered the new product into the Harcourt hub's inventory.   I re-set the tag rules for this product,  re-tagged the new product in inventory,  and I re-tagged all the customers.   I set up a test order cycle -  and the error repeats.   So - this isn't just a tagging issue.  I think its an S2 again.

Sorry - it was my fault this got reduced to an S3,  because I thought it was a straight forward tagging error.  But it is not a tagging error.   The product  continues to show up in a public shop where it should not.

**Comment by RachL** [comment] 2020-04-03 13:17
I'm afraid this is an s3 in any case. The workaround would be to create a dedicated OC that would be visible only to these customers.

**Comment by tschumilas** [comment] 2020-04-03 13:42
If the tagging works for that.  Will try.

**Comment by RachL** [comment] 2020-04-03 13:54
Yes I'm using it regularly. In fact this is why I've selected that papercut: https://github.com/openfoodfoundation/openfoodnetwork/issues/3170

**Comment by tschumilas** [comment] 2020-04-03 14:39
I just have a request from Laurie to follow up with a US user with the very same problem.  Tagged product is showing up where it should not.   I'll investigate and see if it seems like the same issue as this one.

**Comment by tschumilas** [comment] 2020-04-04 00:36
So there are 2 shops -  one on the US instance and the other as @kirstenalarsen reports above with this same problem  I've re-created products, re-created order cycles,  re-done tagging  in both cases - and the error persists.  A tagged variant shows up in a public shop where it should not.    For now,  I've followed @RachL 's advice and tagged order cycles  in both these enterprises --- which can accomplish pretty close to the same thing.     I still have not seen how to reproduce this bug, so I don't know how to proceed.  I've set up several order cycles on OFN-CAN with tagged variants,  and they have worked fine.   Maybe the best we can do is keep a look out for someone else who experiences this problem.  I don't know how else to identify the cause.

**Comment by kirstenalarsen** [comment] 2020-04-05 06:10
The user has now totally recreated the product and apparently solved the problem. But really curly. Am downgrading this to S3 because urgency has passed (and so many other things) but keeping the issue open as we still don't know what caused it

**Comment by lin-d-hop** [comment] 2022-11-21 16:40
Closing as curly edgey old cases like this are too hard to spot. Can be reopened if it pops up again

**Closed by lin-d-hop** 2022-11-21 16:40 UTC
Labels: bug-s3
