### ISSUE TITLE
Instagram links not working 

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1760] opened 2017-08-11 04:04 UTC
## Description
In Enterprise Setting > Social there is a field to insert an Instagram link. This link will appear on enterprise profiles. If the instagram page is https://www.instagram.com/happyfarm/ the link needs to be in the format "happyfarm". 
![image](https://user-images.githubusercontent.com/10843056/48240835-6d659a00-e428-11e8-9e10-c5c72dbca249.png)
Currently there is no pointer telling the user that this is the required format. As a results, there are multiple different ways that people include the link, most of which lead to broken links on their profile.

Link formats that will work: happyfarm
Link formats that do not work: /happyfarm, @happyfarm, https://www.instagram.com/happyfarm/ and www.instagram.com/happyfarm/

## Expected Behavior
Users can find out what format the link needs to be in.
If a user puts in a link in a format that's wrong, the link either corrects, or there is an error message.

## Actual Behavior
Users don't know what to enter. 
If they do enter an incorrect format there's no error message, so they don't know that the link will be broken. The link also doesn't autocorrect, so the instance can have many many profiles with broken links, which looks unprofessional.

## Steps to Reproduce
1. Go to any enterprise settings, and go to the "social" tab
2. See instagram field, no suggestion is shown.
3. Try to put in an incorrect format. You'll notice that the link is accepted even if wrong. Look the result from frontend on your profile, you'll see the link is broken.
4. Try to put Instagram link in the "happyfarm" only format, and look the result on the frontend. Link works.

## Context
This issue is leading to lots of broke links in the directory. 
It's also frustrating for users who are creating their profile because they don't know what format we want the link in.

## Severity
S4 (UX issue I would say as the software is working as expected but the user doesn't know what to do)

## Your Environment
PC, French production, Chrome

## Possible Fix
As at Noverber 9th 2018 the following fix has been decided. We tried to implement this fix via PRs https://github.com/openfoodfoundation/openfoodnetwork/pull/2859 and https://github.com/openfoodfoundation/openfoodnetwork/pull/2849, but as mentioned on 2849 there were some issues. 

Fix 1
- When a user first enters their social media links, if the instagram link is in any of the following four formats (@happyfarm, /happyfarm, https://www.instagram.com/happyfarm/ or www.instagram.com/happyfarm/) the form should convert the link to the correct shorthand format (happyfarm)
- If the system can't recognise the link, and can't convert it, there should be an error message when the user saves the form.
![image](https://user-images.githubusercontent.com/10843056/48240525-2fb44180-e427-11e8-9bfc-bea6af204ca7.png)

Fix 2 - 
- We should add a suggestion to the Instagram field so that the user knows what format to use.
![image](https://user-images.githubusercontent.com/10843056/48240575-62f6d080-e427-11e8-9e7e-956dbd561a47.png)
- We should ensure that any pre-existing profiles that have links in any of the four formats (@happyfarm, /happyfarm, https://www.instagram.com/happyfarm/ or www.instagram.com/happyfarm/) are converted to the correct shorthand format (happyfarm)
- If a pre-existing profile has an instagram link in a format which cannot be converted, the next time that user tries to save their Enterprise settings, they should see the error message pictured above.

Note: Fix 1 and Fix 2 should be merged close to each other in time. If Fix 1 is merged without Fix 2, pre-existing profiles with incorrect links will get an error message without knowing what the correct format their link should be in.

**Comment by sineadfenton** [comment] 2017-08-17 08:06
![](https://github.trello.services/images/mini-trello-icon.png) [Instructions on social page](https://trello.com/c/leuDlICS/81-instructions-on-social-page)

**Comment by sineadfenton** [comment] 2017-08-17 08:22
Hey,

I'd agree here and think it would be a quick fix that saves a lot of support time (have spent a while rectify lots of enterprises who have got this wrong) 

Our suggestions here are also to have the tooltip directing users how to enter this information

S

**Comment by dannyd4315** [comment] 2017-08-31 08:07
Happy to pick this one up as a first commit, if thats ok?

**Comment by sauloperez** [comment] 2017-08-31 08:19
Cool @dannyd4315 ! we're also experiencing the same problem while onboarding new enterprises in our OFN instance.

**Comment by lin-d-hop** [comment] 2017-08-31 08:34
Thanks @dannyd4315 This is a great one to pick up.

I think it would be good to be consistent with the linkedin and facebook links and require the whole URL to be input. I think for twitter people are more used to referring to each other by only the handle so this can be different (eg @mytwitter rather than https://www.twitter.com/mytwitter)

-> Change field so that it does not replace "input" with "https://www.instagram.com/input"
-> Be sure that this does not break existing enterprises that might have put in full url or just the handle
-> Check we have a translatable string for the example "eg. https://www.instagram.com/myinstagrampage"

**Comment by dannyd4315** [comment] 2017-09-02 06:25
@lin-d-hop There is actually already translatable placeholders in the locale files, so not sure why they were not in there, the instagram one isn't quite right however and breaks. So will clean that up. Also with regards to existing enterprises, I could build a rake task that checks and updates all existing enterprises inputs to the new format? Unless you another idea?

With regards to instagram, we currently ask for '@namegoeshere' would you prefer that or just the username without the '@'. It should really be consistent throughout the site. So will update all instances to reflect this.

Finally I am not too sure what you mean about the first point? - "-> Change field so that it does not replace "input" with "https://www.instagram.com/input" Could you confirm?

**Comment by dannyd4315** [comment] 2017-09-02 06:28
On second thoughts the current plans shouldn't break full url's or handles for current enterprises. They would work in both instances. Or not work at all in both...

**Comment by lin-d-hop** [comment] 2017-09-05 13:24
_I think it would be good to be consistent with the linkedin and facebook links and require the whole URL to be input._ 
So, let's just ask for the URL in the same way as we ask for it in the linkedin and facebook links.
Required Input format: "https://www.instagram.com/myinstagrampage"

_-> Change field so that it does not replace "input" with "https://www.instagram.com/input"_
By this I mean, now that we ask the user to input the whole URL we need to reflect this by not appending https://www.instagram.com/ in code.

For any that are in the DB already I agree that we build a rake task to fix any that are different to this format. This should fix links for any currently broken ones as well.

Does that make more sense?

**Comment by sauloperez** [comment] 2017-09-05 13:38
> For any that are in the DB already I agree that we build a rake task to fix any that are different to this format. 

We should create a data migration instead. 

Agree on @lin-d-hop 's over all feedback

**Comment by dannyd4315** [comment] 2017-09-05 22:54
Cheers @lin-d-hop, makes sense.

**Comment by mkllnk** [comment] 2017-09-06 08:21
Yes, I agree that we should use a data migration instead of a rake task.

What if people just put in their page name? Should we check for that and then save it in the database with the complete URL or not bother?

**Comment by sauloperez** [comment] 2017-09-06 08:35
I'm not sure the extra logic to check the account is worth it @mkllnk

**Comment by dannyd4315** [comment] 2017-09-06 09:28
@mkllnk and @sauloperez apologies, not sure why a data migration would be a better option than a rake task?

**Comment by sauloperez** [comment] 2017-09-06 10:24
Migrations are designed to be the means of applying changes on the database. Rails keeps them as a log of historicall changes so you can kind of reproduce the state of the database but also track what changes were applied.

It also ensures that each migration is only run once (although of course you can re run it if you need) and in every environment (dev, prod, staging) and OFN instance (Aus, Uk, France, etc.).

**Comment by mkllnk** [comment] 2017-09-08 05:19
Okay, sure, not that important.

**Comment by myriamboure** [comment] 2018-05-21 17:33
Ok so folks I have read all the comments and tried to clarify the options we have before we jump on a solution. Please read description and tell me if you agree with me that option 1 is the one to choose?
@sstead @lin-d-hop @sauloperez @mkllnk ?
I think it does the job, require much less work, and also is better UX regarding user habits about Instagram profile (more comparable to Twitter to me than Facebook or Linkedin).
Waiting for your feeding before deleting the option we don't keep so that the work to be done is clear.

**Comment by mkllnk** [comment] 2018-05-23 06:05
#### Option 3

It does not matter if people enter their handle or the whole URL. If they enter the whole URL, we extract the handle and store only the handle in the database.

We don't need a database migration, but we could add one to search for URLs and convert them to handles to fix currently broken profiles. It's not that difficult.

**Comment by myriamboure** [comment] 2018-05-23 12:52
I added your option 3 @mkllnk 
@sstead can we have your preference on it ? Maybe also @sineadfenton ? @RachL ?
My vote still goes for option 1 as I think it's still much less work and we have lots of more important things to do. If we do the value matrix I guess option 1 is the one that adds most value for less work, even if others add a bit more value but more work too. But I'm not familiar with users habits on Instagram, almost no users use instagram in French instance for now, so if others have an opinion happy to follow them.

**Comment by sstead** [comment] 2018-09-27 03:17
I had a look at 10 random profiles with instagram links and 3 of the 10 had put the full URL, so i suppose I can support option 1 for now, ideally option 3 one day.

**Comment by albarnaz** [comment] 2018-10-08 13:52
If it`s ok I'm happy to work on option 1. Then you can see and decide if its the best solution.

**Comment by lin-d-hop** [comment] 2019-02-14 11:40
![](https://github.trello.services/images/mini-trello-icon.png) [Shopfront Instagram links not working](https://trello.com/c/BOT7KMYE/383-shopfront-instagram-links-not-working)

**Comment by reuschelcm** [comment] 2020-02-13 01:27
My group and I have taken a look at it and could pick this issue up! It's been a while since it's been worked on, and I see that there's been a few ideas tossed around. I was wondering which of the options (1, 2 or 3) you would like to be implemented?

I see that 2 is more or less implemented with the sample text. I see that in earlier builds fix 1 was implemented in 'enterprise.rb', but had some issues and was removed.  I know the plan before was to merge fixes 1 and 2. Is this still the case? I just am checking before I proceed!

**Comment by sigmundpetersen** [comment] 2020-02-13 12:05
Hey @reuschelcm yes please go ahead! There was an attempt at solving this in #3238, please have a look at how far that got and maybe you would like to continue on what was done in that PR.

You're welcome to join our Slack https://openfoodnetwork.org/slack-invite and ask us anything

**Comment by mkllnk** [comment] 2020-02-13 23:33
Yes, I think the tasks are:

- Provide a hint in the input field (not sure if that has been done).
- Validate format of input on the server (done).
- Convert valid formats to the one we use in the database, pseudo only (done).
- Migrate existing invalid entries to make them valid or remove (check migrations if this happened in the past, I don't think so).
- Bonus: use HTML5 input validation to give immediate feedback to the user.

**Comment by reuschelcm** [comment] 2020-02-25 14:39
Thanks, sorry for the late response. I've been experimenting and trying to get a grasp on parts of the code. 

I had a few questions about that checklist, as some of it seems conflicting, but I could be wrong

- _Provide a hint to the input field (not sure if that has been done)_
This seems to be done on the current version? ie. eg: the_prof in the input field?

- _Validate format of the input on the server (done)_
If I am correct, this was the case the version of OFN in issue [#3238](https://github.com/openfoodfoundation/openfoodnetwork/pull/3238), but is no longer done now? It seems that when anything is entered to the Instagram field, it is accepted regardless of format. Unless I'm interpreting what's being validated incorrectly.

I did see there was a  validate statement used in the build for the referenced issue that did work for most cases, but not all. I did inject

- _Convert valid formats to the one we use in the database, pseudo only (done)_
This also doesn't seem to be in the current version? The version in the referenced issue used a regex statement that worked for most cases, but failed in a few with the tests. I believe one of the updates requested for this was to remove the '@' if just the handle with the symbol was entered?

- _Migrate existing entries to make them valid or remove_
It appears there was a migration attempt back in 2018 to try to make the links valid, but no attempt to remove invalid links that could not be converted. I'll definitely take a look at this. 

- _Bonus: use HTML5 input validation to give immediate feedback to the user._
This would be very useful to implement. I'll see if my team can get this implemented.

Thanks for your time. I just wanted to verify this list before I proceed further, to make sure the changes I implement are what is wanted.

**Comment by mkllnk** [comment] 2020-02-25 22:55
Thank you for looking into this, @reuschelcm. And sorry for my confusing summary before.

> Provide a hint to the input field

Right, this is done.

> Validate format of the input on the server

You are right. That pull request was never merged and this is not done.

> Convert valid formats to the one we use in the database, pseudo only

You are also right here. This needs doing.

> Migrate existing entries to make them valid or remove

This needs to happen after all the validations are in place.

**Comment by reuschelcm** [comment] 2020-03-05 13:30
@mkllnk no worries, thanks for the update. I'll continue to look at the regex and see if I can get it to pass for all the tests.

Once that's done, I'll then see if 

Also, after these changes are made, instagram will be the only social media that is validated. I assume in the future that we'd want to validate all social media in some way? (ie Twitter, facebook, etc.)

**Comment by mkllnk** [comment] 2020-03-10 02:35
Yes, more validation would be awesome.

**Comment by daniellemoorhead** [comment] 2020-03-21 23:49
Hiya @reuschelcm, just checking to see if you'll be working on this again? It's been a couple of weeks since last activity, would be great if you could push through a PR, or we can pop it back into Dev Ready for someone else to pick up.

Let us know 😄

**Comment by reuschelcm** [comment] 2020-03-22 20:10
Apologies for the absence, current events have made progress a bit slow. 

I am still working on the migration, but I have a working fix for the validation of the Instagram links, and accompanying tests. It'll just need to be checked so that it is up to standards of the code base. 

I just need to resolve an issue with getting my branch to push with my team's fork. I should have a PR up within 24 hours. Thanks for your patience!

**Comment by daniellemoorhead** [comment] 2020-03-22 20:42
Awesome!

**Comment by marthaerm** [comment] 2020-12-02 05:06
Hi everyone! I would like to pick this issue, I saw that this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/5052 was opened and I would like to dig into it and continue working on the issue as my first contribution to this project :)

**Comment by mkllnk** [comment] 2020-12-02 06:15
:wave: :sun_with_face: Welcome @marthaerm! It's awesome that you are picking this up. If you need any support, you can head to the [#dev channel on Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A) and ask your questions there. Let us know how you go.

**Comment by marthaerm** [comment] 2020-12-02 06:35
@mkllnk Great! Thanks! I'll join that channel on Slack! And I'll give you any update!

**Comment by Matt-Yorkley** [comment] 2020-12-02 18:47
Welcome @marthaerm :wave:

Just a quick heads-up; this issue is 3 years old and a lot has changed in that time. It might be worth pulling the `master` branch and checking if this issue can be replicated as a first step. It might be fixed already, in which case we can close it and you could grab another issue :smile:

**Comment by marthaerm** [comment] 2020-12-02 18:56
@Matt-Yorkley ok! Thanks for the heads up, I'll start by replicating the issue!

**Comment by marthaerm** [comment] 2020-12-10 08:16
Hey guys! I've been tryin to reproduce the error on the `master` branch, and yes, the issue is still there, i added this instaram link `https://www.instagram.com/happyfarm/` and you can see in the image that is not converted.
![Screen Shot 2020-12-10 at 1 29 36 AM](https://user-images.githubusercontent.com/25876259/101735298-4fdfe000-3a87-11eb-9993-4e4fe2576842.png)
I would like to continue with this https://github.com/openfoodfoundation/openfoodnetwork/issues/1760#issuecomment-590898986 approach, I see some of these things implemented on this PR #5052

**Comment by sauloperez** [comment] 2020-12-14 08:46
All yours @marthaerm

**Comment by bschuer** [comment] 2022-03-21 20:27
Hello! My partner and I are in a student group working on open source projects and would like to help out with this issue. Do you have any advice/tips?

**Comment by drummer83** [comment] 2022-03-21 23:12
Hi Ben (@bschuer),
great to have you here! :smiley: 

As you can see this issue has quite some history. There are a few pull requests which were very close to getting merged but the last bit was missing. So my recommendation would be to have a look at the history above and check the existing pull requests for code that can be reused.

Also I had invested some time to collect **a lot of information around our social media and website links** [in this document here](https://docs.google.com/document/d/1ihDof2HtuzBW1qbDhFxTt1IY28VGRfoJeNqXEzdQX8E/edit?usp=sharing). It lists all (or at least most) issues and pull requests around this topic, it provides a concept and regular expressions to validate the user input, it indicates where social media is being used on our platform and also provides many many test cases for user input.
My intention was to create an epic and list all the issues that need to be done - but I didn't get to it yet. Keep in mind that I am not a developer and all information has not been discussed in the team yet - maybe it is pure nonsense. ;-)

The basic steps that need to be done are:
1. Validate the user input: Can the username be identified and extracted?
2. Convert the user input to 'username only' to store in the database
3. Migrate the existing data in the database to match the 'username only' format
4. Make sure new and existing entries from the database are displayed correctly on the platform and links are working

These steps can be worked on in several pull requests as long as functionality is maintained at all times.

I hope this helps! Feel free to ask any questions here or in our [Slack](https://join.slack.com/t/openfoodnetwork/shared_invite/zt-9sjkjdlu-r02kUMP1zbrTgUhZhYPF~A)!

**Closed** 2022-12-20 12:40 UTC
Labels: good first issue, bug-s5, hackathon
