### ISSUE TITLE
RuntimeError in spree/admin/line_items#create

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#782] opened 2016-01-20 00:13 UTC
## Exception in OpenFoodNetwork

**RuntimeError** in **spree/admin/line_items#create**
Zero Quantity Line Item

[View on Bugsnag](https://bugsnag.com/yaycode/openfoodnetwork/errors/56554b1b15766f1ee3f3785d?event_id=5695dc917a11aee355ec3c65)
## Stacktrace

```
app/models/spree/order_decorator.rb:119 - add_variant
app/controllers/spree/admin/line_items_controller_decorator.rb:24 - create
```

[View full stacktrace](https://bugsnag.com/yaycode/openfoodnetwork/errors/56554b1b15766f1ee3f3785d?event_id=5695dc917a11aee355ec3c65)

**Comment by luisramos0** [comment] 2018-08-18 20:16
this is a duplicate of #1002 
I'm closing it. Please reopen if I am missing something.

**Closed by luisramos0** 2018-08-18 20:16 UTC
Labels: bugsnag
