### ISSUE TITLE
Enterprise fee lingering on order when item is removed from order by making QTY=0

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1629] opened 2017-06-21 06:13 UTC
As the screenshot shows, when an item is removed from an order by making QTY=0, enterprise fees associated with that item don't get removed as they should.

![image](https://user-images.githubusercontent.com/10843056/27369783-dd378f5c-569c-11e7-9154-4798f8063228.png)

**Comment by mkllnk** [comment] 2018-12-19 04:01
Removing the item from the order as admin without clicking "Update and recalculate fees" also results in an orphaned fee. This caused #3127.

**Comment by filipefurtad0** [comment] 2021-03-22 17:48
This bug seems to happen as well in the context of subs, [see comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/7048#issuecomment-804252653).

What's worse in subs, is that they are placed automatically, and as such, quite hard to spot this lingering fee -> this can cause customers to be overcharged... Should we prioritize this one? ping @RachL @lin-d-hop

**Comment by Matt-Yorkley** [comment] 2021-03-23 15:53
@filipefurtad0 could you give this a quick check when testing #6974? I think it'll fix it.

**Comment by filipefurtad0** [comment] 2021-03-23 17:34
I checked this issue while testing #6974 and could not reproduce it any more :tada: 
Closing.

**Closed by filipefurtad0** 2021-03-23 17:34 UTC
Labels: bug-s3
