### ISSUE TITLE
"not-paid" order confirmations resemble "paid" orders

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#7603] opened 2021-05-10 17:03 UTC
## Description

Follow-up from #7562 and [discussed here](https://github.com/openfoodfoundation/openfoodnetwork/issues/7509#issuecomment-833577218).

Order confirmations with due payments look too similar to the ones from paid orders. This maybe tricky for the customer spot the difference.

Context - from Subscription and Backoffice orders:
Failed payments attempts from using the link (received per Email) to authorize payments or from clicking "Authorize" in pending orders (`/account#/transactions`) redirect the customer to the order confirmation. The only visible difference in the UI is:

- a flash error message - displayed only at the moment of the payment attempt
- the wording "Not Paid"

Everything else is identical - See pics below.

## Expected Behavior

It should be straightforward for customers to identify orders with pending payments, from the info provided in the UI.

## Actual Behaviour

It can be rather challenging to identify orders with pending payments, from the info provided in the UI.

## Steps to Reproduce

As an admin:
1. Place a subscription order or a backoffice order with a Stripe-SCA 3D-Auth. card like x-3184.

As the respective customer:
2. Click "Authorize" or use the link received per email.
3. Fail authentication for that payment.
4. Look at the screen and spot the difference between a paid and a non-paid order.

## Animated Gif/Screenshot

Spot the differences:

![image.png](https://images.zenhubusercontent.com/5d761b049dde650001eaf32f/2fd241b7-63ce-46e2-89a2-ad24714cfa7f)

The only difference is the wording "Paid" vs. "Not Paid" only.

Ping @openfoodfoundation/train-drivers-product-owners @openfoodfoundation/designers

**Comment by lauriejefferson** [comment] 2023-06-05 11:06
Is this issue still open?  I would like to work on it.

**Comment by jibees** [comment] 2023-06-05 12:56
Hi @lauriejefferson 
Glad to have you on board ; yes the issue is still open ;) I'll assign it to you.
Thanks!

**Comment by lauriejefferson** [comment] 2023-06-05 18:26
Hi @drummer83.  A discussion on the mockup would be very helpful. How should I proceed?

**Comment by drummer83** [comment] 2023-06-05 22:24
What would you think about taking the screenshot from the opening post ([here](https://github.com/openfoodfoundation/openfoodnetwork/issues/7603#issue-884655682)) and proposing some adjustments to the 'not paid' side?
You could modify the image or make a sketch or just describe what you would like to adjust. That way we will get a common understanding.
Would you be willing to do that?
I don't think anyone of our team has a precise expectation - we haven't put any thought into it yet. So anything you could come up with would be really helpful and will be much appreciated.

Also pinging our designer @mariocarabotta, he might want to be in the loop as well.

Sounds good, @lauriejefferson? Thanks!

**Comment by lauriejefferson** [comment] 2023-06-05 22:33
@drummer83 @mariocarabotta  I'll get started with a mockup sketch of the 'not paid' invoice improvements and add it to this ticket.

**Comment by lauriejefferson** [comment] 2023-06-13 18:05
Attached is a pdf of the 'not paid' invoice with improvements.  I added new rows for Subtotal, Balance and Amount Due so that the customer can see how much was paid and how much balance remains on the invoice.  The Amount Due balance is in red and at the top of the invoice, 'Not Paid' is also in red so that the customer can clearly see that money is owed on the invoice. 
[Openfoodnetwork Mockup.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/11737828/Openfoodnetwork.Mockup.pdf)

**Comment by drummer83** [comment] 2023-06-13 23:14
Thanks, @lauriejefferson! That's looking great!

I think having this information in red is really helpful! 👍🏻

From my point of view you can go for it! 💪🏻

Thanks again, and let us know if you get stuck!

**Comment by lauriejefferson** [comment] 2023-06-15 10:24
@mariocarabotta I added a mockup of the 'Not Paid' invoice with improvements. What happens next?

**Comment by mariocarabotta** [comment] 2023-06-19 07:57
that looks good @lauriejefferson! thank you for picking it up 👍

**Comment by lauriejefferson** [comment] 2023-06-19 10:50
@mariocarabotta What are the next steps to get the changes added to the invoice?

**Comment by drummer83** [comment] 2023-06-19 11:16
@lauriejefferson You can go ahead and create a pull request with your changes. Let us know once ready. Our developers will then review, the testers will test it and if all is good it will be merged and deployed to our production servers.

Does this answer your question?

**Comment by lauriejefferson** [comment] 2023-06-19 11:26
@drummer83 Thanks. I'll get started.

**Comment by lauriejefferson** [comment] 2023-06-20 12:42
@drummer83 @mariocarabotta Is the _order_details.html.haml template used for the 'not paid' order invoice?  Are you using  CSS for your styling or a library like Bootstrap or TailwindCSS?  I don't see where your css files are located.  They don't appear to be in the assets folder.

**Comment by drummer83** [comment] 2023-06-20 13:06
Hi @lauriejefferson,
I think @jibees can answer best. 👍🏻

**Comment by jibees** [comment] 2023-06-20 13:15
I guess the template used is `app/views/spree/admin/orders/_invoice/_payment.html.haml` and/or `app/views/spree/shared/_payment.html.haml` (needs to be checked)
We do have a lot of CSS files, mainly ordered in folder `app/webpacker/css` and we don't use any CSS framework.

**Comment by lauriejefferson** [comment] 2023-06-20 18:23
I don't think these are the right templates.  On the'Not Paid' order screen, the 'Not Paid' text is has classes 'order-summary small' and 'right', and the table below with the order total has a class 'line-items'. None of these classes are used in the templates above.  These classes are used in the _order_detail.html.haml template. Can someone confirm?

**Comment by jibees** [comment] 2023-06-21 08:20
Maybe the right path to confirm is you to test?

**Comment by drummer83** [comment] 2023-06-21 10:45
Yes, @lauriejefferson, I also think it's this one here:
`~/openfoodnetwork/app/views/spree/shared/_order_details.html.haml`

The other one mentioned
~/openfoodnetwork/app/views/spree/shared/_payment.html.haml
might be the one used in order confirmation mails. In a second step we could consider highlighting this one  as well. But that would be a separate pull request.

**Comment by lauriejefferson** [comment] 2023-06-21 13:27
@drummer83 @jibees I tested the _order_details.html.haml and it's the correct view for the order confirmations.  I'm writing the changes to the invoice now and should be done soon.

**Closed** 2023-10-13 16:52 UTC
Labels: good first issue, hacktoberfest, enhancement, design-ui
