### ISSUE TITLE
Create a better 'display only' shopfront option for closed shops.

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1515] opened 2017-03-31 00:34 UTC
Use case: A shop wants to be able to give visitors an indication of the kinds of products they stock when they are closed. 

In the past there was a hack 'display only shopfront' option. This is how it worked- if a OC was open by the shop had no shipping/payment methods, the shop would show as open, but kick out customers if they tried to checkout. It was fiddly to setup (deactivating ship/pay methods, and changing shopfront message) and a terrible customer experience.

This option was removed - https://github.com/openfoodfoundation/openfoodnetwork/issues/1343

So now the questions is, if we wanted shops to be able to setup a display-only shopfront, how could we do this?

One idea... It could be an Order Cycle advanced setting option- 'set this OC as a 'display only shop' to show when all other OCs are closed'. So this OC would never allow checkout, and would only show when no other OC is open. The shop would clearly communicate to visitors that it's for display only.

- Another idea- we could have a setting... 'When my shop is closed show products from my last open order cycle in the shopfront as 'display only'. This could be a 'greyed out' view of the shop, with a note to customers that they can't checkout.

**Comment by myriamboure** [comment] 2017-04-03 09:52
I like both you ideas @sstead and I do think that's a need, I have been using it myself in my hub previously. 
I think having a specific "demo OC" makes more sense to me, especially for a hub managing multiple sub-hubs/ shopfronts. If you have 2 OC in parallel, I'm afraid the system won't be able which one to choose, no?
Also maybe in some seasons there are less products, but the hub want a demo shop that is more representative of what is sold over the year, so prefer to display different products...
The trade-off is that it requires to manage one more OC though. So i guess both options could work, but I think I have a small preference for the first one as leave more flexibilty to the hub to choose what displays in the demo OC.

An expected behavior for me would be: on a demo OC, if a user tries to add quantities to his basket, a pop-in appear and tells this is only a demo hub + a specific message set up by the hub.
Like it could be: "this is a member-only shop if you want to be able to buy, register here" (so the demo OC could also be used by private shops to show non members what they could  by if they became members) or "the shop is closed at the moment, order cycles open every week on Monday and close on Wednesday".

Then we should also set it up in a way that: if there is an active OC, the demo hub doesn't display. But maybe another option should be offered to the hub manager: if there is an active OC but the user is not logged in and the shop requires people to be logged in to see the shopfront (in case of a private shop) then show the demo OC with a clear message saying that the shop is accessible only for members.

**Comment by WalkingBlackBear** [comment] 2019-06-30 19:08
Reviving an oldie, because it's still an issue for some - just not a show stopper for most.

In my head it's as easy (on the front end) as an order cycle option checkbox. "View only"  If checked, all of the add to cart widgets on the page are disabled.  One option, one extra database flag, one if-then condition to add a class to the quantity inputs, one CSS update to hide the inputs.  

It could even piggyback off this bit that's already in there - 
`ng-disabled="!variant.on_demand && variant.on_hand == 0" `
That basically disables an item so it can't be ordered once inventory runs out.  

So if another condition was added, like this:
`ng-disabled="!variant.on_demand && variant.on_hand && order_cycle.view_only == 0"` 

It would absolutely accomplish what we want.  Products visible, but can't be ordered, and a default (existing) message will inform 'shoppers' that they can't order it.

Depending what would be involved on the back end, that could be a quick win. (Or it's far more problematic on the back end than it is in my head right now.)

**Comment by lin-d-hop** [comment] 2019-06-30 19:18
I feel that this is a feature request rather than an issue. Possibly should have been closed in a #gitcull.
Perhaps this needs to go to Discourse and wait to be prioritised?

If you wanted to look at this yourself @WalkingBlackBear perhaps we can support a little in the inception.

**Comment by WalkingBlackBear** [comment] 2019-07-06 23:20
Yeah, it's probably more of a feature request. 

If OFN was a PHP project, I'd be all over trying to make it happen myself, but I don't have time to learn Ruby/Rails.  Tried a few years ago ... couldn't find time when everything I was working on was in PHP.  :(

**Comment by lin-d-hop** [comment] 2019-08-28 17:47
This is now not working at all and requires a full feature inception. #gitcull

**Closed by lin-d-hop** 2019-08-28 17:47 UTC
