### ISSUE TITLE
/shops taking 30+ seconds to load (UK)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#3099] opened 2018-11-21 10:38 UTC
https://openfoodnetwork.org.uk/shops
consistently taking 30 secs to load

## Description
This is a bug.

## Expected Behavior
Page loads in "acceptable" time. I'd say we can close this if it's loads in under 10 seconds.

Edit: At #gathering19 we agreed 3-5 second load time is acceptable

## Actual Behavior
Page takes 30 secs to load.

## Steps to Reproduce
Go to 
https://openfoodnetwork.org.uk/shops
and wait 

## Context
@lin-d-hop says: "Fortunately most users direct straight to their shopfront so we dont get complaints about the slow page load"

## Severity
bug-s3

## Your Environment
* Version used: uk live Nov 20th
* Browser name and version: chrome latest
* Operating System and version (desktop or mobile): osx mojave

## Possible Fix
...

**Comment by myriamboure** [comment] 2018-11-21 10:58
Just tested on French production, it takes 20 sec to load from homepage to "shop" page.

**Comment by sauloperez** [comment] 2018-11-21 11:17
It's weird but I haven't found any trace of `ShopsController#index` in Skylight for UK. By checking on my machine this is what I see, and how I knew it `GET /shops` maps to that controller.

![screenshot from 2018-11-21 12-13-46](https://user-images.githubusercontent.com/762088/48837930-1e542900-ed87-11e8-8d01-66fbd84f0f84.png)

It's pretty obvious the performance hit is related to an N+1 on `producer_properties` and `spree_properties` database tables. See below

![screenshot from 2018-11-21 12-14-05](https://user-images.githubusercontent.com/762088/48838008-52c7e500-ed87-11e8-96d6-4edc915371ff.png)

```
Completed 200 OK in 996.5ms (Views: 790.2ms | ActiveRecord: 204.7ms)
```

**Comment by sauloperez** [comment] 2018-11-21 11:21
>  Could be that Skylight drops these requests due to them hitting a hard limit.

This message in `log/skylight.log` must be it

```
[SKYLIGHT] [1.6.1] failed to instrument span; msg=native Trace#start_span failed; endpoint=ShopsController#index
```

**Comment by RachL** [comment] 2018-11-21 11:40
> 
> 
> Just tested on French production, it takes 20 sec to load from homepage to "shop" page.

Could we agree on using Matomo for these stats :) ? Rather than our own individual network. Matomo shows an average generation time of 13 to 15 seconds. And like Lynne said, the main behaviour is not to reach this page.

**Comment by luisramos0** [comment] 2018-11-21 12:15
yes @RachL matomo is more precise but not too far from our own experience. uk is showing 26.79s.

my opinion: this is totally unacceptable and we should fix this asap in all instances.
there are many dimensions to this, UX for new users being the top one I believe, another one is SEO. search engines will seriously reduce our ranking because of this.

**Comment by RachL** [comment] 2018-11-21 12:48
@luisramos0 I was about to say that I wasn't sure about the "asap" part as stats shows that the page is not used that often.... until I've reach Australian stats where the page is more used and needs 32 to 37s to load. 😱

**Comment by luisramos0** [comment] 2018-11-21 13:18
yes. incredible, a few facts:
- a pretty consistent number is that in all instances in all months with numbers this page represents 5% of the total page views (UK with less views because less page views in matomo, but still ~5%)
- in October /shops was taking FR ~12s, UK ~28s and AUS ~26s
- in November /shops was taking FR ~14s, UK ~26s and AUS ~36s
- but in AUS in September (only instance with data), for the 694 pageviews the load time is 5.5s!
Also, these numbers are always very similar for /producers and /maps
Also, one typical fix for this problem is "metal", in Portuguese we say ferro (iron): https://www.digitalocean.com/pricing/

**Comment by luisramos0** [comment] 2018-11-21 14:39
I agree monitoring is important but this is different, this is about solving a bug in production. So, I think we need to fix this before improving monitoring.
I agree we need to look at our dev process and improve performance at code level, always and continuously.
I agree metal will not solve all problems. But metal is a quick way to improve the situation.

>>> I'm not sure metal will change things too much
I am pretty sure that if you increase the specs of the servers by a factor of 3 or 4, we will see page load time move to 5seconds. Another natural step we can take is to separate the DBs from the apps, that will also have a massive positive impact on performance.

**Comment by luisramos0** [comment] 2018-11-21 14:46
So, I think there are 3 actions here:
- manage performance vs servers cost (this is an ongoing thing), it looks like we very far from appropriate server capacity for the current software solution (for a normal e-commerce website, page load times above 4/5 seconds have to be looked at with priority, ofn is different but the capacity management needs to be done).
- improve monitoring with openfoodfoundation/ofn-install#273
- improve the performance of the app. we need to look at the /shops code and make it faster (lets keep this issue for this part)

**Comment by sauloperez** [comment] 2018-11-21 15:16
Ok, understood. Let's move discussions beyond making `/shops` faster to community.

**Comment by Matt-Yorkley** [comment] 2018-11-21 22:53
So is there a quick way to tidy up those two n+1 queries @sauloperez ?

**Comment by sauloperez** [comment] 2018-11-22 09:51
Sure @kirstenalarsen , this is still an S3 unless we chance our minds. So there are at least S2s on top of it. We just provided the context needed for anyone to tackle it.

**Comment by luisramos0** [comment] 2018-11-22 10:33
Hey @kirstenalarsen
I'd like to clarify that rebuild and redesign are very different and in this case the perf improvement is most probably not related to redesign. Same data will need to be shown: shops with info about them.
So, we can but we shouldnt connect this to redesign.

I'd be interested to know your thoughts about the capacity management. Are we planning to increase server capacity soon to improve website performance or is it not worth the cost?

I understand the decision but I disagree, I think it's unacceptable to live with a broken system. We should begin from a working system and grow from there always. This means I think we should stop every single feature development until we get to a minimal working system: imo these 30secs should be the top priority in our backlog today. I am not sure it's clear but this is 5% of _all_ pageviews, if you take only the frontoffice this will be a lot more than 5%, so, a lot more than 5% of ofn's customers experience.

**Comment by Matt-Yorkley** [comment] 2018-11-22 18:45
I agree @luisramos0 ! "Make what we have great" was something we agreed was a priority, but it never had a concrete form. This is a good example, and I think it should be high priority.

**Comment by sauloperez** [comment] 2018-11-23 12:03
> I'd like to clarify that rebuild and redesign are very different and in this case the perf improvement is most probably not related to redesign. Same data will need to be shown: shops with info about them.
So, we can but we shouldnt connect this to redesign.

I thought exactly the same

**Comment by sauloperez** [comment] 2018-11-27 11:04
Here come the results of my investigation

## Root cause

The actual problem is that in 

https://github.com/openfoodfoundation/openfoodnetwork/blob/d0731574246f6ded559ff5a27c265feeeff310ae/app/helpers/injection_helper.rb#L5

We load ALL the enterprises so that the frontend can filter it later. Although it's a bit slow this is not yet a problem in Katuma because there are not too many enterprises yet. This is a classic problem of young apps because of this exact same reason.

The numbers you shared @luisramos0 totally matched the number of enterprises of each instance. Executing that same query of the `injection_helper.rb`:

```ruby
# alpha.katuma.org
irb(main):001:0> Enterprise.activated.includes(address: :state).count
   (3.1ms)  SELECT COUNT(*) FROM "enterprises" WHERE (sells != 'unspecified')
=> 97

# openfoodnetwork.org.uk
irb(main):001:0> Enterprise.activated.includes(address: :state).count
   (3.1ms)  SELECT COUNT(*) FROM "enterprises" WHERE (sells != 'unspecified')
=> 1197

# www.openfoodfrance.org
irb(main):001:0> Enterprise.activated.includes(address: :state).count
   (2.6ms)  SELECT COUNT(*) FROM "enterprises" WHERE (sells != 'unspecified')
=> 626

# openfoodnetwork.org.au
irb(main):001:0> Enterprise.activated.includes(address: :state).count
   (5.5ms)  SELECT COUNT(*) FROM "enterprises" WHERE (sells != 'unspecified')
=> 2090
```

## How to mitigate

A way to mitigate this is to remove the many N+1 queries that make this GET /shops request even slower.

I've been working on solving two for which I'll open a PR likely tomorrow, but there's still another one that could be tackled separately.

## Final solution

The way to solve this once and for all is not to ask for all the enterprises in the system. And that means paginating the list. By doing this we no longer depend on the number of enterprises in the DB. By having a slow number of them shown per page we can be back to real-world response times and can be certain that it won't degrade much over time.

This, however, should be addressed in a separate issue where we investigate what's the best solution in terms of UX. My proposal: "Show more"-like pagination and sort enterprises by distance; the closest first (if it's not too difficult). Keep in mind, that will entail refactoring quite a lot the frontend. AFAIK the filtering is done on the client side and it will be moved to the backend.

**Comment by luisramos0** [comment] 2018-11-27 11:41
Nice @sauloperez 
Re Final Solution, the map will not want a paginated list of enterprises, it will want all of them. Is it the same endpoint for the map and the shop list?
What about keeping frontend as is and building a backend cache for the enterprises? I think a super fast/cached endpoint with a "full list of enterprises" will always be needed. That way we would not have to mix this with a more expensive frontend/UX rework.

**Comment by sauloperez** [comment] 2018-11-28 15:40
> the map will not want a paginated list of enterprises, it will want all of them. Is it the same endpoint for the map and the shop list?

That's a very good question. I checked and they both depend on `#inject_enterprises`.

> What about keeping frontend as is and building a backend cache for the enterprises? I think a super fast/cached endpoint with a "full list of enterprises" will always be needed. 

There are various arguments here. Let's go from abstract to concrete.

First, caching is the last resort on performance optimization because it also brings high cost. Cache expiracy is amongst the biggest headaches in programming. I've seen many hard to spot bugs because of it. So, when you have optimized db access, backend view rendering, frontend asset loading and frontend rendering, then you can think of caching.

OFN's doesn't have a successful experience doing that either. The products cache is a source of trouble both due to many errors reported on Bugsnag and a negative impact on some endpoint's performance. Also, it operational costs. It requires you to watch after it and iterate because it's hard to get right at the first try.

Even if you go that way, you still risk :boom: the DB on a cache miss. You will still execute those awful queries and so you still have the problem.

Also, from the perspective of the frontend this doesn't scale either. I asked @morantron, a frontend dev good friend of us and he claims that solution does not scale. Already with 2000+ objects on the browser it'll start suffering. He says it's better to get the lat/lng of the maps' viewbox and ask that to the backend.

That being said, when applied at the right moment, caching can make things blazing fast :rocket:

Do you mind moving this high-level discussion to discourse? Let's find the best trade-off.

**Comment by Matt-Yorkley** [comment] 2018-11-28 17:52
With the shops page I think we need to show all the open shops when the page loads, then we can paginate the closed shops (you have to click to see the closed ones anyway). Is that a good compromise?

**Comment by sauloperez** [comment] 2018-11-28 19:04
But again, when the open shops goes up to hundreds? You always need to set a limit for all resources so they don't degrade.

**Comment by luisramos0** [comment] 2018-12-11 18:35
ah, ok. not a problem. I just thought we should check times in matomo.

PR #3151 improves time by 30% which is great! but the pages will still take over 20secs to load. I don't think we should close the issue.

**Comment by sauloperez** [comment] 2018-12-12 11:11
>  I don't think we should close the issue.

Not at all. It's been a good first step that helped identify the source of the performance bottleneck.

As I mentioned, that PR was just a way to mitigate the problem. There's another N+1 I can remove which will reduce the response time even further but we should work on designing the pagination meanwhile and creating the necessary issues to implement it.

thoughts?

**Comment by luisramos0** [comment] 2018-12-12 11:41
- removing another N+1 👍 
- designing /implementing pagination  - to @kirstenalarsen point, I'd leave that for a redesign phase
- I think the next step is to increase server capacity or separate the webapp from the database - have we considered this already? it needs to be done at some point right? 1 server for the app, one server for the db. if we are even considering merging instances (single instance), this will have to be done for sure. so maybe we can start now. create a  new server and put the DB in there. that will have a big impact on performance for sure.
I moved this server scaling conversation to discourse: https://community.openfoodnetwork.org/t/ofn-physical-architecture/1523

**Comment by sauloperez** [comment] 2018-12-12 12:16
Removing an N+1 it's a must but won't solve the underlying problem.

Splitting our single servers into app server + DB server it's something we'll definitely do at some point but... Comparing implementing pagination vs. implementing a DB server, the former undoubtedly wins. Besides, it has to happen sooner or later. Limits must be said on all endpoints.

**Comment by luisramos0** [comment] 2018-12-12 12:36
what do you mean with "wins"?
in terms of estimation, implementing a DB server is a lot smaller, right?
pagination is something that will require UX, right?

**Comment by sauloperez** [comment] 2018-12-12 12:53
> in terms of estimation, implementing a DB server is a lot smaller, right?

there is where I disagree. To me, it is incomparably harder and longer (by few orders of magnitude :trollface: ) than implementing pagination, which requires moving some logic from the frontend to the backend, let's not forget.

With my far-from-perfect sysadmin skills these are the steps I foresee this would have:

* Buying a new DB server
  * we can do it as we do now, one for each instance
  * we can move towards the single-instance and buy a single one that hosts multiple DBs for now. This makes it even harder as nothing on ofn-install is thought for it and we'll need thorough investigation first.
* Creating a bunch of new ansible roles to provision a DB server
* Refactor ofn-install to treat app server and db server separately
* Defining a strategy to migrate all current instances to the new DB + app server set up.
* Refactor ofn-install and the database.yml to allow setting a different DB server
* Provision all instances for the changes to take effect
* Deploy all instances for the app to connect to a different DB

Also, the sysadmin processes is one of our weakest points where we're still taking our first steps. Just think of much long is taking us to set up Datadog or provision and deploy all instances. I believe we're not ready for such big change on the infrastructure. Many things need to happen at organizational/processes level for a change like this to not take several months and end successfully.

However, I do think having a separate DB server it'll be the next infrastructure change on OFN, but just not now.

**Comment by luisramos0** [comment] 2018-12-12 13:14
awesome: I copypasted this conversation to https://community.openfoodnetwork.org/t/ofn-physical-architecture/1523 lets talk there.

the scope of this issue can still include n+1 change (smaller) and the pagination work (not so small). they are all independent tasks btw.

**Comment by Matt-Yorkley** [comment] 2018-12-13 11:06
> It's not included in [v1.23.1](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v1.23.1) but we could work on a v1.23.2 to get it sooner.

It looks like it was merged 7 hours before the last release, doesn't that mean it was included in v1.23.1? It's not in the release notes though.

**Comment by sauloperez** [comment] 2018-12-13 11:46
I did pin the release on a paricular commit before that, so unless I committed a mistake it's not in there.

**Comment by Matt-Yorkley** [comment] 2018-12-13 16:40
Okay, so when we draft the next release, the usual method of finding PRs by date range won't work. I'll try to remember, I'm doing the next one...

**Comment by sigmundpetersen** [comment] 2018-12-14 11:09
Hey @Matt-Yorkley we discussed the release process a bit [here](https://openfoodnetwork.slack.com/messages/C0DNLAZC7/convo/C0DNLAZC7-1543242624.102000/?) and added a part under "Draft a new release..." bullet [here](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Releasing#how-to-make-a-release-spiral_notepad-white_check_mark) that for consistency we should pin the release to the last merge commit and not `master`

So I think finding the PR range to include still works when creating draft release, but that result changes of course if more PRs are merged. That was also part of the rationale behind pinning the release.

**Comment by sauloperez** [comment] 2018-12-14 11:45
nice catch @Matt-Yorkley . Don't forget to update the wiki once you do.

**Comment by sigmundpetersen** [comment] 2018-12-14 12:05
Yes I understand now, you're right of course. 🙈

**Comment by sigmundpetersen** [comment] 2018-12-14 12:07
So we need to use the date range from the _date of the last commit_ included in last release then?

**Comment by daniellemoorhead** [comment] 2019-01-08 06:58
Righto, so this hasn't had any action for 22 days. @sauloperez should I move it back to the dev ready column, or is there a PR not attached to this issue that has been worked on in the last 3 weeks?

![](https://i.gifer.com/1oBR.gif)

**Comment by sauloperez** [comment] 2019-01-10 16:55
Ok, so I created #3305 with the shippable stuff I worked on in December but there won't be any improvement yet.

I also wanted to create an epic to implement frontend pagination but I think it needs a bit more investigation, planning and scheduling. Without pagination, the problem won't be solved. What's the right way? a GH project is an epic enough?

**Comment by sauloperez** [comment] 2019-02-19 18:07
Moving back to the Dev ready as I'm not working on this one. IMO this deserves to wait for the performance voted candidate to start.

**Comment by mkllnk** [comment] 2019-04-12 06:49
Pau did some great work on this but we still have a slow Shops page. I would like to look at the different approaches to see which one leads us to a solution.

### Loading fewer enterprises

One identified problem is that we load all enterprises. We could only load open shops for the Shops page. That is 1% of all currently loaded enterprises in Australia.

This is different for the Map page. The map shows only visible enterprises though. That is less than half of the currently loaded enterprises.

### Avoiding N+1 queries

The inefficient use of the database seems to be the biggest impact on performance. Querying all enterprises takes less than two seconds. But rendering it all with many additional queries takes 30 seconds.

I don't know how much we can save but I would guess that we could reduce the load time to 30% or 40%. It would help in combination with all other solutions as well.

### Caching

This is a last resort approach as it adds complexity and is likely to be buggy. The update of the cache would still be slow but using the cache could reduce the loading time to something like 10%.

### Changing the UX and features

We can reduce the data to load by reducing the data to show. Very few people see the unfolded enterprise box and pay attention to the producers of a shop. By removing that part of the UX we can further reduce the loaded data.

### Throwing metal at it

More memory doesn't make the processing faster. We need faster CPUs. Scaling up with AWS is pretty expensive. In Australia, we use Rimu Hosting and already use the fastest servers they have.

Separating our database server from our application server could help. But the connection delay may make it worse again.

### Conclusion

My perception is that avoiding n+1 queries is the easiest way to have an impact without changing any of the frontend code. Reducing the amount of enterprises loaded is another good one. But it may need some update of the processing logic as well. If there are some particular slow queries, we may decide to cache them in a simple way.

**Comment by sauloperez** [comment] 2019-04-12 07:59
Great investigation @mkllnk These are more or less all the categories of solutions that we can explore and combine. 

I put this on hold until the gathering to have in-depth discussion to decide which path we take, as this is one of our [next priorities](https://community.openfoodnetwork.org/t/focusing-in-for-the-first-half-of-2019-a-proposal-for-the-global-community/1571) once we get over the upgrade (goal #3).

**Comment by luisramos0** [comment] 2019-04-12 21:13
yeah, great Maikel. there's also the pagination of the enterprises call.

I think this is a great opportunity for API both for
- "Loading fewer enterprises" - api endpoint filter
- "Caching" - caching is a fundamental part of any workable API
- "Pagination" - pagination is a must have in the API
So we could start with building these things in the enterprises endpoint which is a relatively simple API use case :-)

**Closed** 2019-06-21 05:02 UTC
Labels: bug-s3
