### ISSUE TITLE
Can't change mobile and admin logo

### ISSUE THREAD

**Issue by romale** [openfoodfoundation/openfoodnetwork#5787] opened 2020-07-19 18:20 UTC
## Description

In any OFN releases (>2.9) I can't change mobile and admin logo via web interface from admin/contents/edit menu.
Logo changed only on main page of the OFN desktop version

## Expected Behavior

After image uploaded, it should be changed on web interface of OFN (mobile and desktop versions)

## Actual Behaviour

Logo not changed

![image](https://user-images.githubusercontent.com/928628/87881953-7da78800-ca05-11ea-9423-a1a168343758.png)

![image](https://user-images.githubusercontent.com/928628/87881972-8ef09480-ca05-11ea-9f21-acc167c4d31e.png)

![image](https://user-images.githubusercontent.com/928628/87881978-97e16600-ca05-11ea-97c7-1252a5368964.png)

```

I, [2020-07-19 20:39:49#6338]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"KWrsA/FDN+L/IafRiyGYjNb3Zg+8ieUCti2jFQz29tQ=", "logo_
mobile"=>#<ActionDispatch::Http::UploadedFile:0x0000563fcc6978e8 @original_filename="logo-ofn-russia-mobile.png", @content_type="image/png", @hea
ders="Content-Disposition: form-data; name=\"logo_mobile\"; filename=\"logo-ofn-russia-mobile.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<
Tempfile:/tmp/RackMultipart20200719-6338-9n1sug>>, "home_page_alert_html"=>"", "home_show_stats"=>"1", "producer_signup_pricing_table_html"=>"tra
nslation missing: ru.content_configuration_pricing_table", "producer_signup_case_studies_html"=>"translation missing: ru.content_configuration_ca
se_studies", "producer_signup_detail_html"=>"translation missing: ru.content_configuration_detail", "hub_signup_pricing_table_html"=>"translation
 missing: ru.content_configuration_pricing_table", "hub_signup_case_studies_html"=>"translation missing: ru.content_configuration_case_studies",
"hub_signup_detail_html"=>"translation missing: ru.content_configuration_detail", "group_signup_pricing_table_html"=>"translation missing: ru.con
tent_configuration_pricing_table", "group_signup_case_studies_html"=>"translation missing: ru.content_configuration_case_studies", "group_signup_
detail_html"=>"translation missing: ru.content_configuration_detail", "menu_1"=>"1", "menu_1_icon_name"=>"ofn-i_019-map-pin", "menu_2"=>"1", "men
u_2_icon_name"=>"ofn-i_037-map", "menu_3"=>"1", "menu_3_icon_name"=>"ofn-i_036-producers", "menu_4"=>"1", "menu_4_icon_name"=>"ofn-i_035-groups",
 "menu_5"=>"1", "menu_5_icon_name"=>"ofn-i_013-help", "menu_6"=>"0", "menu_6_icon_name"=>"ofn-i_035-groups", "menu_7"=>"0", "menu_7_icon_name"=>"
ofn-i_013-help", "footer_facebook_url"=>"", "footer_twitter_url"=>"", "footer_instagram_url"=>"", "footer_linkedin_url"=>"", "footer_googleplus_u
rl"=>"", "footer_pinterest_url"=>"", "footer_email"=>"hello@openfoodnetwork.ru", "community_forum_url"=>"", "footer_links_md"=>"", "footer_about_
url"=>"https://about.openfoodnetwork.ru/", "user_guide_link"=>"https://guide.openfoodnetwork.ru/", "open_street_map_enabled"=>"0", "open_street_m
ap_provider_name"=>"OpenStreetMap.Mapnik", "open_street_map_provider_options"=>"{}", "button"=>""}
I, [2020-07-19 20:39:49#6338]  INFO -- : [paperclip] Saving attachments.
I, [2020-07-19 20:39:49#6338]  INFO -- : [paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-07-19-201438/public/sy
stem/content_configurations/logo_mobiles//original/logo-ofn-russia-mobile_2x.png
E, [2020-07-19 20:39:49#6338] ERROR -- : Redirected by /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-07-19-201438/app/controllers/
admin/contents_controller.rb:21:in `update'
I, [2020-07-19 20:39:49#6338]  INFO -- : Redirected to https://openfoodnetwork.ru/admin/contents/edit
I, [2020-07-19 20:39:49#6338]  INFO -- : Completed 302 Found in 530.1ms (ActiveRecord: 301.0ms)
I, [2020-07-19 20:39:50#6338]  INFO -- : Started GET "/admin/contents/edit" for 127.0.0.1 at 2020-07-19 20:39:50 +0300
I, [2020-07-19 20:39:50#6338]  INFO -- : Processing by Admin::ContentsController#edit as HTML
```

## Steps to Reproduce

1. Go to admin/contents/edit
2. Change mobile logo
3.
4.

## Your Environment

* Version used: v2.10.1
* Browser name and version: Firefox 68.9.0esr, Android Chrome
* Operating System and version (desktop or mobile): desktop, mobile

**Comment by romale** [comment] 2020-07-31 10:08
Today i upgraded stage instance from 2.10.1 to 3.2.0 and the issue is same

```
I, [2020-07-31 13:05:59#7074]  INFO -- : Started PUT "/admin/contents" for 127.0.0.1 at 2020-07-31 13:05:59 +0300
I, [2020-07-31 13:05:59#7074]  INFO -- : Processing by Admin::ContentsController#update as HTML
I, [2020-07-31 13:05:59#7074]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"TlfEtjmd4odeLw6KvhUurIGSZqVduHMH7FiBQX1JNCU=", "logo"=>#<ActionDispatch::Http::UploadedFile:0x000055aa24da7d60 @tempfile=#<Tempfile:/tmp/RackMultipart20200731-7074-tjl7qm>, @original_filename="ofn-logo.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"logo\"; filename=\"ofn-logo.png\"\r\nContent-Type: image/png\r\n">, "home_page_alert_html"=>"", "home_show_stats"=>"1", "producer_signup_pricing_table_html"=>"translation missing: ru.content_configuration_pricing_table", "producer_signup_case_studies_html"=>"translation missing: ru.content_configuration_case_studies", "producer_signup_detail_html"=>"translation missing: ru.content_configuration_detail", "hub_signup_pricing_table_html"=>"translation missing: ru.content_configuration_pricing_table", "hub_signup_case_studies_html"=>"translation missing: ru.content_configuration_case_studies", "hub_signup_detail_html"=>"translation missing: ru.content_configuration_detail", "group_signup_pricing_table_html"=>"translation missing: ru.content_configuration_pricing_table", "group_signup_case_studies_html"=>"translation missing: ru.content_configuration_case_studies", "group_signup_detail_html"=>"translation missing: ru.content_configuration_detail", "menu_1"=>"1", "menu_1_icon_name"=>"ofn-i_019-map-pin", "menu_2"=>"1", "menu_2_icon_name"=>"ofn-i_037-map", "menu_3"=>"1", "menu_3_icon_name"=>"ofn-i_036-producers", "menu_4"=>"1", "menu_4_icon_name"=>"ofn-i_035-groups", "menu_5"=>"1", "menu_5_icon_name"=>"ofn-i_013-help", "menu_6"=>"0", "menu_6_icon_name"=>"ofn-i_035-groups", "menu_7"=>"0", "menu_7_icon_name"=>"ofn-i_013-help", "footer_facebook_url"=>"", "footer_twitter_url"=>"", "footer_instagram_url"=>"", "footer_linkedin_url"=>"", "footer_googleplus_url"=>"", "footer_pinterest_url"=>"", "footer_email"=>"hello@openfoodnetwork.ru", "community_forum_url"=>"", "footer_links_md"=>"", "footer_about_url"=>"https://about.openfoodnetwork.ru/", "user_guide_link"=>"https://guide.openfoodnetwork.ru/", "open_street_map_enabled"=>"0", "open_street_map_provider_name"=>"OpenStreetMap.Mapnik", "open_street_map_provider_options"=>"{}", "button"=>""}
I, [2020-07-31 13:06:00#7074]  INFO -- : [paperclip] Saving attachments.
I, [2020-07-31 13:06:00#7074]  INFO -- : [paperclip] deleting /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-07-31-123937/public/system/content_configurations/logos//original/ofn-logo.png
E, [2020-07-31 13:06:00#7074] ERROR -- : Redirected by /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-07-31-123937/app/controllers/admin/contents_controller.rb:21:in `update'
I, [2020-07-31 13:06:00#7074]  INFO -- : Redirected to https://dev.openfoodnetwork.ru/admin/contents/edit
I, [2020-07-31 13:06:00#7074]  INFO -- : Completed 302 Found in 596ms (ActiveRecord: 329.0ms)
I, [2020-07-31 13:06:00#7077]  INFO -- : Started GET "/admin/contents/edit" for 127.0.0.1 at 2020-07-31 13:06:00 +0300
I, [2020-07-31 13:06:00#7077]  INFO -- : Processing by Admin::ContentsController#edit as HTML
I, [2020-07-31 13:06:00#7077]  INFO -- :   Rendered spree/admin/shared/_configuration_menu.html.haml (13.3ms)
```

**Comment by RachL** [comment] 2020-09-09 09:31
Hello @romale we cannot change the admin logo yet, this is a feature that needs to be implemented.

I've uploaded a mobile logo on staging and it is working well so I cannot reproduce the issue. Have you used the two mobile buttons?

I'm closing the issue, but feel free to reopen if you still have the problem with the mobile one.

**Closed by RachL** 2020-09-09 09:31 UTC
