### ISSUE TITLE
[Flaky] ./spec/system/admin/order_cycles/simple_spec.rb:709

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10464] opened 2023-02-20 11:18 UTC
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage simple order cycles
 modify the minute of a order cycle with the keyboard, check that the modifications are taken into account
     Failure/Error:
       within "#save-bar" do
         expect(page).to have_content "You have unsaved changes"
       end
     
     Capybara::ElementNotFound:
       Unable to find visible css "#save-bar"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_simple_order_cycles_modify_the_minute_of_a_order_cycle_with_the_keyboard__check_that_the_modifications_are_taken_into_account_461.png

     
     # ./spec/system/admin/order_cycles/simple_spec.rb:717:in `block (2 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:44:in `block (2 levels) in <top (required)>'

Finished in 3 minutes 37.2 seconds
46 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/system/admin/order_cycles/simple_spec.rb:709 # 
```

### Context

This came up here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4204413959/jobs/7295057560

**Comment by vviekk** [comment] 2023-02-27 05:01
Another instance: (Doesn't seem to be limited to a specific test)

```
Failures:

  1) 
    As an administrator
    I want to manage orders
 with a complete order logging as superadmin and visiting the orders page ordering orders with different billing addresses orders by last name
     Failure/Error: find("a", text: 'NAME').click # sets ascending ordering
     
     Capybara::ElementNotFound:
       Unable to find visible css "a" with text "NAME"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_orders_with_a_complete_order_logging_as_superadmin_and_visiting_the_orders_page_ordering_orders_with_different_billing_addresses_orders_by_la_428.png

     
     # ./spec/system/admin/orders_spec.rb:330:in `block (6 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:44:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 17 seconds
30 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/orders_spec.rb:329 # 
```

Run: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4274562250/jobs/7441272466

**Comment by filipefurtad0** [comment] 2023-02-27 08:11
Hey @vviekk,

I think failure rather relates to `/orders_spec.rb:330`, which is issue #10408 and is being addressed currently. Thanks for reporting!

**Comment by mkllnk** [comment] 2023-05-02 04:45
Another one:

* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4856803729/jobs/8656715652


Bumping priority.

**Comment by filipefurtad0** [comment] 2023-05-03 11:44
Another one:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4869579078/jobs/8684258066

Similar to https://github.com/openfoodfoundation/openfoodnetwork/issues/10302

**Comment by rioug** [comment] 2023-06-13 03:43
I have not been able to reproduce this flaky spec even with `rspec-slow-repeat` I tried with up to 150 ... still no fail. I can see animation are disable for system test, so It's not an issue with the `#save-bar` taking too long to show. 
The only other idea I have is maybe add another  `input.send_keys :up` here: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/c5ce49e08c4b8377661d7207f0772a5839280f44/spec/system/admin/order_cycles/simple_spec.rb#L759-L764

To make sure the change is taken into account.

 @mkllnk @filipefurtad0 what do you think ?

**Comment by mkllnk** [comment] 2023-06-14 03:26
It's so hard to debug when you can't reproduce it. Did you check out the screenshots on CI to see if the savebar is actually visible or if there's any other hint?

It could also be that the page needs some initialisation time after `visit` and that some of the inputs are not doing anything when done too early.

**Comment by mkllnk** [comment] 2023-06-14 03:34
Hm, just seeing that the latest report was over a month ago and the artifacts are not preserved any more. I can't reproduce it either.

@filipefurtad0 updated that spec since the last fail reported here already: c5358b13035dd9ea76e18ca50d79ab4ca89eff6c

I reckon this may be fixed and we should close it.

**Closed** 2023-06-14 03:34 UTC
Labels: tech debt
