### ISSUE TITLE
ActionView::MissingTemplate in api/order_cycles#products

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/openfoodnetwork#6491] opened 2020-12-09 05:37 UTC
## Error in OpenFoodNetwork USA and Coopcircuits

**ActionView::MissingTemplate** in **api/order_cycles#products**
Missing template api/order_cycles/products, api/base/products with {:locale=>[:en_US, :en], :formats=>[:json, :js, :html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml]}. Searched in:
  * "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-12-08-184619/app/views"
  * "/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2020-12-08-184619/app/views"

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-usa/errors/5fd0218d20374d001835d3aa?event_id=5fd0218d00659ee313d30000&i=gh&m=ci)

## Stacktrace

    app/controllers/api/base_controller.rb:76 - error_during_processing

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-usa/errors/5fd0218d20374d001835d3aa?event_id=5fd0218d00659ee313d30000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

**Comment by filipefurtad0** [comment] 2020-12-28 12:05
Searching in Slack `in:#devops-notifications api/order_cycles#products` show quite some occurrences since the 8th of Dec., which matches with the release date of [v3.4.4](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v3.4.4 ) and the upgrade to rails 4.2 - added the regression label.

This looks like it is user-facing error, maybe a shopfront not loading products. Perhaps we should raise the severity?

**Comment by andrewpbrett** [comment] 2020-12-30 04:05
Based on the stacktrace it looks like this is only happening if an OC is closed; I don't think it's related to the issue where the shopfront doesn't load all products. So I think it's still an S5. In any case it would be nice to fix it and not get the notifications. So: #6577

**Comment by filipefurtad0** [comment] 2020-12-30 09:47
Thanks for feedback and providing a fix for this issue @andrewpbrett ,

Indeed, I see this is reproducible by visiting that the URL on the Request section, on the respective bug report on Bugsnag, for example by visiting this link (as of now the shop still has a closed OC):

https://openfoodnetwork.net/api/order_cycles/1788/products?distributor=191&page=3&per_page=10&q%5Bname_or_meta_keywords_or_variants_display_as_or_variants_display_name_or_supplier_name_cont%5D=

So, it appears to have caused visible snail to the user:
![image](https://user-images.githubusercontent.com/49817236/103343120-29f49c80-4a83-11eb-9af7-66d25dad1ac1.png)

**Closed** 2021-01-09 01:34 UTC
Labels: bug-s5, bugsnag, r4.2-regression
