### ISSUE TITLE
[BO Orders] Clicking customer search results does not fill the details form

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#12085] opened 2024-01-25 11:45 UTC
## Description

Affects only legacy BUU design.

Related to https://github.com/openfoodfoundation/openfoodnetwork/pull/12015.

When placing BO orders, the hub can search customers by email which displays the results in the dropdown. However, clicking these does not fill in the form, as expected, and a console error is triggered, bugsnag:

https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/62b9c22a274a8e0008ce619c?filters[error.status]=open&filters[event.since]=30d&event_id=65b24adf00d277c75dbb0000

## Expected Behavior

Clicking customer search results by email should fill in the details form.

## Actual Behaviour

Clicking customer search results by email does not fill in the details form.

## Steps to Reproduce

0. Disable `admin_style_v3` toggle

Open the console on the browser. As a hub:
1. Create a new order.
2. On the Customer Details tab, type the email address of a customer
3. See that it appears on the dropdow; now click this entry, as you'd do to select the customer
4. Notice customer details are empty; notice the console error

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/eb873250-3246-44e0-884e-a85140cdaff6)

## Workaround

Searching/clicking by customer name.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.27
* Browser name and version: Firefox 122
* Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by filipefurtad0** [comment] 2024-01-25 11:57
There are zero occurrences so far for UK- and FR- production. Maybe ok to downgrade to S4?

**Comment by RachL** [comment] 2024-01-25 12:26
hmmm if we can reproduce it I think I would keep it as s3, it's quite annoying to have to go to customer list and copy-paste...

**Comment by chahmedejaz** [comment] 2024-01-29 08:36
Hey @filipefurtad0 - I tried to reproduced it locally, but it's working as expected. 
I've investigated the code for this, I've a hunch but just to confirm, can you please share the screenshot of the Bugsnag error (_as I don't have access_) and the full console error from the start.
The shared screenshot shows the ending part of the error only. 

Thanks :)

**Comment by filipefurtad0** [comment] 2024-01-29 15:11
Hey @chahmedejaz ,
Thanks for following up on this. Here's a screenshot:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/73b5c3c5-c6d6-4aea-ba4e-7a6e9c9e67cb)

Hum, I believe I forgot to mention that this only occurs for the legacy BUU design, I've edited the description now - indeed I cannot reproduce it on the new design.

**Comment by chahmedejaz** [comment] 2024-02-01 10:27
That's strange :sweat_smile: . The Bugsnag error is in conflict with the code.
My hunch was that for some reason the `customer` const is `undefined`. However it's the error for the some `r`variable which is not even in the file Bugsnag is showing :sweat_smile: 

Are you still able to reproduce this?

**Comment by filipefurtad0** [comment] 2024-02-01 11:01
Thanks for investigating @chahmedejaz ! This is a tricky one :sweat_smile: 

> Are you still able to reproduce this?

Unfortunately yes... I observe it for both Firefox and Chrome. But it's a bit strange, as it seems not always to occur in Chrome - in my system, sometimes the page is not correctly loaded (notice the strange characters):

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/fa195867-1388-4c19-9afa-13eb9527c347)

However, it seems to always to occur in Firefox:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/fba073f2-92eb-4563-bfd6-e6a5f0a212ce)

I'm on Ubuntu 22.04, not sure this is relevant. Would it help if I grant you access to a staging server?

**Comment by chahmedejaz** [comment] 2024-02-01 11:06
> Unfortunately yes... I observe it for both Firefox and Chrome. But it's a bit strange, as it seems not always to occur in Chrome - in my system, sometimes the page is not correctly loaded (notice the strange characters)

This is even strange-er :sweat_smile: 

> Would it help if I grant you access to a staging server?

Sure it would be great. I'll see if there is the data issue for this or something. Thanks.

**Comment by chahmedejaz** [comment] 2024-02-01 14:14
The issue has been reproduced. It's very tricky and mostly due to the 3rd party library we are using for the search functionality.
I'll share the detailed repro steps in a loom tonight. Thanks.

**Comment by chahmedejaz** [comment] 2024-02-01 14:15
@filipefurtad0 - You may assign it to me, I'm working on it. :)

**Comment by chahmedejaz** [comment] 2024-02-01 19:43
Here's the repro steps and the root cause explained:

https://github.com/openfoodfoundation/openfoodnetwork/assets/59338032/078235ee-a3fd-4d70-9872-695a753c297e

Please let me know if you have any follow-up questions on this. I'm working on the fix. Thanks.

**Comment by chahmedejaz** [comment] 2024-02-01 21:38
The issue has been fixed, the PR is ready for review now. Thanks. :)

**Closed** 2024-02-12 12:29 UTC
Labels: bug-s3, regression
