### ISSUE TITLE
Saving failed notification when saving product changes in spree - UK 

### ISSUE THREAD

**Issue by sineadfenton** [openfoodfoundation/openfoodnetwork#2769] opened 2018-09-24 18:56 UTC
## Description

In UK production site, in spree. Click save on the product page and you see an error message when infact the request has been processed. This is not the intended flow, instead you should see a saved/complete notification.

## Expected Behavior

You should seed a "saved" notification when you click save and not 'Saving failed.Save failed due to invalid data:422'. This should only show when there is an error.

## Actual Behavior

You click save and Saving failed.Save failed due to invalid data:422 comes up

## Steps to Reproduce

1. Go to product page
2. Make a change - I changed the weight of an item.
3. Click save
4. Saving processes and then you get Saving failed with "Save failed due to invalid data:422" at the bottom of the screen
5. Refresh the page. You'll see your changes have actually gone through

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/28807449/45972367-7397e680-c033-11e8-9fd9-9f0c89b5c9b7.png)

## Context

Users will be confused and this there is an error when there is not. this will result in more support requests

## Your Environment

* Version used:
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop, windows
UK production was upgraded to 1.20.0 today (24/09) and this issue is new as of today.

## Possible Fix

Have the correct message when a task is successfully completed, and error show up only when there is an error.

**Comment by sineadfenton** [comment] 2018-09-24 18:57
![](https://github.trello.services/images/mini-trello-icon.png) [Saving failed.Save failed due to invalid data:422](https://trello.com/c/UfiOaWiF/247-saving-failedsave-failed-due-to-invalid-data422)

**Comment by myriamboure** [comment] 2018-09-25 15:44
@sineadfenton I logged in today on UK production with a hub manager user to reproduce the bug and see how to move it forward. I couldn't reproduct it, I tested on both price and weight and had the correct "product saved" message. Can you please describe more precisely which user was concerned, were you logged in as super admin? What product exactly did you try changing, for which type of user, etc. ? Is the user trying to change the product info the owner of the producer profile or a hub manager that has right to edit products on that producer? Without those info I don't see how we can move forward, if we can't reproduce the bug...
![capture du 2018-09-25 17-40-43](https://user-images.githubusercontent.com/8135376/46026049-ab159a00-c0ea-11e8-8491-21de4d7f966b.png)
![capture du 2018-09-25 17-41-59](https://user-images.githubusercontent.com/8135376/46026060-afda4e00-c0ea-11e8-995d-3ca799971de5.png)

**Comment by OliverUK** [comment] 2018-09-26 10:37
@myriamboure 
It happens when I'm logged in and try and save a change in BEP. It doesn't seem to matter what the change is.

http://recordit.co/PDpnjTo1pt

**Comment by myriamboure** [comment] 2018-09-26 15:19
@OliverUK as I could do it on UK production using Nick account, it seems to happen under certain specific conditions. Your profile is regular hub owner and manager. Not super admin.
You are the owner of Global Organic Markets, in your video the product you try to upload info for, so there shouldn't be any permission bug.... Global organic markets sell the products through multiple hubs, so catalog seems to be shared by multiple distributors, but only one (stroudco) can manage products. All those are exactly same conditions as when I did the test yesterday on UK production. Can it be linked to a loading time error @kristinalim ?
@OliverUK that could help Kristina if you can before reproducing the error click on your browser menu "developers tool / console" and look at consol tab and share screenshot of the error that appears when you try to modify a product. Then you can click on the error to see details and share them. You can click on "network" and share details.
Unless @kristinalim manages to reproduce the bug... it might be hard to find where the issue comes from :-(

**Comment by OliverUK** [comment] 2018-09-27 09:42
@myriamboure I'm afraid the only thing I get in the console is that google analytics was blocked.

**Comment by OliverUK** [comment] 2018-09-27 10:06
@kristinalim I hope this isn't just confusing the issue but I've got another problem and wondered if it might be related. If I got to the inventory for Stroudco and try and filter for Producer:Wharf Farm, it doesn't come up. They also don't come up if I leave Producer unfiltered and search for their produce. This happens for me logged in as me and it happens when I log in as super admin but it seems to work fine for Nick.

**Comment by myriamboure** [comment] 2018-10-01 09:55
@OliverUK please to avoid mixing up conversation please open a new issue for the new bug. It is likely all those bug might have a common cause, but let's keep discussion separate so that we can investigate for each one. Can you open a new issue please and then reference it here to ask if that can be related?

**Comment by myriamboure** [comment] 2018-10-01 12:17
Thanks @OliverUK ! Here is the issue as a record: https://github.com/openfoodfoundation/openfoodnetwork/issues/2799

**Comment by kristinalim** [comment] 2018-10-04 04:18
@OliverUK If it is from a permission problem, it could be related. Thanks for creating the new issue!

I have been able to confirm that #2776 is not related to this issue. For Sacred Lotus:

* All products are valid
* Their master variants are valid
* Their non-master variants are valid

**Comment by kristinalim** [comment] 2018-10-04 12:42
Sorry, I haven't been able to figure this out yet.

I've already checked nested associated records of products under Sacred Lotus and Global Organic Markets, and haven't been able to find anything which the software considers invalid. It appears that this isn't related to #2776.

I've looked into possible permission related issues too, but no promising hint so far.

I'll be back to continue investigating in a couple of hours.

**Comment by Matt-Yorkley** [comment] 2018-10-05 14:48
I've added myself as a manager for that enterprise and can update the products on that page successfully...?

**Comment by myriamboure** [comment] 2018-10-05 15:00
@Matt-Yorkley maybe you can "sit" (virtually) with @OliverUK or even hack his account with his permission to reproduce the bug? It seems @OliverUK has the issue with any item he tries to change in BEP... but no one managed to reproduce the error so far.

**Comment by myriamboure** [comment] 2018-10-05 15:01
@OliverUK is it only for sacred lotus that you have an issue? Or all products you have access to?

**Comment by OliverUK** [comment] 2018-10-05 15:02
@Matt-Yorkley @myriamboure fine by me. Can change my password to a temporary one and share with you, Matt.

**Comment by myriamboure** [comment] 2018-10-05 15:05
@Matt-Yorkley I'm wondering if there is not some common problem also below this issue https://github.com/openfoodfoundation/openfoodnetwork/issues/2739#issuecomment-425881286, I found that behavior super strange, seems like a big breach in our app... and alsohttps://github.com/openfoodfoundation/openfoodnetwork/issues/2756#issuecomment-423355684. I don't know it feels to me like if all those issues could be connected... @OliverUK did this start just after you were added as a manager to a new enterprise? Or created a new enterprise? Do you have any clue of things you've done just before it starts bugging?

**Comment by OliverUK** [comment] 2018-10-05 15:28
@Matt-Yorkley have sent you my password on Slack

**Comment by Matt-Yorkley** [comment] 2018-10-05 15:58
Okay, I've tried with Oliver's login, and I can reproduce the bug with that. I get the 422 error. So a permissions issue makes the most sense, if I can save on one account and not on another.

Bugsnag is giving me nothing, and the production log is also giving me nothing...

**Comment by Matt-Yorkley** [comment] 2018-10-05 16:05
@kristinalim maybe you can have a look as well. I'm looking in the `#bulk_update` method of `products_controller_decorator.rb` and trying to match up what's shown in the logs.

![screenshot from 2018-10-05 17-01-48](https://user-images.githubusercontent.com/9029026/46546255-6cd56300-c8c0-11e8-8ee1-9f369b6cd92b.png)

![screenshot from 2018-10-05 17-02-58](https://user-images.githubusercontent.com/9029026/46546322-9c846b00-c8c0-11e8-99a3-5c67903c301f.png)

It looks like the `products_set` is being saved, as the redirect to to the api route is definitely happening. And I think the `authorize!` in line 44 is also passing, otherwise the response would be different...?

**Comment by lin-d-hop** [comment] 2018-10-05 16:06
Was anything that touches permissions recently merged to master? This appears in v1.20.

**Comment by myriamboure** [comment] 2018-10-05 16:10
@HugsDaniel just did some tests and found strange permission bugs on can instance, seems all the s2 and some s3 bugs could be linked to a same permission issue.

**Comment by lin-d-hop** [comment] 2018-10-05 16:14
@myriamboure I definitely think they are all related!

**Comment by Matt-Yorkley** [comment] 2018-10-05 16:16
Update: on oliver's account, I update a product and the error message shows, but if I reload the page the product _has_ actually been updated successfully.

**Comment by HugsDaniel** [comment] 2018-10-05 16:19
This doesn't appear to be the case in Can instance

**Comment by HugsDaniel** [comment] 2018-10-05 16:19
> Update: on oliver's account, I update a product and the error message shows, but if I reload the page the product _has_ actually been updated successfully.


This doesn't appear to be the case in Can instance

**Comment by kristinalim** [comment] 2018-10-05 16:19
> Update: on oliver's account, I update a product and the error message shows, but if I reload the page the product _has_ actually been updated successfully.

@Matt-Yorkley This could be misleading because an incomplete save continues to save other changes: https://github.com/openfoodfoundation/openfoodnetwork/issues/2776

**Comment by Matt-Yorkley** [comment] 2018-10-05 16:29
But if I can save with one account with no errors, but on another account I get the 422, we can assume the product data that's being saved is ok, right?

**Comment by kristinalim** [comment] 2018-10-05 16:32
Yes, you're right.

**Comment by Matt-Yorkley** [comment] 2018-10-05 16:37
The redirect to '/api/products/bulk_products?page=1;per_page=500;' after saving seems a bit odd... we fetch 500 products every time we hit save on one or more products?

**Comment by Matt-Yorkley** [comment] 2018-10-05 17:13
Also, the angular controller looks like it should be passing `$scope.currentFilters`, but this always seems to be blank, and it doesn't seem to be set anywhere?

**Comment by Matt-Yorkley** [comment] 2018-10-05 17:59
@kristinalim Looks like the initial POST request is fine, but the subsequent redirect to the API route is what returns the 422, with this:

![screenshot from 2018-10-05 18-56-48](https://user-images.githubusercontent.com/9029026/46551767-8aaac400-c8d0-11e8-93c3-03f0fc3f3bbb.png)

**Comment by kristinalim** [comment] 2018-10-05 18:02
@Matt-Yorkley I'm on it now too. Getting the same error in the console when running this:

```ruby
u = Spree::User.find_by_email("olivermuller@gmx.com")
products = OpenFoodNetwork::Permissions.new(u).editable_products.merge(Spree::Product.not_deleted).order('created_at DESC').ransack({}).result.page(1).per(500)
json_object = ActiveModel::ArraySerializer.new(products, each_serializer: Api::Admin::ProductSerializer)
json_object.to_json
```

**Comment by kristinalim** [comment] 2018-10-05 18:06
Nice detective work, @Matt-Yorkley. So it's `#import_date` that's breaking. It's a simple change - I'll submit the PR for this.

**Comment by kristinalim** [comment] 2018-10-05 19:31
I submitted PR #2831 which should address this.

Sorry I was looking at the wrong places. :slightly_frowning_face:  HTTP 422 is normally used when submitted data could not be processed, and the error was happening in a separate read-only request that did not indicate the error in the logs.

**Comment by lin-d-hop** [comment] 2018-10-06 11:40
UK have deployed this patch to prod and can confirm that the issues we've been experiencing have been fixed

**Comment by OliverUK** [comment] 2018-10-07 13:42
Thank you guys!! Well done indeed.

**Closed** 2018-10-10 08:54 UTC
Labels: bug-s2
