### ISSUE TITLE
Cannot create new variant

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/openfoodnetwork#4999] opened 2020-03-16 04:02 UTC
## Description

I cannot add a new variant from the variants screen (not bulk edit). This bug has been introduced by the removal of spree_backend.

## Expected Behavior

I click the "New Variant" button and see a screen to enter the variant details.

## Actual Behaviour

I click the "New Variant" button, a loading message pops up for a moment and nothing changes.

## Steps to Reproduce

1. Log in as enterprise user.
2. Go to a product.
3. Go to the variants tab of that product.
4. Click "New Variant".

## Animated Gif/Screenshot

![Peek 2020-03-16 15-06](https://user-images.githubusercontent.com/3524483/76722556-32037a00-6798-11ea-8bfa-e41a1daba4b2.gif)

## Workaround

Go to the bulk products edit screen and add variants there.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.7.8

## Possible Fix

```diff
diff --git a/app/views/spree/admin/variants/new.js.erb b/app/views/spree/admin/variants/new.js.erb
index 9ddfd6997..d0f6b4069 100644
--- a/app/views/spree/admin/variants/new.js.erb
+++ b/app/views/spree/admin/variants/new.js.erb
@@ -1,3 +1,3 @@
-$("#new_variant").html('<%= escape_javascript(render template: 'spree/admin/variants/new', formats: [:html], handlers: [:erb]) %>');
+$("#new_variant").html('<%= escape_javascript(render template: 'spree/admin/variants/new', formats: [:html], handlers: [:haml]) %>');
 $(".select2").select2();
 $("#new_var_link").hide();
```

The other option would be to remove that button or direct it to the bulk edit screen. We shouldn't have two ways of adding variants. Some UX design may be helpful here but fixing the bug is probably a 5 minute job and much easier.

## Error in OpenFoodNetwork

**ActionView::Template::Error** in **spree/admin/variants#new**
Missing template spree/admin/variants/new with {:locale=>[:en_AU, :en], :formats=>[:html], :handlers=>[:erb]}. Searched in:
  * "/home/openfoodnetwork/apps/openfoodnetwork/current/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.3.0/gems/foundation-rails-5.5.2.1/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.3.0/gems/gmaps4rails-1.5.6/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.3.0/gems/devise-2.2.8/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.3.0/bundler/gems/better_spree_paypal_express-27ad7165ea4c/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.3.0/bundler/gems/spree-8a8585a43cd0/core/app/views"
  * "/home/openfoodnetwork/.gem/ruby/2.3.0/gems/kaminari-0.14.1/app/views"
  * "/home/openfoodnetwork/apps/openfoodnetwork/current/engines/web/app/views"

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5e6d73624c74330017a137db?event_id=5e6dddf0005834f4635e0000&i=gh&m=ci)

## Stacktrace

    app/views/spree/admin/variants/new.js.erb:1 - _b07794c81d1f941cf08f61ac46323ab9
    app/controllers/spree/admin/resource_controller.rb:18 - block (2 levels) in new
    lib/spree/core/controller_helpers/respond_with_decorator.rb:17 - respond_with
    app/controllers/spree/admin/resource_controller.rb:16 - new

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5e6d73624c74330017a137db?event_id=5e6dddf0005834f4635e0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

**Comment by RachL** [comment] 2020-03-16 08:15
This is a duplicate of: https://github.com/openfoodfoundation/openfoodnetwork/issues/4961 so closing

**Closed by RachL** 2020-03-16 08:15 UTC
Labels: bug-s3, bugsnag
